### ISSUE TITLE
Issue with version v1.20.2+k3s1 when curl is not installed

### ISSUE THREAD

**Issue by neilmcauliffe** [k3s-io/k3s#2849] opened 2021-01-22 22:30 UTC
I got a strange error when trying to run the setup on ubuntu 18.04, " Downloading hash https://github.com/rancher/k3s/releases/download/v1.20.2+k3s1", "socket-worker-5029ae85.js/sha256sum-amd64.txt" I noticed the download  string had some extra data in there. 

Having looked at the file from here https://get.k3s.io I noticed that the issue was related to how the url was retrieved when curl was not installed.

when wget is used  in the case switch on line 350 the return value for VERSION_K3S is 

```
wget -SqO /dev/null https://update.k3s.io/v1-release/channels/stable 2>&1 | grep -i Location | sed -e 's|.*/||'
```

v1.20.2+k3s1
socket-worker-5029ae85.js

however the return value is correct when curl is used

**Comment by brandond** [comment] 2021-01-22 22:55
Duplicate of #2814 - this was caused by github adding another header that matches the 'location' pattern we're grepping for.

**Closed by brandond** 2021-01-22 22:55 UTC
