### ISSUE TITLE
Consider switching default CNI to Calico

### ISSUE THREAD

**Issue by sandys** [k3s-io/k3s#1880] opened 2020-06-09 11:54 UTC
hi ,
so we have begun using k3s in production. We have had intermittent issues with flannel - especially with spot instances coming up and going down. we have also seen this issue - https://github.com/coreos/flannel/issues/1245

What is most worrying is that flannel seems to be effectively unmaintained. There also seems to be compatibility issues with k8s 1.17.2

Calico is one of the only plugins supported by AWS ( https://docs.aws.amazon.com/eks/latest/userguide/alternate-cni-plugins.html) , AKS ( https://docs.microsoft.com/en-us/azure/aks/use-network-policies#network-policy-options-in-aks ) and GKE ( https://cloud.google.com/kubernetes-engine/docs/concepts/network-overview ) 

Calico is also part of CNCF - https://landscape.cncf.io/selected=project-calico with an Apache 2.0 license.

Wanted to open a placeholder issue for any consideration to choose calico as default

**Comment by blaggacao** [comment] 2020-09-23 21:01
calico can advertise BGP routes and thereby effectively implement bare metal external lbs without the need for metalLB, iirc.

**Comment by balibebas** [comment] 2020-12-14 05:31
Wireguard support for Calico [was announced](https://www.projectcalico.org/introducing-wireguard-encryption-with-calico/) four days before this was opened — positive. But if other CNIs may already be swapped in what's the advantage of changing the default when it would take away time from adding support other CNIs [such as Cilium](https://github.com/k3s-io/k3s/pull/2696/files#diff-683343bdf93f55ed3cada86151abb8051282e1936e58d4e0a04beca95dff6e51R14)? I see 21 thumbs up for the default adjustment but no attention from maintainers on this issue—which seems a bit strange. Are 90% of users switching the default? Or is this more of a nice-to-have consideration issue?

**Comment by balibebas** [comment] 2020-12-14 05:56
Related docs:

https://rancher.com/docs/k3s/latest/en/installation/network-options/

https://rancher.com/blog/2019/2019-03-21-comparing-kubernetes-cni-providers-flannel-calico-canal-and-weave/

https://k3d.io/usage/guides/calico/

https://docs.projectcalico.org/getting-started/kubernetes/k3s/

**Comment by balibebas** [comment] 2020-12-14 06:03
Wireguard support for Calico [was announced](https://www.projectcalico.org/introducing-wireguard-encryption-with-calico/) four days before this was opened — positive. But if other CNIs [can already be swapped in](https://rancher.com/docs/k3s/latest/en/installation/network-options/) what's the advantage of changing the default when it would take away time from adding support other CNIs [such as Cilium](https://github.com/k3s-io/k3s/pull/2696/files#diff-683343bdf93f55ed3cada86151abb8051282e1936e58d4e0a04beca95dff6e51R14)? I see 21 thumbs up for the default adjustment but no attention from maintainers on this issue—which seems a bit strange. Are 90% of users switching the default? Or is this more of a nice-to-have consideration issue?

See also:

- https://rancher.com/blog/2019/2019-03-21-comparing-kubernetes-cni-providers-flannel-calico-canal-and-weave/
- https://k3d.io/usage/guides/calico/
- https://docs.projectcalico.org/getting-started/kubernetes/k3s/

**Comment by sandys** [comment] 2021-03-08 13:56
Calico can now announce service lb ip addresses to BGP.  Wireguard support is stable. https://docs.projectcalico.org/archive/v3.18/networking/advertise-service-ips#advertise-service-load-balancer-ip-addresses

**Comment by billimek** [comment] 2021-04-01 19:49
It would be a really great user experience if we could at least choose Calico as the CNI as part of the k3s bootstrapping/installation instead of needing to install it out-of-band.

Do any of the k3s maintainers have insights if this is even a possibility in the future, or should we continue to workarounds like we do today?

**Comment by brandond** [comment] 2021-04-01 20:22
We don't currently provide 'alternatives' for any of K3s' opinionated defaults. At some point we may wholesale change out components, but we don't currently have that on the roadmap.

**Comment by Bessonov** [comment] 2021-09-28 21:10
activity

**Comment by Bessonov** [comment] 2022-03-28 00:08
activity

**Comment by Bessonov** [comment] 2022-09-24 20:07
activity

**Comment by cwayne18** [comment] 2022-09-24 21:20
At this point we do not plan to change the default CNI any time soon.  You should be able to disable flannel and use other CNIs, but k3s by design is opinionated. I'm going to close this out for now.

**Closed by cwayne18** 2022-09-24 21:20 UTC
