### ISSUE TITLE
Add pprof capability to k3s server?

### ISSUE THREAD

**Issue by TylerBrock** [k3s-io/k3s#1635] opened 2020-04-12 14:00 UTC
Hi all, I'm running k3s on x86_64 as well as armv7 (raspberry pi 4) and I've noticed that there is a consistent amount of CPU in use after starting the service while it should just be idle. One core always take about 15-20% cpu with no pods of my own running.

Additionally, every ~5 seconds it uses ~25% of all four cores on both boxes to do something (I think this is collecting metrics most likely).

I'm not sure if this is a kubernetes problem in general but for something like k3s I'd like to figure out what is going on (since it's supposed to be lightweight).

Would anyone object to adding pprof to k3s to see exactly what it's doing with that constant CPU?

Some additional details:
 - This is a single node cluster consisting of just the server itself.
 - I'm not running any of my own pods
 - This is after a fresh installation
 - There is nothing alarming or repetitive in the logs from what I can tell

**Comment by runningman84** [comment] 2020-04-12 19:03
this is a similar issue: https://github.com/rancher/k3s/issues/294

**Comment by TylerBrock** [comment] 2020-04-12 19:34
Yup I read through that and it seems like there was no outcome/solution so I wanted to try and move things forward by seeing if anyone is against this. I would be willing to try to add pprof support via a PR but I want to know my time won't be a complete waste if folks are against it / or if they have profiled before and know what the problem is.

**Comment by runningman84** [comment] 2020-04-13 18:57
I would be very happy to see the root cause for this issue...

@erikwilson what do you guys think about it?

**Comment by MichaelKissling** [comment] 2020-06-29 08:35
Hello @TylerBrock 

I am also very interested in the result. Currently we have the same problems with k3s-server using about 20-30 % CPU on a fresh Lubuntu 20.04 installation. It would be great to find and remove the cause.

regards
Michael

**Comment by sysadmiral** [comment] 2021-08-12 13:10
not stale. Still happens in 2021 running v1.21.3+k3s1 on a pi cluster. No other pods running. k3s process is constantly consuming about 20-30% CPU.

In my cluster I stopped k3s on the primary and the agent node that is showing the consistent CPU usage dropped down. When the primary came back up the CPU went back up on the node agent.

![image](https://user-images.githubusercontent.com/5868863/129202428-265ce421-8ced-4b47-8296-784ed9efa01a.png)

**Comment by pfisterer** [comment] 2021-11-01 13:21
I also see 10-13%  consistently on a fresh install on Debian 11 w/o any workload.

**Comment by brandond** [comment] 2021-11-01 21:47
Yes, that is to be expected. See https://rancher.com/docs/k3s/latest/en/installation/installation-requirements/resource-profiling/

**Comment by dereknola** [comment] 2022-06-14 16:18
PR was merged https://github.com/k3s-io/k3s/pull/5527 to address this

**Closed** 2022-06-16 19:14 UTC
Labels: kind/feature
