### ISSUE TITLE
Install script doesn't work AMD64

### ISSUE THREAD

**Issue by vhuezo** [k3s-io/k3s#6034] opened 2022-08-25 20:58 UTC
![fe](https://user-images.githubusercontent.com/41808201/186767507-01e78f14-2e3d-418f-9adb-9b00656473cd.png)

`curl -sfL https://get.k3s.io | sh -`

**Comment by rabbagliettiandrea** [comment] 2022-08-25 21:01
Same here, going deeper `https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt` returns HTTP404

**Comment by nicklasfrahm** [comment] 2022-08-25 21:04
Duplicate of #6033.

**Comment by briandowns** [comment] 2022-08-25 23:04
Closing as duplicate. Original linked above has resolution.

**Closed by briandowns** 2022-08-25 23:04 UTC
