### ISSUE TITLE
Enabling ipvs on k3s resulted in SSH connection failure

### ISSUE THREAD

**Issue by hooke-49** [k3s-io/k3s#8946] opened 2023-11-23 09:38 UTC
**Environmental Info:**
K3s Version: 

k3s version v1.26.10+k3s1 (a6687b59)
go version go1.20.10

Node(s) CPU architecture, OS, and Version: 

Linux k3s01 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux

Cluster Configuration:

1 servers

**Describe the bug:**

Enabling ipvs on k3s resulted in SSH connection failure

After enabling ipvs, a virtual network card kube-ipvs0 will be added with an IP address 192.168.0.231/32, which conflicts with 192.168.0.231/24 on the eth0 network card, resulting in SSH connection failure

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment] 2023-11-27 23:45
I believe this is a duplicate of https://github.com/k3s-io/k3s/issues/7183. This was traced back to upstream issues https://github.com/kubernetes/kubernetes/issues/117613 and https://github.com/kubernetes/kubernetes/issues/117621, and fixed in https://github.com/kubernetes/kubernetes/pull/115019.

As per comments on that thread, the fix wasn't backported to Kubernetes 1.26, so you'll need to upgrade to 1.27 or newer.

**Closed by brandond** 2023-11-27 23:45 UTC

**Comment by DamianoSamperi** [comment] 2025-03-03 18:39
I have the same problem, I'm using version v1.29.13+k3s1
