### ISSUE TITLE
NodePort does not accept IPv6 trafic

### ISSUE THREAD

**Issue by majkrzak** [k3s-io/k3s#767] opened 2019-08-27 20:09 UTC
When NodePort Service is created it is listening on all the interfaces but does not accept IPv6 traffic.

**Comment by warmchang** [comment] 2019-08-28 05:08
Your environment is IPv6 single stack or dualstack (IPv6+IPv4)?

**Comment by majkrzak** [comment] 2019-08-28 05:13
Dualstack, non kubernetes services (ssh for example) works fine.

**Comment by majkrzak** [comment] 2019-08-28 05:24
When k3s service is down connections are rejected, but if ut is up then
they stuck.

**Comment by warmchang** [comment] 2019-08-28 06:08
The upstream k/k community is still working on IPv4/IPv6 dual-stack support, and the current release only supports single stack.

**Comment by majkrzak** [comment] 2019-08-28 06:15
It seems to bind interface correctly, but drops the packets later. No
matter what it is not expe behavior and should be fixable quite easily,
either by binding to v4 only or doing v6 in the proper way.

**Comment by majkrzak** [comment] 2019-08-28 17:05
Sure, just please point me where NodePort traffic is handled

**Comment by erikwilson** [comment] 2019-08-29 23:45
If you have some more info on what is happening that might help @majkrzak, such as steps to reproduce and host system information. 

It isn't clear to me if this is an upstream k8s ipv6 issue or a problem with k3s specifically.

**Comment by majkrzak** [comment] 2019-09-04 18:54
It also doesn't work when `externalIPs` are specified. In `netstat` is visible that only ipv4 was bounded.

```apiVersion: v1
kind: Service
spec:
  type: NodePort
  externalIPs:
  - "111.111.111.111"
  - "1111:::::1"
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https```

**Comment by leoluk** [comment] 2021-07-31 10:22
Still relevant

**Comment by majkrzak** [comment] 2022-01-27 11:01
nope

**Comment by rbrtbnfgl** [comment] 2022-07-21 09:28
Hi. I don't know if this is still an issue, but in case of exposed services on DualStack Kuberenetes declares `.spec.ipFamilyPolicy: SingleStack` and it gives only the IPv4 service address; to force the service to be exposed on both IPv4 and IPv6 that policy should be configured as `PreferDualStack` or `RequireDualStack`.

**Comment by majkrzak** [comment] 2023-01-17 17:28
not stale

**Comment by caroline-suse-rancher** [comment] 2023-06-21 21:31
Closing due to staleness

**Closed by caroline-suse-rancher** 2023-06-21 21:31 UTC
