### ISSUE TITLE
Running crictl commands give grpclog output

### ISSUE THREAD

**Issue by afbjorklund** [k3s-io/k3s#568] opened 2019-06-23 20:07 UTC
**Describe the bug**

When running `crictl` (through k3s), I get grpclog output.
The command still works OK, but it looks rather ugly.

**To Reproduce**

Run any crictl command.

**Expected behavior**

There should be no such output.

Regular cri-tools works.

**Screenshots**

k3s:
```
tc@k8s:~$ sudo crictl ps
I0623 19:58:13.113910    7075 clientconn.go:431] parsed scheme: ""
I0623 19:58:13.114833    7075 clientconn.go:431] scheme "" not registered, fallback to default scheme
I0623 19:58:13.115289    7075 asm_amd64.s:1337] ccResolverWrapper: sending new addresses to cc: [{/var/run/crio/crio.sock 0  <nil>}]
I0623 19:58:13.115558    7075 clientconn.go:785] ClientConn switching balancer to "pick_first"
I0623 19:58:13.115907    7075 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc00061c280, CONNECTING
I0623 19:58:13.116464    7075 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc00061c280, READY
I0623 19:58:13.116839    7075 clientconn.go:431] parsed scheme: ""
I0623 19:58:13.117103    7075 clientconn.go:431] scheme "" not registered, fallback to default scheme
I0623 19:58:13.117359    7075 asm_amd64.s:1337] ccResolverWrapper: sending new addresses to cc: [{/var/run/crio/crio.sock 0  <nil>}]
I0623 19:58:13.117638    7075 clientconn.go:785] ClientConn switching balancer to "pick_first"
I0623 19:58:13.117904    7075 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc00061c5b0, CONNECTING
I0623 19:58:13.118322    7075 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc00061c5b0, READY
CONTAINER ID        IMAGE                                                              CREATED             STATE               NAME                ATTEMPT             POD ID
7c4815a46d670       2ee68ed074c6e06374666ad34098fb5a3a9602ac32c803acbdcc563523a902e1   26 minutes ago      Running             coredns             1                   c3f5d5f6bca04
```
cri-tools:
```
tc@k8s:~$ sudo ./crictl ps
CONTAINER ID        IMAGE                                                              CREATED             STATE               NAME                ATTEMPT             POD ID
7c4815a46d670       2ee68ed074c6e06374666ad34098fb5a3a9602ac32c803acbdcc563523a902e1   24 minutes ago      Running             coredns             1                   c3f5d5f6bca04
```

**Additional context**

custom build of k3s: `k3s version dev (HEAD)`

**Comment by galal-hussein** [comment] 2019-06-25 17:07
@afbjorklund I wasn't able to reproduce the issue with the latest build of the master:
```
sudo ./k3s crictl ps
CONTAINER ID        IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID
69c61f8169d7c       4a065d8dfa588       20 hours ago        Running             lb-port-443         0                   0e76ce900af1c
a6373d611481b       98768a8bf3fed       20 hours ago        Running             traefik             0                   dc6b158624ac6
1b6f004404c09       4a065d8dfa588       20 hours ago        Running             lb-port-80          0                   0e76ce900af1c
535d1fa7ab95e       2ee68ed074c6e       20 hours ago        Running             coredns             0                   89e3b99b5c3b0
```
Can you add the steps for your custom build and how are you running crictl exactly?

**Comment by afbjorklund** [comment] 2019-06-25 18:23
I am using cri-o, maybe that could make a difference ?

`go build -tags "libsqlite3 seccomp no_btrfs netgo osusergo" -ldflags "-w -s" -o k3s ./cmd/server/main.go`

**Comment by afbjorklund** [comment] 2019-06-25 18:31
Ah, just found this little snippet in containerd `init()`:

``` go
        // Discard grpc logs so that they don't mess with our stdio
        grpclog.SetLoggerV2(grpclog.NewLoggerV2(ioutil.Discard, ioutil.Discard, ioutil.Discard))
```

I'm thinking that this has something to do with it.

**Comment by erikwilson** [comment] 2019-06-25 21:18
It looks like you need to compile with the ctrd tag.

**Comment by afbjorklund** [comment] 2019-06-26 16:59
> It looks like you need to compile with the ctrd tag.

That might have to be the workaround for now, yes.

**Comment by erikwilson** [comment] 2019-06-26 17:08
Is there a reason not to?

**Comment by afbjorklund** [comment] 2019-06-26 18:17
Don't really need _both_ containerd and crio, but I'm not sure how much extra baggage it brings anyway.
Not sure that I will try to bundle cri-o with k3s, as it seems to be working just fine as a stand-alone binary.

**Comment by brandond** [comment] 2020-12-05 00:19
Closing due to age.

**Closed by brandond** 2020-12-05 00:19 UTC
Labels: status/more-info
