### ISSUE TITLE
suse12.5, k3s start error, when enable dual stack

### ISSUE THREAD

**Issue by cm1366034465** [k3s-io/k3s#9303] opened 2024-01-26 06:26 UTC
**Environmental Info:**
K3s Version: v1.27.1+k3s1

Node(s) CPU architecture, OS, and Version: 

1. node, 8c16G,
1. arch: x86
1. OS: sles 12.5
1. kernel: 4.12.14-122.88-default   or   4.12.14-120-default

Cluster Configuration: Single Node with sqlite

**Describe the bug:**

when install k3s when dual stack, k3s service failed

**Steps To Reproduce:**

- set node ipv6 addr and set sysctl value like this: 
```
net.ipv6.conf.all.disable_ipv6 = 0
net.ipv6.conf.default.disable_ipv6 = 0
net.ipv6.conf.lo.disable_ipv6 = 0
```

- set cluster_cidr and serivce_cidr with dual stack config:
```
--cluster-cidr=113.122.0.0/16,2001:cafe:42:0::/56 --service-cidr=113.123.0.0/16,2001:cafe:42:1::/112
```

- Installed K3s
k3s.service
```
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target
After=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=-/etc/default/%N
EnvironmentFile=-/etc/sysconfig/%N
EnvironmentFile=-/etc/systemd/system/k3s.service.env
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=/bin/sh -xc '! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service'
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStartPre=-/sbin/modprobe ip_vs
ExecStartPre=-/sbin/modprobe ip_vs_rr
ExecStartPre=-/sbin/modprobe ip_vs_wrr
ExecStartPre=-/sbin/modprobe ip_vs_sh
ExecStartPre=-/sbin/modprobe nf_conntrack
ExecStart=/usr/local/bin/k3s \
    server \
        '--write-kubeconfig' \
        '/dev/null' \
        '--write-kubeconfig-mode' \
        '666' \
        '--cluster-cidr' \
        '113.122.0.0/16,2001:cafe:42:0::/56' \
        '--service-cidr' \
        '113.123.0.0/16,2001:cafe:42:1::/112' \
        '--service-node-port-range' \
        '400-32767' \
        '--node-name' \
        'uap-node' \
        '--docker' \
        '--disable' \
        'traefik' \
        '--disable' \
        'coredns' \
        '--cluster-dns' \
        '113.123.0.10' \
        '--disable' \
        'local-storage' \
        '--kube-proxy-arg=proxy-mode=ipvs' \
        '--kubelet-arg=container-log-max-files=5' \
        '--kubelet-arg=container-log-max-size=100Mi' \
        '--resolv-conf=/etc/rancher/k3s/resolv.conf' \
        '--kubelet-arg=eviction-hard=imagefs.available<0.00000001%,nodefs.available<0.00000001%' \
        '--kubelet-arg=eviction-minimum-reclaim=imagefs.available=0.00000001%,nodefs.available=0.00000001%' \
        '--kube-proxy-arg=proxy-mode=ipvs' \
        '--kubelet-arg=config=/etc/rancher/k3s/kubelet.config' \



linux-4123:~# cat /etc/rancher/k3s/kubelet.config
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
imageGCHighThresholdPercent: 100
containerLogMaxSize: 100Mi
containerLogMaxFiles: 5


linux-4123:~ # cat /etc/rancher/k3s/resolv.conf
nameserver 8.8.8.8
nameserver 114.114.114.114
nameserver 8.8.8.8
nameserver 114.114.114.114

```

**Expected behavior:**

k3s running normally

**Actual behavior:**

k3s start failed

**Additional context / logs:**

```
Jan 26 13:54:00 linux-4123 k3s[30020]: time="2024-01-26T13:54:00+08:00" level=info msg="Proxy done" err="context canceled" url="wss://127.0.0.1:6443/v1-k3s/connect"
Jan 26 13:54:00 linux-4123 k3s[30020]: time="2024-01-26T13:54:00+08:00" level=info msg="error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF"
Jan 26 13:54:00 linux-4123 k3s[30020]: I0126 13:54:00.867510   30020 event.go:307] "Event occurred" object="kube-system/metrics-server-service" fieldPath="" kind="Addon" apiVersion="k3s.cattle.io/v1" type="Normal" reason="ApplyingManifest" message="Applying manifest at \"/var/lib/rancher/k3s/server/manifests/metrics-server/metrics-server-service.yaml\""
Jan 26 13:54:00 linux-4123 k3s[30020]: time="2024-01-26T13:54:00+08:00" level=info msg="Handling backend connection request [uap-node]"
Jan 26 13:54:00 linux-4123 k3s[30020]: I0126 13:54:00.891723   30020 kube.go:151] Node controller sync successful
Jan 26 13:54:00 linux-4123 k3s[30020]: I0126 13:54:00.891823   30020 vxlan.go:140] VXLAN config: VNI=1 Port=0 GBP=false Learning=false DirectRouting=false
Jan 26 13:54:00 linux-4123 k3s[30020]: time="2024-01-26T13:54:00+08:00" level=fatal msg="flannel exited: Link not found"
Jan 26 13:54:01 linux-4123 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Jan 26 13:54:01 linux-4123 systemd[1]: k3s.service: Unit entered failed state.
Jan 26 13:54:01 linux-4123 systemd[1]: k3s.service: Failed with result 'exit-code'.
Jan 26 13:54:06 linux-4123 systemd[1]: k3s.service: Service RestartSec=5s expired, scheduling restart.
Jan 26 13:54:06 linux-4123 systemd[1]: Stopped Lightweight Kubernetes.
Jan 26 13:54:06 linux-4123 systemd[1]: Starting Lightweight Kubernetes...
```

k3s log output that “flannel exited: Link not found” and the flannel interfaces **flannel-v6.1** were not created:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:b8:39:45 brd ff:ff:ff:ff:ff:ff
    inet 172.17.7.207/23 brd 172.17.7.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:feb8:3945/64 scope link
       valid_lft forever preferred_lft forever
4: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 02:bf:81:de:2f:b3 brd ff:ff:ff:ff:ff:ff
7: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:cf:a0:1a:0c brd ff:ff:ff:ff:ff:ff
    inet 11.23.45.2/16 brd 11.23.255.255 scope global docker0
       valid_lft forever preferred_lft forever
8: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default
    link/ether ae:5b:dd:3a:9c:51 brd ff:ff:ff:ff:ff:ff
    inet 113.123.0.1/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 113.123.179.109/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
9: flannel.1: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN group default
    link/ether 0e:ca:2a:2d:3e:c6 brd ff:ff:ff:ff:ff:ff
```

**the flannel nic info:**
```
linux-4123:~ # ip -d link show dev flannel.1
9: flannel.1: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN mode DEFAULT group default
    link/ether 0e:ca:2a:2d:3e:c6 brd ff:ff:ff:ff:ff:ff promiscuity 0
    vxlan id 1 local 172.17.7.207 dev eth0 srcport 0 0 dstport 8472 nolearning ageing 300 udpcsum noudp6zerocsumtx noudp6zerocsumrx addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
linux-4123:~ # ip a|grep flannel
9: flannel.1: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN group default
```

**Comment by brandond** [comment] 2024-01-26 08:09
Please use the latest 1.27, 1.28, or 1.29 release. v1.27.1 is several months old and there have been some dual stack fixes since it was released.

Also, it appears that eth0 only has a link-local ipv6 address. Is this host properly prepared to use ipv6?

**Comment by cm1366034465** [comment] 2024-01-26 08:51
**K3s Version: v1.29.0+k3s1**
```
https://github.com/k3s-io/k3s/releases/download/v1.29.0%2Bk3s1/k3s
```
- k3s logs
```
Jan 26 16:42:59 linux-4123 k3s[8456]: time="2024-01-26T16:42:59+08:00" level=info msg="cri-dockerd is now running"
Jan 26 16:42:59 linux-4123 k3s[8456]: time="2024-01-26T16:42:59+08:00" level=info msg="Running kubelet --address=0.0.0.0 --allowed-unsafe-sysctls=net.ipv4.ip_forward,net.ipv6.conf.all.forwarding --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=cgroupfs --client-ca-file=/var/lib/rancher/k3s/agent/client-ca.crt --cloud-provider=external --cluster-dns=113.123.0.10 --cluster-domain=cluster.local --config=/etc/rancher/k3s/kubelet.config --container-log-max-files=5 --container-log-max-size=100Mi --container-runtime-endpoint=unix:///run/k3s/cri-dockerd/cri-dockerd.sock --eviction-hard=imagefs.available<0.00000001%,nodefs.available<0.00000001 --eviction-minimum-reclaim=imagefs.available=0.00000001%,nodefs.available=0.00000001 --fail-swap-on=false --feature-gates=CloudDualStackNodeIPs=true --healthz-bind-address=127.0.0.1 --hostname-override=uap-node --kubeconfig=/var/lib/rancher/k3s/agent/kubelet.kubeconfig --node-ip=172.17.7.207,fe80::250:56ff:feb8:3945 --node-labels= --pod-infra-container-image=rancher/mirrored-pause:3.6 --pod-manifest-path=/var/lib/rancher/k3s/agent/pod-manifests --read-only-port=0 --resolv-conf=/etc/rancher/k3s/resolv.conf --serialize-image-pulls=false --tls-cert-file=/var/lib/rancher/k3s/agent/serving-kubelet.crt --tls-private-key-file=/var/lib/rancher/k3s/agent/serving-kubelet.key"
Jan 26 16:42:59 linux-4123 k3s[8456]: time="2024-01-26T16:42:59+08:00" level=info msg="Connecting to proxy" url="wss://127.0.0.1:6443/v1-k3s/connect"
Jan 26 16:42:59 linux-4123 k3s[8456]: time="2024-01-26T16:42:59+08:00" level=info msg="Handling backend connection request [uap-node]"
Jan 26 16:43:00 linux-4123 k3s[8456]: time="2024-01-26T16:43:00+08:00" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:6443/v1-k3s/readyz: 500 Internal Server Error"



Jan 26 16:43:01 linux-4123 k3s[8456]: I0126 16:43:01.220577    8456 desired_state_of_world_populator.go:151] "Desired state populator starts to run"
Jan 26 16:43:01 linux-4123 k3s[8456]: I0126 16:43:01.220697    8456 reconciler_new.go:29] "Reconciler: start to sync state"
Jan 26 16:43:01 linux-4123 k3s[8456]: I0126 16:43:01.288633    8456 factory.go:221] Registration of the systemd container factory successfully
Jan 26 16:43:01 linux-4123 k3s[8456]: I0126 16:43:01.288869    8456 factory.go:219] Registration of the crio container factory failed: Get "http://%2Fvar%2Frun%2Fcrio%2Fcrio.sock/info": dial unix /var/run/crio/crio.sock: connect: no such file or directory
Jan 26 16:43:01 linux-4123 k3s[8456]: I0126 16:43:01.288930    8456 factory.go:219] Registration of the containerd container factory failed: unable to create containerd client: containerd: cannot unix dial containerd api service: dial unix /run/containerd/containerd.sock: connect: no such file or directory



Jan 26 16:43:02 linux-4123 k3s[8456]: I0126 16:43:02.130404    8456 tokencleaner.go:112] "Starting token cleaner controller"
Jan 26 16:43:02 linux-4123 k3s[8456]: I0126 16:43:02.130441    8456 shared_informer.go:311] Waiting for caches to sync for token_cleaner
Jan 26 16:43:02 linux-4123 k3s[8456]: I0126 16:43:02.130453    8456 shared_informer.go:318] Caches are synced for token_cleaner
Jan 26 16:43:02 linux-4123 k3s[8456]: time="2024-01-26T16:43:02+08:00" level=info msg="Stopped tunnel to 127.0.0.1:6443"
Jan 26 16:43:02 linux-4123 k3s[8456]: time="2024-01-26T16:43:02+08:00" level=info msg="Connecting to proxy" url="wss://172.17.7.207:6443/v1-k3s/connect"
Jan 26 16:43:02 linux-4123 k3s[8456]: time="2024-01-26T16:43:02+08:00" level=info msg="Proxy done" err="context canceled" url="wss://127.0.0.1:6443/v1-k3s/connect"
Jan 26 16:43:02 linux-4123 k3s[8456]: time="2024-01-26T16:43:02+08:00" level=info msg="error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF"
Jan 26 16:43:02 linux-4123 k3s[8456]: I0126 16:43:02.155845    8456 certificate_controller.go:115] "Starting certificate controller" name="csrsigning-kubelet-serving"
Jan 26 16:43:02 linux-4123 k3s[8456]: I0126 16:43:02.155885    8456 shared_informer.go:311] Waiting for caches to sync for certificate-csrsigning-kubelet-serving
Jan 26 16:43:02 linux-4123 k3s[8456]: I0126 16:43:02.155924    8456 dynamic_serving_content.go:132] "Starting controller" name="csr-controller::/var/lib/rancher/k3s/server/tls/server-ca.nochain.crt::/var/lib/rancher/k3s/server/tls/server-ca.key"
Jan 26 16:43:02 linux-4123 k3s[8456]: I0126 16:43:02.156308    8456 certificate_controller.go:115] "Starting certificate controller" name="csrsigning-kubelet-client"
Jan 26 16:43:02 linux-4123 k3s[8456]: I0126 16:43:02.156325    8456 shared_informer.go:311] Waiting for caches to sync for certificate-csrsigning-kubelet-client
Jan 26 16:43:02 linux-4123 k3s[8456]: I0126 16:43:02.156341    8456 certificate_controller.go:115] "Starting certificate controller" name="csrsigning-kube-apiserver-client"
Jan 26 16:43:02 linux-4123 k3s[8456]: I0126 16:43:02.156363    8456 shared_informer.go:311] Waiting for caches to sync for certificate-csrsigning-kube-apiserver-client
Jan 26 16:43:02 linux-4123 k3s[8456]: I0126 16:43:02.156369    8456 dynamic_serving_content.go:132] "Starting controller" name="csr-controller::/var/lib/rancher/k3s/server/tls/client-ca.nochain.crt::/var/lib/rancher/k3s/server/tls/client-ca.key"
Jan 26 16:43:02 linux-4123 k3s[8456]: I0126 16:43:02.156348    8456 dynamic_serving_content.go:132] "Starting controller" name="csr-controller::/var/lib/rancher/k3s/server/tls/client-ca.nochain.crt::/var/lib/rancher/k3s/server/tls/client-ca.key"
Jan 26 16:43:02 linux-4123 k3s[8456]: I0126 16:43:02.156445    8456 controllermanager.go:735] "Started controller" controller="certificatesigningrequest-signing-controller"
Jan 26 16:43:02 linux-4123 k3s[8456]: I0126 16:43:02.156641    8456 certificate_controller.go:115] "Starting certificate controller" name="csrsigning-legacy-unknown"
Jan 26 16:43:02 linux-4123 k3s[8456]: I0126 16:43:02.156651    8456 shared_informer.go:311] Waiting for caches to sync for certificate-csrsigning-legacy-unknown
Jan 26 16:43:02 linux-4123 k3s[8456]: I0126 16:43:02.156668    8456 dynamic_serving_content.go:132] "Starting controller" name="csr-controller::/var/lib/rancher/k3s/server/tls/server-ca.nochain.crt::/var/lib/rancher/k3s/server/tls/server-ca.key"
Jan 26 16:43:02 linux-4123 k3s[8456]: I0126 16:43:02.162660    8456 apiserver.go:52] "Watching apiserver"
Jan 26 16:43:02 linux-4123 k3s[8456]: time="2024-01-26T16:43:02+08:00" level=info msg="Handling backend connection request [uap-node]"
Jan 26 16:43:02 linux-4123 k3s[8456]: I0126 16:43:02.177129    8456 topology_manager.go:215] "Topology Admit Handler" podUID="5c6de14a-ee8f-413f-b7b9-02d782180b21" podNamespace="kube-system" podName="metrics-server-54dc485875-xnxjz"
Jan 26 16:43:02 linux-4123 k3s[8456]: time="2024-01-26T16:43:02+08:00" level=info msg="Tunnel authorizer set Kubelet Port 10250"
Jan 26 16:43:02 linux-4123 k3s[8456]: I0126 16:43:02.185380    8456 kube.go:144] Node controller sync successful
Jan 26 16:43:02 linux-4123 k3s[8456]: I0126 16:43:02.186087    8456 vxlan.go:141] VXLAN config: VNI=1 Port=0 GBP=false Learning=false DirectRouting=false
Jan 26 16:43:02 linux-4123 k3s[8456]: time="2024-01-26T16:43:02+08:00" level=fatal msg="flannel exited: failed to register flannel network: Link not found"
Jan 26 16:43:02 linux-4123 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Jan 26 16:43:02 linux-4123 systemd[1]: k3s.service: Unit entered failed state.
Jan 26 16:43:02 linux-4123 systemd[1]: k3s.service: Failed with result 'exit-code'.
```

**Comment by brandond** [comment] 2024-01-26 19:26
`Jan 26 16:43:02 linux-4123 k3s[8456]: time="2024-01-26T16:43:02+08:00" level=fatal msg="flannel exited: failed to register flannel network: Link not found"`

For some reason the vxlan backend is getting a `Link not found` error when creating the vxlan interfaces. It is unclear if this is coming from the ipv4 or ipv6 vxlan device setup, but since your ipv6 setup looks a little odd, I suspect it's on that side.

Can you try assigning your interface an actual globally-routable ipv6 address, and try again? Either that or set `--node-ip=<ipv4>,<ipv6>` with the addresses you'd like it to use. You might also see if setting `--flannel-iface=eth0` helps.

**Comment by cm1366034465** [comment] 2024-01-29 06:31
**ipv6 address**
```
ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:b8:39:45 brd ff:ff:ff:ff:ff:ff
    inet 172.17.7.207/23 brd 172.17.7.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fd6d:172:17:6::207/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:feb8:3945/64 scope link
       valid_lft forever preferred_lft forever
```

**node-ip**
```
172.17.7.207,fd6d:172:17:6::207
```

**K3s Version**
```
v1.27.0+k3s1   or  v1.29.0+k3s1
```

**Result:**
Referring to the above configuration, I tried again, but still reported a similar error,Could it be related to the suse kernel version? But I can only upgrade suse kernel version to 4.12.14-122.88-default
```
Jan 29 13:42:54 linux-4123 k3s[15043]: time="2024-01-29T13:42:54+08:00" level=info msg="Connecting to proxy" url="wss://172.17.7.207:6443/v1-k3s/connect"
Jan 29 13:42:54 linux-4123 k3s[15043]: time="2024-01-29T13:42:54+08:00" level=info msg="Proxy done" err="context canceled" url="wss://127.0.0.1:6443/v1-k3s/connect"
Jan 29 13:42:54 linux-4123 k3s[15043]: time="2024-01-29T13:42:54+08:00" level=info msg="error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF"
Jan 29 13:42:54 linux-4123 k3s[15043]: I0129 13:42:54.624260   15043 kube.go:151] Node controller sync successful
Jan 29 13:42:54 linux-4123 k3s[15043]: I0129 13:42:54.624307   15043 vxlan.go:140] VXLAN config: VNI=1 Port=0 GBP=false Learning=false DirectRouting=false
Jan 29 13:42:54 linux-4123 k3s[15043]: I0129 13:42:54.624461   15043 controllermanager.go:638] "Started controller" controller="replicaset"
Jan 29 13:42:54 linux-4123 k3s[15043]: time="2024-01-29T13:42:54+08:00" level=fatal msg="flannel exited: Link not found"
Jan 29 13:42:54 linux-4123 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Jan 29 13:42:54 linux-4123 systemd[1]: k3s.service: Unit entered failed state.
Jan 29 13:42:54 linux-4123 systemd[1]: k3s.service: Failed with result 'exit-code'
```

suse info:
```
cat /etc/os-release
NAME="SLES"
VERSION="12-SP5"
VERSION_ID="12.5"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP5"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp5"


uname -r
4.12.14-120-default
```

**Comment by brandond** [comment] 2024-01-29 17:23
cc @manuelbuil

**Comment by manuelbuil** [comment] 2024-01-30 10:30
SLE 12 is not in the support matrix. It must be something to do with that old OS. If you still want to continue debugging, the problem is in this flannel call: https://github.com/flannel-io/flannel/blob/master/pkg/backend/vxlan/device.go#L86 that uses this library: https://github.com/vishvananda/netlink. That library uses syscalls to get network information from the kernel. Perhaps the syscalls it uses are not supported in SLE12 yet

**Comment by cm1366034465** [comment] 2024-02-04 02:36
Suse should be a paid linux, I can not install other versions of suse or upgrade suse kernel version, so I would like to confirm which suse versions support the installation of k3s dual stack, thank you.  @manuelbuil

**Comment by manuelbuil** [comment] 2024-02-05 10:46
> Suse should be a paid linux, I can not install other versions of suse or upgrade suse kernel version, so I would like to confirm which suse versions support the installation of k3s dual stack, thank you. @manuelbuil

If you have a SUSE license, please contact your support to get help. Here is the support matrix: https://www.suse.com/suse-k3s/support-matrix/all-supported-versions/k3s-v1-29/

**Comment by brandond** [comment] 2024-02-05 16:11
Closing as SLE12 is not on the support matrix.

**Closed** 2024-02-05 16:11 UTC
