### ISSUE TITLE
Helm charts not being deployed, when accessing cluster remotely

### ISSUE THREAD

**Issue by thiemok** [k3s-io/k3s#251] opened 2019-03-20 21:16 UTC
**Describe the bug**
When trying to deploy a helm chart manifest using `kubectl apply` while accessing the cluster remotely kubectl returns successful, but the chart is never actually deployed.

**To Reproduce**
* Configure a local kubectl to remotely access your cluster
* Copy the default traefik manifest and make a change
```
apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: stable/traefik
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"
    debug.enabled: "true"
```
* Run `kubectl apply -f traefik.yaml`

**Expected behavior**
The traefik configuration is changed and a new pod is launched to replace the outdated one.

**Comment by kyleterry** [comment] 2019-03-22 04:40
I don't even think this works locally. I tried it on the master and it didn't deploy.

**Comment by mxplusb** [comment] 2019-03-28 11:45
I can confirm this doesn't work locally.

**Comment by erikwilson** [comment] 2019-03-29 00:55
Are you running k3s with `--no-deploy traefik`?

**Comment by thiemok** [comment] 2019-03-29 06:34
No, I'm running with default options

**Comment by erikwilson** [comment] 2019-03-29 15:23
If you don't want k3s to manage traefik then just launch the server with `--no-deploy traefik`.

```sh
erik@lubuntu:~/go/src/github.com/rancher/k3s$ ./install.sh --no-deploy traefik
...
erik@lubuntu:~/go/src/github.com/rancher/k3s$ cat >custom-traefik.yaml
apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: stable/traefik
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"
    debug.enabled: "true"
erik@lubuntu:~/go/src/github.com/rancher/k3s$ kubectl get pods --all-namespaces
NAMESPACE     NAME                       READY   STATUS    RESTARTS   AGE
kube-system   coredns-7748f7f6df-k9bw6   1/1     Running   0          8s
erik@lubuntu:~/go/src/github.com/rancher/k3s$ kubectl apply -f custom-traefik.yaml 
helmchart.k3s.cattle.io/traefik created
erik@lubuntu:~/go/src/github.com/rancher/k3s$ kubectl get pods --all-namespaces
NAMESPACE     NAME                             READY   STATUS      RESTARTS   AGE
kube-system   coredns-7748f7f6df-k9bw6         1/1     Running     0          2m21s
kube-system   helm-install-traefik-8nvs8       0/1     Completed   0          2m2s
kube-system   svclb-traefik-6d4d77b959-fm5lt   2/2     Running     0          115s
kube-system   traefik-6487fddfff-6nzx7         1/1     Running     0          115s
erik@lubuntu:~/go/src/github.com/rancher/k3s$ kubectl logs -n kube-system traefik-6487fddfff-6nzx7
{"level":"info","msg":"Using TOML configuration file /config/traefik.toml","time":"2019-03-29T15:20:05Z"}
{"level":"info","msg":"No tls.defaultCertificate given for https: using the first item in tls.certificates as a fallback.","time":"2019-03-29T15:20:05Z"}
{"level":"info","msg":"Traefik version v1.7.9 built on 2019-02-11_11:36:32AM","time":"2019-03-29T15:20:05Z"}
{"level":"debug","msg":"Global configuration loaded {\"LifeCycle\":{\"RequestAcceptGraceTimeout\":0,\"GraceTimeOut\":10000000000},\"GraceT
```

**Comment by thiemok** [comment] 2019-03-30 18:13
I'm not asking about not managing traefik, that was just an simple example.
But I guess updating charts that are deployed from `/var/lib/rancher/k3s/server/manifests` through kubectl is not intended usage?

**Comment by stove-panini** [comment] 2019-06-23 23:01
I can confirm this happens to me (using the `stable/unifi` helm chart) no matter if applied locally, remotely, or by putting the manifest directly in `/var/lib/rancher/k3s/server/manifests`.

Curiously, it worked once on a fresh install, but no updates are applied. Even if I delete the namespace I created for it, it never gets redeployed.

**Comment by skjnldsv** [comment] 2020-03-02 10:23
Same here :(

How do I force update any edits made on /var/lib/rancher/k3s/server/manifests ?

**Comment by mcwienczek** [comment] 2020-06-14 14:57
Same here

**Comment by brandond** [comment] 2020-12-05 00:31
Closing due to age.

**Closed by brandond** 2020-12-05 00:31 UTC
Labels: status/more-info
