### ISSUE TITLE
Job for k3s.service failed because the control process exited with error code

### ISSUE THREAD

**Issue by Aliabbask08** [k3s-io/k3s#556] opened 2019-06-20 12:22 UTC
Hello Team,

Trying to run k3s cluster on raspberrypi using official doc but causing this issue.
● k3s.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-06-20 12:18:07 UTC; 4min 13s ago
     Docs: https://k3s.io
  Process: 1722 ExecStart=/usr/local/bin/k3s server (code=exited, status=1/FAILURE)
  Process: 1719 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 1716 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
 Main PID: 1722 (code=exited, status=1/FAILURE)
      CPU: 2.150s

Jun 20 12:18:06 master systemd[1]: k3s.service: Unit entered failed state.
Jun 20 12:18:06 master systemd[1]: k3s.service: Failed with result 'exit-code'.
Jun 20 12:18:07 master systemd[1]: k3s.service: Service hold-off time over, scheduling restart.
Jun 20 12:18:07 master systemd[1]: Stopped Lightweight Kubernetes.
Jun 20 12:18:07 master systemd[1]: k3s.service: Start request repeated too quickly.
Jun 20 12:18:07 master systemd[1]: Failed to start Lightweight Kubernetes.
Jun 20 12:18:07 master systemd[1]: k3s.service: Unit entered failed state.
Jun 20 12:18:07 master systemd[1]: k3s.service: Failed with result 'exit-code'.

**Comment by erikwilson** [comment] 2019-06-20 13:28
Are you able to provide some more information such as how you are installing and the k3s logs? When using systemd logs you should be able to find the logs in /var/log/syslog or using `journalctl -u k3s.service`

**Comment by Aliabbask08** [comment] 2019-06-20 14:09
![Screen Shot 2019-06-20 at 7 37 55 PM](https://user-images.githubusercontent.com/25411971/59855708-17c87700-9393-11e9-8bc9-b951fb28e306.png)

**Comment by Aliabbask08** [comment] 2019-06-20 14:10
![Screen Shot 2019-06-20 at 7 37 55 PM](https://user-images.githubusercontent.com/25411971/59855750-2d3da100-9393-11e9-8c4d-eb8ace7f4d79.png)

**Comment by Aliabbask08** [comment] 2019-06-20 14:10
![Screen Shot 2019-06-20 at 7 38 49 PM](https://user-images.githubusercontent.com/25411971/59855785-3e86ad80-9393-11e9-8a70-6b7bedac5d1c.png)
This is journalctl -u k3s.service logs

**Comment by erikwilson** [comment] 2019-06-20 14:13
Thanks! The screenshots make it hard to work with, if you can copy & paste the complete line where it says `level=fatal msg="starting tls server:`, hopefully there is more info where the text is cut off.

**Comment by Aliabbask08** [comment] 2019-06-20 14:14
@erikwilson I followed below steps:
1. Edit /boot/cmdline.txt and add cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory
2. curl -sfL https://get.k3s.io | sh -
after this step I'm getting this error

**Comment by Aliabbask08** [comment] 2019-06-21 05:14
> Thanks! The screenshots make it hard to work with, if you can copy & paste the complete line where it says `level=fatal msg="starting tls server:`, hopefully there is more info where the text is cut off.

level=fatal msg="starting tls server: Get https://localhost:6444/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: dial tcp [::1]:6444: connect: connection refused"

**Comment by jtcmedia** [comment] 2019-06-22 01:34
Same problem here when deploying on raspberry pis.

 `journalctl -xe` returns:

```
Jun 22 02:32:01 k3s-master k3s[898]: E0622 02:32:01.103038     898 pod_workers.go:190] Error syncing pod cb649775-8c13-11e9-a5b4-b827ebc766cc ("tiller-deploy-764df4d966-zpq59_kube-system(cb649775-8c13-11e9
```

`systemctl status k3s-server.service` responds with:
```
 k3s-server.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2019-06-22 02:23:48 BST; 6min ago
     Docs: https://k3s.io
  Process: 1242 ExecStart=/usr/local/bin/k3s server (code=exited, status=1/FAILURE)
 Main PID: 1242 (code=exited, status=1/FAILURE)
      CPU: 345ms

Jun 22 02:23:47 k3s-master k3s[1242]:   -v, --v Level                          number for the log level verbosity
Jun 22 02:23:47 k3s-master k3s[1242]:       --version version[=true]           Print version information and quit
Jun 22 02:23:47 k3s-master k3s[1242]:       --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
Jun 22 02:23:47 k3s-master k3s[1242]: time="2019-06-22T02:23:47.813388594+01:00" level=fatal msg="apiserver exited: failed to create listener: failed to listen on 127.0.0.1:6444: listen tcp 127.0.0.1:6444:
Jun 22 02:23:48 k3s-master systemd[1]: k3s-server.service: Service hold-off time over, scheduling restart.
Jun 22 02:23:48 k3s-master systemd[1]: Stopped Lightweight Kubernetes.
Jun 22 02:23:48 k3s-master systemd[1]: k3s-server.service: Start request repeated too quickly.
Jun 22 02:23:48 k3s-master systemd[1]: Failed to start Lightweight Kubernetes.
Jun 22 02:23:48 k3s-master systemd[1]: k3s-server.service: Unit entered failed state.
Jun 22 02:23:48 k3s-master systemd[1]: k3s-server.service: Failed with result 'exit-code'.
```

I deploy using [ansible-k3s-rpi](https://github.com/aapit/ansible-k3s-rpi).

**Comment by jtcmedia** [comment] 2019-06-25 00:59
I think this issue and https://github.com/rancher/k3s/issues/478 might be related. Seems to be an issue with systemd on debian/ubuntu/raspbian because `sudo /usr/local/bin/k3s server &` brings it up fine.

**Comment by tdewitt** [comment] 2019-06-28 15:14
I just had two fresh raspbian lite installed Pi 3 B+ nodes become non responsive after installing k3s.  The installer runs, the service starts and the nodes die almost immediately.  I let them sit overnight, in case they were just locked up temporarily but they're dead.  If I reboot, I have a ~30 second window to get in and stop k3s before it becomes non responsive again.

I've tried with and without `cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory` appended to cmdline.txt, with no change.

**Comment by erikwilson** [comment] 2019-06-28 15:23
Thanks for the info @Aliabbask08, is it possible to share the output of `netstat -tlnp`?

Are you able to find any more info from the logs @tdewitt or how it dies? Kubectl commands work initially but then... hang or produce an error?

If it is possible to try out [v0.7.0-rc1](https://github.com/rancher/k3s/releases/tag/v0.7.0-rc1), I am curious if it helps with the issue at all.

**Comment by tdewitt** [comment] 2019-06-28 15:48
The entire node dies about 20s after service startup.  I measured from when ansible completes (using setup in contrib now so I can do things concurrently) until I'm no longer receiving ping replies.  This is with 0.6.1.  I can try with 0.7.0-rc1 in a little while.  I dump the journal from the intended master node and copy to here in a few minutes.

**Comment by tdewitt** [comment] 2019-06-28 16:34
Just tried with 0.7.0-rc1.  Same results.  Node service seems to be fine.  Master dies.

**Comment by tdewitt** [comment] 2019-06-28 18:27
Swap disabled.  Looked OK but turns out it's not.  This is everything before it dies: https://gist.github.com/tdewitt/75e5342f85b3f6f9d0f5ba3af2d1d685

**Comment by tdewitt** [comment] 2019-06-28 21:18
My problem was networking.  My local network collides with the default networks in k3s.  Moved them to a couple new blocks and all is well.  Thanks @erikwilson for helping me work this out.

**Comment by skarlekar** [comment] 2019-09-23 01:23
@tdewitt Can you kindly explain what you did to resolve this issue? I am having the same failure while starting up the master. Any pointers will be appreciated.

I have edit /etc/dhcpcd.conf and set the static ip as follows:
```
sudo cat >> /etc/dhcpcd.conf
interface eth0
static ip_address=192.168.1.52/24
static routers=192.168.1.1
static domain_name_servers=192.168.1.1
```

 Error as follows:
```
● k3s.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2019-09-22 21:21:09 EDT; 4s ago
     Docs: https://k3s.io
  Process: 19579 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
  Process: 19580 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 19581 ExecStart=/usr/local/bin/k3s server --write-kubeconfig-mode 644 KillMode=process (code=exited, status=1/FAILURE)
 Main PID: 19581 (code=exited, status=1/FAILURE)
```

**Comment by tdewitt** [comment] 2019-09-24 15:44
My problem was that I was colliding with the default networks.  My home
network uses 10.42.0.0/23.  I used the following args to change the network
used by k3s.

```
   --cluster-cidr value                Network CIDR to use for pod IPs
(default: "10.42.0.0/16")
   --service-cidr value                Network CIDR to use for services IPs
(default: "10.43.0.0/16")
```

**Comment by ssedrick** [comment] 2019-10-24 03:46
I'm running into the same issue as @Aliabbask08 . I'm trying to setup the server on a RPI 2B+ and keep getting the error:

> level=fatal msg="starting tls server: Get https://localhost:6444/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: dial tcp [::1]:6444: connect: connection refused"

I'm using version v0.10.0

`netstat -tlnp` produces the following:
![Screenshot from 2019-10-23 22-46-26](https://user-images.githubusercontent.com/8585377/67451801-fef0fc00-f5e6-11e9-8829-2a513a540080.png)


`journalctl -u k3s.service`:
![Screenshot from 2019-10-23 22-44-24](https://user-images.githubusercontent.com/8585377/67451686-b6394300-f5e6-11e9-80f1-f7916ff61810.png)

**Comment by Aliabbask08** [comment] 2019-10-24 07:21
@ssedrick can u please share the steps you follow?
and what are the changes u made in 1. /etc/hosts and 2. /boot/cmdline.txt

**Comment by ssedrick** [comment] 2019-10-24 18:24
I had a clean install of Raspbian Buster. From there I ran the instructions on https://www.k3s.io. Didn't work.

I've done a little bit of troubleshooting, and followed the k3sup project https://k3sup.dev, and that worked. It is using 0.9.1


/etc/hosts:
```
127.0.0.1	localhost
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters

127.0.1.1	k3s-master
```

/boot/cmdline.txt
`console=serial0,115200 console=tty1 root=PARTUUID=6c586e13-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory`

**Comment by otto-dev** [comment] 2019-10-25 12:10
I'm running into what I believe to be the same issue, except that my error message is slightly different. I'm getting

```
[...] level=fatal msg="starting tls server: Get https://127.0.0.1:6444/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: net/http: TLS handshake timeout"
```
More context:
```
Oct 25 13:06:36 alpha1.lan k3s[7877]: I1025 13:06:36.699054    7877 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,RuntimeClass,ResourceQuota.
Oct 25 13:06:37 alpha1.lan k3s[7877]: time="2019-10-25T13:06:37.216363858+01:00" level=info msg="Running kube-controller-manager --allocate-node-cidrs=true --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --cluster-signing-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --leader-elect=false --port=10252 --root-ca-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --secure-port=0 --service-account-private-key-file=/var/lib/rancher/k3s/server/tls/service.key --use-service-account-credentials=true"
Oct 25 13:06:37 alpha1.lan k3s[7877]: time="2019-10-25T13:06:37.228451710+01:00" level=info msg="Running kube-scheduler --bind-address=127.0.0.1 --kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --leader-elect=false --port=10251 --secure-port=0"
Oct 25 13:06:38 alpha1.lan k3s[7877]: I1025 13:06:38.900959    7877 server.go:143] Version: v1.16.2-k3s.1
Oct 25 13:06:38 alpha1.lan k3s[7877]: I1025 13:06:38.905452    7877 defaults.go:91] TaintNodesByCondition is enabled, PodToleratesNodeTaints predicate is mandatory
Oct 25 13:06:39 alpha1.lan k3s[7877]: I1025 13:06:39.029636    7877 controllermanager.go:161] Version: v1.16.2-k3s.1
Oct 25 13:06:39 alpha1.lan k3s[7877]: W1025 13:06:39.049020    7877 authorization.go:47] Authorization is disabled
Oct 25 13:06:39 alpha1.lan k3s[7877]: W1025 13:06:39.051023    7877 authentication.go:79] Authentication is disabled
Oct 25 13:06:39 alpha1.lan k3s[7877]: I1025 13:06:39.054275    7877 deprecated_insecure_serving.go:51] Serving healthz insecurely on [::]:10251
Oct 25 13:06:39 alpha1.lan k3s[7877]: I1025 13:06:39.191349    7877 deprecated_insecure_serving.go:53] Serving insecurely on [::]:10252
Oct 25 13:06:48 alpha1.lan k3s[7877]: time="2019-10-25T13:06:48.187072448+01:00" level=fatal msg="starting tls server: Get https://127.0.0.1:6444/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: net/http: TLS handshake timeout"
Oct 25 13:06:48 alpha1.lan systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
```

Both on Raspberry Pi 3 and Zero.

**Comment by mfriedenhagen** [comment] 2019-10-25 14:42
Just another me-too without any further (real) clues.
* System is a raspberrypi 3+.
* I tried updating from 0.8.1 to 0.10.0 using `systemctl stop k3s.service && curl -sfL https://get.k3s.io |  sh -s - server --no-deploy=traefik`, got above message.
* Then I did a complete k3s-uninstall. That did not help, got above message again.
* Then I just replaced 0.10.0 executable with 0.8.1. Now k3s is up and running again. I had to reapply my tillerless helm charts again and everything was fine.

**Comment by otto-dev** [comment] 2019-10-25 21:34
Can confirm that the issue does not occur with v0.9.1. It's a regression. Maybe we should open a new issue for this?

**Comment by erikwilson** [comment] 2019-10-25 21:53
I am tracking the arm issue in https://github.com/rancher/k3s/issues/939, hopefully this is fixed with https://github.com/rancher/k3s/releases/tag/v0.10.1-rc1 and v0.10.1 will be released here shortly.

**Comment by erikwilson** [comment] 2019-10-27 19:15
Sorry the previous referenced issue was for a segfault, #869 & #970 also have logs for "_TLS handshake timeout_"

**Comment by madyasiwi** [comment] 2019-11-02 06:03
> Can confirm that the issue does not occur with v0.9.1. It's a regression. Maybe we should open a new issue for this?
> 
> Tested on RPI B+ and Zero W

Having similar case with Armbian on OrangePi One/PC.

**Comment by manhluong** [comment] 2019-11-02 13:18
Got similar error on Archlinux, Raspberry PI 3B+, latest version of k3s (`v0.10.2`).

Uninstalled and reinstalled `v0.9.1` with:

`curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v0.9.1 sh -`

k3s service started with no issues.

**Comment by Rambou** [comment] 2019-11-02 20:08
> Got similar error on Archlinux, Raspberry PI 3B+, latest version of k3s (`v0.10.2`).
> 
> Uninstalled and reinstalled `v0.9.1` with:
> 
> `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v0.9.1 sh -`
> 
> k3s service started with no issues.

I've just tested v0.9.1 with Raspberry Pi 3B and Works too!

**Comment by gvanderberg** [comment] 2019-11-03 12:10
downgrading to k3s version 0.9.1 worked for me too.

Running on RPi 3B+ with OS:
```
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

The error I got on version 0.10.2 and 0.10.0 was ``` starting tls server: Get https://127.0.0.1:6444/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: net/http: TLS handshake timeout ```

**Comment by xiaods** [comment] 2019-11-10 00:48
Running on RPi 3B+ with OS:
```
$ k3s --version
k3s version v0.10.2 (8833bfd9)
```

i setup a airdrop environment and networking is completely disabled. so i have to add below add a default route:

```
sudo ip -c address add 192.168.123.123/24 dev eno1
sudo ip route add default via 192.168.123.1
```
then sudo k3s server , it finally raised blow error:
```
https://127.0.0.1:6444/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: net/http: TLS handshake timeout
```
don't know what reason.

**Comment by b0nete** [comment] 2019-11-13 02:07
> Got similar error on Archlinux, Raspberry PI 3B+, latest version of k3s (`v0.10.2`).
> 
> Uninstalled and reinstalled `v0.9.1` with:
> 
> `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v0.9.1 sh -`
> 
> k3s service started with no issues.

Same for here. 
Also with Raspberry PI 3B+ and Arch ARM.
Uninstall k3s 0.10.2 and install 0.9.1 and now works!

**Comment by drestauri** [comment] 2019-11-27 23:22
I had a similar error I was working through for hours and it turned out I needed to update this file on my agent node:
`/etc/systemd/system/k3s-agent.service.env`
Replace the token (even if it appears to be the same) and make sure the K3S_URL matches your server node's IP address and port including the https:// prefix. For example:
`K3S_TOKEN=<your_token>`
`K3S_URL=https://<server_ip>:6443`

**Comment by alepee** [comment] 2020-11-15 15:37
Just ran into the same issue with `k3s version v1.19.3+k3s3 (0e4fbfef)` on RPI4 2GB with a fresh RaspberryOS install. I get it up and running by enable CGROUPS through `cmdline` instruction.

```
cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory
```

**Comment by mfriedenhagen** [comment] 2020-11-17 19:48
I had problems with Raspbian "Buster" because it updated the kernel to major 5. Going back to Linux kernel 4 fixed this for me.

**Comment by alepee** [comment] 2020-11-17 23:16
@mfriedenhagen could it be linked to `iptables` / `nftables` issue ?
https://rancher.com/docs/k3s/latest/en/advanced/#enabling-legacy-iptables-on-raspbian-buster

**Comment by mfriedenhagen** [comment] 2020-11-18 18:48
Hello @alepee , indeed, thanks for the link. I think I will give this a try together with kernel 5.

**Comment by mfriedenhagen** [comment] 2020-11-18 19:59
Hm, I already tried this back in the day. 
```
  339  update-alternatives
  340  update-alternatives iptables
  341  update-alternatives --query iptables
  342  update-alternatives --set iptables
  343  update-alternatives --set iptables /usr/sbin/iptables-legacy
  344  iptables --version
  345  k3s check-config
```
but it did not work with the new kernel back then. 
What I had to do was restore the kernel back to "Linux raspberrypi 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux" by running:
`rpi-update e1050e94821a70b2e4c72b318d6c6c968552e9a2`

**Comment by mfriedenhagen** [comment] 2020-11-18 20:30
* I just gave it another try following  and ran `apt-get update ; apt-get -y dist-upgrade`. 
* Before rebooting, I ran `systemctl stop k3s.service ; /usr/local/bin/k3s-killall.sh` to really stop everything
* Now I am on "Linux raspberrypi 5.4.72-v7+ #1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux" and everything seems to be up and running.
* So basically, this issue may be another problem, sorry for the noise.
* Thanks again @alepee.

**Comment by johnrkriter** [comment] 2020-11-28 04:20
Ran the following and resulted in successful deployment
- Pi 4B 4Gb
- fresh raspbian install based on 2020-08-20-raspios-buster-armhf-lite
- Full upgrade to all system components
- modify `/boot/cmdline.txt` to add `cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1`
- execute `curl -sfL https://get.k3s.io | sh -` and install version `v1.19.3+k3s3`
- installation works fine, and results in a working master, same as @alepee

**Comment by brandond** [comment] 2020-12-05 00:17
Closing due to age. Anyone experiencing similar problems should open a new issue and fill out the template.

**Closed by brandond** 2020-12-05 00:17 UTC
Labels: status/more-info

**Comment by cianiandreadev** [comment] 2021-04-14 13:18
Don't know if it may help but I fixed this issue by adding these at the end of `/boot/firmware/cmdline.txt`

[...]`cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory`

**Comment by quangthe** [comment] 2021-07-02 15:23
> curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v0.9.1 sh -

Thanks it saves me a day!

**Comment by quangthe** [comment] 2021-07-02 15:24
> Got similar error on Archlinux, Raspberry PI 3B+, latest version of k3s (`v0.10.2`).
> 
> Uninstalled and reinstalled `v0.9.1` with:
> 
> `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v0.9.1 sh -`
> 
> k3s service started with no issues.

Thanks it saves me a day!

**Comment by brandond** [comment] 2021-07-02 16:23
That's a really old version of k3s, I wouldn't recommend using it.

**Comment by quangthe** [comment] 2021-07-03 04:44
> That's a really old version of k3s, I wouldn't recommend using it.

Luckily, after uninstall the v0.9.1, and try with latest version again, now it works! Thanks @brandond

**Comment by tylerharpool** [comment] 2021-08-25 14:55
@quangthe Do you have any idea why we need to install v0.9.1 before the latest version to get it to work? Surely this is a bug.

**Comment by brandond** [comment] 2021-08-25 16:27
They didn't **have** to install the old version first... they're saying that the new version worked for them, and that they uninstalled the old version they were previously using before trying the new version.

**Comment by tylerharpool** [comment] 2021-09-13 18:32
@brandond Thank you for correcting my misunderstanding. Was able to get it working by upgrading:
```
Installed:
  kernel-4.18.0-305.17.1.el8_4.x86_64          kernel-core-4.18.0-305.17.1.el8_4.x86_64 
  kernel-modules-4.18.0-305.17.1.el8_4.x86_64 
Removed:
  kernel-4.18.0-240.10.1.el8_3.x86_64          kernel-core-4.18.0-240.10.1.el8_3.x86_64 
  kernel-modules-4.18.0-240.10.1.el8_3.x86_64 
```

**Comment by doormat18** [comment] 2024-07-25 18:29
Had similar issue on RHEL 9 running on AWS, fixed it with this.

```
systemctl disable nm-cloud-setup.service nm-cloud-setup.timer
reboot
```

**Comment by brandond** [comment] 2024-07-25 18:49
This is covered here: https://docs.k3s.io/installation/requirements?os=rhel#operating-systems

But in general please do not bump years old issues with unrelated comments.
