### ISSUE TITLE
Airgap install k3s.service fails, maybe "no default routes found"

### ISSUE THREAD

**Issue by MayanNetwork** [k3s-io/k3s#6265] opened 2022-10-13 12:16 UTC
**Environmental Info:**
K3s Version: 

k3s version v1.25.0+k3s1 (26e94057)
go version go1.19

Node(s) CPU architecture, OS, and Version: 

Linux A10 4.18.0-305.el8.x86_64 #1 SMP Thu Apr 29 08:54:30 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

Airgap, Single cluster first time install on RHEL 8.4

**Describe the bug:**

Upon installing, Airgap K3S, the K3S service exits, 
I believe, "no default routes found", see full attachment.

I saw other older posts, somewhat related, tried and failed, maybe need more details and be specific to my IP addressing.   Do I need to modify the command, INSTALL_K3S_SKIP_DOWNLOAD=true ./install.sh 

**Steps To Reproduce:**

- Installed K3s: 
logged in as root:

mkdir -p /var/lib/rancher/k3s/agent/images/
cp ./k3s-airgap-images-amd64.tar /var/lib/rancher/k3s/agent/images/
-rwxr-xr-x 1 root root 67633152 Jun 22 20:31 /usr/local/bin/k3s

INSTALL_K3S_SKIP_DOWNLOAD=true ./install.sh

**Expected behavior:**

K3S service to complete start

**Actual behavior:**

K3S service exits, 
I believe, "no default routes found", see full attachment.

**Additional context / logs:**

- I have attached the output of the install, systemctl status k3.service, journalctl -xe
- Also attached ifconfig output,  my address is **192.168.10.110**  

[install_125_failed.txt](https://github.com/k3s-io/k3s/files/9776449/install_125_failed.txt)

[IpAddress.txt](https://github.com/k3s-io/k3s/files/9776453/IpAddress.txt)

**Comment by brandond** [comment] 2022-10-13 23:29
Duplicate of https://github.com/k3s-io/k3s/issues/1144 - please see the discussion on that issue.

**Closed by brandond** 2022-10-13 23:29 UTC

**Comment by MayanNetwork** [comment] 2022-10-27 13:14
That #1144 I did not understand, e.g. what values do I use?
my subnet, off of  enp6s0, is 192.168.100.

It did give me a hint to try simply, 

        **ip route add default via 192.168.100.1 dev enp6s0**

That worked even on reboot.
