### ISSUE TITLE
k3s script fails sometimes due to https://update.k3s.io/v1-release/channels/stable being down 

### ISSUE THREAD

**Issue by DiaaUddin** [k3s-io/k3s#7252] opened 2023-04-08 11:14 UTC
**Environmental Info:**
K3s Version: 
curl -sfL https://get.k3s.io | sh - 

Node(s) CPU architecture, OS, and Version: 
amd64, ubuntu, 1 node

Cluster Configuration:
Default, github ci

**Describe the bug:**
the above script stops when trying to download and compare hash for this url [https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt](https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt)
that's after this url fail to provide the correct latest stable version  [ https://update.k3s.io/v1-release/channels/stable](https://update.k3s.io/v1-release/channels/stable) because it was down for the last ~13 hours or so.

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**
throw some error maybe to give more clue to the problem 

**Actual behavior:**
it just gives info downloading k3s then abort, no errors 

**Additional context / logs:**
a temp fix is to `export INSTALL_K3S_CHANNEL="v1.26.3+k3s1"` before installing k3s

<details>
  <summary>logs </summary>
  
 ```
 
Run curl -sfL https://get.k3s.io/ | K3S_KUBECONFIG_MODE=777 sh -x -
+ set -e
+ set -o noglob
+ GITHUB_URL=https://github.com/k3s-io/k3s/releases
+ STORAGE_URL=https://k3s-ci-builds.s3.amazonaws.com/
+ DOWNLOADER=
+ escape 
+ sed -e s/\([][!#$%&()*;<=>?\_`***|***]\)/\\\1/g;
+ printf %s 
+ quote
+ eval set --
+ set --
+ verify_system
+ [ -x /sbin/openrc-run ]
+ [ -x /bin/systemctl ]
+ HAS_SYSTEMD=true
+ return
+ setup_env
+ [ -z  ]
+ CMD_K3S=server
+ verify_k3s_url
+ quote_indent
+ printf  \\\n
+ CMD_K3S_EXEC=server \
+ [ -n  ]
+ [ server = server ]
+ SYSTEM_NAME=k3s
+ sed -e s/[][!#$%&()*;<=>?\_`***|***/[:space:]]/^/g;
+ printf %s k3s
+ valid_chars=k3s
+ [ k3s != k3s ]
+ SUDO=sudo
+ id -u
+ [ 1001 -eq 0 ]
+ [ -n  ]
+ SYSTEMD_TYPE=notify
+ [ -n  ]
+ BIN_DIR=/usr/local/bin
+ sudo sh -c touch /usr/local/bin/k3s-ro-test && rm -rf /usr/local/bin/k3s-ro-test
+ [ -n  ]
+ SYSTEMD_DIR=/etc/systemd/system
+ SERVICE_K3S=k3s.service
+ UNINSTALL_K3S_SH=/usr/local/bin/k3s-uninstall.sh
+ KILLALL_K3S_SH=/usr/local/bin/k3s-killall.sh
+ [ true = true ]
+ FILE_K3S_SERVICE=/etc/systemd/system/k3s.service
+ FILE_K3S_ENV=/etc/systemd/system/k3s.service.env
+ get_installed_hashes
+ sudo sha256sum /usr/local/bin/k3s /etc/systemd/system/k3s.service /etc/systemd/system/k3s.service.env
+ true
+ PRE_INSTALL_HASHES=sha256sum: /usr/local/bin/k3s: No such file or directory
sha256sum: /etc/systemd/system/k3s.service: No such file or directory
sha256sum: /etc/systemd/system/k3s.service.env: No such file or directory
+ [  = true ]
+ INSTALL_K3S_CHANNEL_URL=https://update.k3s.io/v1-release/channels
+ INSTALL_K3S_CHANNEL=stable
+ download_and_verify
+ can_skip_download_binary
+ [  != true ]
+ [  != binary ]
+ return 1
+ setup_verify_arch
+ [ -z  ]
+ uname -m
+ ARCH=x86_64
+ ARCH=amd64
+ SUFFIX=
+ verify_downloader curl
+ command -v curl
+ [ -x /usr/bin/curl ]
+ DOWNLOADER=curl
+ return 0
+ setup_tmp
+ mktemp -d -t k3s-install.XXXXXXXXXX
+ TMP_DIR=/tmp/k3s-install.cVAE3FNcO8
[INFO]  Finding release for channel stable
+ TMP_HASH=/tmp/k3s-install.cVAE3FNcO8/k3s.hash
+ TMP_BIN=/tmp/k3s-install.cVAE3FNcO8/k3s.bin
+ trap cleanup INT EXIT
+ get_release_version
+ [ -n  ]
+ [ -n  ]
+ info Finding release for channel stable
+ echo [INFO]  Finding release for channel stable
+ version_url=https://update.k3s.io/v1-release/channels/stable
+ sed -e s|.*/||
+ curl -w %***url_effective*** -L -s -S https://update.k3s.io/v1-release/channels/stable -o /dev/null
+ VERSION_K3S=stable
[INFO]  Using stable as release
+ info Using stable as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt
+ echo [INFO]  Using stable as release
+ download_hash
+ [ -n  ]
+ HASH_URL=https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt
+ info Downloading hash https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt
+ echo [INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt
+ download /tmp/k3s-install.cVAE3FNcO8/k3s.hash https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt
+ [ 2 -eq 2 ]
+ curl -o /tmp/k3s-install.cVAE3FNcO8/k3s.hash -sfL https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt
+ cleanup
+ code=[22](https://github.com/fastfishio/gc-grocery-api/actions/runs/4644783950/jobs/8220254385#step:4:23)
+ set +e
+ trap - EXIT
+ rm -rf /tmp/k3s-install.cVAE3FNcO8
+ exit 22

```
 </details>

**Comment by migs35323** [comment] 2023-04-08 13:40
i am getting a image pull back off when trying to use the automated upgrade controller with the v1.24
not sure if this is related

**Comment by brandond** [comment] 2023-04-08 19:37
@migs35323 no that would not be related. What image are you trying to pull?

**Comment by brandond** [comment] 2023-04-08 19:39
Closing this as a duplicate of https://github.com/k3s-io/k3s/issues/6052#issuecomment-1231692473

As discussed elsewhere, the channel server is on infra shared with Rancher's content distribution system. This system is occasionally overwhelmed by traffic. When this happens, you can use INSTALL_K3S_VERSION to specify a release you'd like to install, which will bypass the channel server lookup.

**Closed by brandond** 2023-04-08 19:39 UTC
