### ISSUE TITLE
Failed to upgrade k3s using rancher from v.18.10 to v1.19.3

### ISSUE THREAD

**Issue by AbelTaylor** [k3s-io/k3s#2462] opened 2020-10-30 02:17 UTC
My original k3s version was v1.18.10, and then I used the upgrade on the rancher interface, the target version was v1.19.3, but it failed. The log is as follows
![image](https://user-images.githubusercontent.com/71317399/97652009-6a8e6480-1a98-11eb-91b1-8c4dbbfda9b8.png)

![image](https://user-images.githubusercontent.com/71317399/97652933-8bf05000-1a9a-11eb-853b-891f39fe4f88.png)

and the events is as follows

![image](https://user-images.githubusercontent.com/71317399/97653064-dd98da80-1a9a-11eb-9b80-816739f80903.png)

the node system is as follows

![image](https://user-images.githubusercontent.com/71317399/97653330-792a4b00-1a9b-11eb-8ffa-a49fbe95c3fb.png)

What should I do

**Comment by brandond** [comment] 2020-10-30 04:59
This should probably be a Rancher issue, although I believe they've fixed it. What version of Rancher are you using?

**Comment by myzhuh** [comment] 2020-10-30 05:53
> This should probably be a Rancher issue, although I believe they've fixed it. What version of Rancher are you using?

Hi , the rancher version is 2.5.1

**Comment by brandond** [comment] 2020-10-30 06:27
This appears to be a duplicate of https://github.com/rancher/rancher/issues/25991

**Comment by brandond** [comment] 2020-10-30 20:49
@myzhuh what OS is this on? May be related to https://github.com/rancher/k3s-upgrade/commit/1df5c3592fcaa9103489086b6a55f4267bdeaae8#commitcomment-40300740

**Comment by myzhuh** [comment] 2020-11-02 03:33
> @myzhuh what OS is this on? May be related to [rancher/k3s-upgrade@1df5c35#commitcomment-40300740](https://github.com/rancher/k3s-upgrade/commit/1df5c3592fcaa9103489086b6a55f4267bdeaae8#commitcomment-40300740) although your screenshot suggests Ubuntu 20.04?

Hi，Are you asking about the operating system of the host where Rancher is located? Is CentOS 7.8, and the k3s cluster is Ubuntu 20.04.1。

**Comment by myzhuh** [comment] 2020-11-02 03:49
> @myzhuh what OS is this on? May be related to [rancher/k3s-upgrade@1df5c35#commitcomment-40300740](https://github.com/rancher/k3s-upgrade/commit/1df5c3592fcaa9103489086b6a55f4267bdeaae8#commitcomment-40300740) although your screenshot suggests Ubuntu 20.04?

This is the log of the queried pod upgrade, which may be helpful.

kubectl describe po apply-k3s-master-plan-on-xa-master-150-with-a8249459eb5ed-44sph -n cattle-system
Name:         apply-k3s-master-plan-on-xa-master-150-with-a8249459eb5ed-44sph
Namespace:    cattle-system
Priority:     0
Node:         xa-master-150/192.168.1.150
Start Time:   Mon, 02 Nov 2020 11:36:29 +0800
Labels:       controller-uid=4350e59c-6c2f-40a7-9ba4-55751bb9f709
              job-name=apply-k3s-master-plan-on-xa-master-150-with-a8249459eb5ed-29b9e
              plan.upgrade.cattle.io/k3s-master-plan=a8249459eb5ed229a113d4c6ec280c44125523cdbc5e5f6888887549
              upgrade.cattle.io/controller=system-upgrade-controller
              upgrade.cattle.io/node=xa-master-150
              upgrade.cattle.io/plan=k3s-master-plan
              upgrade.cattle.io/version=v1.19.3-k3s1
Annotations:  <none>
Status:       Failed
IP:           192.168.1.150
IPs:
  IP:           192.168.1.150
Controlled By:  Job/apply-k3s-master-plan-on-xa-master-150-with-a8249459eb5ed-29b9e
Init Containers:
  drain:
    Container ID:  docker://f3b3f5052f1e5157c57f9be20d303d4b518c38b0e61d6a80265a22ba26343833
    Image:         rancher/kubectl:v1.18.0
    Image ID:      docker-pullable://rancher/kubectl@sha256:468e924fb0e33e8e9700944ecca4ad89fa8c5b080b55936c44974bb880470ae0
    Port:          <none>
    Host Port:     <none>
    Args:
      drain
      xa-master-150
      --pod-selector
      !upgrade.cattle.io/controller
      --ignore-daemonsets
      --delete-local-data
      --force
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 02 Nov 2020 11:36:38 +0800
      Finished:     Mon, 02 Nov 2020 11:37:42 +0800
    Ready:          True
    Restart Count:  0
    Environment:
      SYSTEM_UPGRADE_NODE_NAME:             (v1:spec.nodeName)
      SYSTEM_UPGRADE_POD_NAME:             apply-k3s-master-plan-on-xa-master-150-with-a8249459eb5ed-44sph (v1:metadata.name)
      SYSTEM_UPGRADE_POD_UID:               (v1:metadata.uid)
      SYSTEM_UPGRADE_PLAN_NAME:            k3s-master-plan
      SYSTEM_UPGRADE_PLAN_LATEST_HASH:     a8249459eb5ed229a113d4c6ec280c44125523cdbc5e5f6888887549
      SYSTEM_UPGRADE_PLAN_LATEST_VERSION:  v1.19.3-k3s1
    Mounts:
      /host from host-root (rw)
      /run/system-upgrade/pod from pod-info (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from system-upgrade-token-dlp9r (ro)
Containers:
  upgrade:
    Container ID:   docker://e1d7584ef66069b4dc9b0830ad9dde01f42d77bc10ee906bb195af47bb398c3d
    Image:          rancher/k3s-upgrade:v1.19.3-k3s1
    Image ID:       docker-pullable://rancher/k3s-upgrade@sha256:14e4c9bfadd5239a71ed2815ba5378f47e730a5b3d846c16c45bab5db78d4ad1
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 02 Nov 2020 11:37:51 +0800
      Finished:     Mon, 02 Nov 2020 11:37:51 +0800
    Ready:          False
    Restart Count:  0
    Environment:
      SYSTEM_UPGRADE_NODE_NAME:             (v1:spec.nodeName)
      SYSTEM_UPGRADE_POD_NAME:             apply-k3s-master-plan-on-xa-master-150-with-a8249459eb5ed-44sph (v1:metadata.name)
      SYSTEM_UPGRADE_POD_UID:               (v1:metadata.uid)
      SYSTEM_UPGRADE_PLAN_NAME:            k3s-master-plan
      SYSTEM_UPGRADE_PLAN_LATEST_HASH:     a8249459eb5ed229a113d4c6ec280c44125523cdbc5e5f6888887549
      SYSTEM_UPGRADE_PLAN_LATEST_VERSION:  v1.19.3-k3s1
    Mounts:
      /host from host-root (rw)
      /run/system-upgrade/pod from pod-info (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from system-upgrade-token-dlp9r (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  host-root:
    Type:          HostPath (bare host directory volume)
    Path:          /
    HostPathType:  Directory
  pod-info:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.labels -> labels
      metadata.annotations -> annotations
  system-upgrade-token-dlp9r:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  system-upgrade-token-dlp9r
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  9m56s  default-scheduler  0/3 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules, 2 node(s) didn't match node selector.
  Warning  FailedScheduling  9m56s  default-scheduler  0/3 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules, 2 node(s) didn't match node selector.
  Normal   Scheduled         9m46s  default-scheduler  Successfully assigned cattle-system/apply-k3s-master-plan-on-xa-master-150-with-a8249459eb5ed-44sph to xa-master-150
  Normal   Pulling           9m46s  kubelet            Pulling image "rancher/kubectl:v1.18.0"
  Normal   Pulled            9m39s  kubelet            Successfully pulled image "rancher/kubectl:v1.18.0"
  Normal   Created           9m39s  kubelet            Created container drain
  Normal   Started           9m38s  kubelet            Started container drain
  Normal   Pulling           8m34s  kubelet            Pulling image "rancher/k3s-upgrade:v1.19.3-k3s1"
  Normal   Pulled            8m26s  kubelet            Successfully pulled image "rancher/k3s-upgrade:v1.19.3-k3s1"
  Normal   Created           8m26s  kubelet            Created container upgrade
  Normal   Started           8m25s  kubelet            Started container upgrade

**Comment by cwayne18** [comment] 2022-07-20 16:38
As 1.18 and 1.19 are both EOL, I'd close this out for now, but if the issue is persisting with latest versions please do re-open this!

**Closed by cwayne18** 2022-07-20 16:38 UTC
Labels: area/upgrade
