### ISSUE TITLE
update.k3s.io returning 503

### ISSUE THREAD

**Issue by olix0r** [k3s-io/k3s#6006] opened 2022-08-18 03:52 UTC
Creating a k3s/k3d cluster with a channel referenced like:

```sh
:; k3d cluster create --image=+latest --verbose              
```

is failing with an error:

```log
FATA[0000] error getting K3s version for channel latest: error unmarshalling channelserver response: invalid character '<' looking for beginning of value 
```

Ideally, k3s should return a better error message when it receives a non-2XX response instead of trying to parse the HTML response.

It looks like the update.k3s.io webserver is returning 503 errors:
```console
:; curl -vL  https://update.k3s.io/v1-release/channels/latest
*   Trying 2606:4700:20::ac43:45d1:443...
* Connected to update.k3s.io (2606:4700:20::ac43:45d1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: May 11 00:00:00 2022 GMT
*  expire date: May 10 23:59:59 2023 GMT
*  subjectAltName: host "update.k3s.io" matched cert's "*.k3s.io"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5648f03202c0)
> GET /v1-release/channels/latest HTTP/2
> Host: update.k3s.io
> user-agent: curl/7.74.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 503 
< date: Thu, 18 Aug 2022 03:49:56 GMT
< content-type: text/html
< strict-transport-security: max-age=15552000; includeSubDomains; preload
< cf-cache-status: DYNAMIC
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=UqJUd7UIH%2FXjOBABsOeDCo992xlNhpsV60Z4foTlyVd8wIXmfhlqp0sLJB1gKxMSj6AE5kS6RW%2F0VeYgpUX4GhD3t4EersqWE8v9sD6YnAN5yg4mq0hZMVHebZpC9hiNXTXlSSockxPSAao%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< x-content-type-options: nosniff
< server: cloudflare
< cf-ray: 73c7aeb6ad97982a-SJC
< 
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>openresty/1.15.8.1</center>
</body>
</html>
* Connection #0 to host update.k3s.io left intact
```

This is causing the Linkerd CI to fail...

**Comment by olix0r** [comment] 2022-08-18 05:08
It looks like this endpoint is no longer returning a 503 error.

I'm going to leave this open, though, as it would be great if these errors could be handled properly (i.e. instead of manifesting as a parse error).

**Comment by olix0r** [comment] 2022-08-18 15:50
Also, I realize (now) that `https://update.k3s.io/v1-release/channels/latest` isn't a valid URL; but I was seeing the same errors for `https://update.k3s.io/v1-release/channels`

**Comment by cwayne18** [comment] 2022-08-19 17:28
This would be an issue for k3d I'd think.  SInce the 503 is no longer reproducible I'd like to close this out, but I'd suggest opening an issue against k3d-io/k3d about the error handling

**Closed by cwayne18** 2022-08-19 17:28 UTC

**Comment by iosifnicolae2** [comment] 2022-08-30 12:55
we're getting the same error `503 Service Temporarily Unavailable openresty/1.15.8.1`  when accessing https://update.k3s.io/v1-release/channels
