### ISSUE TITLE
Consider dropping support for armhf

### ISSUE THREAD

**Issue by briandowns** [k3s-io/k3s#3213] opened 2021-04-17 01:12 UTC
Starting with the 1.22 release, we'd like to stop producing armhf builds. It is a significant burden to maintain and is our least used architecture. We see the industry moving primarily to ARM64 for edge devices.

The primary maintenance burden is that CI for it is unreliable and unpredictable. We have had multiple releases delayed and PRs blocked because our armhf builds mysteriously stopped working. Each time, multiple days were sunk into the effort of debugging our build only to find some arbitrary, low level, and unrelated problem in compiling. A few times, we couldn't even root cause; some random code change or library update simply caused the problem to disappear.

Regarding industry adoption, it seems to us that:
	- It is not well tested and supported upstream (both Go and Kubernetes)
	- Fewer images and apps run on it than other architectures
	- Edge devices such as Raspberry Pis are transitioning to arm64 by default
	- There are few experts upstream. When we've run into an issue, it seems like there are few folks able to confidently answer or help us address

We've considered drawing this out to a longer transition period to allow the industry more time to fully standardize on arm64, but we want to speed it up because the burden seriously impedes the team's ability to produce and release.

**Comment by alexellis** [comment] 2021-04-17 07:00
Nobody likes don't extra work for no business benefit, and it sounds like your team is frustrated. 

Removing armhf would be a huge pain for Raspberry Pi users, because ecosystem support in Ubuntu isn't as good as Raspberry Pi OS. Unfortunately there's not been a release of the Raspberry Pi OS 64-bit release since August 2020 and the official, supported OS is 32-bit.

But who am I and why should you listen to me?

https://www.raspberrypi.org/blog/five-years-of-raspberry-pi-clusters/

https://youtube.com/watch?v=jfUpF40--60

https://k3sup.dev

I don't know what the answer is, but this will be noticed and cause pain for many people - course authors, software maintainers, home users.

**Comment by ranjanprj** [comment] 2021-04-17 07:54
For Demo, POC, Educational purposes it's quite an easy option to run on default RPI 32 OS.
If it is supported on RPI 64Bit, than it should be4 fine, but as alexellis there is little movement there, but that should stop things.
But I do understand the enormous effort and little returns that comes out of it.

**Comment by rockaut** [comment] 2021-04-17 12:52
My guess is, that as long there is no default RPi 64Bit OS, there will be some sort of frustration in the community. Maybe you guys can work with Raspberry themselve on this?

**Comment by cjellick** [comment] 2021-04-17 14:38
Full disclosure: I asked @briandowns to write up this issue and am the one advocating to accelerate the timeline to before it's the default arch for pi's.

One other idea I had is that we could somehow take it out of the critical path for CI and get a community maintainer to "own" it. This way, that when it breaks randomly again, we aren't spinning our wheels and pushing out release dates.

Thoughts? Any takers for the maintenance bit? ...might require some refactoring to our CI.

**Comment by cjellick** [comment] 2021-04-17 14:44
Cross linking Darren's Twitter thread where some discussion is happening too https://twitter.com/ibuildthecloud/status/1383264085941178368?s=21

**Comment by nickgerace** [comment] 2021-04-17 14:47
I've seen a lot of Raspberry Pi 3 in the wild still. I think that deprecation could arrive before completely dropping.

Is it possible to drop armhf from CI, but keep publishing builds? Perhaps there can be a disclaimer added as well.

**Comment by cjellick** [comment] 2021-04-17 15:29
That's basically what we do now...when I say it breaks CI, I mean the build breaks. Either just stops compiling or simply trying to start it up results in esoteric errors and panics.

**Comment by cjellick** [comment] 2021-04-17 15:30
But if a breakage didn't make the build go red and we (or a community member) could circle round to fixing it when time allowed, that could help.

**Comment by himslm01** [comment] 2021-04-17 15:39
Please don't.
As Alex said above, the arm64 support for RPi 3/4 is much worse than armhf.
There are many of us who get invaluable experience of multi-node kubernetes clusters by using RPis.

**Comment by franklesniak** [comment] 2021-04-17 15:55
+1 to all the Raspberry Pi arguments to keep support. Really appreciate it!

**Comment by ibuildthecloud** [comment] 2021-04-17 17:16
@alexellis Just to be clear, this isn't an issue of not getting enough in return and we aren't frustrated. This is just a simple, "hey it would be easier to drop 32bit, how much do people care."

I hope we've demonstrated in the past we listen to our users and this is just an attempt at that.

**Comment by cjellick** [comment] 2021-04-17 19:00
@ibuildthecloud is 100% right. I helped with the wording of the issue. We could have been a little clearer that this is primarily intended to solicit opinions from the community on the matter.

**Comment by briandowns** [comment] 2021-04-17 19:35
@cjellick The idea of taking amrhf out of the critical path was echoed when soliciting feedback on the initial draft and if nothing else, seems like a reasonable first step.

**Comment by cjellick** [comment] 2021-04-17 19:41
Oh! @briandowns apologies if I co-opted your idea as my own

**Comment by briandowns** [comment] 2021-04-18 01:05
Nah, not my idea. 😀 Initially I believe it was brought up by @dweomer. It's a good one though but I do agree with @ibuildthecloud that it could very easily fall by the wayside.

**Comment by vielmetti** [comment] 2021-04-18 11:07
If dropping armhf means freeing up cycles from frustrating, hard to debug problems on 32-bit systems, and instead leads to improvements overall in the arm64 ecosystem, I'm all for it.

**Comment by SvenDowideit** [comment] 2021-04-19 02:07
@cjellick do you by any chance have a list of the last few months of issues and pr's that were caused by armhf issues?

it might help some of us work out what we'd be committing to as community maintainers :)

**Comment by vielmetti** [comment] 2021-04-19 13:21
@SvenDowideit I would start by browsing https://github.com/k3s-io/k3s/labels/arch%2Farmhf for all issues tagged with "armhf". More than half of those issues are still open.

**Comment by cjellick** [comment] 2021-04-19 14:19
@SvenDowideit good question - @briandowns can you describe our most recent issue?

The thing is Sven, generally the breakages we have are not easily tied back to a single problem. I'll let Brian explain though.

That said, I think I (and @ibuildthecloud) have seen enough to convince us that **we should not drop armhf support in 1.22**.

@ibuildthecloud's position has been that we shouldn't do it at least until when 64-bit was the default os for pi's. I needed to at least float this to see where folks stood. It seems like we are years out from a point where arm 32-bit boards aren't important to people using k3s.

The team will brainstorm ways to reduce the impact of the problems we see while continuing to produce armhf builds.

**Comment by rockaut** [comment] 2021-04-19 14:49
It actually surprises me that there are not more comments tickling in here. I thought there would be more discussion.

Do you have any metrics/counts how many k3s-armhf binaries are active out there? Or any insights on which OS the boards are running?

I can see, that some folks are not concerned by dropping armhf because I think most people are nowadays using Pi4 (2GB at least) anyways. It always wasn't pleasant with 1GB or even Pi3 at all imo. But then there's more to that because PiOS is still on 32-bit but maybe a lot of people aren't using PiOS but, say Ubuntu 64-bit? IDK.

**Comment by gideontong** [comment] 2021-04-19 18:47
> It actually surprises me that there are not more comments tickling in here. I thought there would be more discussion.
> 
> Do you have any metrics/counts how many k3s-armhf binaries are active out there? Or any insights on which OS the boards are running?
> 
> I can see, that some folks are not concerned by dropping armhf because I think most people are nowadays using Pi4 (2GB at least) anyways. It always wasn't pleasant with 1GB or even Pi3 at all imo. But then there's more to that because PiOS is still on 32-bit but maybe a lot of people aren't using PiOS but, say Ubuntu 64-bit? IDK.

Purely anecdotal, but I'm still using Pi2's/Pi3's/other 32-bit boards because I started my projects long ago and as a student I don't have money to just upgrade to Pi4. So it wouldn't even be possible for me to use 64-bit builds.

**Comment by jcgregorio** [comment] 2021-04-23 18:58
Repeating here what I shared on Twitter: https://twitter.com/bitworking/status/1384183867074961414

I understand the desire, but I'd have to replace about 50 devices :-(

More details here: https://docs.google.com/presentation/d/18Uvak6H07Ft7-WsWzELsEh400EFrXsxNEvYQCV6-dp0/edit#slide=id.p

But that slide deck is from 2017, so replace "NFS/Ansible" with "k3s" :-)

![PXL_20210419_162557207](https://user-images.githubusercontent.com/1726460/115917118-bddbe100-a443-11eb-8782-aa2a91a91475.jpg)

**Comment by cjellick** [comment] 2021-04-26 14:57
Going to close this issue. We see the importance to the community and will continue to support this.

More details in this comment: https://github.com/k3s-io/k3s/issues/3213#issuecomment-822504245

**Closed by cjellick** 2021-04-26 14:57 UTC
Labels: arch/armhf

**Comment by dims** [comment] 2023-02-13 21:32
xref: https://github.com/kubernetes/kubernetes/issues/115738
