### ISSUE TITLE
While passing --disable-agent flag metrics-server is unable to fetch metrics from the cluster

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#5330] opened 2022-03-23 21:10 UTC
**Environmental Info:**
K3s Version: 
k3s version v1.23.5-rc1+k3s1 (df94b372)

Node(s) CPU architecture, OS, and Version: 
Ubuntu 20.04

Cluster Configuration:
Two node cluster, server with disable-agent and agent node

**Describe the bug:**
While metrics server is running on the cluster, no metrics is returned
```
$ kubectl get deploy,svc -n kube-system | egrep metrics-server
deployment.apps/metrics-server           1/1     1            1           16m
```
```
$ kubectl top node
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes.metrics.k8s.io)
ubuntu@ip-172-31-2-1:~$ kubectl get --raw "/apis/metrics.k8s.io/v1beta1/nodes"
Error from server (ServiceUnavailable): the server is currently unable to handle the request
```

**Steps To Reproduce:**
Install the server passing --disable-agent flag
Join another node as agent

**Expected behavior:**
Cluster should be up with all functionality as a regular single node cluster with agent

**Actual behavior:**
 metrics-server is unable to fetch metrics from the cluster

**Additional context / logs:**
```
ubuntu@ip-172-31-2-1:~$ kubectl get nodes
NAME               STATUS   ROLES    AGE   VERSION
ip-172-31-15-177   Ready    <none>   28m   v1.23.5-rc1+k3s1

ubuntu@ip-172-31-2-1:~$ kubectl get pods -o wide -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE   IP          NODE               NOMINATED NODE   READINESS GATES
kube-system   local-path-provisioner-6c79684f77-pkh77   1/1     Running     0          19m   10.42.0.6   ip-172-31-15-177   <none>           <none>
kube-system   coredns-d76bd69b-885bd                    1/1     Running     0          19m   10.42.0.2   ip-172-31-15-177   <none>           <none>
kube-system   helm-install-traefik-crd-g94xq            0/1     Completed   0          19m   10.42.0.3   ip-172-31-15-177   <none>           <none>
kube-system   metrics-server-7cd5fcb6b7-wnzmw           1/1     Running     0          19m   10.42.0.5   ip-172-31-15-177   <none>           <none>
kube-system   helm-install-traefik-97zmq                0/1     Completed   2          19m   10.42.0.4   ip-172-31-15-177   <none>           <none>
kube-system   svclb-traefik-c6zl8                       2/2     Running     0          19m   10.42.0.7   ip-172-31-15-177   <none>           <none>
kube-system   traefik-58b759688b-pzfxn                  1/1     Running     0          19m   10.42.0.8   ip-172-31-15-177   <none>           <none>
ubuntu@ip-172-31-2-1:~
```
As expected on server port 10250 is not open
```
ubuntu@ip-172-31-2-1:~$ curl -v http://localhost:10250
*   Trying 127.0.0.1:10250...
* TCP_NODELAY set
* connect to 127.0.0.1 port 10250 failed: Connection refused
* Failed to connect to localhost port 10250: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 10250: Connection refused
```
On agent(kubelet)
```
ubuntu@ip-172-31-15-177:~$ curl -v http://localhost:10250
*   Trying 127.0.0.1:10250...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 10250 (#0)
> GET / HTTP/1.1
> Host: localhost:10250
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
* HTTP 1.0, assume close after body
< HTTP/1.0 400 Bad Request
< 
Client sent an HTTP request to an HTTPS server.
* Closing connection 0
```
Logs:
```
$ kubectl logs -n kube-system metrics-server-7cd5fcb6b7-wnzmw
I0323 20:39:24.925006       1 serving.go:341] Generated self-signed cert (/tmp/apiserver.crt, /tmp/apiserver.key)
I0323 20:39:25.833098       1 requestheader_controller.go:169] Starting RequestHeaderAuthRequestController
I0323 20:39:25.833117       1 shared_informer.go:240] Waiting for caches to sync for RequestHeaderAuthRequestController
I0323 20:39:25.833141       1 configmap_cafile_content.go:202] Starting client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0323 20:39:25.833147       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0323 20:39:25.833164       1 configmap_cafile_content.go:202] Starting client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0323 20:39:25.833169       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0323 20:39:25.833768       1 secure_serving.go:202] Serving securely on [::]:4443
I0323 20:39:25.833849       1 dynamic_serving_content.go:130] Starting serving-cert::/tmp/apiserver.crt::/tmp/apiserver.key
I0323 20:39:25.833878       1 tlsconfig.go:240] Starting DynamicServingCertificateController
I0323 20:39:25.840726       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0323 20:39:25.933350       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file 
I0323 20:39:25.933382       1 shared_informer.go:247] Caches are synced for RequestHeaderAuthRequestController 
I0323 20:39:25.933394       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file 
I0323 20:39:26.091084       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0323 20:39:26.392359       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0323 20:39:28.092537       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0323 20:39:30.091158       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0323 20:39:32.090391       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0323 20:39:34.091661       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0323 20:39:36.091474       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0323 20:39:38.091506       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
I0323 20:39:40.095336       1 server.go:188] "Failed probe" probe="metric-storage-ready" err="not metrics to serve"
ubuntu@ip-172-31-2-1:~$ 

```

**Comment by brandond** [comment] 2022-03-30 19:09
This occurs because the metrics-server service is deployed as a cluster service. Without an agent running on the same node, the agent has no way to reach the service's in-cluster endpoint.

```
/ # kubectl get service -n kube-system metrics-server
NAME             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
metrics-server   ClusterIP   10.43.210.56   <none>        443/TCP   3m21s

E0330 19:04:31.801873      53 available_controller.go:524] v1beta1.metrics.k8s.io failed with: failing or missing response from https://10.43.210.56:443/apis/metrics.k8s.io/v1beta1: Get "https://10.43.210.56:443/apis/metrics.k8s.io/v1beta1": dial tcp 10.43.210.56:443: connect: network is unreachable
```

**Comment by brandond** [comment] 2022-04-06 23:38
Opened a PR to switch to EgressSelector as described above.

**Comment by mdrahman-suse** [comment] 2022-05-11 21:46
Reproduced in v1.23.6+k3s1

```
kubectl top node
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes.metrics.k8s.io)
```

Verified in master commit 2f22703c9e2f3cee40709265de8676811d0aadff

```
kubectl top node
NAME              CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
ip-xxx-yy-z-227   32m          1%     626Mi           16%
```

**Comment by mdrahman-suse** [comment] 2022-05-13 18:19
@brandond I have created a follow up issue on the error that was observed on the logs: https://github.com/k3s-io/k3s/issues/5565 Please advice
CC: @ShylajaDevadiga

**Comment by brandond** [comment] 2022-05-13 18:32
Replied on that issue. That is the expected output from metrics-server when there are no nodes to collect metrics from.

**Comment by mdrahman-suse** [comment] 2022-05-17 14:59
Thanks @brandond , I have closed out the issue

**Comment by katran001** [comment] 2022-05-31 14:32
@brandond is this resolved or should I move it to next milestone?

**Comment by mdrahman-suse** [comment] 2022-05-31 17:19
@katran001 This has been fixed, I will close it as part of RC validation

**Comment by mdrahman-suse** [comment] 2022-06-03 23:47
Verified in RC v1.23.7-rc1+k3s1

```
$ k3s -v
k3s version v1.23.7-rc1+k3s1 (4b2aa16c)
go version go1.17.5
```
```
$ kubectl top node
NAME              CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
ip-172-31-36-99   33m          1%     597Mi           15%
```

**Closed by mdrahman-suse** 2022-06-03 23:47 UTC
Labels: kind/bug
