### ISSUE TITLE
Getting error `invalid capacity 0 on image filesystem`

### ISSUE THREAD

**Issue by harryzcy** [k3s-io/k3s#6997] opened 2023-02-21 23:08 UTC
**Environmental Info:**
K3s Version: v1.26.1+k3s1 (f10af367)

Node(s) CPU architecture, OS, and Version: Linux harryzcy-1 5.15.0-1024-raspi #&#x2060;26-Ubuntu SMP PREEMPT Wed Jan 18 15:29:53 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

Cluster Configuration: 1 master, 2 agents

**Describe the bug:**

Getting the following events from `kubectl get events`:

```
43s         Normal    Starting                  node/harryzcy-2
44s         Normal    NodeHasSufficientMemory   node/harryzcy-2                               Node harryzcy-2 status is now: NodeHasSufficientMemory
44s         Normal    NodeHasNoDiskPressure     node/harryzcy-2                               Node harryzcy-2 status is now: NodeHasNoDiskPressure
44s         Normal    NodeHasSufficientPID      node/harryzcy-2                               Node harryzcy-2 status is now: NodeHasSufficientPID
43s         Normal    NodeReady                 node/harryzcy-2                               Node harryzcy-2 status is now: NodeReady
43s         Normal    NodeAllocatableEnforced   node/harryzcy-2                               Updated Node Allocatable limit across pods
35s         Normal    Starting                  node/harryzcy-2                               Starting kubelet.
35s         Warning   InvalidDiskCapacity       node/harryzcy-2                               invalid capacity 0 on image filesystem
34s         Normal    NodeHasSufficientMemory   node/harryzcy-2                               Node harryzcy-2 status is now: NodeHasSufficientMemory
34s         Normal    Starting                  node/harryzcy-2
34s         Normal    NodeHasNoDiskPressure     node/harryzcy-2                               Node harryzcy-2 status is now: NodeHasNoDiskPressure
34s         Normal    NodeHasSufficientPID      node/harryzcy-2                               Node harryzcy-2 status is now: NodeHasSufficientPID
34s         Normal    NodeNotReady              node/harryzcy-2                               Node harryzcy-2 status is now: NodeNotReady
34s         Normal    NodeAllocatableEnforced   node/harryzcy-2                               Updated Node Allocatable limit across pods
26s         Normal    Starting                  node/harryzcy-2                               Starting kubelet.
26s         Warning   InvalidDiskCapacity       node/harryzcy-2                               invalid capacity 0 on image filesystem
25s         Normal    NodeHasSufficientMemory   node/harryzcy-2                               Node harryzcy-2 status is now: NodeHasSufficientMemory
25s         Normal    Starting                  node/harryzcy-2
25s         Normal    NodeHasNoDiskPressure     node/harryzcy-2                               Node harryzcy-2 status is now: NodeHasNoDiskPressure
25s         Normal    NodeHasSufficientPID      node/harryzcy-2                               Node harryzcy-2 status is now: NodeHasSufficientPID
25s         Normal    NodeReady                 node/harryzcy-2                               Node harryzcy-2 status is now: NodeReady
25s         Normal    NodeAllocatableEnforced   node/harryzcy-2                               Updated Node Allocatable limit across pods
17s         Normal    Starting                  node/harryzcy-2                               Starting kubelet.
17s         Warning   InvalidDiskCapacity       node/harryzcy-2                               invalid capacity 0 on image filesystem
17s         Normal    NodeHasSufficientMemory   node/harryzcy-2                               Node harryzcy-2 status is now: NodeHasSufficientMemory
16s         Normal    Starting                  node/harryzcy-2
17s         Normal    NodeHasNoDiskPressure     node/harryzcy-2                               Node harryzcy-2 status is now: NodeHasNoDiskPressure
17s         Normal    NodeHasSufficientPID      node/harryzcy-2                               Node harryzcy-2 status is now: NodeHasSufficientPID
16s         Normal    NodeNotReady              node/harryzcy-2                               Node harryzcy-2 status is now: NodeNotReady
16s         Normal    NodeAllocatableEnforced   node/harryzcy-2                               Updated Node Allocatable limit across pods
16s         Normal    NodeReady                 node/harryzcy-2                               Node harryzcy-2 status is now: NodeReady
7s          Normal    Starting                  node/harryzcy-2                               Starting kubelet.
7s          Warning   InvalidDiskCapacity       node/harryzcy-2                               invalid capacity 0 on image filesystem
```

All the pods on that node is in `PENDING` state.

**Steps To Reproduce:**

I installed K3s via the installation script without customizing any configurations. Then one of my agent node failed because of disk failure. I then deleted the node via `kubectl delete node`, and have 1 master, 1 agent at this point.

After I added the third node again as a agent node, I'm getting the above errors, and all the nodes are pending.

**Expected behavior:**
All pods should be running.

**Actual behavior:**
Pods are pending. The events are shown above.

**Additional context / logs:**

**Comment by brandond** [comment] 2023-02-21 23:12
* Duplicate of https://github.com/k3s-io/k3s/issues/1857

**Closed by brandond** 2023-02-21 23:12 UTC

**Comment by harryzcy** [comment] 2023-02-22 00:41
That issue is only for when starting k3s node, but mine happens repeatedly for hours after node starts, making a node unusable.

Uninstalling and reinstalling on that node doesn't solve the issue either. @brandond

**Comment by brandond** [comment] 2023-02-22 00:52
> That issue is only for when starting k3s node

Yes, have you noticed from the **other** messages that surround that one that K3s is constantly restarting?
```
17s         Normal    Starting                  node/harryzcy-2                               Starting kubelet.
17s         Warning   InvalidDiskCapacity       node/harryzcy-2                               invalid capacity 0 on image filesystem

7s          Normal    Starting                  node/harryzcy-2                               Starting kubelet.
7s          Warning   InvalidDiskCapacity       node/harryzcy-2                               invalid capacity 0 on image filesystem
```

Have you done any investigation as to why K3s is constantly crashing and being restarted? If you want the message to go away, fix that.

**Comment by brandond** [comment] 2023-02-22 00:55
Since you're running this on an Raspberry Pi, I suspect that you've enabled etcd, and it is crashing due to the etcd storage latency being too high? Probably a bunch of stuff in the k3s service logs about failing to renew leases and so on?

**Comment by harryzcy** [comment] 2023-02-22 01:08
No, I didn't enable etcd and it's a single master setup. There's no logs from `journalctl` after the agent starts

**Comment by brandond** [comment] 2023-02-22 01:19
The k3s journald logs would be the first place I'd start.

**Comment by harryzcy** [comment] 2023-02-22 01:30
Thank you. I'm able to resolve it. It's some kernel modules needs installations separately.

**Comment by samnzay** [comment] 2023-06-07 07:01
> 

@harryzcy How did you solve this problem exactly? I will appreciate your feedback. I have been struggling for so long to solve this issue.

**Comment by harryzcy** [comment] 2023-06-11 17:46
> > 
> 
> @harryzcy How did you solve this problem exactly? I will appreciate your feedback. I have been struggling for so long to solve this issue.

@samnzay `apt install linux-modules-extra-raspi`

**Comment by ale9412** [comment] 2024-10-19 08:56
In case it helps. In my case I am using rke2 1.21.14, faced the same issue. What I did was first of all enable level 8 on kubelet logs, this parameter is set in rke2 config file under kubelet-arg, and also set stderrthreshold=ERROR. After analyzin kueblet logs i found out this:
```
Oct 18 14:03:41 node-3 rke2[5363]: E1018 14:03:41.848399    5363 kubelet.go:1384] "Failed to start ContainerManager" err="[invalid kernel flag: vm/overcommit_memory, expected value: 1, actual value: 0, invalid kernel flag: kernel/panic, expected value: 10, actual value: 60]" 
Oct 18 14:04:34 node-3 rke2[5576]: E1018 14:04:34.820158    5576 kubelet.go:1384] "Failed to start ContainerManager" err="invalid kernel flag: kernel/panic, expected value: 10, actual value: 60"
```
After setting these flags to the right value kubelet the ivalid capacity 0 on image filesystem went away and kubelet started ok and node went to ready state.
