### ISSUE TITLE
Failed to get unit file state for nm-cloud-setup.service: No such file or directory

### ISSUE THREAD

**Issue by springfred** [k3s-io/k3s#5424] opened 2022-04-13 08:43 UTC
**Environmental Info:**
K3s Version: 

k3s version v1.21.7+k3s1 (ac705709)
go version go1.16.10

Node(s) CPU architecture, OS, and Version: 

Linux k3s1-s01 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

#3 servers, 3 agents, 1 lb
- 192.168.2.53 k3s1-s01
- 192.168.2.54 k3s1-s02
- 192.168.2.55 k3s1-s03
- 192.168.2.56 k3s1-a01
- 192.168.2.57 k3s1-a02
- 192.168.2.58 k3s1-a03
- 192.168.2.60 k3s1-lb

**Describe the bug:**

**Steps To Reproduce:**

- Installed K3s: 
# master1:192.168.2.53
`curl -sLS http://rancher-mirror.cnrancher.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn K3S_TOKEN='k3s1v1217' INSTALL_K3S_EXEC='server --tls-san 192.168.2.60 --tls-san 192.168.2.53 --tls-san 192.168.2.54 --tls-san 192.168.2.55 --node-external-ip 192.168.2.53 --cluster-cidr 10.42.0.0/16' INSTALL_K3S_VERSION='v1.21.7+k3s1' sh -`

####################
[root@k3s1-s01 ~]# kubectl get node
NAME       STATUS   ROLES                  AGE    VERSION
k3s1-s01   Ready    control-plane,master   103m   v1.21.7+k3s1
###################

# master2:192.168.2.54
`curl -sLS http://rancher-mirror.cnrancher.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn K3S_URL='https://192.168.2.53:6443' K3S_TOKEN='k3s1v1217' INSTALL_K3S_EXEC='server --server https://192.168.2.53:6443 --tls-san 192.168.2.60 --tls-san 192.168.2.53 --tls-san 192.168.2.54 --tls-san 192.168.2.55 --node-external-ip 192.168.2.54 --cluster-cidr 10.42.0.0/16' INSTALL_K3S_VERSION='v1.21.7+k3s1' sh -`
####################
#Failed to get unit file state for nm-cloud-setup.service: No such file or directory
#starting kubernetes: preparing server: https://192.168.2.53:6443/v1-k3s/server-bootstrap: 401 Unauthorized"
###################

**Expected behavior:**

**Actual behavior:**

#master2:
#Failed to get unit file state for nm-cloud-setup.service: No such file or directory
#starting kubernetes: preparing server: https://192.168.2.53:6443/v1-k3s/server-bootstrap: 401 Unauthorized"

**Additional context / logs:**

<img width="1484" alt="image" src="https://user-images.githubusercontent.com/23000050/163137971-01ee3c0f-c760-441b-bb9e-ce445e97b13c.png">

<img width="1477" alt="image" src="https://user-images.githubusercontent.com/23000050/163138126-b7715d5e-7c6f-42b5-a7f9-6a6b5a3013f4.png">

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment] 2022-04-13 17:06
Duplicate of https://github.com/k3s-io/k3s/issues/4911

See the comment at https://github.com/k3s-io/k3s/issues/4911#issuecomment-1087968204

**Closed by brandond** 2022-04-13 17:06 UTC
