### ISSUE TITLE
Not all addresses are tried for proxy connect

### ISSUE THREAD

**Issue by texascloud** [k3s-io/k3s#986] opened 2019-10-30 01:28 UTC
**Version:**
k3s version v0.10.1 (7d650d32)

**Describe the bug**
In tunnel.go, the available endpoints to initiate a remote dial to is `config.ServerAddress`, and also any endpoints listed under the default kubernetes service. Even if the resulting `addresses` slice has more than 1 address, only the first one is ever used. In the event that the first one is unable to be reached, none of the other addresses are tried.

**To Reproduce**
Connect an agent while specifying `K3S_URL` and make sure it's different than what would appear for the kubernetes service endpoint

**Expected behavior**
I expect all the addresses to be tried, finally using one which works and is routable

**Actual behavior**
The first, non-routable, address is attempted to be connected to over and over forever

**Additional context**

**Comment by CamelCaseNotation** [comment] 2019-10-30 01:28
https://github.com/rancher/k3s/commit/e0212144e8a8c60b1b455dab923ca43a49ea8e68 this commit doesn't appear to work as intended

**Comment by CamelCaseNotation** [comment] 2019-10-30 01:29
@erikwilson Are there any tests for ensuring other addresses are used when establishing the proxy tunnel?

**Comment by CamelCaseNotation** [comment] 2019-10-30 01:37
I was able to have the remotedial URL be the load balancer local address which points to the `addresses`, which allowed the tunnel to correctly establish. I had to comment out these lines however:

```
		endpoint, _ := client.CoreV1().Endpoints("default").Get("kubernetes", metav1.GetOptions{})
		if endpoint != nil {
			addresses = getAddresses(endpoint)
			if onChange != nil {
				onChange(addresses)
			}
		}
```

The `onChange` function is a "setter" for the LoadBalancer struct, which ultimately calls this function: https://github.com/rancher/k3s/blob/a17e336993dce9f0bede53f311c51c5ac31e9b03/pkg/agent/loadbalancer/servers.go#L9

**Comment by erikwilson** [comment] 2019-10-30 01:38
The purpose of that change is for HA support, it is expecting that the endpoints are routable.

How are you running k3s to where the endpoints are not routable?

**Comment by CamelCaseNotation** [comment] 2019-10-30 01:41
I'm running the k3s server with `--disable-agent` in a "hosted control plane" setup. The `K3S_URL` value I'm using to connect the agent to the server is a nodeport service which maps to the apiserver. The endpoints under the default kubernetes service are not reachable by any worker nodes

**Comment by erikwilson** [comment] 2019-10-30 01:46
It is recommended not to use `--disable-agent` unless you are really sure you need it, it breaks too many things and I am thinking about changing it to `--disable-agent-and-kubelet-and-containerd-and-networking-plz`. 

There is probably more we can do to support the use case of nodes behind a nat, but it sounds like the particular change you pointed out is working as intended.

**Comment by CamelCaseNotation** [comment] 2019-10-30 01:52
I spoke too soon about commenting out the code making it work. 

```
Oct 30 01:48:08 josh-vm-1 k3s[12324]: time="2019-10-30T01:48:08.858400327Z" level=info msg="Tunnel endpoint watch event: [10.20.35.191:6443]"
Oct 30 01:48:08 josh-vm-1 k3s[12324]: time="2019-10-30T01:48:08.858925119Z" level=info msg="Stopped tunnel to 127.0.0.1:37265"
Oct 30 01:48:08 josh-vm-1 k3s[12324]: time="2019-10-30T01:48:08.859004603Z" level=info msg="Connecting to proxy" url="wss://10.20.35.191:6443/v1-k3s/connect"
```

It still watches the endpoints and updates it accordingly.

I don't want to run kubelet and containerd, so the `--disable-agent` flag works fine for me. Is that flag somehow related to the full slice of addresses not being tried when an agent connects to the k3s server?

**Comment by erikwilson** [comment] 2019-10-30 01:55
Perhaps, the agent portion sets up flannel for networking. 
The best approach may be to mark the master nodes as unschedulable so pods are not deployed there.

**Comment by CamelCaseNotation** [comment] 2019-10-30 01:56
I was planning to run the k3s server as a Pod. Is that possible without using `--disable-agent`?

**Comment by erikwilson** [comment] 2019-10-30 01:58
Possibly, it may need privileged mode for networking.

**Comment by erikwilson** [comment] 2019-10-30 01:59
Also, if connecting nodes through a public network it would be wise to enable ipsec or some type of encryption.

**Comment by CamelCaseNotation** [comment] 2019-10-30 02:15
Okay thanks, do you mean like a different backend for flannel?

> The purpose of that change is for HA support, it is expecting that the endpoints are routable.

What is the expected behavior if an endpoint isn't routable? I guess if an endpoint isn't routable, kubernetes handles removing it from the kubernetes service

**Comment by CamelCaseNotation** [comment] 2019-10-30 02:23
I feel like there's still a bug here. If I remove any invocation of the `onChange` function, the proxy uses the local loadbalancer address for connecting to the proxy, which has a list of addresses which _should_ be routable. This will always work as long as the loadbalancer is updating its list of addresses when the endpoints update (the watch that it's currently doing), but don't cause the proxy to drop its connection. 

Ohh hmm, I see the problem with that. I'm not sure. Maybe my use-case just doesn't align with the assumptions made about endpoint reachability

**Comment by erikwilson** [comment] 2019-10-30 02:34
Yah, sorry the endpoints are the ip of the node. There is some assumption that k3s nodes are on the same network and accessible. It might be worth checking out https://github.com/alexellis/k3sup to see if it helps with your scenario also. I would like to make this better, but ideally would also support the HA scenario.

**Comment by CamelCaseNotation** [comment] 2019-10-30 03:50
Would you be open to an optional flag to `k3s agent` which allows Pods to talk to an apiserver with a non-routable IP from nodes?

The flag could do something like:
- creates a NIC with IPs which match the ones listed as endpoints of the kubernetes service (this is cuz kube-proxy owns the iptables/ipvs rules in the service's CIDR so cannot override the endpoints)
- the endpoint watch logic in the codebase here can be used to route the requests from Pods to the kubernetes service IP through the established proxy tunnel

**Comment by erikwilson** [comment] 2019-10-30 03:58
It is something we should make better, there was a PR and discussion here:
https://github.com/rancher/k3s/pull/881

**Comment by caroline-suse-rancher** [comment] 2022-11-30 16:22
Closing due to age

**Closed by caroline-suse-rancher** 2022-11-30 16:22 UTC
Labels: kind/enhancement
