### ISSUE TITLE
cattle-node-agent and rancher-agent:v2.3.3 not found.

### ISSUE THREAD

**Issue by vishuPPatel** [k3s-io/k3s#1277] opened 2020-01-07 09:00 UTC
Hello K3s Team

**I Create a k3s-agent into rapberry pi3. but your document support install.**

Failed to pull image "rancher/rancher-agent:v2.3.3": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/rancher/rancher-agent:v2.3.3": failed to unpack image on snapshotter overlayfs: no match for platform in manifest sha256:ad0b39814ba3f6e1e5e16e1c2b46f02c8056298a45f5feacf833126f66fb3fd6: not found

Operating Systems
K3s should run on just about any flavor of Linux. However, K3s is tested on the following operating systems and their subsequent non-major releases.

Ubuntu 16.04 (amd64)
Ubuntu 18.04 (amd64)
Raspbian Buster (armhf)

pi@node2:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

root@node2:/home/pi# systemctl status k3s-agent
● k3s-agent.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s-agent.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-01-07 08:01:15 GMT; 28min ago
     Docs: https://k3s.io
  Process: 17661 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
  Process: 17662 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
 Main PID: 17663 (k3s-agent)
    Tasks: 74
   Memory: 347.0M
   CGroup: /system.slice/k3s-agent.service
           ├─17663 /usr/local/bin/k3s agent
           ├─17683 containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/li
           ├─17903 /var/lib/rancher/k3s/data/c96e02c5a53589ce1b73ea475296dfd2297b0806ff82f2ea452f1ed6f56463e0/bin/containerd-shim-runc-v2 -namespace k8s.io -id 6dccfb2d
           ├─17924 /pause
           ├─18017 /bin/sh /usr/bin/entry
           ├─18064 /bin/sh /usr/bin/entry
           ├─18324 /var/lib/rancher/k3s/data/c96e02c5a53589ce1b73ea475296dfd2297b0806ff82f2ea452f1ed6f56463e0/bin/containerd-shim-runc-v2 -namespace k8s.io -id db7d83c7
           ├─18344 /pause
           ├─19203 /var/lib/rancher/k3s/data/c96e02c5a53589ce1b73ea475296dfd2297b0806ff82f2ea452f1ed6f56463e0/bin/containerd-shim-runc-v2 -namespace k8s.io -id bfa01504
           ├─19224 /pause
           ├─19464 nginx: master process nginx -g daemon off;
           ├─19484 nginx: worker process
           ├─20168 /var/lib/rancher/k3s/data/c96e02c5a53589ce1b73ea475296dfd2297b0806ff82f2ea452f1ed6f56463e0/bin/containerd-shim-runc-v2 -namespace k8s.io -id 0f30e832
           ├─20188 /pause
           └─20253 /bin/sh /usr/bin/entry

Jan 07 08:28:44 node2 k3s[17663]: E0107 08:28:44.093834   17663 pod_workers.go:191] Error syncing pod 042bc94d-4fcb-44f1-a93c-80c745a83e32 ("cattle-node-agent-jphtl_cat
Jan 07 08:28:55 node2 k3s[17663]: E0107 08:28:55.093209   17663 pod_workers.go:191] Error syncing pod 042bc94d-4fcb-44f1-a93c-80c745a83e32 ("cattle-node-agent-jphtl_cat
Jan 07 08:29:06 node2 k3s[17663]: E0107 08:29:06.094162   17663 pod_workers.go:191] Error syncing pod 042bc94d-4fcb-44f1-a93c-80c745a83e32 ("cattle-node-agent-jphtl_cat
Jan 07 08:29:19 node2 k3s[17663]: E0107 08:29:19.093958   17663 pod_workers.go:191] Error syncing pod 042bc94d-4fcb-44f1-a93c-80c745a83e32 ("cattle-node-agent-jphtl_cat
Jan 07 08:29:32 node2 k3s[17663]: E0107 08:29:32.094468   17663 pod_workers.go:191] Error syncing pod 042bc94d-4fcb-44f1-a93c-80c745a83e32 ("cattle-node-agent-jphtl_cat
Jan 07 08:29:46 node2 k3s[17663]: E0107 08:29:46.033309   17663 remote_image.go:113] PullImage "rancher/rancher-agent:v2.3.3" from image service failed: rpc error: code
Jan 07 08:29:46 node2 k3s[17663]: E0107 08:29:46.037245   17663 kuberuntime_image.go:50] Pull image "rancher/rancher-agent:v2.3.3" failed: rpc error: code = NotFound de
Jan 07 08:29:46 node2 k3s[17663]: E0107 08:29:46.039059   17663 kuberuntime_manager.go:803] container start failed: ErrImagePull: rpc error: code = NotFound desc = fail
Jan 07 08:29:46 node2 k3s[17663]: E0107 08:29:46.040427   17663 pod_workers.go:191] Error syncing pod 042bc94d-4fcb-44f1-a93c-80c745a83e32 ("cattle-node-agent-jphtl_cat
Jan 07 08:30:00 node2 k3s[17663]: E0107 08:30:00.096434   17663 pod_workers.go:191] Error syncing pod 042bc94d-4fcb-44f1-a93c-80c745a83e32 ("cattle-node-agent-jphtl_cat

k3s Team please fix it this problem & otherwise how to fix it.

Thanks!!..

**Comment by davidnuzik** [comment] 2020-01-14 19:27
Hello. K3s supports armhf and arm64. The issue is that at this time the rancher-agent does not support armhf. Let us know if you have any other questions.

**Comment by davidnuzik** [comment] 2020-01-14 19:38
Re-opening. We'll use this issue to track the issue. Once rancher/agent has an armhf image we can validate.

**Comment by vishuPPatel** [comment] 2020-02-15 06:00
Hello K3s Team

what is the status about the K3s supports armhf for agent connection?

**Comment by caroline-suse-rancher** [comment] 2022-12-01 15:47
Closing due to age - please make a new issue if this is still a problem.

**Closed by caroline-suse-rancher** 2022-12-01 15:47 UTC
Labels: kind/feature, arch/armhf, os/raspbian
