### ISSUE TITLE
Can't kubectl exec or log to pods: 401 Unauthorized 

### ISSUE THREAD

**Issue by simsicon** [k3s-io/k3s#7962] opened 2023-07-13 16:13 UTC
K3s Version: 
```bash
$ k3s -v
k3s version v1.24.2+k3s2 (a2372602)
go version go1.18.1
```

Node(s) CPU architecture, OS, and Version: 
```bash
$ uname -a
Linux node4-dev 5.10.0-22-amd64 #1 SMP Debian 5.10.178-3 (2023-04-22) x86_64 GNU/Linux
```

Cluster Configuration:
```bash
$ kubectl get nodes
NAME        STATUS   ROLES                  AGE    VERSION
node1       Ready    control-plane,master   535d   v1.24.2+k3s2
node4-dev   Ready    <none>                 31d    v1.24.2+k3s2
```

**Describe the bug:**
Today I realized I can not `exec -it` or `log` into the pods, this might have happened for at most 2 days.
When I run `kubectl exec -it lab-my-0 -n lab -- /bin/bash` I got:
```
Error from server: error dialing backend: proxy error from 127.0.0.1:6443 while dialing 192.168.10.91:10250, code 401: 401 Unauthorized
```
I think this is not a `10250` specific problem, because I also see similar errors from my failed pods `helm-install-traefik-vkczh`:

```
Error: UPGRADE FAILED: create: failed to create: Internal error occurred: failed calling webhook "rancher.cattle.io": failed to call webhook: Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s": proxy error from 127.0.0.1:6443 while dialing 10.42.0.86:9443, code 401: 401 Unauthorized
```

There is no any ufw or firewall settings in both two nodes, (there was one for the node1, but it worked fine and I have turned it off now)

**Steps To Reproduce:**
Not sure how to reproduce it, because I basically have no changes for 2 days.

But I do have create a new user in rancher and add to the cluster, but I have no idea how that could affect k3s.

I have no clues how to look into the problem, and I have tried a lot, any ideas to help me start with would be appreciated, thank you.

**Comment by brandond** [comment] 2023-07-13 16:18
> `proxy error from 127.0.0.1:6443 while dialing 192.168.10.91:10250, code 401: 401 Unauthorized`

Do you have a HTTP_PROXY environment variable set on your node? Is the NO_PROXY environment variable set to properly exclude node IPs and hostnames from going through the proxy, or alternately - will your proxy allow anonymous connections to nodes?

**Comment by simsicon** [comment] 2023-07-17 02:07
> > `proxy error from 127.0.0.1:6443 while dialing 192.168.10.91:10250, code 401: 401 Unauthorized`
> 
> Do you have a HTTP_PROXY environment variable set on your node? If so, is the NO_PROXY environment variable set to properly exclude node IPs and hostnames from going through the proxy, or alternately - will your proxy allow anonymous connections to nodes?
> 
> If you don't have any proxy environment variables set, can you show the logs from the k3s service on your server?

Hi brandond, good to see you

No, I have no HTTP_PROXY or HTTPS_PROXY set.

For node4-dev, the latest log of`sudo journalctl -u k3s-agent` suggests 2 things: the failing helm installing and something about iptables:

```
Jul 14 09:53:14 node4-dev k3s[469315]: I0714 09:53:14.444684  469315 scope.go:110] "RemoveContainer" containerID="c1f88760bb01dcaf2895ef4f1da29765cf5fd05042f4efdb398a2ed0b8ec
b681"
Jul 14 09:53:14 node4-dev k3s[469315]: E0714 09:53:14.445299  469315 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"helm\" with Cra
shLoopBackOff: \"back-off 5m0s restarting failed container=helm pod=helm-install-traefik-qdv5s_kube-system(aa5d6a65-7011-4165-9290-0ac93926edaa)\"" pod="kube-system/helm-inst
all-traefik-qdv5s" podUID=aa5d6a65-7011-4165-9290-0ac93926edaa
Jul 14 09:53:22 node4-dev k3s[469315]: E0714 09:53:22.261678  469315 network_policy_controller.go:269] Aborting sync. Failed to cleanup stale iptables rules: unable to list c
hains: running [/usr/sbin/iptables -t filter -S --wait]: exit status 1: # Warning: iptables-legacy tables present, use iptables-legacy to see them
Jul 14 09:53:22 node4-dev k3s[469315]: iptables v1.8.7 (nf_tables): table `filter' is incompatible, use 'nft' tool.
```

For node1, `sudo journalctl -u k3s` suggests about the orphaned pod volume dirs,

```
Jul 14 10:02:36 node1 k3s[754872]: I0714 10:02:36.445253  754872 kubelet_volumes.go:160] "Cleaned up orphaned pod volumes dir" podUID=77def977-95a9-4300-b7ff-2e061b96c5cb pat
h="/var/lib/kubelet/pods/77def977-95a9-4300-b7ff-2e061b96c5cb/volumes"
Jul 14 10:02:36 node1 k3s[754872]: I0714 10:02:36.445309  754872 kubelet_getters.go:300] "Path does not exist" path="/var/lib/kubelet/pods/a3c0bca8-3507-4d25-879e-7d252777662
d/volumes"
Jul 14 10:02:36 node1 k3s[754872]: I0714 10:02:36.445320  754872 kubelet_getters.go:300] "Path does not exist" path="/var/lib/kubelet/pods/a3c0bca8-3507-4d25-879e-7d252777662
d/volumes"
Jul 14 10:02:36 node1 k3s[754872]: I0714 10:02:36.445372  754872 kubelet_volumes.go:160] "Cleaned up orphaned pod volumes dir" podUID=a3c0bca8-3507-4d25-879e-7d252777662d pat
h="/var/lib/kubelet/pods/a3c0bca8-3507-4d25-879e-7d252777662d/volumes"
Jul 14 10:02:36 node1 k3s[754872]: E0714 10:02:36.445391  754872 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"
1bfcbff6-5738-4ccb-926c-2f54f526d271\" found, but failed to rmdir() subpath at path /var/lib/kubelet/pods/1bfcbff6-5738-4ccb-926c-2f54f526d271/volume-subpaths/volume-skypride
-hub-config/skypride-hub-celery/0: not a directory" numErrs=11
```

Looks like something with iptables is wrong at node4-dev.

`$ sudo /usr/sbin/iptables -t filter -S --wait` At node1 will display a lot of iptables rules.

`$ sudo /usr/sbin/iptables -t filter -S --wait` At node4-dev will display:

```
$ sudo /usr/sbin/iptables -t filter -S --wait
# Warning: iptables-legacy tables present, use iptables-legacy to see them
iptables v1.8.7 (nf_tables): table `filter' is incompatible, use 'nft' tool.
```

If I run `sudo nft list ruleset` at the both nodes, I can get a lot of rules at the both nodes.

@brandond does this look wrong to you? Thank you

**Comment by brandond** [comment] 2023-07-19 00:35
The `table "filter' is incompatible` error is not one I've seen before. You might confirm that your hosts are consistently using iptables-legacy or iptable-nft; it kinda sounds like there are packages on the hosts using a mix of both.

The `failed to rmdir() subpath at path /var/lib/kubelet/pods/1bfcbff6-5738-4ccb-926c-2f54f526d271/volume-subpaths/volume-skypride-hub-config/skypride-hub-celery/0` is usually caused by a CSI storage provider crashing or otherwise failing to unmount volumes cleanly. You may need to reboot the node and/or clean up (delete) the affected paths manually in order to resolve the error.

**Comment by simsicon** [comment] 2023-07-23 10:03
@brandond Thanks for your help

After kill-all and restart the k3s service, the network issues are gone. In order to use `prefer-bundled-bin` flag, I try to upgrade to v1.24.15+k3s1 since I am using v1.24.2+k3s2, using official script to upgrade.

However after the upgrading, I got a lot of SandboxChanged events(dozens in several minutes per pod), then pods got killed constantly, I think something is wrong with CNI but I have no proof about it.

To save the cluster back online, I have to switch back to v1.24.2+k3s2 then things go back to normal, all problems are solved.

now the origin issue is solved, but I am  wonder do you have any ideas what are the possible reasons for the SandboxChanged events issues.

Thanks.

**Comment by brandond** [comment] 2023-07-24 22:11
> what are the possible reasons for the SandboxChanged events issues

There are a lot of possible causes for SandboxChanged events, but upgrades to the container runtime or CNI are definitely potential causes.

If you don't have any additional logs, or a good way to reproduce this, I'm going to close it out. Please feel free to reopen if you do figure out how to reproduce it on demand.

**Closed by brandond** 2023-07-24 22:11 UTC
