### ISSUE TITLE
x509: cannot validate certificate for <worker IP> because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by edita-timo** [k3s-io/k3s#6102] opened 2022-09-06 10:28 UTC
**Environmental Info:**
K3s Version:

k3s version v1.24.4+k3s1 (c3f830e9)
go version go1.18.1

Node(s) CPU architecture, OS, and Version: 

Linux my.node.fi 4.18.0-372.19.1.el8_6.x86_64 #1 SMP Tue Aug 2 13:42:59 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 server, 3 agents 

**Describe the bug:**

kubectl commands targeted to agents such as "kubectl logs <pod> or kubectl exec ... " fail as they are unable to verify agent TLS certificate:

Exact error:
`Error from server: Get "https://<worker ip>:10250/containerLogs/development/my-pod-name-7cbd66d77c-rl5xz/my-pod-name": x509: cannot validate certificate for <worker ip> because it doesn't contain any IP SANs`

**Steps To Reproduce:**

- Installed K3s:
 curl -sfL https://get.k3s.io |  K3S_URL=https://<master hostname>:6443 K3S_TOKEN=<token> sh -

**Expected behavior:**

The command should work without validation error.

**Actual behavior:**

**Additional context / logs:**

using openssl s_client the certificate is using the hostname, so either the certificate should include the IP address of worker node in the cert or the master should be using the hostname when connecting to the worker.

**Comment by brandond** [comment] 2022-09-06 17:24
I'm unable to reproduce this. Can you provide the output of `kubectl get node -o yaml`?

**Comment by edita-timo** [comment] 2022-09-07 05:25
Ah, mistake on my part regarding the worker cert. The openssl s_client output does not seem to display the SAN of given cert by default. 
I used " openssl s_client -connect <worker#3 host>:10250" and copied the cert part to cert.pem file locally and displayed it from there with "openssl x509 -in cert.pem -text -noout". With that it indeed shows the kubernetes worker cert IP SAN's as expected:

```
...
            X509v3 Subject Alternative Name: 
                DNS:<worker#3 host>, DNS:localhost, IP Address:127.0.0.1, IP Address:<worker external ip>
```
I verified that this matches the result of /var/lib/rancher/k3s/agent/serving-kubelet.crt on the worker host. It would seem that the worker cert is correctly generated with the necessary SAN info. But the issue remains that the kubernetes master does not seem to parse/process the worker certs correctly:

```
# /usr/local/bin/k3s kubectl -n development logs <pod on worker#3>
Error from server: Get "https://<worker#3 external ip>:10250/containerLogs/development/<pod on worker#3>/<pod name>": x509: cannot validate certificate for <worker#3 external ip> because it doesn't contain any IP SANs
# 
```
I have one old worker node, one reconnected worker and one totally new worker server. Accessing pods on any worker gives the same error. 

I'm not comfortable on pasting the whole yaml output, any specific part you wish to see?

**Comment by brandond** [comment] 2022-09-07 06:41
If you'd like, you could join the Rancher Users slack and DM me at the same username.

**Comment by brandond** [comment] 2022-09-07 17:07
Do you by any chance have HTTP_PROXY/HTTPS_PROXY set in the environment for the K3s service?

**Comment by edita-timo** [comment] 2022-09-08 05:05
Ah, our environment is using http proxy for outgoing traffic. Looking the network traffic a bit more closely the k3s master seems to be using the proxy for worker connections as well.

I'm guessing but it seems the k3s installer has copied the proxy options present during installation to /etc/systemd/system/k3s.service.env file. Meaning me tuning the proxy settings in /etc/environment had no effect on k3s. After adding the k3s cluster network CIDR to /etc/systemd/system/k3s.service.env no_proxy env variable made the kubectl commands go directly to workers and connections now succeed.

Has there been any changes on proxy handling in recent k3s work? Our proxy setup has been running without changes for a long while so it is odd that k3s started to use just now.

**Comment by lsascha** [comment] 2022-09-15 12:31
getting the same error after an update from k3s v1.22.9+k3s1 to v1.22.13+k3s1.

trying to get logs results in 
```
Failed to load logs: Get "https://10.0.1.5:10250/containerLogs/cert-manager/cert-manager-86b4798576-vrcrv/cert-manager?tailLines=502&timestamps=true": x509: certificate is valid for 127.0.0.1, 162.55.45.171, 2a01:4f8:c010:7658::1, not 10.0.1.5
Reason: undefined (500)
```

**Comment by brandond** [comment] 2022-09-15 20:37
What are the `<ipv4>, <ipv6>` addresses shown in your command? Are they addresses of the node in question as shown in `kubectl get node -o wide` or are they some other, unrelated addresses or addresses bound to secondary interfaces on the node?

**Comment by lsascha** [comment] 2022-09-15 20:46
ah sorry that i wasn't clear enough. these are the external pointing IP-Addresses of the Node the Pod is running on. IPv4 appears also in the `kubectl get node -o wide` output.

**Comment by lsascha** [comment] 2022-09-16 00:10
i get valid ecdsa-with-SHA256 certificates on all server and agent nodes. (pretty much exactly 1 year from now)
they contain these SAN entries:
```
X509v3 Subject Alternative Name:
                DNS:k3s-control-plane-0, DNS:localhost, IP Address:127.0.0.1, IP Address:<IPv4>, IP Address:<IPv6>
```
```
X509v3 Subject Alternative Name:
                DNS:k3s-agent-0, DNS:localhost, IP Address:127.0.0.1, IP Address:<IPv4>, IP Address:<IPv6>
```

but they are missing their internal IPs like 10.0.1.5 mentioned in the error.
So i would guess the error is correct.

Question is, why is k3s not adding that IP to the certificate?
Was it added before and since one update not anymore? (unfortunately never checked the certificates before the update)
What would be the fix?

**Comment by brandond** [comment] 2022-09-16 20:31
> but they are missing their internal IPs like 10.0.1.5 mentioned in the error.
> Question is, why is k3s not adding that IP to the certificate?

It should add SANS for all the addresses specified for the --node-ip and --node-external-ip flags, as well as the hostname and localhost/loopback addresses. I'm curious how you got the node internal and external addresses set without having to use those flags, which would have added them to the kubelet cert. Have you by any chance disabled the k3s embedded cloud controller and deployed your own?

**Comment by lsascha** [comment] 2022-09-18 20:10
Okay, i downgraded again to k3s v1.22.9 and accessing logs etc. does work again.

As soon as the control pane node was downgraded, the logs started working again without error.

only difference i see in the certificate is that it is now missing the IPv6 address. Nothing else has changed.
So it is definetly a change after the update that broke it.

and yes. it is running an external cloud controller: https://github.com/hetznercloud/hcloud-cloud-controller-manager

But i have seen that the new version of the controller changed the order of IPs to access the API server. which might be the reason it breaks. So will try that next and report back.

**Comment by lowercase00** [comment] 2022-11-05 08:29
Not sure my issue is exactly the same, but does seem similar. I just started a single-node vm k3s server, and I can't access the API from my local machine.

I'm using:
k3s version v1.25.3+k3s1 (f2585c16)
go version go1.19.2

I've added the `--tls-san EXTERNAL_VM_IP` and got the config, now trying to use `kubectl` get's me the `x509: cannot validate certificate` error. I can use `kubectl` on the server without issues, just not access it remotely. Certificates are valid, tried rotating them as well. 

When looking at the certificate, the `X509v3 Subject Alternative Name` DNS shows both the local IP (`127.0.0.1` and the external server IP.

**Comment by brandond** [comment] 2022-11-07 18:23
I suspect that what's happening is that the hetzner cloud-provider is adding additional node addresses, but the Kubelet cert is only valid for the default node address and any addresses that are listed in the `node-ip` or `node-external-ip` flags.

**Comment by zifeo** [comment] 2022-12-10 23:02
@brandond would be great to have an option to add more IPs, especially handy when having some internal VIPs.

**Comment by lsascha** [comment] 2022-12-10 23:22
i still hope there is any way to fix this. Hetzner seem to ignore that issue completely unfortunately. :(

**Comment by brandond** [comment] 2022-12-11 09:52
I don't see a good workaround for this. If hetzner is going to add additional IPs to the node after the fact, how are we supposed to know what those will be when generating the kubelet certificates? That doesn't seem possible. The only thing I can suggest is to switch the apiserver's kubelet address order to use prefer hostnames over IPs.

**Comment by brandond** [comment] 2023-05-02 21:31
I am going to close this out as caused by the hetzner cloud provider; if someone from one of the hetzner projects has some suggestions on how we can improve this on our side I'm glad to reopen it.

**Closed by brandond** 2023-05-02 21:31 UTC
