### ISSUE TITLE
[release-1.23] Setting CONTAINERD_NO_PROXY does not work

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#5707] opened 2022-06-14 23:47 UTC
Backport to branch `release-1.23`:
*  #5642

**Comment by rancher-max** [comment] 2022-06-22 23:36
## Validated using v1.23.8-rc1+k3s1
 
### Environment Details

 
*Infrastructure*
- [x] Cloud (AWS)
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
$ uname -a
Linux ip-172-31-42-97 5.15.0-1011-aws #14-Ubuntu SMP Wed Jun 1 20:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
 
*Cluster Configuration:*

```
1 server
```
 
*Config.yaml:*

N/A
 
### Replication Steps

 Followed the same steps exactly as mentioned in the original issue, using v1.23.7+k3s1
 
**Results:**

I see the same results as mentioned in the original issue when using `journalctl -u k3s -f`
```
Jun 22 23:19:20 ip-172-31-42-97 k3s[1663]: E0622 23:19:20.079087    1663 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"metrics-server-7cd5fcb6b7-4rtb9_kube-system(ffe16015-33d2-4340-87a3-d2ed3f814952)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"metrics-server-7cd5fcb6b7-4rtb9_kube-system(ffe16015-33d2-4340-87a3-d2ed3f814952)\\\": rpc error: code = Unknown desc = failed to get sandbox image \\\"rancher/mirrored-pause:3.6\\\": failed to pull image \\\"rancher/mirrored-pause:3.6\\\": failed to pull and unpack image \\\"docker.io/rancher/mirrored-pause:3.6\\\": failed to resolve reference \\\"docker.io/rancher/mirrored-pause:3.6\\\": failed to do request: Head \\\"https://registry-1.docker.io/v2/rancher/mirrored-pause/manifests/3.6\\\": proxyconnect tcp: dial tcp: lookup this.is.my.fake.proxy on 127.0.0.53:53: no such host\"" pod="kube-system/metrics-server-7cd5fcb6b7-4rtb9" podUID=ffe16015-33d2-4340-87a3-d2ed3f814952
```
 
### Validation Steps

Follow the same steps but using v1.23.8-rc1+k3s1
 
 
**Results:**
Still fails in ALMOST same way:
```
Jun 22 23:23:15 ip-172-31-42-97 k3s[2529]: E0622 23:23:15.488318    2529 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"metrics-server-7cd5fcb6b7-5sbxv_kube-system(31816f4f-bd57-474d-a12d-c7f7420a7bca)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"metrics-server-7cd5fcb6b7-5sbxv_kube-system(31816f4f-bd57-474d-a12d-c7f7420a7bca)\\\": rpc error: code = Unknown desc = failed to get sandbox image \\\"rancher/mirrored-pause:3.6\\\": failed to pull image \\\"rancher/mirrored-pause:3.6\\\": failed to pull and unpack image \\\"docker.io/rancher/mirrored-pause:3.6\\\": failed to copy: httpReadSeeker: failed open: failed to do request: Get \\\"https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/62/6270bb605e12e581514ada5fd5b3216f727db55dc87d5889c790e4c760683fee/data?verify=1655943195-l5IF1XRd%2BIPihfxZ9b%2B%2FrfUQkYc%3D\\\": proxyconnect tcp: dial tcp: lookup this.is.my.fake.proxy on 127.0.0.53:53: no such host\"" pod="kube-system/metrics-server-7cd5fcb6b7-5sbxv" podUID=31816f4f-bd57-474d-a12d-c7f7420a7bca
```
Notice the log now has this bit, which is different: `failed to copy: httpReadSeeker: failed open`
 
**Additional context / logs:**
```
$ ps aux | grep -i k3s
root        2529 18.4 10.8 1180512 430312 ?      Ssl  23:21   0:36 /usr/local/bin/k3s server
root        2542  2.1  1.4 758596 58876 ?        Sl   23:21   0:04 containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd
```
- k3s environment from the process. Notice this DOES show the `CONTAINERD_NO_PROXY` variable set.
```
$ sudo cat /proc/2529/environ 
PATH=/var/lib/rancher/k3s/data/0f3c82168685ce0795e8274ae883307e515987ed3d622082b0d5f76da3103793/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/var/lib/rancher/k3s/data/0f3c82168685ce0795e8274ae883307e515987ed3d622082b0d5f76da3103793/bin/auxNOTIFY_SOCKET=/run/systemd/notifyINVOCATION_ID=1f0c5198387f4ccfaaab11c979bcf576JOURNAL_STREAM=8:27019SYSTEMD_EXEC_PID=2529CONTAINERD_HTTP_PROXY=http://this.is.my.fake.proxy/CONTAINERD_HTTPS_PROXY=https://this.is.my.fake.proxy/CONTAINERD_NO_PROXY=.docker.ioRES_OPTIONS= K3S_DATA_DIR=/var/lib/rancher/k3s/data/0f3c82168685ce0795e8274ae883307e515987ed3d622082b0d5f76da3103793
```
- containerd environment from the process. Notice this also DOES show the `NO_PROXY` variable set:
```
$ sudo cat /proc/2542/environ 
LANG=C.UTF-8PATH=/var/lib/rancher/k3s/data/0f3c82168685ce0795e8274ae883307e515987ed3d622082b0d5f76da3103793/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/var/lib/rancher/k3s/data/0f3c82168685ce0795e8274ae883307e515987ed3d622082b0d5f76da3103793/bin/auxINVOCATION_ID=1f0c5198387f4ccfaaab11c979bcf576JOURNAL_STREAM=8:27019SYSTEMD_EXEC_PID=2529RES_OPTIONS= K3S_DATA_DIR=/var/lib/rancher/k3s/data/0f3c82168685ce0795e8274ae883307e515987ed3d622082b0d5f76da3103793NO_PROXY=.docker.ioNODE_NAME=ip-172-31-42-97HTTP_PROXY=http://this.is.my.fake.proxy/HTTPS_PROXY=https://this.is.my.fake.proxy/
```
- Doing the same workaround as the user who reported this issue on v1.23.7+k3s1 does fail the same way:
```
# Workaround: Use NO_PROXY instead:
CONTAINERD_HTTP_PROXY=http://this.is.my.fake.proxy/
CONTAINERD_HTTPS_PROXY=https://this.is.my.fake.proxy/
NO_PROXY=".docker.io"
```
```
# Log results:
Jun 22 23:34:46 ip-172-31-42-97 k3s[3725]: E0622 23:34:46.540317    3725 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"metrics-server-7cd5fcb6b7-k9c4n_kube-system(293cdfb3-23a1-44fc-a798-955e8cd5993e)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"metrics-server-7cd5fcb6b7-k9c4n_kube-system(293cdfb3-23a1-44fc-a798-955e8cd5993e)\\\": rpc error: code = Unknown desc = failed to get sandbox image \\\"rancher/mirrored-pause:3.6\\\": failed to pull image \\\"rancher/mirrored-pause:3.6\\\": failed to pull and unpack image \\\"docker.io/rancher/mirrored-pause:3.6\\\": failed to copy: httpReadSeeker: failed open: failed to do request: Get \\\"https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/62/6270bb605e12e581514ada5fd5b3216f727db55dc87d5889c790e4c760683fee/data?verify=1655943886-p6z5NmEMjUmDZ%2BNwimyCqkcTH%2BU%3D\\\": proxyconnect tcp: dial tcp: lookup this.is.my.fake.proxy on 127.0.0.53:53: no such host\"" pod="kube-system/metrics-server-7cd5fcb6b7-k9c4n" podUID=293cdfb3-23a1-44fc-a798-955e8cd5993e
```

**_Due to this last note, I do believe this is resolved and working as intended, so I am closing this issue._**

**Closed by rancher-max** 2022-06-22 23:36 UTC
