### ISSUE TITLE
Airgap installation without registry looses images under DiskPressure

### ISSUE THREAD

**Issue by smerschjohann** [k3s-io/k3s#1552] opened 2020-03-17 08:14 UTC
**Version:**
v1.17.0+k3s.1

**K3s arguments:**
export INSTALL_K3S_SKIP_DOWNLOAD="true"
export INSTALL_K3S_EXEC="server"

**Describe the bug**
Under disk pressure the node will delete imported images that are not used. In our situation the rancher/pause:3.1 image got deleted which later resulted in a unusable state as Kubernetes tried to pull this image, which it can't as it was just once imported by the airgap image. Even if the actual pod could be started as the mandatory requirements are fullfilled, it will still wait for the pause image.

**To Reproduce**
- Install k3s
- Deploy some apps, that do not trigger the pause image
- Produce disk pressure and watch the node events, it will delete data
- Try to start a deployment which will trigger the pause image.

**Expected behavior**
Mandatory images (and the ability to mark such images) should not be deleted

**Actual behavior**
The pause container image and possibly other relevant images get deleted

**Additional context / logs**
This was observed in a airgap single node instance

**Comment by C-Side** [comment] 2021-01-19 09:22
The same thing happened to me. How did you go for a fix? Reinstall the k3s?

**Comment by brandond** [comment] 2021-01-19 10:16
Restarting k3s will trigger re-import of tarballs in the images directory without taking down workload pods.

**Comment by Nold360** [comment] 2021-08-02 07:08
Still an issue in k3s 1.21.3 - duplicate of #3193

**Comment by brandond** [comment] 2021-08-02 08:44
Will be fixed in 1.22, see #3193

**Closed** 2021-08-02 08:45 UTC
