### ISSUE TITLE
K3s agent can't start: Failed to verify rule exists in KUBE-ROUTER-INPUT

### ISSUE THREAD

**Issue by rossbachp** [k3s-io/k3s#3103] opened 2021-03-20 17:20 UTC
**Environmental Info:**
k3s version v1.20.4+k3s1 (838a906a)
go version go1.15.8

**Node(s) CPU architecture, OS, and Version:**
Linux endor 5.4.0-1-generic #0~upboard2-Ubuntu SMP Sun Oct 25 14:06:23 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

iptables --version
iptables v1.8.4 (legacy)

**Cluster Configuration:**
1 master & 5 worker

Master RPI arm64 and 3 worker RPI arm64 boot without any issue!

```
cut -f1 -d " "  /proc/modules | grep -e ip_vs -e nf_conntrack
ip_vs_rr
ip_vs_wrr
ip_vs_sh
ip_vs
nf_conntrack
```

```
...
ExecStart=/usr/local/bin/k3s \
    agent \
    '--kube-proxy-arg' \
    'proxy-mode=ipvs' \
```

**Describe the bug:**

K3s agent doesn't started. Missing port to configure iptable rule!

```
Sat 2021-03-20 17:02:08.328464 UTC [s=b8fc4782704e4388a9f51c50d287f772;i=8acb;b=e1e5d0680dca4127bd3a54bfe10ff94d;m=1351697b;t=5bdfacaf8c710;x=e96a71d82275f525]
    PRIORITY=6
    _MACHINE_ID=a509a8ad18814408b572fe3a9a308810
    _HOSTNAME=endor
    SYSLOG_FACILITY=3
    _UID=0
    _GID=0
    _SELINUX_CONTEXT=unconfined
    _SYSTEMD_SLICE=system.slice
    _CAP_EFFECTIVE=3fffffffff
    _TRANSPORT=stdout
    SYSLOG_IDENTIFIER=k3s
    _CMDLINE=/usr/local/bin/k3s agent
    _SYSTEMD_CGROUP=/system.slice/k3s-agent.service
    _SYSTEMD_UNIT=k3s-agent.service
    _COMM=k3s-agent
    _EXE=/var/lib/rancher/k3s/data/a6857be08414815b83ca6b960373efd98879a0b286fb24cb62b1c5fdbf3a8cb5/bin/containerd
    _BOOT_ID=e1e5d0680dca4127bd3a54bfe10ff94d
    _STREAM_ID=79e6112995fa4676a3fbaf921369da4b
    _PID=3530
    _SYSTEMD_INVOCATION_ID=df7e9d267c96441c9761c17b745cc779
    MESSAGE=F0320 17:02:08.327931    3530 network_policy_controller.go:261] Failed to verify rule exists in KUBE-ROUTER-INPUT chain due to running [/usr/sbin/iptables -t filter -C KUBE-ROUTER-INPUT
 -p tcp -m comment --comment allow LOCAL TCP traffic to node ports - NTGHJFAJAOEPWU6M -m addrtype --dst-type LOCAL -m multiport --dports  -j RETURN --wait]: exit status 2: iptables v1.8.4 (legacy):
 invalid port/service `' specified
Sat 2021-03-20 17:02:08.328464 UTC [s=b8fc4782704e4388a9f51c50d287f772;i=8acc;b=e1e5d0680dca4127bd3a54bfe10ff94d;m=1351697b;t=5bdfacaf8c710;x=73d020f2c2b04f8e]
    PRIORITY=6
    _MACHINE_ID=a509a8ad18814408b572fe3a9a308810
    _HOSTNAME=endor
    SYSLOG_FACILITY=3
    _UID=0
    _GID=0
    _SELINUX_CONTEXT=unconfined
    _SYSTEMD_SLICE=system.slice
    _CAP_EFFECTIVE=3fffffffff
    _TRANSPORT=stdout
    SYSLOG_IDENTIFIER=k3s
    _CMDLINE=/usr/local/bin/k3s agent
    _SYSTEMD_CGROUP=/system.slice/k3s-agent.service
    _SYSTEMD_UNIT=k3s-agent.service
    _COMM=k3s-agent
    _EXE=/var/lib/rancher/k3s/data/a6857be08414815b83ca6b960373efd98879a0b286fb24cb62b1c5fdbf3a8cb5/bin/containerd
    MESSAGE=Try `iptables -h' or 'iptables --help' for more information.
    _BOOT_ID=e1e5d0680dca4127bd3a54bfe10ff94d
    _STREAM_ID=79e6112995fa4676a3fbaf921369da4b
    _PID=3530
    _SYSTEMD_INVOCATION_ID=df7e9d267c96441c9761c17b745cc779
```

**Steps To Reproduce:**

Restart the node
Restart node without ipvs -> same behavior

**Expected behavior:**

A k3s node is started.

**Actual behavior:**

* Restart loop...
* k3s agent not ready

**Additional context / logs:**

```
sudo  ipvsadm -ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.27.21.6:31963 rr
  -> 10.42.3.7:80                 Masq    1      0          0         
TCP  10.27.21.6:32659 rr
  -> 10.42.3.7:443                Masq    1      0          0         
TCP  10.27.21.224:80 rr
  -> 10.42.3.7:80                 Masq    1      0          0         
TCP  10.27.21.224:443 rr
  -> 10.42.3.7:443                Masq    1      0          0         
TCP  10.43.0.1:443 rr
  -> 10.27.21.2:6443              Masq    1      0          0         
TCP  10.43.0.10:53 rr
  -> 10.42.0.8:53                 Masq    1      0          0         
TCP  10.43.0.10:9153 rr
  -> 10.42.0.8:9153               Masq    1      0          0         
TCP  10.43.0.69:80 rr
  -> 10.42.3.7:80                 Masq    1      0          0         
TCP  10.43.0.69:443 rr
  -> 10.42.3.7:443                Masq    1      0          0         
TCP  10.43.58.119:80 rr
TCP  10.43.131.245:443 rr
  -> 10.42.3.7:8443               Masq    1      0          0         
TCP  10.43.132.168:9913 rr
  -> 10.42.3.7:10254              Masq    1      0          0         
TCP  10.43.138.116:9402 rr
  -> 10.42.1.16:9402              Masq    1      0          0         
TCP  10.43.140.219:443 rr
  -> 10.42.3.9:10250              Masq    1      0          0         
TCP  10.43.172.36:443 rr
  -> 10.42.0.9:443                Masq    1      0          0         
TCP  10.43.197.152:443 rr
  -> 10.42.3.8:8443               Masq    1      0          0         
TCP  127.0.0.1:31963 rr
  -> 10.42.3.7:80                 Masq    1      0          0         
TCP  127.0.0.1:32659 rr
  -> 10.42.3.7:443                Masq    1      0          0         
UDP  10.43.0.10:53 rr
  -> 10.42.0.8:53                 Masq    1      0          0      
```

**Comment by brandond** [comment] 2021-03-20 17:48
Duplicate of #2996. Please make sure the server is the same version or newer than the agent.

**Closed** 2021-03-20 17:49 UTC
