### ISSUE TITLE
installer fails due to hash file for stable release missing

### ISSUE THREAD

**Issue by banthalabs** [k3s-io/k3s#10608] opened 2024-07-30 02:22 UTC
**Environmental Info:**
K3s Version: 

N/A unable to install

Node(s) CPU architecture, OS, and Version: 

root@k3s:~# uname -a
Linux k3s 6.8.0-36-generic #36-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun 10 10:49:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

N/A unable to install

**Describe the bug:**

On an lxd ubuntu 24.04 vm instance, running the command `curl -sfL https://get.k3s.io | sh -` fails due to the hash file https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt not being found

**Steps To Reproduce:**

sudo snap install lxd 
sudo lxd init
lxc launch ubuntu:24.04 k3s --vm -c limits.cpu=4 -c limits.memory=4GiB
lxc shell k3s
curl -sfL https://get.k3s.io | sh -

**Expected behavior:**

Install script should be able to download hash files and complete install
curl -sfL https://get.k3s.io | sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.29.6+k3s2 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.29.6+k3s2/sha256sum-amd64.txt
[INFO]  Skipping binary downloaded, installed k3s matches hash
[INFO]  Skipping installation of SELinux RPM
[INFO]  Skipping /usr/local/bin/kubectl symlink to k3s, command exists in PATH at /snap/bin/kubectl
[INFO]  Skipping /usr/local/bin/crictl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/ctr symlink to k3s, already exists
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  No change detected so skipping service start

**Actual behavior:**

install script tries to download from stable but the file cannot be found
root@k3s:~# curl -sfL https://get.k3s.io | sh -
[INFO]  Finding release for channel stable
[INFO]  Using stable as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt
[ERROR]  Download failed

**Additional context / logs:**

Doing a curl on the url returns not found
root@k3s:~# curl https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt
Not Found

When running the installer on a ubuntu 24.04 desktop, the installer selects  v1.29.6+k3s2 as the release and is able to download the hash files. However, when running on a ubuntu 24.04 lxd vm, the install selects stable as the release instead.

**Comment by brandond** [comment] 2024-07-30 02:28
Duplicate of https://github.com/k3s-io/k3s/issues/10578

**Closed by brandond** 2024-07-30 02:28 UTC
