### ISSUE TITLE
If KUBECONFIG isn't set, default to ~/.kube/config if the file exists when invoked with `k3s kubectl`

### ISSUE THREAD

**Issue by EvanCarroll** [k3s-io/k3s#5626] opened 2022-05-31 19:59 UTC
There seems to be a strong convention to

* Have a `k3s.yaml` owned by root, and mode-ed to `0600` (this is the default on install).
* Have a local copy of `k3s.yaml` in `~/.kube/config`. Perhaps we should simply try the local `~/.kube/config` **FIRST**. That is to say, have `k3s kubectl` set `KUBECONFIG` if not set to `~/.kube/config` and if `~/.kube/config` exists.

This would stop users from having to add the `export KUBECONFIG=~/.kube/config` to their `~/.bashrc` or `~/.profile` scripts. It shaves off a step from setup.

**Comment by brandond** [comment] 2022-05-31 20:06
Duplicate of https://github.com/k3s-io/k3s/issues/1541 - answered at https://github.com/k3s-io/k3s/issues/1541#issuecomment-1029452328

**Closed by brandond** 2022-05-31 20:06 UTC
