### ISSUE TITLE
Upgrade containerd to v1.7.3

### ISSUE THREAD

**Issue by CemalUnal** [k3s-io/k3s#8149] opened 2023-08-06 15:06 UTC
containerd has recently been released at version 1.7.3: see https://github.com/containerd/containerd/releases/tag/v1.7.3.
I am raising this because v1.7.3 contains [image pin support](https://github.com/containerd/containerd/pull/8718). Currently the pause image in my k3s cluster is getting deleted by the Kubelet garbage collector. I would like to add pinned label to the pause image(and maybe other images) and prevent it from being deleting. When will the latest version of the k3s include this containerd release?

Thanks!

**Comment by brandond** [comment] 2023-08-06 16:38
Duplicate of https://github.com/k3s-io/k3s/issues/7986

**Closed by brandond** 2023-08-06 16:38 UTC
