### ISSUE TITLE
getting the final child's pid from pipe caused \\\"EOF\\\"\": unknown"

### ISSUE THREAD

**Issue by hosea118** [k3s-io/k3s#494] opened 2019-05-23 03:52 UTC
I have an arm32 linux system, the pod can't create successfully when the node is ready，here is the logs：

# ./k3s-armhf --debug  agent --pause-image=platform/pause:arm --server http
s://192.168.2.99:6443 --cluster-secret test2019 --node-name 192.168.2.220 -d /a
bdata
DEBU[0000] Asset dir /abdata/data/c7d5121e4e0ca5a45c8534f81a5ad6d429a846f670d301dac35f3e96415ec3e6
DEBU[0000] Running /abdata/data/c7d5121e4e0ca5a45c8534f81a5ad6d429a846f670d301dac35f3e96415ec3e6/bin/k3s-agent [./k3s-armhf --debug agent --pause-image=platform/pause:arm --registry=http://192.168.2.99:5000 --registry-user=admin --registry-pass=AIBee_dep* --server https://192.168.2.99:6443 --cluster-secret aibee2019 --node-name 192.168.2.220 -d /abdata]
INFO[2019-05-23T03:43:09.477004337Z] Starting k3s agent 4afd74ee (4afd74ee)
INFO[2019-05-23T03:43:09.690450337Z] Running containerd -c /abdata/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /abdata/agent/containerd
INFO[2019-05-23T03:43:09.698180337Z] Waiting for containerd startup: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /run/k3s/containerd/containerd.sock: connect: no such file or directory"
INFO[2019-05-23T03:43:09.937267337Z] starting containerd                           revision= version=1.2.5+unknown
INFO[2019-05-23T03:43:09.938647003Z] loading plugin "io.containerd.content.v1.content"...  type=io.containerd.content.v1
INFO[2019-05-23T03:43:09.938806003Z] loading plugin "io.containerd.snapshotter.v1.native"...  type=io.containerd.snapshotter.v1
INFO[2019-05-23T03:43:09.938970003Z] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  type=io.containerd.snapshotter.v1
INFO[2019-05-23T03:43:09.939380337Z] loading plugin "io.containerd.metadata.v1.bolt"...  type=io.containerd.metadata.v1
INFO[2019-05-23T03:43:09.940253337Z] loading plugin "io.containerd.differ.v1.walking"...  type=io.containerd.differ.v1
INFO[2019-05-23T03:43:09.940416003Z] loading plugin "io.containerd.gc.v1.scheduler"...  type=io.containerd.gc.v1
INFO[2019-05-23T03:43:09.940614670Z] loading plugin "io.containerd.service.v1.containers-service"...  type=io.containerd.service.v1
INFO[2019-05-23T03:43:09.940712670Z] loading plugin "io.containerd.service.v1.content-service"...  type=io.containerd.service.v1
INFO[2019-05-23T03:43:09.940780670Z] loading plugin "io.containerd.service.v1.diff-service"...  type=io.containerd.service.v1
INFO[2019-05-23T03:43:09.940858337Z] loading plugin "io.containerd.service.v1.images-service"...  type=io.containerd.service.v1
INFO[2019-05-23T03:43:09.940932670Z] loading plugin "io.containerd.service.v1.leases-service"...  type=io.containerd.service.v1
INFO[2019-05-23T03:43:09.941002003Z] loading plugin "io.containerd.service.v1.namespaces-service"...  type=io.containerd.service.v1
INFO[2019-05-23T03:43:09.941074670Z] loading plugin "io.containerd.service.v1.snapshots-service"...  type=io.containerd.service.v1
INFO[2019-05-23T03:43:09.942905337Z] loading plugin "io.containerd.runtime.v1.linux"...  type=io.containerd.runtime.v1
INFO[2019-05-23T03:43:09.943480337Z] loading plugin "io.containerd.runtime.v2.task"...  type=io.containerd.runtime.v2
INFO[2019-05-23T03:43:09.943849003Z] loading plugin "io.containerd.monitor.v1.cgroups"...  type=io.containerd.monitor.v1
INFO[2019-05-23T03:43:09.945667337Z] loading plugin "io.containerd.service.v1.tasks-service"...  type=io.containerd.service.v1
INFO[2019-05-23T03:43:09.945867670Z] loading plugin "io.containerd.internal.v1.restart"...  type=io.containerd.internal.v1
INFO[2019-05-23T03:43:09.946166670Z] loading plugin "io.containerd.grpc.v1.containers"...  type=io.containerd.grpc.v1
INFO[2019-05-23T03:43:09.946303003Z] loading plugin "io.containerd.grpc.v1.content"...  type=io.containerd.grpc.v1
INFO[2019-05-23T03:43:09.946393003Z] loading plugin "io.containerd.grpc.v1.diff"...  type=io.containerd.grpc.v1
INFO[2019-05-23T03:43:09.946472337Z] loading plugin "io.containerd.grpc.v1.events"...  type=io.containerd.grpc.v1
INFO[2019-05-23T03:43:09.946590003Z] loading plugin "io.containerd.grpc.v1.healthcheck"...  type=io.containerd.grpc.v1
INFO[2019-05-23T03:43:09.946685670Z] loading plugin "io.containerd.grpc.v1.images"...  type=io.containerd.grpc.v1
INFO[2019-05-23T03:43:09.946764670Z] loading plugin "io.containerd.grpc.v1.leases"...  type=io.containerd.grpc.v1
INFO[2019-05-23T03:43:09.946834337Z] loading plugin "io.containerd.grpc.v1.namespaces"...  type=io.containerd.grpc.v1
INFO[2019-05-23T03:43:09.946903003Z] loading plugin "io.containerd.internal.v1.opt"...  type=io.containerd.internal.v1
INFO[2019-05-23T03:43:09.947145670Z] loading plugin "io.containerd.grpc.v1.snapshots"...  type=io.containerd.grpc.v1
INFO[2019-05-23T03:43:09.947275670Z] loading plugin "io.containerd.grpc.v1.tasks"...  type=io.containerd.grpc.v1
INFO[2019-05-23T03:43:09.947362003Z] loading plugin "io.containerd.grpc.v1.version"...  type=io.containerd.grpc.v1
INFO[2019-05-23T03:43:09.947432670Z] loading plugin "io.containerd.grpc.v1.cri"...  type=io.containerd.grpc.v1
INFO[2019-05-23T03:43:09.948109003Z] Start cri plugin with config {PluginConfig:{ContainerdConfig:{Snapshotter:overlayfs DefaultRuntime:{Type:io.containerd.runtime.v1.linux Engine: Root: Options:<nil>} UntrustedWorkloadRuntime:{Type: Engine: Root: Options:<nil>} Runtimes:map[] NoPivot:false} CniConfig:{NetworkPluginBinDir:/abdata/data/c7d5121e4e0ca5a45c8534f81a5ad6d429a846f670d301dac35f3e96415ec3e6/bin NetworkPluginConfDir:/abdata/agent/etc/cni/net.d NetworkPluginConfTemplate:} Registry:{Mirrors:map[docker.io:{Endpoints:[http://192.168.2.99:5000]}] Auths:map[docker.io:{Username:admin Password:AIBee_dep* Auth: IdentityToken:}]} StreamServerAddress:192.168.2.220 StreamServerPort:10010 EnableSelinux:false SandboxImage:platform/pause:arm StatsCollectPeriod:10 SystemdCgroup:false EnableTLSStreaming:false X509KeyPairStreaming:{TLSCertFile: TLSKeyFile:} MaxContainerLogLineSize:16384 DisableCgroup:false DisableApparmor:false RestrictOOMScoreAdj:false} ContainerdRootDir:/abdata/agent/containerd ContainerdEndpoint:/run/k3s/containerd/containerd.sock RootDir:/abdata/agent/containerd/io.containerd.grpc.v1.cri StateDir:/run/k3s/containerd/io.containerd.grpc.v1.cri}
INFO[2019-05-23T03:43:09.948324003Z] Connect containerd service
INFO[2019-05-23T03:43:09.949042337Z] Get image filesystem path "/abdata/agent/containerd/io.containerd.snapshotter.v1.overlayfs"
INFO[2019-05-23T03:43:09.951782337Z] loading plugin "io.containerd.grpc.v1.introspection"...  type=io.containerd.grpc.v1
INFO[2019-05-23T03:43:09.952717337Z] serving...                                    address=/run/k3s/containerd/containerd.sock
INFO[2019-05-23T03:43:09.952858337Z] containerd successfully booted in 0.017148s
INFO[2019-05-23T03:43:09.970800003Z] Start subscribing containerd event
INFO[2019-05-23T03:43:09.989094337Z] Start recovering state
INFO[2019-05-23T03:43:10.006652670Z] Start event monitor
INFO[2019-05-23T03:43:10.007056003Z] Start snapshots syncer
INFO[2019-05-23T03:43:10.007318670Z] Start streaming server
WARN[2019-05-23T03:43:10.706791003Z] failed to start br_netfilter module
INFO[2019-05-23T03:43:10.714355670Z] Connecting to wss://192.168.2.99:6443/v1-k3s/connect
INFO[2019-05-23T03:43:10.714715337Z] Connecting to proxy                           url="wss://192.168.2.99:6443/v1-k3s/connect"
WARN[2019-05-23T03:43:10.744039337Z] Disabling CPU quotas due to missing cpu.cfs_period_us
INFO[2019-05-23T03:43:10.750487337Z] Running kubelet --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --serialize-image-pulls=false --tls-private-key-file=/abdata/agent/token-node.key --eviction-hard=imagefs.available<5%,nodefs.available<5% --cni-conf-dir=/abdata/agent/etc/cni/net.d --cert-dir=/abdata/agent/kubelet/pki --healthz-bind-address=127.0.0.1 --authorization-mode=Webhook --tls-cert-file=/abdata/agent/token-node.crt --cgroup-driver=cgroupfs --anonymous-auth=false --kubeconfig=/abdata/agent/kubeconfig.yaml --client-ca-file=/abdata/agent/client-ca.pem --hostname-override=192.168.2.220 --fail-swap-on=false --cni-bin-dir=/abdata/data/c7d5121e4e0ca5a45c8534f81a5ad6d429a846f670d301dac35f3e96415ec3e6/bin --resolv-conf=/tmp/k3s-resolv.conf --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --cluster-domain=cluster.local --root-dir=/abdata/agent/kubelet --seccomp-profile-root=/abdata/agent/kubelet/seccomp --cluster-dns=10.43.0.10 --address=0.0.0.0 --allow-privileged=true --authentication-token-webhook=true --cpu-cfs-quota=false --read-only-port=0 --container-runtime=remote
Flag --allow-privileged has been deprecated, will be removed in a future version
W0523 03:43:10.751221    2258 server.go:214] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
I0523 03:43:10.752966    2258 server.go:398] Version: v1.14.1-k3s.4
DEBU[2019-05-23T03:43:10.769681003Z] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
DEBU[2019-05-23T03:43:10.771608337Z] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
E0523 03:43:10.777124    2258 machine.go:288] failed to get cache information for node 0: open /sys/devices/system/cpu/cpu0/cache: no such file or directory
E0523 03:43:10.777535    2258 info.go:139] Failed to get system UUID: open /etc/machine-id: no such file or directory
W0523 03:43:10.777739    2258 info.go:52] Couldn't collect info from any of the files in "/etc/machine-id,/var/lib/dbus/machine-id"
DEBU[2019-05-23T03:43:10.778537670Z] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
DEBU[2019-05-23T03:43:10.779220670Z] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
I0523 03:43:10.780531    2258 server.go:591] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
I0523 03:43:10.783303    2258 container_manager_linux.go:261] container manager verified user specified cgroup-root exists: []
I0523 03:43:10.783536    2258 container_manager_linux.go:266] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:remote CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs KubeletRootDir:/abdata/agent/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:imagefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>}]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerReconcilePeriod:10s ExperimentalPodPidsLimit:-1 EnforceCPULimits:false CPUCFSQuotaPeriod:100ms}
I0523 03:43:10.784141    2258 container_manager_linux.go:286] Creating device plugin manager: true
I0523 03:43:10.784375    2258 state_mem.go:36] [cpumanager] initializing new in-memory state store
I0523 03:43:10.784962    2258 state_mem.go:84] [cpumanager] updated default cpuset: ""
I0523 03:43:10.785328    2258 state_mem.go:92] [cpumanager] updated cpuset assignments: "map[]"
I0523 03:43:10.785861    2258 kubelet.go:299] Watching apiserver
W0523 03:43:10.798423    2258 proxier.go:480] Failed to read file /lib/modules/4.9.37/modules.builtin with error open /lib/modules/4.9.37/modules.builtin: no such file or directory. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0523 03:43:10.802781    2258 proxier.go:493] Failed to load kernel module ip_vs with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0523 03:43:10.805990    2258 proxier.go:493] Failed to load kernel module ip_vs_rr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0523 03:43:10.809364    2258 proxier.go:493] Failed to load kernel module ip_vs_wrr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0523 03:43:10.813983    2258 proxier.go:493] Failed to load kernel module ip_vs_sh with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0523 03:43:10.817233    2258 proxier.go:493] Failed to load kernel module nf_conntrack_ipv4 with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
I0523 03:43:10.855778    2258 kuberuntime_manager.go:210] Container runtime containerd initialized, version: 1.2.5+unknown, apiVersion: v1alpha2
W0523 03:43:10.856505    2258 probe.go:268] Flexvolume plugin directory at /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ does not exist. Recreating.
E0523 03:43:10.856864    2258 plugins.go:570] Error initializing dynamic plugin prober: Error (re-)creating driver directory: mkdir /usr/libexec: read-only file system
I0523 03:43:10.857869    2258 server.go:987] Started kubelet
I0523 03:43:10.875260    2258 fs_resource_analyzer.go:64] Starting FS ResourceAnalyzer
I0523 03:43:10.875747    2258 volume_manager.go:248] Starting Kubelet Volume Manager
I0523 03:43:10.877034    2258 server.go:137] Starting to listen on 0.0.0.0:10250
I0523 03:43:10.884761    2258 desired_state_of_world_populator.go:130] Desired state populator starts to run
I0523 03:43:10.887035    2258 server.go:328] Adding debug handlers to kubelet server.
I0523 03:43:10.892698    2258 status_manager.go:152] Starting to sync pod status with apiserver
I0523 03:43:10.893011    2258 kubelet.go:1774] Starting kubelet main sync loop.
I0523 03:43:10.893209    2258 kubelet.go:1791] skipping pod synchronization - [container runtime status check may not have completed yet., PLEG is not healthy: pleg has yet to be successful.]
E0523 03:43:10.933335    2258 cri_stats_provider.go:373] Failed to get the info of the filesystem with mountpoint "/abdata/agent/containerd/io.containerd.snapshotter.v1.overlayfs": unable to find data in memory cache.
E0523 03:43:10.933457    2258 kubelet.go:1250] Image garbage collection failed once. Stats initialization may not have completed yet: invalid capacity 0 on image filesystem
I0523 03:43:11.014164    2258 kubelet.go:1791] skipping pod synchronization - [container runtime status check may not have completed yet., PLEG is not healthy: pleg has yet to be successful.]
DEBU[2019-05-23T03:43:11.081132003Z] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
I0523 03:43:11.170519    2258 kubelet_node_status.go:281] Setting node annotation to enable volume controller attach/detach
DEBU[2019-05-23T03:43:11.171491003Z] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
DEBU[2019-05-23T03:43:11.172163003Z] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
E0523 03:43:11.172566    2258 kubelet.go:2207] node "192.168.2.220" not found
INFO[2019-05-23T03:43:11.254453670Z] waiting for node 192.168.2.220: nodes "192.168.2.220" not found
I0523 03:43:11.268767    2258 kubelet.go:1791] skipping pod synchronization - container runtime status check may not have completed yet.
I0523 03:43:11.287482    2258 kubelet_node_status.go:70] Attempting to register node 192.168.2.220
E0523 03:43:11.322368    2258 kubelet.go:2207] node "192.168.2.220" not found
I0523 03:43:11.363691    2258 kubelet_node_status.go:281] Setting node annotation to enable volume controller attach/detach
DEBU[2019-05-23T03:43:11.364379003Z] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
DEBU[2019-05-23T03:43:11.364980003Z] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
I0523 03:43:11.414174    2258 cpu_manager.go:155] [cpumanager] starting with none policy
I0523 03:43:11.414400    2258 cpu_manager.go:156] [cpumanager] reconciling every 10s
I0523 03:43:11.414536    2258 policy_none.go:42] [cpumanager] none policy: Start
E0523 03:43:11.476168    2258 kubelet.go:2207] node "192.168.2.220" not found
W0523 03:43:11.498408    2258 node.go:113] Failed to retrieve node info: nodes "localhost" not found
I0523 03:43:11.498515    2258 server_others.go:148] Using iptables Proxier.
W0523 03:43:11.498808    2258 proxier.go:314] invalid nodeIP, initializing kube-proxy with 127.0.0.1 as nodeIP
I0523 03:43:11.515518    2258 server.go:555] Version: v1.14.1-k3s.4
E0523 03:43:11.527985    2258 eviction_manager.go:247] eviction manager: failed to get summary stats: failed to get node info: node "192.168.2.220" not found
I0523 03:43:11.532546    2258 conntrack.go:52] Setting nf_conntrack_max to 131072
I0523 03:43:11.540616    2258 config.go:202] Starting service config controller
I0523 03:43:11.540876    2258 controller_utils.go:1027] Waiting for caches to sync for service config controller
I0523 03:43:11.541076    2258 config.go:102] Starting endpoints config controller
I0523 03:43:11.542798    2258 controller_utils.go:1027] Waiting for caches to sync for endpoints config controller
I0523 03:43:11.572050    2258 kubelet_node_status.go:73] Successfully registered node 192.168.2.220
E0523 03:43:11.702710    2258 kubelet.go:2207] node "192.168.2.220" not found
I0523 03:43:11.785980    2258 reconciler.go:154] Reconciler: start to sync state
I0523 03:43:11.792242    2258 controller_utils.go:1034] Caches are synced for endpoints config controller
E0523 03:43:11.830565    2258 kubelet.go:2207] node "192.168.2.220" not found
I0523 03:43:11.923257    2258 kubelet_node_status.go:281] Setting node annotation to enable volume controller attach/detach
DEBU[2019-05-23T03:43:11.924127670Z] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
DEBU[2019-05-23T03:43:11.924735004Z] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
I0523 03:43:11.977892    2258 controller_utils.go:1034] Caches are synced for service config controller
I0523 03:43:12.015133    2258 kuberuntime_manager.go:946] updating runtime config through cri with podcidr 10.42.13.0/24
INFO[2019-05-23T03:43:12.143351670Z] No cni config template is specified, wait for other system components to drop the config.
I0523 03:43:12.177232    2258 kubelet_network.go:69] Setting Pod CIDR:  -> 10.42.13.0/24
DEBU[2019-05-23T03:43:12.182581004Z] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
DEBU[2019-05-23T03:43:12.183454337Z] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
E0523 03:43:12.184545    2258 proxier.go:1366] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 11 failed
)
DEBU[2019-05-23T03:43:12.345390004Z] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
DEBU[2019-05-23T03:43:12.346178004Z] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
I0523 03:43:12.360564    2258 reconciler.go:181] operationExecutor.UnmountVolume started for volume "default-token-5wwxh" (UniqueName: "kubernetes.io/secret/7386a39a-7d0b-11e9-afab-94c6911fb820-default-token-5wwxh") pod "7386a39a-7d0b-11e9-afab-94c6911fb820" (UID: "7386a39a-7d0b-11e9-afab-94c6911fb820")
I0523 03:43:12.361035    2258 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "dev" (UniqueName: "kubernetes.io/host-path/c166cc66-7d0c-11e9-afab-94c6911fb820-dev") pod "carsdkarm-vw265" (UID: "c166cc66-7d0c-11e9-afab-94c6911fb820")
I0523 03:43:12.361378    2258 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-5wwxh" (UniqueName: "kubernetes.io/secret/c166cc66-7d0c-11e9-afab-94c6911fb820-default-token-5wwxh") pod "carsdkarm-vw265" (UID: "c166cc66-7d0c-11e9-afab-94c6911fb820")
I0523 03:43:12.400655    2258 operation_generator.go:799] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/7386a39a-7d0b-11e9-afab-94c6911fb820-default-token-5wwxh" (OuterVolumeSpecName: "default-token-5wwxh") pod "7386a39a-7d0b-11e9-afab-94c6911fb820" (UID: "7386a39a-7d0b-11e9-afab-94c6911fb820"). InnerVolumeSpecName "default-token-5wwxh". PluginName "kubernetes.io/secret", VolumeGidValue ""
I0523 03:43:12.470718    2258 reconciler.go:285] Volume detached for volume "default-token-5wwxh" (UniqueName: "kubernetes.io/secret/7386a39a-7d0b-11e9-afab-94c6911fb820-default-token-5wwxh") on node "192.168.2.220" DevicePath ""
INFO[2019-05-23T03:43:12.743999670Z] RunPodsandbox for &PodSandboxMetadata{Name:carsdkarm-vw265,Uid:c166cc66-7d0c-11e9-afab-94c6911fb820,Namespace:default,Attempt:0,}
INFO[2019-05-23T03:43:12.899523004Z] shim containerd-shim started                  address=/containerd-shim/k8s.io/64a9a0b833eb69855aeb57a800cc5c5fe813735e4752b1a8683b566578aafd37/shim.sock debug=false pid=2363
INFO[2019-05-23T03:43:13.003370337Z] shim reaped                                   id=64a9a0b833eb69855aeb57a800cc5c5fe813735e4752b1a8683b566578aafd37
W0523 03:43:13.029204    2258 kubelet_getters.go:279] Path "/abdata/agent/kubelet/pods/7386a39a-7d0b-11e9-afab-94c6911fb820/volumes" does not exist
ERRO[2019-05-23T03:43:13.180331670Z] RunPodSandbox for &PodSandboxMetadata{Name:carsdkarm-vw265,Uid:c166cc66-7d0c-11e9-afab-94c6911fb820,Namespace:default,Attempt:0,} failed, error  error="failed to start sandbox container: failed to create containerd task: OCI runtime create failed: container_linux.go:345: starting container process caused \"process_linux.go:303: getting the final child's pid from pipe caused \\\"EOF\\\"\": unknown"
E0523 03:43:13.182310    2258 remote_runtime.go:109] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox container: failed to create containerd task: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:303: getting the final child's pid from pipe caused \"EOF\"": unknown

Can anyone help？thanks！

**Comment by erikwilson** [comment] 2019-05-23 15:34
It looks like the kernel is not built with the necessary modules. Can you give more information on the device & kernel?

**Comment by hosea118** [comment] 2019-05-24 03:10
> It looks like the kernel is not built with the necessary modules. Can you give more information on the device & kernel?
The attach files is generated by ‘cat /proc/kallsyms > /home/kallsyms.txt’.
I do not have the kernel source code so I cannot provide the kernel configuration file now

[kallsyms.txt](https://github.com/rancher/k3s/files/3214890/kallsyms.txt)

**Comment by github-ninjya** [comment] 2019-06-29 08:46
My built k3s-armhf reproduces the same problem in arm32v7 env.
On the other hand, I know the released k3s-armhf works fine.
For example, https://github.com/rancher/k3s/releases/download/v0.6.1/k3s-armhf
So, there is no kernel module issue in my case.

BTW, how do you guys build k3s-armhf ?

I just kick "make" in top of src dir like below.
~~~
# git checkout v0.6.1
# make
# ./dist/artifacts/k3s-armhf server
(snip)
E0629 17:43:37.260958   14681 pod_workers.go:190] Error syncing pod 6bc38e4b-9a1b-11e9-bdee-2c4d54429983 ("traefik-56688c4464-kgl9k_kube-system(6bc38e4b-9a1b-11e9-bdee-2c4d54429983)"), skipping: failed to "CreatePodSandbox" for "traefik-56688c4464-kgl9k_kube-system(6bc38e4b-9a1b-11e9-bdee-2c4d54429983)" with CreatePodSandboxError: "CreatePodSandbox for pod \"traefik-56688c4464-kgl9k_kube-system(6bc38e4b-9a1b-11e9-bdee-2c4d54429983)\" failed: rpc error: code = Unknown desc = failed to start sandbox container: failed to create containerd task: OCI runtime create failed: container_linux.go:345: starting container process caused \"process_linux.go:303: getting the final child's pid from pipe caused \\\"EOF\\\"\": unknown"
~~~

**Comment by TaichiKageyama** [comment] 2019-08-04 03:23
In my case, self-built k3s, actually "runc" introduces this error on arm32v7 platform.
My workaround is here.
~~~
# docker pull arm32v6/golang:1.12.1-alpine3.9
# docker tag arm32v6/golang:1.12.1-alpine3.9 golang:1.12.1-alpine3.9
# git clone https://github.com/rancher/k3s.git
# git checkout v0.7.0
# cd k3s
# make
~~~

The build script tries to pull golang:1.12.1-alpine3.9 and then arm32v7/golang:1.12.1-alpine3.9 is usually pulled on arm32v7 env.  However,  It seems arm32v7 image is not good for build env.
I guess something linked with runc in the images introduces segment error because the "runc" provided by arm32v7/alpine also doesn't work.
See https://gitlab.alpinelinux.org/alpine/aports/issues/10139

**Comment by wstian** [comment] 2020-04-13 11:06
grep docker container on the node, to which the pod is assigned
```
docker ps -a |grep [pod-name]
```

a related `pause` container is in `Created` status， got the container id. then grep the 
`/var/log/meessage` ， you will find the root cause, why pause container failed to create.

in our case,  the error is ` page allocation failure`, which it's due to low system free memory. To fix this,  
according to this article https://discuss.aerospike.com/t/page-allocation-failure/2856
```
# free the caches
sync ; echo 3|tee /proc/sys/vm/drop_caches
# rm the container, the kubelet will restart the pod
docker rm <container-id>
```

to prevent, increase the free memory
```
sysctl -w vm.min_free_kbytes=5242880
```

**Comment by brandond** [comment] 2020-04-13 17:36
@wstian if your system has so little memory that you have to drop the filesystem caches just to get pods to run, it might have too little memory to reliably run k3s.

**Comment by brandond** [comment] 2020-12-05 00:44
Closing due to age.

**Closed by brandond** 2020-12-05 00:44 UTC
