### ISSUE TITLE
Flannel specify IP address

### ISSUE THREAD

**Issue by andyleap** [k3s-io/k3s#1365] opened 2020-01-30 18:03 UTC
**Is your feature request related to a problem? Please describe.**
the `--flannel-iface` flag only accepts interface names, and binds to the "most open" IP address on that interface.  In my cloud (Linode), VMs get an interface with 2 IPs if you set up a private IP for the VM.  I'd like to route flannel traffic between the VMs over the private IP(it's free, whereas inter-VM traffic over the public IP is charged, and it's also a little more secure)

**Describe the solution you'd like**
Either expand `--flannel-iface` to allow an IP and look up the interface it's associated with, or add a `--flannel-ip` flag that can pass an IP to override the ip bind.

**Describe alternatives you've considered**
Should be possible to override this via manually configure flannel, but that's a lot of headache for something so trivial.

**Comment by galal-hussein** [comment] 2020-02-05 23:04
I think this can be added to k3s by passing `public-ip` to the flannel command line like flannel-iface

**Comment by orangejuice** [comment] 2020-03-23 20:05
Yeah, this is a very useful. It can also make specify a public ip to be used as flannel communication possible. As when we using the clusters on cloud VMs, there is usually no interfaces with the real public ip.

**Comment by caroline-suse-rancher** [comment] 2022-11-30 17:31
@manuelbuil does the flannel-external-ip flag handle this now?

**Comment by manuelbuil** [comment] 2022-11-30 18:28
> @manuelbuil does the flannel-external-ip flag handle this now?

Not exactly, but I think it should be possible by defining `node-ip` in the config file. Flannel will pick that information up. @andyleap if you are still looking for a solution, could you give that a try please?

**Comment by caroline-suse-rancher** [comment] 2023-02-21 14:54
Closing for now - can reopen if the issue re-emerges

**Closed by caroline-suse-rancher** 2023-02-21 14:54 UTC
Labels: kind/enhancement

**Comment by wedi** [comment] 2023-03-12 00:57
> can reopen if the issue re-emerges

@caroline-suse-rancher Please reopen this issue.


> Flannel will pick that information up.

@manuelbuil Unfortunately the IP is not picket up.

I installed k3s on Hetzner cloud servers with both public and private IPs using `--node-ip 10.0.0.2`. There is no connection unless I open port 8472 udp for the public IPs on the cloud network firewall (no local firewall).
I also tried `--node-ip 10.0.0.2 --node-external-ip 1.2.3.4`.

```sh
# netstat -ulpn | grep 8472
udp        0      0 0.0.0.0:8472            0.0.0.0:*                           -
```

I can post all commands necessary to replicate this on Hetzner if you are interested.

**Comment by thomasferrandiz** [comment] 2023-03-14 13:53
@wedi could you share the steps you use to replicate this issue?
I'm trying to reproduce it but on AWS I don't have any issue because the public IP is not the VM interface itself.

**Comment by wb14123** [comment] 2023-10-16 02:10
@thomasferrandiz  I'm facing the same issue: flannel doesn't pickup `--node-ip`. Even though I can resolve it by defining `--flannel-iface`, it would be great it can pickup node ip or  have a configuration like `--flannel-ip` . I have this Vagrant file that can reproduce it:

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

distro = "hashicorp/bionic64"


Vagrant.configure("2") do |config|
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  # disable firewall
  config.vm.provision "shell", inline: "ufw disable"

  # requirement for longhorn
  config.vm.provision "shell", inline: "apt-get install open-iscsi"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  config.vm.define "k3s-server1" do |v|
    v.vm.box = distro
    v.vm.hostname = "k3s-server1"
    v.vm.network "private_network", ip: "192.168.56.2"
    v.vm.provision "file", source: "./k3s-config/server1.yaml", destination: "$HOME/k3s-config.yaml"
    v.vm.provision "shell", inline: "mkdir -p /etc/rancher/k3s && mv /home/vagrant/k3s-config.yaml /etc/rancher/k3s/config.yaml"
    v.vm.provision "shell", inline: "curl -sfL https://get.k3s.io | sh -"
    v.vm.provision "file", source: "./longhorn.yaml", destination: "$HOME/longhorn.yaml"
  end

  config.vm.define "k3s-server2" do |v|
    v.vm.box = distro
    v.vm.hostname = "k3s-server2"
    v.vm.network "private_network", ip: "192.168.56.3"
    v.vm.provision "file", source: "./k3s-config/server2.yaml", destination: "$HOME/k3s-config.yaml"
    v.vm.provision "shell", inline: "mkdir -p /etc/rancher/k3s && mv /home/vagrant/k3s-config.yaml /etc/rancher/k3s/config.yaml"
    v.vm.provision "shell", inline: "curl -sfL https://get.k3s.io | sh -"
  end

  config.vm.define "k3s-server3" do |v|
    v.vm.box = distro
    v.vm.hostname = "k3s-server3"
    v.vm.network "private_network", ip: "192.168.56.4"
    v.vm.provision "file", source: "./k3s-config/server3.yaml", destination: "$HOME/k3s-config.yaml"
    v.vm.provision "shell", inline: "mkdir -p /etc/rancher/k3s && mv /home/vagrant/k3s-config.yaml /etc/rancher/k3s/config.yaml"
    v.vm.provision "shell", inline: "curl -sfL https://get.k3s.io | sh -"
  end

  config.vm.define "k3s-agent1" do |v|
    v.vm.box = distro
    v.vm.hostname = "k3s-agent1"
    v.vm.network "private_network", ip: "192.168.56.5"
    v.vm.provision "file", source: "./k3s-config/agent1.yaml", destination: "$HOME/k3s-config.yaml"
    v.vm.provision "shell", inline: "mkdir -p /etc/rancher/k3s && mv /home/vagrant/k3s-config.yaml /etc/rancher/k3s/config.yaml"
    v.vm.provision "shell", inline: "curl -sfL https://get.k3s.io | sh -s agent -"
  end

end

```

Here are the config files:

```yaml
==> k3s-config/agent1.yaml <==
node-ip: "192.168.56.4"
token: unsecureagenttoken
server: https://192.168.56.2:6443

==> k3s-config/server1.yaml <==
cluster-init: true
disable-helm-controller: true
disable:
  - traefik
node-ip: "192.168.56.2"
token: unsecureservertoken
agent-token: unsecureagenttoken

==> k3s-config/server2.yaml <==
disable-helm-controller: true
disable:
  - traefik
node-ip: "192.168.56.3"
token: unsecureservertoken
agent-token: unsecureagenttoken
server: https://192.168.56.2:6443

==> k3s-config/server3.yaml <==
disable-helm-controller: true
disable:
  - traefik
node-ip: "192.168.56.4"
token: unsecureservertoken
agent-token: unsecureagenttoken
server: https://192.168.56.2:6443
```

It creates network interfaces like this:

```
root@k3s-server1:~# ip a                                                                  
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00                                                                                                                            
    inet 127.0.0.1/8 scope host lo                                                        
       valid_lft forever preferred_lft forever         
    inet6 ::1/128 scope host                                                              
       valid_lft forever preferred_lft forever    
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:bb:14:75 brd ff:ff:ff:ff:ff:ff                                                                                                                               
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0       
       valid_lft 85609sec preferred_lft 85609sec  
    inet6 fe80::a00:27ff:febb:1475/64 scope link 
       valid_lft forever preferred_lft forever                                                                                                                                       
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:99:da:54 brd ff:ff:ff:ff:ff:ff
    inet 192.168.56.2/24 brd 192.168.56.255 scope global eth1
       valid_lft forever preferred_lft forever                                                                                                                                       
    inet6 fe80::a00:27ff:fe99:da54/64 scope link                     
       valid_lft forever preferred_lft forever 
```

The IP `192.168.56.2` is bound to `eth1`, which is used for communication between nodes. However, flannel is still using eth0:

```
Oct 16 01:50:11 k3s-server1 k3s[820]: time="2023-10-16T01:50:11Z" level=info msg="The interface eth0 with ipv4 address 10.0.2.15 will be used by flannel"
```
