### ISSUE TITLE
install script refers to checksum txt which does not exist

### ISSUE THREAD

**Issue by JustinGuese** [k3s-io/k3s#10610] opened 2024-07-30 07:21 UTC
When trying to install k3s via the script
curl -sfL https://get.k3s.io ...
it fails at the "get checksum txt" step, and the link really does not exist (404)
Downloading hash https://github.com/k3s-io/k3s/releases/download/latest/sha256sum-amd64.txt
Downloading hash https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt

**Comment by brandond** [comment] 2024-07-30 08:36
Duplicate of https://github.com/k3s-io/k3s/issues/10578

**Closed by brandond** 2024-07-30 08:36 UTC
