### ISSUE TITLE
Ability to use Basic Auth File

### ISSUE THREAD

**Issue by adi90x** [k3s-io/k3s#424] opened 2019-05-01 09:31 UTC
**Describe the bug**
Trying to use the new --kube-apiserver-arg to enable basic auth in k3s

**To Reproduce**
`sudo k3s server --no-deploy traefik --kube-apiserver-arg basic-auth-file=/home/adrienm/pass.csv --kube-apiserver-arg v=9`

**Expected behavior**
K3S server starting as expected

**Error**
`panic: creating CRD store Unauthorized`

`goroutine 544 [running]: github.com/rancher/k3s/vendor/github.com/rancher/norman/stor/crd.(*Factory).BatchCreateCRDs.func1(0x400168ac20, 0x4001363e00, 0x3, 0x3, 0x400197ebe0, 0x58c4d20, 0x3747500, 0x4001363fb0, 0x0, 0x0)`
	`/go/src/github.com/rancher/k3s/vendor/github.com/rancher/norman/store/crd/init.go:65 +0x258
created by github.com/rancher/k3s/vendor/github.com/rancher/norman/store/crd.(*Factory).BatchCreateCRDs
	/go/src/github.com/rancher/k3s/vendor/github.com/rancher/norman/store/crd/init.go:50 +0x9c`

**Full logs**

[Pastebin code](https://pastebin.com/BCTXUCwg)

Without this flag it start as expected.

**Comment by galal-hussein** [comment] 2019-05-01 17:19
@adi90x The problem is that the rest of components are using the following kubeconfig `/var/lib/rancher/k3s/server/cred/kubeconfig-system.yaml` which is generated by k3s and contain different credentials than the one you specified in the basic auth file, this will not work because this changes the way k3s orchestrate the authentication between components.

**Comment by adi90x** [comment] 2019-05-01 17:23
Ok make senses, at the moment I am adding the content of my file to the one
generated by k3s and reloading the service, will stick to that solution
then.

Le mer. 1 mai 2019 à 19:20, Hussein Galal <notifications@github.com> a
écrit :

**Comment by caroline-suse-rancher** [comment] 2023-04-26 18:54
Closing due to age

**Closed by caroline-suse-rancher** 2023-04-26 18:54 UTC
Labels: kind/enhancement
