### ISSUE TITLE
Upgrading a k3s node with ipvs as kube-proxy-mode renders NodePort unreachable

### ISSUE THREAD

**Issue by CiraciNicolo** [k3s-io/k3s#5031] opened 2022-01-26 19:04 UTC
**Environmental Info:**
K3s Version: 
k3s version v1.22.5+k3s1 (405bf79d)

Node(s) CPU architecture, OS, and Version: 
Linux hostname 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Single node

**Describe the bug:**
Upgrading a k3s node with ipvs as kube-proxy-mode renders NodePort unreachable

**Steps To Reproduce:**
- Installed K3s:
- Use ipvs as proxy mode
- Upgrade via UpgradController 
- NodePorts are unreachable with connection failed 

**Expected behavior:**
Upgrade a node should not render NodePort unreachable

**Actual behavior:**
NodePort are unreachable

**Fix**
Rebooting the node fixes the issue, using k3s-killall.sh or restarting k3s service DID NOT fix the issue. Is this a known issue?

**Comment by vincentchivas** [comment] 2022-06-28 02:58
i have the same problem

**Comment by brandond** [comment] 2022-06-28 23:45
I suspect this is an upstream issue, or perhaps related to the host OS. We're not doing anything special with kube-proxy. 

@vincentchivas are you also on EL7?

**Comment by sigurdblueface** [comment] 2022-11-14 15:37
same issue on ubuntu 22.04 and v1.22.2+k3s2

**Comment by thomasferrandiz** [comment] 2023-02-27 10:44
I tested with an upgrade from k3s 1.25.6 to 1.26.1 and the NodePort was still reachable after the upgrade.

Command used to install k3s:
```
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik,metrics-server,--kube-proxy-arg=ipvs-scheduler=lc,proxy-mode=ipvs" sh -s -
```

**Comment by caroline-suse-rancher** [comment] 2023-02-28 22:39
Closing, as we cannot reproduce with more recent versions

**Closed by caroline-suse-rancher** 2023-02-28 22:39 UTC
Labels: kind/bug
