### ISSUE TITLE
Port 80 and 443 are in a filtered state for any node beyond master-1

### ISSUE THREAD

**Issue by akingstonlas** [k3s-io/k3s#8348] opened 2023-09-13 20:51 UTC
**Environmental Info:**
K3s Version: 
k3s version v1.27.5+k3s1 (8d074ecb)
go version go1.20.7

Node(s) CPU architecture, OS, and Version: 
Linux awx-worker1 5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
2 masters 1 Worker

**Describe the bug:**
When adding nodes to the cluster whether another master or worker, once the svclb-traefik pod comes up for the node the nmap shows that the ports 443 and 80 are filtered. This is the case only for the nodes that are getting added and not the original master node. 

I have looked at the logs for container lb-tcp-80 and  lb-tcp-443 and everything is nominal from what I can tell

NMAP output master-1

```
root@MCSTD4-A-VDI027:~# nmap -sV 10.86.44.101
Starting Nmap 7.80 ( https://nmap.org ) at 2023-09-13 13:38 PDT
Nmap scan report for 10.86.44.101
Host is up (0.0015s latency).
Not shown: 997 closed ports
PORT    STATE SERVICE  VERSION
22/tcp  open  ssh      OpenSSH 8.9p1 Ubuntu 3ubuntu0.3 (Ubuntu Linux; protocol 2.0)
80/tcp  open  http     Golang net/http server (Go-IPFS json-rpc or InfluxDB API)
443/tcp open  ssl/http Golang net/http server (Go-IPFS json-rpc or InfluxDB API)
Service Info: OS: Linux; CPE: cpe:/o:linux:linux_kernel
```

NMAP output master-2

```
~# nmap -sV 10.86.44.102
Starting Nmap 7.80 ( https://nmap.org ) at 2023-09-13 13:37 PDT
Nmap scan report for 10.86.44.102
Host is up (0.0018s latency).
Not shown: 997 closed ports
PORT    STATE    SERVICE VERSION
22/tcp  open     ssh     OpenSSH 8.9p1 Ubuntu 3ubuntu0.3 (Ubuntu Linux; protocol 2.0)
80/tcp  filtered http
443/tcp filtered https
Service Info: OS: Linux; CPE: cpe:/o:linux:linux_kerne
```

```
kubectl get nodes
NAME          STATUS   ROLES                  AGE   VERSION
awx-master1   Ready    control-plane,master   55m   v1.27.5+k3s1
awx-master2   Ready    control-plane,master   52m   v1.27.5+k3s1
```

```
kubectl describe node awx-master2
Name:               awx-master2
Roles:              control-plane,master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=k3s
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=awx-master2
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/control-plane=true
                    node-role.kubernetes.io/master=true
                    node.kubernetes.io/instance-type=k3s
Annotations:        flannel.alpha.coreos.com/backend-data: {"VNI":1,"VtepMAC":"5e:e8:e3:a0:9a:0d"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 10.86.44.102
                    k3s.io/hostname: awx-master2
                    k3s.io/internal-ip: 10.86.44.102
                    k3s.io/node-args: ["agent"]
                    k3s.io/node-config-hash: XNMUH4OBHDEZETQJKX47MEUR2Z4BSSLJDFLBPN3KFWOSUFB7QMSQ====
                    k3s.io/node-env:
                      {"K3S_DATA_DIR":"/var/lib/rancher/k3s/data/8a84c92c5c245778005e7fa2a03c4d84118fde366594fe826bcd7351d8b88d21","K3S_TOKEN":"********","K3S_U...
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Wed, 13 Sep 2023 19:55:24 +0000
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  awx-master2
  AcquireTime:     <unset>
  RenewTime:       Wed, 13 Sep 2023 20:48:49 +0000
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Wed, 13 Sep 2023 20:46:59 +0000   Wed, 13 Sep 2023 19:55:24 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Wed, 13 Sep 2023 20:46:59 +0000   Wed, 13 Sep 2023 19:55:24 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Wed, 13 Sep 2023 20:46:59 +0000   Wed, 13 Sep 2023 19:55:24 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Wed, 13 Sep 2023 20:46:59 +0000   Wed, 13 Sep 2023 19:55:24 +0000   KubeletReady                 kubelet is posting ready status. AppArmor enabled
Addresses:
  InternalIP:  10.86.44.102
  Hostname:    awx-master2
Capacity:
  cpu:                4
  ephemeral-storage:  102623160Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             8128044Ki
  pods:               110
Allocatable:
  cpu:                4
  ephemeral-storage:  99831809970
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             8128044Ki
  pods:               110
System Info:
  Machine ID:                 83866d265cf44e2b93c6b6add19bfe5f
  System UUID:                29111842-1b3a-4154-5129-b43557de4c69
  Boot ID:                    45e77323-191d-4e41-b0c7-5d7b239a8fe9
  Kernel Version:             5.15.0-83-generic
  OS Image:                   Ubuntu 22.04.1 LTS
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.7.3-k3s1
  Kubelet Version:            v1.27.5+k3s1
  Kube-Proxy Version:         v1.27.5+k3s1
PodCIDR:                      10.42.1.0/24
PodCIDRs:                     10.42.1.0/24
ProviderID:                   k3s://awx-master2
Non-terminated Pods:          (1 in total)
  Namespace                   Name                            CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                            ------------  ----------  ---------------  -------------  ---
  kube-system                 svclb-traefik-45ab9192-568bz    0 (0%)        0 (0%)      0 (0%)           0 (0%)         53m
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests  Limits
  --------           --------  ------
  cpu                0 (0%)    0 (0%)
  memory             0 (0%)    0 (0%)
  ephemeral-storage  0 (0%)    0 (0%)
  hugepages-1Gi      0 (0%)    0 (0%)
  hugepages-2Mi      0 (0%)    0 (0%)
Events:
  Type     Reason                   Age                From                   Message
  ----     ------                   ----               ----                   -------
  Normal   Starting                 53m                kube-proxy
  Normal   Synced                   53m                cloud-node-controller  Node synced successfully
  Normal   RegisteredNode           53m                node-controller        Node awx-master2 event: Registered Node awx-master2 in Controller
  Normal   Starting                 53m                kubelet                Starting kubelet.
  Warning  InvalidDiskCapacity      53m                kubelet                invalid capacity 0 on image filesystem
  Normal   NodeAllocatableEnforced  53m                kubelet                Updated Node Allocatable limit across pods
  Normal   NodeHasSufficientMemory  53m (x2 over 53m)  kubelet                Node awx-master2 status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    53m (x2 over 53m)  kubelet                Node awx-master2 status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     53m (x2 over 53m)  kubelet                Node awx-master2 status is now: NodeHasSufficientPID
  Normal   NodeReady                53m                kubelet                Node awx-master2 status is now: NodeReady
```

```
kubectl describe pod svclb-traefik-45ab9192-568bz -n kube-system
Name:             svclb-traefik-45ab9192-568bz
Namespace:        kube-system
Priority:         0
Service Account:  svclb
Node:             awx-master2/10.86.44.102
Start Time:       Wed, 13 Sep 2023 19:55:25 +0000
Labels:           app=svclb-traefik-45ab9192
                  controller-revision-hash=649987f7f6
                  pod-template-generation=1
                  svccontroller.k3s.cattle.io/svcname=traefik
                  svccontroller.k3s.cattle.io/svcnamespace=kube-system
Annotations:      <none>
Status:           Running
IP:               10.42.1.2
IPs:
  IP:           10.42.1.2
Controlled By:  DaemonSet/svclb-traefik-45ab9192
Containers:
  lb-tcp-80:
    Container ID:   containerd://b733a8f1a7260bde0f0805193f21dbb2f673206995e2629f01e285c955687dde
    Image:          rancher/klipper-lb:v0.4.4
    Image ID:       docker.io/rancher/klipper-lb@sha256:d6780e97ac25454b56f88410b236d52572518040f11d0db5c6baaac0d2fcf860
    Port:           80/TCP
    Host Port:      80/TCP
    State:          Running
      Started:      Wed, 13 Sep 2023 19:55:27 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      SRC_PORT:    80
      SRC_RANGES:  0.0.0.0/0
      DEST_PROTO:  TCP
      DEST_PORT:   80
      DEST_IPS:    10.43.85.209
    Mounts:        <none>
  lb-tcp-443:
    Container ID:   containerd://7a4d99aacf04437c65586e3ffabc0f1092639233d6fc5d446f229fc02b062f27
    Image:          rancher/klipper-lb:v0.4.4
    Image ID:       docker.io/rancher/klipper-lb@sha256:d6780e97ac25454b56f88410b236d52572518040f11d0db5c6baaac0d2fcf860
    Port:           443/TCP
    Host Port:      443/TCP
    State:          Running
      Started:      Wed, 13 Sep 2023 19:55:27 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      SRC_PORT:    443
      SRC_RANGES:  0.0.0.0/0
      DEST_PROTO:  TCP
      DEST_PORT:   443
      DEST_IPS:    10.43.85.209
    Mounts:        <none>
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:            <none>
QoS Class:          BestEffort
Node-Selectors:     <none>
Tolerations:        CriticalAddonsOnly op=Exists
                    node-role.kubernetes.io/control-plane:NoSchedule op=Exists
                    node-role.kubernetes.io/master:NoSchedule op=Exists
                    node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                    node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                    node.kubernetes.io/not-ready:NoExecute op=Exists
                    node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                    node.kubernetes.io/unreachable:NoExecute op=Exists
                    node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  47m   default-scheduler  Successfully assigned kube-system/svclb-traefik-45ab9192-568bz to awx-master2
  Normal  Pulling    47m   kubelet            Pulling image "rancher/klipper-lb:v0.4.4"
  Normal  Pulled     47m   kubelet            Successfully pulled image "rancher/klipper-lb:v0.4.4" in 1.000929299s (1.000945852s including waiting)
  Normal  Created    47m   kubelet            Created container lb-tcp-80
  Normal  Started    47m   kubelet            Started container lb-tcp-80
  Normal  Pulled     47m   kubelet            Container image "rancher/klipper-lb:v0.4.4" already present on machine
  Normal  Created    47m   kubelet            Created container lb-tcp-443
  Normal  Started    47m   kubelet            Started container lb-tcp-443
```

```
 kubectl logs  svclb-traefik-45ab9192-568bz -c  lb-tcp-443 -n kube-system
+ trap exit TERM INT
+ BIN_DIR=/sbin
+ check_iptables_mode
+ set +e
+ lsmod
+ grep nf_tables
nf_tables             249856 292 nft_chain_nat,nft_compat,nft_counter
nfnetlink              20480  4 nf_conntrack_netlink,ip_set,nft_compat,nf_tables
libcrc32c              16384  5 nf_nat,nf_conntrack,nf_tables,btrfs,raid456
+ '[' 0 '=' 0 ]
+ mode=nft
+ set -e
+ info 'nft mode detected'
+ echo '[INFO] ' 'nft mode detected'
+ set_nft
+ ln -sf /sbin/xtables-nft-multi /sbin/iptables
[INFO]  nft mode detected
+ ln -sf /sbin/xtables-nft-multi /sbin/iptables-save
+ ln -sf /sbin/xtables-nft-multi /sbin/iptables-restore
+ ln -sf /sbin/xtables-nft-multi /sbin/ip6tables
+ start_proxy
+ echo 0.0.0.0/0
+ grep -Eq :
+ iptables -t filter -I FORWARD -s 0.0.0.0/0 -p TCP --dport 443 -j ACCEPT
+ echo 10.43.85.209
+ grep -Eq :
+ cat /proc/sys/net/ipv4/ip_forward
+ '[' 1 '==' 1 ]
+ iptables -t filter -A FORWARD -d 10.43.85.209/32 -p TCP --dport 443 -j DROP
+ iptables -t nat -I PREROUTING -p TCP --dport 443 -j DNAT --to 10.43.85.209:443
+ iptables -t nat -I POSTROUTING -d 10.43.85.209/32 -p TCP -j MASQUERADE
+ '[' '!' -e /pause ]
+ mkfifo /pause
```

```
kubectl logs  svclb-traefik-45ab9192-568bz -c  lb-tcp-80 -n kube-system
+ trap exit TERM INT
+ BIN_DIR=/sbin
+ check_iptables_mode
+ set +e
+ lsmod
+ grep nf_tables
nf_tables             249856 272 nft_chain_nat,nft_compat,nft_counter
nfnetlink              20480  4 nf_conntrack_netlink,ip_set,nft_compat,nf_tables
libcrc32c              16384  5 nf_nat,nf_conntrack,nf_tables,btrfs,raid456
+ '[' 0 '=' 0 ]
+ mode=nft
+ set -e
+ info 'nft mode detected'
+ echo '[INFO] ' 'nft mode detected'
+ set_nft
[INFO]  nft mode detected
+ ln -sf /sbin/xtables-nft-multi /sbin/iptables
+ ln -sf /sbin/xtables-nft-multi /sbin/iptables-save
+ ln -sf /sbin/xtables-nft-multi /sbin/iptables-restore
+ ln -sf /sbin/xtables-nft-multi /sbin/ip6tables
+ start_proxy
+ echo 0.0.0.0/0
+ grep -Eq :
+ iptables -t filter -I FORWARD -s 0.0.0.0/0 -p TCP --dport 80 -j ACCEPT
+ + echo 10.43.85.209grep
 -Eq :
+ cat /proc/sys/net/ipv4/ip_forward
+ '[' 1 '==' 1 ]
+ iptables -t filter -A FORWARD -d 10.43.85.209/32 -p TCP --dport 80 -j DROP
+ iptables -t nat -I PREROUTING -p TCP --dport 80 -j DNAT --to 10.43.85.209:80
+ iptables -t nat -I POSTROUTING -d 10.43.85.209/32 -p TCP -j MASQUERADE
+ '[' '!' -e /pause ]
+ mkfifo /pause
```

**Steps To Reproduce:**

- Installed K3s: 
Added the nodes with the appropriate token with 

``curl -sfL https://get.k3s.io | K3S_URL=https://10.86.44.101:6443 K3S_TOKEN="<token>" sh -`

**Expected behavior:**
The expected behavior would be for the ports to be open

**Actual behavior:**
Ports are in a filtered state, If I shuffle the IPs the effect is the same meaning the main master will always be open and workers/master-2 will be in a filtered state which is causing issues when deploying a web server

**Comment by brandond** [comment] 2023-09-13 22:25
Are you running with ufw or firewalld enabled? Do you see the same results if you disable these? svclb just handles forwarding traffic from the node port to the service, if you've got firewall rules on the host blocking those ports, that will still prevent the traffic from being allowed.

**Comment by akingstonlas** [comment] 2023-09-14 03:04
It is a brand new installation, Ubuntu 22.04.1, no firewalld, and as far as UFW I have disabled it to no effect. 

I have redeployed the VMs from scratch a couple of times now. I have gone as far as deploying the original master on different VMs and IPs, and the subsequent nodes experience the same filtered state where the original master remains wide-open but other nodes do not.


It is worth noting prior to adding the nodes to the cluster or deploying K3s, ports 80 and 443 were not available and only became available in a filtered state until svclb-traefik-45ab9192-568bz was fully initialized.

The only port that is open with the vanilla deployment of Ubuntu is port 22.

Also, when the first master comes up, it is in a filtered state momentarily, and it changes to open. However, that does not change when any other nodes are added to the cluster.

**Comment by brandond** [comment] 2023-09-14 04:02
Do you see svclb pods deployed to the nodes in question? Regardless of what nmap says, are you able to use curl to make requests against the ports on those nodes?

I'm not aware of any issues that match what you're describing, short of leaving a firewall enabled somewhere, or configuring things such that servicelb doesn't run pods on some nodes. I suspect there is something going on that is unique to your environment.

**Comment by akingstonlas** [comment] 2023-09-14 17:21
Unfortunately, that is how I discovered the whole filtering status, the port was not responsive, and curl was unsuccessful; as a result, I resorted to NMAP. 

svclb does get deployed successfully on the nodes without any errors.

Thank you for the rapid response. I will keep troubleshooting and let you know whether I find anything. If you have any other ideas please share them with me. 

Thanks again

**Comment by infroger** [comment] 2023-10-06 01:31
I've hit the same issue. Three nodes cluster, all servers, all the same OS, all in the same L2 network. Trying to run Rancher. Recreated the cluster many times. Noticed that when the cluster has only one node/server, all works fine and I access Rancher UI. When I add a second node, depending on which node is responding in port 80 I may get Rancher UI or HTTP 504. 

Disabled ufw to no effect. MTU is 1450 in all virtual interfaces (veth*, flannel.1 and cni0), 1500 on LAN/public interface, and 65536 on lo interface.

After adding "--flannel-backend=host-gw" and restarting k3s service, instead of getting HTTP 504, I get "too many redirects" in Chrome.

It looks like

$ k3s -v
k3s version v1.26.9+k3s1 (4e217286)
go version go1.20.8

$ lsb_release -d
Description:	Ubuntu 22.04.3 LTS

$ uname -a
Linux hostname 5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by brandond** [comment] 2023-10-06 02:50
I continue to be unable to reproduce this either locally in my physical home lab, on ec2, or in docker. What sort of infrastructure and network are these nodes on? Are you sure that vxlan traffic between nodes isn't being dropped or filtered?

**Comment by infroger** [comment] 2023-10-06 14:19
The VMs run in VMWare ESXi 8.

```
$ for s in server{01..03}; do echo -n "$s: "; ssh $s nc -vzu server1 8472; done
server1: Connection to server1 (127.0.0.1) 8472 port [udp/*] succeeded!
server2: Connection to server1 (10.151.16.49) 8472 port [udp/*] succeeded!
server3: Connection to server1 (10.151.16.49) 8472 port [udp/*] succeeded!
$ for s in server{01..03}; do echo -n "$s: "; ssh $s nc -vzu server2 8472; done
server1: Connection to server2 (10.151.16.50) 8472 port [udp/*] succeeded!
server2: Connection to server2 (127.0.0.1) 8472 port [udp/*] succeeded!
server3: Connection to server2 (10.151.16.50) 8472 port [udp/*] succeeded!
$ for s in server{01..03}; do echo -n "$s: "; ssh $s nc -vzu server3 8472; done
server1: Connection to server3 (10.151.16.51) 8472 port [udp/*] succeeded!
server2: Connection to server3 (10.151.16.51) 8472 port [udp/*] succeeded!
server3: Connection to server3 (127.0.0.1) 8472 port [udp/*] succeeded!

```

**Comment by infroger** [comment] 2023-10-06 20:33
After recreating the cluster with --flannel-backend=host-gw, all three nodes now respond on port 80. Editing /etc/systemd/system/k3s.service and restarting k3s in an existing cluster isn't sufficient. 

The VXLAN mistery remains. I suspect some config in ESXi 8 (and that didn't exist or wasn't enabled in our ESXi 7) ruins it, but I don't have the means to further investigate.

**Comment by brandond** [comment] 2023-10-07 00:02
Yes, there is a long-unresolved bug with the vmware NIC driver that may require disabling hardware checksum offload, see https://github.com/kubernetes/kubernetes/pull/92035#issuecomment-1329950771

This keeps popping up; I was fairly sure it was fixed independently by both vmware and kube-proxy side but apparently not.

**Closed by brandond** 2023-10-07 00:02 UTC
