### ISSUE TITLE
Service does not take effect on some nodes

### ISSUE THREAD

**Issue by BillyChen1** [k3s-io/k3s#7029] opened 2023-03-07 12:10 UTC
**Environmental Info:**
k3s version v1.24.8+k3s1 (648004e4)
go version go1.18.8

Node(s) CPU architecture, OS, and Version: 

node31: arch64, Ubuntu 20.04.5 LTS, kernel version 5.10.110
node33: arch64, Ubuntu 20.04.5 LTS, kernel version 5.10.110
node35: arch64, Ubuntu 20.04.5 LTS, kernel version 5.10.104-tegra

Cluster Configuration:

1 server, 2 agents.
server: node31 (192.168.1.31)
agent: node33 (192.168.1.33) and node35 (192.168.1.35)

**Describe the bug:**

Service does not take effect on node31 and node33, but takes effect on node35.

**Steps To Reproduce:**

- Create nginx deployment:
I created an nginx deployment and 2 nginx pods for test.
```bash
firefly@node31:~$ k get pod -o wide
NAME                       READY   STATUS    RESTARTS       AGE     IP           NODE     NOMINATED NODE   READINESS GATES
nginx-5cbd7c46f7-jzwl7     1/1     Running   1 (121m ago)   3h16m   10.42.0.32   node31   <none>           <none>
mynginx1                   1/1     Running   1 (120m ago)   3h32m   10.42.1.13   node33   <none>           <none>
nginx-5cbd7c46f7-g94cz     1/1     Running   1 (120m ago)   4h13m   10.42.1.17   node33   <none>           <none>
nginx-5cbd7c46f7-nxxct     1/1     Running   1 (123m ago)   3h17m   10.42.2.22   node35   <none>           <none>
mynginx                    1/1     Running   1 (123m ago)   3h37m   10.42.2.21   node35   <none>           <none>
```
- Create service:
Service name is `nginx-deployment`, the type is ClusterIP. The service IP is **10.43.196.207**.

```bash
firefly@node31:~$ k get svc
NAME               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
kubernetes         ClusterIP   10.43.0.1       <none>        443/TCP    7h56m
nginx-deployment   ClusterIP   10.43.196.207   <none>        8080/TCP   45m
```

- Check iptables
I find that the iptables rule only takes effect on node35, but doesn't take effect on node31 and node33.

On node35:
```bash
nvidia@node35:~$ sudo iptables-save | grep 10.43.196.207
-A KUBE-SERVICES -d 10.43.196.207/32 -p tcp -m comment --comment "default/nginx-deployment:nginx cluster IP" -m tcp --dport 8080 -j KUBE-SVC-2IPOHR47BYPWHVT5
-A KUBE-SVC-2IPOHR47BYPWHVT5 ! -s 10.42.0.0/16 -d 10.43.196.207/32 -p tcp -m comment --comment "default/nginx-deployment:nginx cluster IP" -m tcp --dport 8080 -j KUBE-MARK-MASQ
```
But on node31 and node35, I didn't get any output.

- Behavior
I hava a `mynginx` pod on node35. I can curl the service successfully.
```bash
root@mynginx:/# curl 10.43.196.207:8080
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```
But when I tried it on node31 or node33, something went wrong.
```bash
root@mynginx1:/# curl 10.43.196.207:8080
curl: (7) Failed to connect to 10.43.196.207 port 8080: No route to host
```

**Expected behavior:**

Service takes effect on all nodes. Pods on all nodes are expected to curl the service successfully.

**Actual behavior:**

Service only take effect on node35.

**Additional context / logs:**

I think something went wrong on node31 and node33 beacause I found no iptable rules added on these nodes, here I got some logs that may be helpful.
```
Mar 07 17:14:33 node31 k3s[155302]: E0307 17:14:33.310990  155302 proxier.go:1481] "Failed to execute iptables-restore" err=<
Mar 07 17:14:33 node31 k3s[155302]:         exit status 2: iptables-restore v1.8.4 (legacy): Couldn't load match `statistic':No such file or directory
Mar 07 17:14:33 node31 k3s[155302]:         
Mar 07 17:14:33 node31 k3s[155302]:         Error occurred at line: 47
Mar 07 17:14:33 node31 k3s[155302]:         Try `iptables-restore -h' or 'iptables-restore --help' for more information.
Mar 07 17:14:33 node31 k3s[155302]:  >
```

**Comment by brandond** [comment] 2023-03-07 17:06
Looks like you're missing support for some iptables modules on a few of your nodes. Since this is aarch64 I'm guessing the different devices are running board-specific kernels? You may need to install an extra package, or grab the source and config and build the missing modules yourself.

**Comment by brandond** [comment] 2023-03-07 17:07
Closing as this appears to be caused by the vendor not providing a full set of iptables modules.

**Closed by brandond** 2023-03-07 17:07 UTC
