### ISSUE TITLE
cluster-ca cert isn't rotated with the others

### ISSUE THREAD

**Issue by farcaller** [k3s-io/k3s#6182] opened 2022-09-28 08:54 UTC
**Environmental Info:**
K3s Version: v1.24.4+k3s1 (c3f830e9)

Cluster Configuration: 1 server

**Describe the bug:**
`k3s certificate rotate` doesn't rotate the client-ca. If the client-ca is removed manually, k3s restores it (from somewhere?).

**Steps To Reproduce:**
- `rm /var/lib/rancher/k3s/server/client-{admin,ca,controller,k3s-cloud-controller,k3s-controller,kube-apiserver,kube-proxy,scheduler}.*`
- restart k3s

**Expected behavior:**
k3s starts with a new client-ca

**Actual behavior:**
k3s starts with the same client-ca

**Additional context / logs:**
I see it as a problem as it's not clear what to do if a leaf user certificate is leaked. Without rotating the ca there's always a concern that the leaf certificate is used inappropriately.

It looks like it should be a feature [based on this test](https://github.com/k3s-io/k3s/blob/master/tests/integration/certrotation/certrotation_int_test.go#L44) but it's clearly [not](https://github.com/k3s-io/k3s/blob/master/pkg/cli/cert/cert.go#L125-L184).

**Comment by brandond** [comment] 2022-09-28 15:55
Duplicate of https://github.com/k3s-io/k3s/issues/5147#issuecomment-1048269049

**Closed by brandond** 2022-09-28 15:55 UTC
