### ISSUE TITLE
GVFS cpu usage

### ISSUE THREAD

**Issue by tdickman** [k3s-io/k3s#522] opened 2019-06-05 17:19 UTC
**Describe the bug**
GVFS uses a significant amount of cpu on my computer when I'm running a k3s cluster.

**To Reproduce**
* Install k3s
* Run 10 - 15 pods (estimate) inside your cluster, ideally pods that use a persistent disk (unsure if this part is required)

**Expected behavior**
CPU usage of gvfs does not spike (specifically the `gvfs-udisks2-vo` process on ubuntu).

**Additional context**
CPU usage spikes to ~50% and stays there. Further discussion can be found on the [k3s slack channel](https://rancher-users.slack.com).

**Comment by erikwilson** [comment] 2019-06-07 17:30
As noted in the slack channel, this is probably a general issue with `gvfs-udisks2-volume-monitor`: https://bugzilla.redhat.com/show_bug.cgi?id=1438232

It is probably worth checking that you are on an up-to-date version of gvfs/gvfs-udisks2-volume-monitor and filing an issue upstream with gvfs or ubuntu if the issue has already been fixed.

**Comment by brandond** [comment] 2020-12-05 00:15
Closing due to age.

**Closed by brandond** 2020-12-05 00:15 UTC

**Comment by peterrosell** [comment] 2021-01-15 15:02
I run into this behavior as well. Running on Ubuntu 20.04 and k3s 1.20. When I looked into the pods' config I found that all my pods used an exec readiness probe with period of 5 seconds. Removing the readiness probe removed the CPU spikes for the gvfs-udisk2-volume-monitor process.
I changed the readiness probe from exec to tcp port and http and the CPU load now goes up to about 5% every 5 seconds.

**Comment by lhotari** [comment] 2021-04-01 08:18
It seems that the correct fix for this issue would be to add `x-gvfs-hide` mount options to the loopback device mounts. Another solution is to pass `ENV{UDISKS_IGNORE}="1"` in a udev rule. 

This is the solution in moby (docker): https://github.com/moby/moby/blob/b96a0909f0ebc683de817665ff090d57ced6f981/contrib/udev/80-docker.rules#L3

I opened this PR to add x-gvfs-hide mount option to squashfs loopback device mounts:
https://github.com/snapcore/snapd/pull/10104

**Comment by mossroy** [comment] 2023-12-08 18:54
I have this same issue, with Ubuntu 22.04.3 amd64, k3s version 1.27.7+k3s2 (installed with default settings)

gvfs-udisks2-volume-monitor consumes 100% of one CPU core when deploying some workload (using local-path storageClass), even when idle.

Adding the `/etc/udev/rules.d/90-loopback.rules` file with content in previous comment (and restart the computer) does not help. I also tried a few different contents with no luck so far

Stopping the process with `systemctl stop --user gvfs-udisks2-volume-monitor` can be a temporary workaround. But it comes back in some circumstances (opening system monitor, for example)

**Comment by mossroy** [comment] 2023-12-22 16:27
It's possible to reproduce the issue in a brand new default Ubuntu 22.04.3 VM, after installing default k3s (currently 1.28.4+k3s2) and deploying some workload using local-path storageClass.
