### ISSUE TITLE
system-upgrade-controller is trying to downgrade k3s due to the bad reference of https://update.k3s.io/v1-release/channels/v1.31 to https://github.com/k3s-io/k3s/releases/tag/v1.31.2+k3s1

### ISSUE THREAD

**Issue by tomklapka** [k3s-io/k3s#11435] opened 2024-12-09 11:53 UTC
**Environmental Info:**
K3s Version:  v1.31.3+k3s1

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

3 servers, 3 agents

**Describe the bug:**

**Steps To Reproduce:**

```
Defaulted container "upgrade" out of: upgrade, cordon (init)
+ upgrade
+ get_k3s_process_info
+ ps -ef
+ grep -E '( |/)k3s .*(server|agent)'
+ grep -E -v '(init|grep|channelserver|supervise-daemon)'
+ awk '{print $2}'
+ K3S_PID=1202
+ + echo 1202
wc -w
+ '[' 1 '!=' 1 ]
+ '[' -z 1202 ]
+ echo 1202
+ wc -w
+ '[' 1 '!=' 1 ]
+ ps -p 1202 -o 'ppid='
+ awk '{print $1}'
+ K3S_PPID=1
+ info 'K3S binary is running with pid 1202, parent pid 1'
+ echo '[INFO] ' 'K3S binary is running with pid 1202, parent pid 1'
+ '[' 1 '!=' 1 ]
+ '[' 1202 '=' 1 ]
+ awk 'NR==1 {print $1}' /host/proc/1202/cmdline
+ K3S_BIN_PATH=/usr/local/bin/k3s
+ '[' -z /usr/local/bin/k3s ]
+ '[' '!' -e /host/usr/local/bin/k3s ]
+ return
+ replace_binary
+ NEW_BINARY=/opt/k3s
+ FULL_BIN_PATH=/host/usr/local/bin/k3s
+ '[' '!' -f /opt/k3s ]
+ info 'Comparing old and new binaries'
+ echo '[INFO] ' 'Comparing old and new binaries'
+ sha256sum /opt/k3s /host/usr/local/bin/k3s
[INFO]  K3S binary is running with pid 1202, parent pid 1
[INFO]  Comparing old and new binaries
+ BIN_CHECKSUMS='256ca852ff2ca165afbc14ed34df450aa1295e4eb01e3d1da9f251f37e546712  /opt/k3s
0d4aee46981d6aa78ed9285f8d97be175d6bf07ed3cac952e7f861b4a3ecddf7  /host/usr/local/bin/k3s'
+ '[' 0 '!=' 0 ]
+ echo '256ca852ff2ca165afbc14ed34df450aa1295e4eb01e3d1da9f251f37e546712  /opt/k3s
0d4aee46981d6aa78ed9285f8d97be175d6bf07ed3cac952e7f861b4a3ecddf7  /host/usr/local/bin/k3s'
+ + uniq
awk '{print $1}'
+ wc -l
+ BIN_COUNT=2
+ '[' 2 '=' 1 ]
+ set +e
+ /opt/k3s -v+ head -1

+ NEW_BIN_SEMVER='k3s version v1.31.2+k3s1 (6da20424)'
+ /host/usr/local/bin/k3s -v
+ head -1
+ FULL_BIN_SEMVER='k3s version v1.31.3+k3s1 (6e6af988)'
+ compare_versions 'k3s version v1.31.3+k3s1 (6e6af988)' 'k3s version v1.31.2+k3s1 (6da20424)'
+ echo 'k3s version v1.31.3+k3s1 (6e6af988)'
+ grep -Eo '[0-9]+\.[0-9]+\.[0-9]+'
+ version1=1.31.3
+ + grep -Eoecho '[0-9]+\.[0-9]+\.[0-9]+' 'k3s version v1.31.2+k3s1 (6da20424)'

+ version2=1.31.2
+ '[' 1.31.3 '=' 1.31.2 ]
+ IFS=.
+ set -- 1 31 3
+ printf '%03d%03d%03d' 1 31 3
+ version1=001031003
+ set -- 1 31 2
+ printf '%03d%03d%03d' 1 31 2
Error: Current version k3s version v1.31.3+k3s1 (6e6af988) is higher than k3s version v1.31.2+k3s1 (6da20424)
+ version2=001031002
+ test 001031002 -ge 001031003
+ '[' 1 -eq 1 ]
+ echo 'Error: Current version k3s version v1.31.3+k3s1 (6e6af988) is higher than k3s version v1.31.2+k3s1 (6da20424)'
+ exit 1
```
- Installed K3s:  v1.31.3+k3s1

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by brandond** [comment] 2024-12-09 16:38
Duplicate of https://github.com/k3s-io/k3s/issues/11422#issuecomment-2524027161

**Closed by brandond** 2024-12-09 16:38 UTC
