### ISSUE TITLE
dns resolve

### ISSUE THREAD

**Issue by SpringHgui** [k3s-io/k3s#7947] opened 2023-07-12 07:25 UTC
**Environmental Info:**
K3s Version: v1.26.4+k3s1

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

**Describe the bug:**

k3s events 
```
Failed to pull image "harbor.bx.com.cn/devops/bx-devops-agent:20230711014646": rpc error: code = Unknown desc = failed to pull and unpack image "harbor.bx.com.cn/devops/bx-devops-agent:20230711014646": failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://harbor.bx.com.cn/v2/devops/bx-devops-agent/manifests/sha256:81262b5d42a3c26939c88f8ea575360296d50fb78b59cead1868af1f9f2293f1": dial tcp: lookup harbor.bx.com.cn on 192.168.1.1:53: no such host
````
but on pc
```
root@debian:~# dig harbor.bx.com.cn @192.168.1.1

; <<>> DiG 9.16.37-Debian <<>> harbor.bx.com.cn @192.168.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44375
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;harbor.bx.com.cn.              IN      A

;; ANSWER SECTION:
harbor.bx.com.cn.       30      IN      A       47.96.43.6

;; Query time: 12 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Wed Jul 12 15:25:03 CST 2023
;; MSG SIZE  rcvd: 61
```

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by SpringHgui** [comment] 2023-07-12 07:26
The host can resolve domain names，kubelet can`t

**Comment by SpringHgui** [comment] 2023-07-12 07:29
```
root@debian:~# kubectl get cm coredns -n kube-system -o yaml
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
    import /etc/coredns/custom/*.server
  NodeHosts: |
    192.168.1.6 debian
kind: ConfigMap
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yQwWrzMBCEX0Xs2fEf20nsX9BDybH02lMva2kdq1Z2g6SkBJN3L8IUCiVtbyNGOzvfzoAn90IhOmHQcKmgAIsJQc+wl0CD8wQaSr1t1PzKSilFIUiIix4JfRoXHQjtdZHTuafAlCgq488xUSi9wK2AybEFDXvhwR2e8QQFHCnh50ZkloTJCcf8lP6NTIqUyuCkNJiSp9LJP5czoLjryztTWB0uE2iYmvjFuVSFenJsHx6tFf41gvGY6Y0Eshz/9D2e0OSZfIJVvMZExwzusSf/I9SIcQQNvaG6a+r/XVdV7abBddPtsN9W66Eedi0N7aberM22zaHf6t0tcPsIAAD//8Ix+PfoAQAA
    objectset.rio.cattle.io/id: ""
    objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
    objectset.rio.cattle.io/owner-name: coredns
    objectset.rio.cattle.io/owner-namespace: kube-system
  creationTimestamp: "2023-05-16T03:49:12Z"
  labels:
    objectset.rio.cattle.io/hash: bce283298811743a0386ab510f2f67ef74240c57
  name: coredns
  namespace: kube-system
  resourceVersion: "1653"
  uid: 49b77232-e839-4d81-b0f5-c1571c4e24c7
```

**Comment by SpringHgui** [comment] 2023-07-12 07:29
```
root@debian:~# cat /etc/resolv.conf
nameserver 192.168.1.1
```

**Comment by SpringHgui** [comment] 2023-07-14 01:03
> Are you using a proxy or a VPN connection on the host?

no，Finally I had to reinstall and the problem was solved

**Comment by caroline-suse-rancher** [comment] 2023-07-20 14:56
Closing this as the problem is resolved. We can reopen if it reoccurs.

**Closed by caroline-suse-rancher** 2023-07-20 14:56 UTC
