### ISSUE TITLE
building kine: storage backend is not defined

### ISSUE THREAD

**Issue by damozhiying** [k3s-io/k3s#1281] opened 2020-01-08 09:38 UTC
**Version:**
v1.17.0-rc.4-k3s.1

**Describe the bug**
```
sudo docker run -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=123456 -d mysql:5.7
```
```
/usr/local/bin/k3s server  --advertise-address=x.x.x.x  --docker --datastore-endpoint='mysql://root:123456@tcp(x.88.xx.x:3306)/k3sdb'

```
**log**
```
Jan 08 17:34:59 server16 k3s[3804597]: time="2020-01-08T17:34:59.310282133+08:00" level=fatal msg="starting kubernetes: preparing server: creating storage endpoint: building kine: storage backend is not defined"
Jan 08 17:34:59 server16 systemd[1]: k3s.service: main process exited, code=exited, status=1/FAILURE
Jan 08 17:34:59 server16 systemd[1]: Unit k3s.service entered failed state.
Jan 08 17:34:59 server16 systemd[1]: k3s.service failed.
Jan 08 17:35:04 server16 systemd[1]: k3s.service holdoff time over, scheduling restart.
Jan 08 17:35:04 server16 systemd[1]: Starting Lightweight Kubernetes...
Jan 08 17:35:04 server16 systemd[1]: Started Lightweight Kubernetes.
```

**Comment by ideal** [comment] 2020-06-12 09:43
Same problem here.
But if I manually start it from command line, it it ok. With `systemctl start` it fails.

**Comment by ideal** [comment] 2020-06-12 10:49
--datastore-endpoint=
Removing `=` here will be OK for me.

**Comment by brandond** [comment] 2020-06-12 18:08
I am guessing that you haven't quoted the arguments in your systemd unit and they are getting mangled. Mine looks like this:

```
ExecStart=/usr/local/bin/k3s \
        'server' \
        '--disable=coredns,servicelb,traefik,local-storage,metrics-server' \
        '--disable-cloud-controller' \
        '--disable-network-policy' \
        '--flannel-backend=host-gw' \
        '--write-kubeconfig-mode=664' \
        '--datastore-endpoint=http://localhost:2379' \
```

**Comment by boreBoar** [comment] 2020-08-09 17:54
For me, the problem was that i was connecting to a postgres node pool.
It started working as soon as i connected directly to the database port instead of the node-pool port.

**Comment by orvice** [comment] 2021-11-29 06:15
using env  instead of flag works for me:
```
K3S_DATASTORE_ENDPOINT='mysql://xxxxxxx'
```

ref: https://stackoverflow.com/questions/64904952/installing-k3s-offline-faild-with-error-starting-kubernetes-preparing-server

**Comment by brandond** [comment] 2021-11-29 22:12
Closing; this is caused by incorrect CLI flags.

**Closed by brandond** 2021-11-29 22:12 UTC
Labels: area/ha

**Comment by venc0r** [comment] 2022-10-07 21:11
the problem appears to be the generated systemd unit file, which escapes the parantheses arround tcp
this works:
 ```
 ...
 '--datastore-endpoint=mysql://root:XXXXXX@tcp(hostname:3306)/k3s' \
 ...
 ```
