### ISSUE TITLE
Invalid `hosts.toml` for private registry is generated

### ISSUE THREAD

**Issue by kurokobo** [k3s-io/k3s#9983] opened 2024-04-19 15:58 UTC
**Environmental Info:**
K3s Version: v1.29.3+k3s1 (8aecc26b)

```
k3s version v1.29.3+k3s1 (8aecc26b)
go version go1.21.8
```

Node(s) CPU architecture, OS, and Version: CentOS Stream 9

```
Linux <hostname> 5.14.0-427.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Feb 23 04:45:07 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:

Single node cluster

**Describe the bug:**

By adding following simple `/etc/rancher/k3s/registries.yaml` and restarting k3s, invalid `hosts.toml` for containerd is generated and causes `configs` to be ignored.

**Steps To Reproduce:**

- Install K3s: `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.29.3+k3s1 sh -s - --write-kubeconfig-mode 644`
- Add following `registries.yaml` to specify credentials and to skip certificate verification
  ```bash
  sudo tee /etc/rancher/k3s/registries.yaml <<EOF
  configs:
    registry.example.com:
      auth:
        username: reguser
        password: Registry123!
      tls:
        insecure_skip_verify: true
  EOF
  ```
- Restart k3s: `sudo systemctl restart k3s`

**Expected behavior:**

Generated `hosts.toml` is correct and pulling from private registry is completed without any errors

**Actual behavior:**

- Generated `hosts.toml` causes ``error="invalid `host` tree"`` since there is no `[host."https://registry.example.com/v2"]`
- Pulling from private registry is failed since any configuration in `hosts.toml` is ignored

```bash
$ sudo cat /var/lib/rancher/k3s/agent/etc/containerd/certs.d/registry.example.com/hosts.toml
# File generated by k3s. DO NOT EDIT.

server = "https://registry.example.com/v2"
capabilities = ["pull", "resolve", "push"]

skip_verify = true
```

```bash
$ sudo $(which k3s) ctr images pull --hosts-dir "/var/lib/rancher/k3s/agent/etc/containerd/certs.d" --user 'reguser:Registry123!' registry.example.com/demo/demo:demo
ERRO[0000] failed to decode hosts.toml                   error="invalid `host` tree"
INFO[0000] trying next host                              error="failed to do request: Head \"https://registry.example.com/v2/demo/demo/manifests/demo\": tls: failed to verify certificate: x509: certificate signed by unknown authority" host=registry.example.com
ctr: failed to resolve reference "registry.example.com/demo/demo:demo": failed to do request: Head "https://registry.example.com/v2/demo/demo/manifests/demo": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

**Additional context / logs:**

Adding `mirrors` does not help.

```bash
$ sudo tee /etc/rancher/k3s/registries.yaml <<EOF
mirrors:
  registry.example.com:
    endpoint:
      - https://registry.example.com
configs:
  registry.example.com:
    auth:
      username: reguser
      password: Registry123!
    tls:
      insecure_skip_verify: true
EOF

$ sudo systemctl restart k3s

$ sudo cat /var/lib/rancher/k3s/agent/etc/containerd/certs.d/registry.example.com/hosts.toml
# File generated by k3s. DO NOT EDIT.

server = "https://registry.example.com/v2"
capabilities = ["pull", "resolve", "push"]

skip_verify = true
```

Exact the same configration and steps work as expected on the older `v1.28.7+k3s1`.

```bash
$ k3s -v
k3s version v1.28.7+k3s1 (051b14b2)
go version go1.21.7
```

By `v1.28.7+k3s1`, the same `registries.yaml` will generate following `hosts.toml` that contains `[host."https://registry.example.com/v2"]`.

```bash
$ sudo cat /var/lib/rancher/k3s/agent/etc/containerd/certs.d/registry.example.com/hosts.toml
# File generated by k3s. DO NOT EDIT.


[host."https://registry.example.com/v2"]
  capabilities = ["pull", "resolve"]
  skip_verify = true
```

Pulling from private registry with this `hosts.toml` works.

```bash
$ sudo $(which k3s) ctr images pull --hosts-dir "/var/lib/rancher/k3s/agent/etc/containerd/certs.d" --user 'reguser:Registry123!' registry.example.com/demo/demo:demo
registry.example.com/demo/demo:demo:                                              resolved       |++++++++++++++++++++++++++++++++++++++| 
manifest-sha256:f7394791f5b6030de1952e40803687fbcd307291591440f70ec781e33340af34: done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:add061545bb927986a16eadb5de08c2b77262c58ee26db302ed5620e78534023:    done           |++++++++++++++++++++++++++++++++++++++| 
...
layer-sha256:9cd2056efb53587a8f5b28457317a34ce3388b9e6d15ba88c3783c2a5aeb93bc:    done           |++++++++++++++++++++++++++++++++++++++| 
elapsed: 0.1 s                                                                    total:   0.0 B (0.0 B/s)                                         
unpacking linux/amd64 sha256:f7394791f5b6030de1952e40803687fbcd307291591440f70ec781e33340af34...
done: 7.918237ms
```

I didn't dive into the code deeper yet, but since no `[host."https://registry.example.com/v2"]` is generated by `v1.29.3+k3s1`, I suspect the `.Endpoints` is empty by some reason.

- `HostsTomlTemplate`: https://github.com/k3s-io/k3s/blob/8aecc26b0f167d5e9e4e9fbcfd5a471488bf5957/pkg/agent/templates/templates.go#L43-L88
- `getHostConfigs()`: https://github.com/k3s-io/k3s/blob/8aecc26b0f167d5e9e4e9fbcfd5a471488bf5957/pkg/agent/containerd/config.go#L71-L154

**Comment by brandond** [comment] 2024-04-19 16:45
Duplicate of pinned issue: https://github.com/k3s-io/k3s/issues/9839

**Closed by brandond** 2024-04-19 16:45 UTC

**Comment by kurokobo** [comment] 2024-04-19 16:47
Ah sorry to bother you, thank you!
