### ISSUE TITLE
k3s server failed to work with docker on Ubuntu 20.04 ARM64

### ISSUE THREAD

**Issue by lazywhite** [k3s-io/k3s#6082] opened 2022-09-01 06:42 UTC
**Environmental Info:**
K3s Version:   v1.24.4+k3s1 (c3f830e9)

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:
os: Ubuntu 20.04
arch: arm64
docker: 20.10

**Describe the bug:**
1 master, 1 worker

**Steps To Reproduce:**

- install docker: curl https://releases.rancher.com/install-docker/20.10.sh | sh
- start k3s server: k3s server --docker --snapshotter fuse-overlayfs 
**Expected behavior:**

k get node, node status should be ready
**Actual behavior:**

https://gist.github.com/lazywhite/52ee1643747555643c4e06519106c798
**Additional context / logs:**

**Comment by brandond** [comment] 2022-09-02 20:05
`error checking rule: exit status 2: ip6tables v1.8.4 (legacy): Couldn't load match `comment':No such file or directory`

Duplicate of https://github.com/k3s-io/k3s/issues/6093#issuecomment-1235654912

**Closed by brandond** 2022-09-02 20:05 UTC
