### ISSUE TITLE
etcd dilemma with "too many learner members in cluster" if one of the master cannot be added

### ISSUE THREAD

**Issue by stevefan1999-personal** [k3s-io/k3s#2306] opened 2020-09-24 09:58 UTC
**Environmental Info:**
K3s Version: 
`k3s version v1.19.2+k3s1 (d38505b1)`

Node(s) CPU architecture, OS, and Version: 
Linux abc.def 3.10.0-1127.8.2.vz7.151.14 rancher/k3s#1 SMP Tue Jun 9 12:58:54 MSK 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
2 masters, 1 workers currently

yes i know 2 masters are bad because it degrades to the nearest odd floor number = 1, but I'm just testing

**Describe the bug:**
Can't remove the rogue master node that is failed to add, and as such the 2 live masters kept contacting it

**Steps To Reproduce:**
1. start the server with 2 master nodes
2. start another master that doesn't work at all
3. see both the 2 live master nodes spamming etcd connection error
```
Sep 24 10:54:23 <redacted>-f5217e k3s[3767401]: health check for peer bbffe1eaef41e5c2 could not connect: dial tcp <redacted>:2380: connect: connection refused
```

**Expected behavior:**
if the connection threshold fails for any master node and is not registered before, k3s should tell etcd to remove that node

otherwise consult the devops/owner to manually remove the node in the log, but do not try to connect to such AWOL node anymore, because it can be a DDoS attack.

**Actual behavior:**
It doesn't work intelligently as I described

Also, I cannot continue adding other master nodes because it will return "too many learner members in cluster" such that I might have to resort to forgetting all nodes by resetting the cluster

**Additional context / logs:**
Yes I'm stupid that I tried to run a master node on OpenVZ...but I had opted to remove agent by the option `disable-agent`, and I think the master API server could be a nice viable option to just run control plane without having to run containers upon containers...I'm stupid and wrong to think like that

**Comment by brandond** [comment] 2020-09-24 20:46
This is the same issue as https://github.com/rancher/rke2/issues/347.

Note that --disable-agent isn't recommended, as the etcd controller relies on having a node defined for every host that's running etcd, so that it can remove the etcd cluster member when the node gets deleted. --disable-agent prevents the host from registering a node, which breaks that assumption. If you want to run a lightweight control plane node, just taint it to prevent scheduling workload pods.

**Comment by stevefan1999-personal** [comment] 2020-09-25 06:11
@brandond i know it isn't recommended to disable agents but it just wouldn't work on OpenVZ due to kernel tuning check...it will panic on sysctl citing a permission denied error and then the entire go stack is flushing before my eyes...

Also if I tried to manually remove the node I was not able to contact `etcdctl member list` and it returns 404, not sure why that's the case

**Comment by brandond** [comment] 2020-09-25 07:31
You need to give etcdctl a bunch of command-line options to point it at the right certs. I don't think we have all that documented at the moment.

**Comment by xiaoluhong** [comment] 2020-11-12 11:25
I had a similar problem testing rke2. I run three new nodes，the first node runs init Server. 

After init server starts successfully, start the other two rke2 servers at the same time, one or two etcd containers will show "too many learner members in cluster".  However, when I started rke2 Server one by one, it didn't have any problems.

**Comment by brandond** [comment] 2020-11-13 08:59
Yes, that's correct. Etcd only allows one learner at a time. We could probably handle this with some retries or something.

**Comment by stevefan1999-personal** [comment] 2020-11-14 09:43
@brandond Yes. Set a time out for the new learner on how long it will take to promote. 

So we can benchmark/guess the average MB/s transferred and divide that by the DB state file size (usually in terms of gigabytes). 

For example, we have an existing node A,B, and a new node C wants to join. 

A and B can transfer 10MB/s and 5MB/s to C at maximum and we expect a 15% dropoff, so the guesstimated total average bandwidth initially is 12.8MB/s. 

Let's say the DB state files are ~3GB, so existing masters will expect to see learner C to be promoted around 3000/12.8 = ~235 seconds = ~4 minutes max to transfer all the needed information to promote C to master. 

If it took C more than 4 minutes to do that, we simply consider C to be starving and drop it off, then let the next node to join.

**Comment by brandond** [comment] 2020-11-14 11:06
We already have a timeout for new learners. As long as they continue making progress they are allowed to remain in the cluster. If they fail to make any progress for 60 seconds they are removed from the cluster.

The problem is adding multiple new learners at once. That is not allowed by etcd, so the other nodes will have to try again once the first learner has finished promoting. We don't currently do that, although systemd simply restarting the service over and over again will probably get it there eventually.

**Comment by brandond** [comment] 2023-02-28 17:05
Closing in favor of https://github.com/k3s-io/k3s/issues/7000

**Closed by brandond** 2023-02-28 17:05 UTC
Labels: area/etcd
