### ISSUE TITLE
DNS resolution stop working after k3s installation

### ISSUE THREAD

**Issue by umairyounus** [k3s-io/k3s#3624] opened 2021-07-13 14:08 UTC
**Environmental Info:**
K3s Version: 
k3s version v1.21.2+k3s1 (5a67e8dc)
go version go1.16.4

Node(s) CPU architecture, OS, and Version: 
Linux dell1 5.11.0-22-generic #23-Ubuntu SMP Thu Jun 17 00:34:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server, 3 agents

**Describe the bug:**
After doing a fresh installation of the ubuntu 20.01 server, when I installed k3s the DNS resolution on the machine stops working.  DNS resolution doesn't work on the host machine and inside the pods as well. I've tried it on a few different machines same behaviour.  

DNS works fine before k3s agent installation, looks like there is some kind of conflict. 

**Steps To Reproduce:**
- Fresh ubuntu-21.04 installation
- install k3s as an agent

- Installed K3s: 

**Expected behavior:**
DNS resolution should work

**Actual behavior:**
name resolution failed

**Additional context / logs:**
/ # ping google.com
ping: bad address 'google.com'

**Comment by brandond** [comment] 2021-07-13 20:34
I run K3s extensively on Ubuntu, and QA validates on it as well. I can't reproduce this issue. Can you share any more information about your environment or workload?

**Comment by umairyounus** [comment] 2021-07-14 16:19
Hi Brandond,

Thanks for a prompt reply. I've just installed a fresh copy of ubuntu on raspberry pi and the old dell machine. Raspberry pi is a master node and dell is a worker node. Now DNS is working on the host machine and pods on the master node but doesn't work inside pods on the dell machine. It's a fresh installation.  Here is a copy of resolv.conf from the pod

```search default.svc.cluster.local svc.cluster.local cluster.local localdomain
nameserver 10.43.0.10
options ndots:5```

**Comment by brandond** [comment] 2021-07-14 20:52
That sounds like cluster networking (flannel CNI) isn't working. Can you confirm that you've disabled firewalld/ufw on both nodes, and that there's not anything else between the two filtering traffic?

**Comment by umairyounus** [comment] 2021-07-14 22:02
Both firewalld and ufw are disabled, there is no firewall in between. Master node is successfully deploying pods. Just pods on the worker nodes can't resolve.

**Comment by umairyounus** [comment] 2021-07-19 13:23
The issue is related to Ubuntu 21.04. I've tried Ubuntu 21.04 on few different machines but the same result. After downgrading to Ubuntu 20.04 everything is working fine.

**Comment by brandond** [comment] 2021-07-19 19:22
Interesting. I believe we only technically support LTS releases of Ubuntu, but this is worth looking into regardless.

**Comment by trallnag** [comment] 2021-07-22 17:58
@umairyounus, I'm using Ubuntu 21.04 and for me K3s and DNS is working fine

**Comment by xtenduke** [comment] 2021-07-25 07:48
I resolved this with K3s v1.19.13 on Ubuntu 21.04 on RaspberryPi 4B wby using `host-gw` flannel config
`--flannel-backend=host-gw`

I was experiencing DNS resolution issues in pods (works fine on host)

I have 4 Ubuntu 21.04 Nodes running Ubuntu 21.04,  I installed with k3sup
They have static IPs and are configured as 192.168.1.20 - through 192.168.1.23 with 8.8.8.8 & 8.8.4.4
Other than that, they are stock installs of Ubuntu's 21.04 RaspberryPi distribution


Maybe 21.04 has issues with vxlan? 
I am happy to help with debugging

**Comment by WhiteBahamut** [comment] 2021-08-07 08:53
Same for me, also switched to `--flannel-backend=host-gw`. I did some googeling (cant find the links anymore), but it seems there is a bug in flannel for vxlan

**Comment by sonicbells** [comment] 2021-08-10 18:34
I experienced the same issue on Ubuntu 20.04, and the following helped me (maybe not ideal, but worked for me):
added `DNS=1.1.1.1` to the `/etc/systemd/resolved.conf` on the host, and then `systemctl restart systemd-resolved` - pods started resolving external names correctly.

**Comment by WhiteBahamut** [comment] 2021-08-10 19:10
And you kept vxlan mode?

**Comment by manelpb** [comment] 2021-08-25 02:27
Also having the same issues with ubuntu 21

**Comment by markmcgookin** [comment] 2021-09-06 16:24
Hey, I am experiencing this too.... I have a k3s cluster that I just rebuilt from scratch (because I thought this issue would go away with a fresh build... nope) 

Happy to try anything and debug anything as this cluster is now useless until I get this sorted.

Setup 

master node - Pi4B 8GB
nodes a,b,c - Pi4B 4GB 

Installed Ubuntu Server 64 via raspberry pi imager tool.

sudo apt-get update 
sudo apt-get upgrade

change hostnames to kmaster, knodea, knodeb, knodec 

Do the container thing with cmdline.txt (cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory) 

added a few secrets, some pvcs etc.. to support the deployments.

Pods download fine (DNS still works fine on hosts when you ssh onto them) 

Pods that run code that calls to the outside world (in this case bitbucket api) fail with errors like

`Unhandled exception. Flurl.Http.FlurlHttpException: Call failed. Resource temporarily unavailable (bitbucket.org:443) POST https://bitbucket.org/site/oauth2/access_token`

I tried @sonicbells 'fix' and rebooted that node as well, deleted and redeployed the pod, no change, same failure.

Generally running a fresh stock install. Getting desperate here.

**Comment by trallnag** [comment] 2021-09-06 16:52
Really weird I wonder why it started to work again for me using Ubuntu 21.04 after creating a K3s cluster from scratch

**Comment by markmcgookin** [comment] 2021-09-06 16:56
Due to work pressure I might not be able to keep this whole cluster for debugging. Going to roll it back to 19.04 and build up from there. I have one spare 4B 8GB I could create a single node cluster on that to debug if needed

**Closed as completed** 2021-10-28 18:58 UTC

**Comment by matthew-ellis** [comment] 2022-12-12 21:01
Was hitting the same DNS issue on a bootstrapped kubeadm cluster running on RHEL 8.4 servers with Flannel network installed. Changing the Backend Type in `net-conf.json` to `host-gw` in the yaml before applying to the cluster seems to have fixed it!


`net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        "Type": "host-gw"
      }
    }`
