### ISSUE TITLE
Node stuck at deletion due to finalizer - regression

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#2669] opened 2020-12-09 20:02 UTC
**Environment**
k3s version v1.19.4+k3s-989c9369 (989c9369)
**Issue**
Deletion of node is stuck due to presence of finalizer. This seems to be a regression

**Steps to reproduce**
1. Create a 3 node cluster
2. Verify nodes are Ready and pods are Running
3. Delete node3 using kubectl delete node
Deletion of a node is stuck, unless finalizer is removed.
```
--
    finalizers:
    - wrangler.cattle.io/managed-etcd-controller
    - wrangler.cattle.io/node
    labels:
--
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/managed-etcd-controller": {}
            v:"wrangler.cattle.io/node": {}
```

Related issue https://github.com/rancher/rke2/issues/401

**Comment by davidnuzik** [comment] 2020-12-09 21:03
The issue was also reproduced in v1.19.3+k3s3. Since the issue is pre-existing we don't want it to block our imminent releases. We'll mention this in the release notes. I've bumped the milestone to the next set of patch releases. This will need to get fixed in 1.19, 1.20, and master.

**Comment by ShylajaDevadiga** [comment] 2020-12-09 21:12
Note: To delete the node that is stuck during delete
```
kubectl get node <nodename> -o yaml -> check for finalizer

kubectl edit node <nodename> -> delete the entries after finalizer
```

**Comment by xiaods** [comment] 2021-04-17 05:39
@davidnuzik do you know what reason caused this issue? curiously want to know the root cause.

**Comment by brandond** [comment] 2021-04-17 06:49
etcd node controller

**Comment by xiaods** [comment] 2021-04-21 12:21
> etcd node controller

Opps, where is etcd node controller?

**Comment by brandond** [comment] 2021-04-21 20:19
https://github.com/k3s-io/k3s/blob/master/pkg/etcd/controller.go

**Comment by xiaods** [comment] 2021-04-26 03:37
@brandond  hi, with my testing,  i have not found the stable reproduce the ndoe stuck for this bug.

**Comment by brandond** [comment] 2021-04-26 19:43
I'm not sure how to reproduce it on demand either. My understanding is that something on the rancher/wrangler side has an issue where onDelete handlers leave stuck finalizers. For this reason, onDelete handlers are to be avoided in general, and the code needs to be rewritten to periodically reconcile the Kubernetes and etcd cluster member lists, instead of relying on watching v1.Node.

**Comment by xiaods** [comment] 2021-04-28 07:22
> I'm not sure how to reproduce it on demand either. My understanding is that something on the rancher/wrangler side has an issue where onDelete handlers leave stuck finalizers. For this reason, onDelete handlers are to be avoided in general, and the code needs to be rewritten to periodically reconcile the Kubernetes and etcd cluster member lists, instead of relying on watching v1.Node.

thanks for your clarify. can't wait to fix it asap.

**Comment by mitchellmaler** [comment] 2021-07-26 23:54
I have been testing IaC code to rebuild rke2 nodes and ran into this issue. From what I can tell it is only the control-plane nodes which points as noted above is probably the etcd controller. When recreating the issue I checked that the etcd member was removed which it always was so the controller didn't fail to complete that task. One thing I have started checking is if the current node being deleted is the current etcd leader. I have added some logic to call 'move-leader' if the current node being deleted is the etcd leader and have yet to run into the same issue.

**Comment by rancher-max** [comment] 2021-08-31 23:42
#### Validated on master branch using commitid `ad1a40a96c400c17780cf9455f5da330d690194c`

As this is an intermittent issue, I spun up multiple clusters and deleted a node and none of them were stuck. This has been fixed in all of our currently released versions as well (1.19.14, 1.20.10, and 1.21.4) so any users tracking this thread should be able to upgrade to one of those versions to see this fixed.

**Closed by rancher-max** 2021-08-31 23:42 UTC

**Comment by ozbillwang** [comment] 2022-06-10 11:41
> Note: To delete the node that is stuck during delete
> 
> ```
> kubectl get node -o name <nodename> | xargs -i kubectl patch {} -p '{"metadata":{"finalizers":[]}}' --type=merge
> ```

Thanks so much. I stuck here for more than 1 hour, until saw this

**Comment by CihatDinc** [comment] 2024-01-26 09:15
> Note: To delete the node that is stuck during delete
> 
> ```
> kubectl get node -o name <nodename> | xargs -i kubectl patch {} -p '{"metadata":{"finalizers":[]}}' --type=merge
> ```

it worked, thanks 👍
