### ISSUE TITLE
cAdvisor metrics are missing pod network metrics

### ISSUE THREAD

**Issue by sbouchex** [k3s-io/k3s#2895] opened 2021-02-05 09:25 UTC
**Environmental Info:**
K3s Version: 
k3s version v1.20.2+k3s1 (1d4adb03)
go version go1.15.5

Node(s) CPU architecture, OS, and Version: 
Linux sbo-k3s-1.iv.local 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 master + 2 workers

**Describe the bug:**
Scraping /metrics/cadvisor metrics with prometheus and could not find container_network_* metrics at the pod level. I only see container_network_receive_bytes_total at the node level.
```
# TYPE container_network_receive_bytes_total counter
container_network_receive_bytes_total{container="",id="/",image="",interface="cni0",name="",namespace="",pod=""} 1.209670734e+09 1612516652331
container_network_receive_bytes_total{container="",id="/",image="",interface="ens192",name="",namespace="",pod=""} 3.216718864e+09 1612516652331
container_network_receive_bytes_total{container="",id="/",image="",interface="flannel.1",name="",namespace="",pod=""} 1.744845961e+09 1612516652331

```

**Steps To Reproduce:**
K3s has been installed with the default install (i.e. no particular flags)
Then I started some pods and I'm using curl to scrape the cAdviser metrics (command looks like:
`curl --insecure --header "Authorization: Bearer $TOKEN" https://10.148.20.68:10250/metrics/cadvisor | grep container_network_receive_bytes_total
`

**Expected behavior:**
I would expect to see "container_network_receive_bytes_total" metrics labeled with the pod name

**Actual behavior:**
they are missing

**Comment by brandond** [comment] 2021-02-05 09:33
Duplicate of #2831

**Closed by brandond** 2021-02-05 09:33 UTC

**Comment by air3ijai** [comment] 2023-11-03 12:49
cAdvisor output show the following
```shell
kubectl get --raw "/api/v1/nodes/<node-01>/proxy/metrics/cadvisor" |\
  grep container_network_transmit_packets_total
```

And container is empty - `container=""`
```
container_network_transmit_packets_total{container="",id="/kubepods/burstable/podfd94a85e-73cc-4492-a3fc-5c9a1aca304c
```
