### ISSUE TITLE
Unable to setup k3s on Rhel 9 (k3s service is not starting)

### ISSUE THREAD

**Issue by m3rryqold** [k3s-io/k3s#7098] opened 2023-03-15 18:02 UTC
**Environmental Info:**
K3s Version: 

 k3s version v1.25.7+k3s1 (f7c20e23)
go version go1.19.6

Node(s) CPU architecture, OS, and Version: 

**server**: Linux 5.14.0-162.18.1.el9_1.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Feb 9 04:28:41 EST 2023 x86_64 x86_64 x86_64 GNU/Linux
**agent**: Linux 5.14.0-70.43.1.el9_0.x86_64 #1 SMP PREEMPT Mon Jan 16 06:54:25 EST 2023 x86_64 x86_64 x86_64 GNU/Linux
Cluster Configuration:

1 server, 1 agent

**Describe the bug:**

The k3s service does not start after installation on the agent

**Steps To Reproduce:**

- disabled selinux
```bash
sudo nano /etc/selinux/config
```
changed `SELINUX` value to `disabled`

- Installed K3s: 
```bash
curl -sfL https://get.k3s.io | K3S_URL=https:${k3s_url}:6443 K3S_TOKEN=SECRET sh -
```

**Expected behavior:**

Successful installation and starting of k3s agent

**Actual behavior:**

The agent service does not start.
```bash
sudo systemctl start k3s-agent
```
Result:
```
Job for k3s-agent.service failed because the control process exited with error code.
See "systemctl status k3s-agent.service" and "journalctl -xeu k3s-agent.service" for details.
```
```bash
systemctl status k3s-agent
```
Result:
```
● k3s-agent.service - Lightweight Kubernetes
     Loaded: loaded (/etc/systemd/system/k3s-agent.service; enabled; vendor preset: disabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2023-03-15 17:54:27 UTC; 4s ago
       Docs: https://k3s.io
    Process: 8340 ExecStartPre=/bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service (code=exited, status=1/FAILURE)
        CPU: 7ms
```

**Additional context / logs:**

```bash
journalctl -xeu k3s-agent.service
```
Result:
```
Subject: A start job for unit k3s-agent.service has failed
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit k3s-agent.service has finished with a failure.
░░ 
░░ The job identifier is 171490 and the job result is failed.
Mar 15 18:01:06 ip-172-31-22-61.ec2.internal systemd[1]: k3s-agent.service: Scheduled restart job, restart counter is at 79.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ Automatic restarting of the unit k3s-agent.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
Mar 15 18:01:06 ip-172-31-22-61.ec2.internal systemd[1]: Stopped Lightweight Kubernetes.
░░ Subject: A stop job for unit k3s-agent.service has finished
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A stop job for unit k3s-agent.service has finished.
░░ 
░░ The job identifier is 171571 and the job result is done.
Mar 15 18:01:06 ip-172-31-22-61.ec2.internal systemd[1]: Starting Lightweight Kubernetes...
░░ Subject: A start job for unit k3s-agent.service has begun execution
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit k3s-agent.service has begun execution.
░░ 
░░ The job identifier is 171571.
Mar 15 18:01:06 ip-172-31-22-61.ec2.internal sh[8520]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Mar 15 18:01:06 ip-172-31-22-61.ec2.internal systemd[1]: k3s-agent.service: Control process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ An ExecStartPre= process belonging to unit k3s-agent.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Mar 15 18:01:06 ip-172-31-22-61.ec2.internal systemd[1]: k3s-agent.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ The unit k3s-agent.service has entered the 'failed' state with result 'exit-code'.
Mar 15 18:01:06 ip-172-31-22-61.ec2.internal systemd[1]: Failed to start Lightweight Kubernetes.
░░ Subject: A start job for unit k3s-agent.service has failed
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit k3s-agent.service has finished with a failure.
░░ 
░░ The job identifier is 171571 and the job result is failed.
```

**Comment by brandond** [comment] 2023-03-15 18:25
Duplicate of https://github.com/k3s-io/k3s/issues/7077#issuecomment-1468880186

**Closed by brandond** 2023-03-15 18:25 UTC

**Comment by m3rryqold** [comment] 2023-03-15 18:40
Thanks @brandond 
The fix worked.
