### ISSUE TITLE
Race condition when attempting to provision multiple hosts in HA

### ISSUE THREAD

**Issue by dramich** [k3s-io/k3s#2449] opened 2020-10-28 22:07 UTC
**Environmental Info:**
K3s Version: 1.19.3+k3s1

Node(s) CPU architecture, OS, and Version: 

Linux <redacted> 5.4.0-1029-aws #30~18.04.1-Ubuntu SMP Tue Oct 20 11:09:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

4 masters, HA setup with mariadb running in RDS

**Describe the bug:**
Using terraform to create 4 hosts, there appears to be a race when registering the DB, 3 out of 4 seem to make it ok, on the one that doesn't make it the error `level=fatal msg="starting kubernetes: preparing server: key exists"` is seen. 

**Steps To Reproduce:**
Use terraform to create 4 hosts with cloud-init that attempts to use the k3s install script to register all hosts at the same time

- Installed K3s: 

**Expected behavior:**
All 4 hosts are able to register 

**Actual behavior:**
3 outta 4 made it, the last one failed and my script caused it to never work again. 

**Additional context / logs:**

Worked around this by adding a sleep jitter to stop the race `sleep $(expr $RANDOM % 10)`

**Comment by dereknola** [comment] 2023-06-22 16:29
Closing this as unable to reproduce in latest stable. We have made several changes to "smooth out" multiple servers connection since this bug was posted, which has likely resolved this issue.

**Closed by dereknola** 2023-06-22 16:29 UTC
Labels: area/ha, priority/important-soon
