### ISSUE TITLE
K3s service failing after etcd reset

### ISSUE THREAD

**Issue by mayuresh-quartic** [k3s-io/k3s#7825] opened 2023-06-26 12:17 UTC
**Environmental Info:**
K3s Version: k3s version v1.25.4+k3s1 (0dc63334)

Node(s) CPU architecture, OS, and Version: Linux QA-k3s-master-1 5.4.0-1109-azure #115~18.04.1-Ubuntu SMP Mon May 22 20:06:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration: 3 Masters, 5 Worker

**Describe the bug:**
Etcd service was not responding (unable to connect via 2379 port)
This made the Master nodes down

We tried to reset the etcd using cluster reset
```
sudo k3s server --cluster-reset --cluster-reset-restore-path=/application-volume/k3s/server/db/snapshots/etcd-snapshot-qa-k3s-master-1-1687392000 --data-dir /application-volume/k3s
```

Command ran successfully and then after restarting service  to restart k3s
```
/usr/local/bin/k3s \
    server \
	'--cluster-init' \
	'--tls-san' \
	'<ip>' \
	'--data-dir' \
	'/application-volume/k3s' \
	'--write-kubeconfig-mode' \
	'644' \
	'--etcd-arg=--data-dir=/var/lib/etcd' \
	'--etcd-arg=--debug' \
	'--disable' \
	'traefik'
```

But still I am getting 
```
Jun 26 12:05:09 QA-k3s-master-1 k3s[8035]: time="2023-06-26T12:05:09Z" level=info msg="runtime is not yet initialized"
Jun 26 12:05:10 QA-k3s-master-1 k3s[8035]: {"level":"warn","ts":"2023-06-26T12:05:10.657Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_SNAPSHOT","remote-peer-id":"298b911665c13aa0","rtt":"0s","error":"dial tcp 10.47.0.4:2380: connect: connection refused"}
Jun 26 12:05:10 QA-k3s-master-1 k3s[8035]: {"level":"warn","ts":"2023-06-26T12:05:10.657Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"298b911665c13aa0","rtt":"0s","error":"dial tcp 10.47.0.4:2380: connect: connection refused"}
Jun 26 12:05:10 QA-k3s-master-1 k3s[8035]: {"level":"warn","ts":"2023-06-26T12:05:10.662Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_SNAPSHOT","remote-peer-id":"f875d12643597ed2","rtt":"0s","error":"dial tcp 10.47.0.5:2380: connect: connection refused"}
Jun 26 12:05:10 QA-k3s-master-1 k3s[8035]: {"level":"warn","ts":"2023-06-26T12:05:10.662Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"f875d12643597ed2","rtt":"0s","error":"dial tcp 10.47.0.5:2380: connect: connection refused"}
Jun 26 12:05:10 QA-k3s-master-1 k3s[8035]: time="2023-06-26T12:05:10Z" level=info msg="Tunnel server egress proxy waiting for runtime core to become available"
Jun 26 12:05:11 QA-k3s-master-1 k3s[8035]: time="2023-06-26T12:05:11Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:6443/v1-k3s/readyz: 500 Internal Server Error"
```

- Installed K3s: v1.25.4+k3s1 (0dc63334)

**Expected behavior:**
After etcd reset and restart k3s it should start the k3s service and work

**Comment by brandond** [comment] 2023-06-26 20:00
Did you stop the k3s service before running the cluster-reset command? The output suggests that it's still trying to connect to other etcd peers, which would indicate that the cluster-reset did not complete due to k3s still being running.

**Comment by mayuresh-quartic** [comment] 2023-06-27 03:37
@brandond 
Yes k3s was completely stopped before resetting

The above logs are after reset when we tried starting k3s service

**Comment by brandond** [comment] 2023-06-27 04:43
v1.25.4+k3s1 is from November. Please update to the latest 1.25 release, and try the reset again. If it continues to attempt to contact other peers, please attach the complete k3s log from journald.

**Comment by brandond** [comment] 2023-08-02 23:57
closing; please repoen and attach the requested logs if you can reproduce on recent releases.

**Closed by brandond** 2023-08-02 23:57 UTC
