### ISSUE TITLE
"stable" tag seems to have gone missing

### ISSUE THREAD

**Issue by jwatte** [k3s-io/k3s#10614] opened 2024-07-31 01:50 UTC
**Steps To Reproduce:**
Try to download https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt

**Expected behavior:**
Getting the checksum file for the current stable version

**Actual behavior:**
Now just returns in Not Found.

**Additional Context**
This used to work fine, but stopped working sometime today 2024-07-30 PDT.

**Comment by brandond** [comment] 2024-07-31 04:49
Duplicate of https://github.com/k3s-io/k3s/issues/10578

**Closed** 2024-07-31 04:49 UTC
