### ISSUE TITLE
K3s' `kubectl` prefers `/etc/rancher/k3s/k3s.yaml` over `~/.kube/config`

### ISSUE THREAD

**Issue by optix2000** [k3s-io/k3s#1541] opened 2020-03-15 03:53 UTC
**Version:**
k3s version v1.17.3+k3s1 (5b17a175)

**K3s arguments:**
` curl -sfL https://get.k3s.io | sh -s - --no-flannel --no-deploy traefik`

**Describe the bug**
`kubectl` prefers reading `/etc/rancher/k3s/k3s.yaml` over `~/.kube/config` when `~/.kube/config` exists.

**To Reproduce**

1. Write a valid `~/.kube/config` file. `sudo kubectl config view --raw > ~/.kube/config`
2. Try running a `kubectl` command. `kubectl config view`

**Expected behavior**
K3s' `kubectl` follows the load rules in `kubectl config --help`, with a fallback to `/etc/rancher/k3s/k3s.yaml` as an additional last rule.
```
 The loading order follows these rules:

  1.  If the --kubeconfig flag is set, then only that file is loaded. The flag may only be set once and no merging takes
place.
  2.  If $KUBECONFIG environment variable is set, then it is used as a list of paths (normal path delimiting rules for
your system). These paths are merged. When a value is modified, it is modified in the file that defines the stanza. When
a value is created, it is created in the first file that exists. If no files in the chain exist, then it creates the
last file in the list.
  3.  Otherwise, ${HOME}/.kube/config is used and no merging takes place.
```

**Actual behavior**
- `kubectl` tries to read `/etc/rancher/k3s/k3s.yaml` and fails.
Yes I understand that I can work around this with `--write-kubeconfig-mode`, but having a proper `~/.kube/config` file provides interop with existing K8s tools (ie helm) and lets me work on other k8s clusters using the same kubectl command.
Yes I also understand I can also work around this issue by exporting my own `$KUBECONFIG` env var, but k3s' `kubectl` breaks assumptions of how the command works (see below).
- `kubectl config --help` says `3.  Otherwise, ${HOME}/.kube/config is used and no merging takes place`, which doesn't seem to be the case.

**Additional context / logs**

```
% ls -l ~/.kube/config
-rw-r--r-- 1 user user 1052 Mar 14 20:32 /home/user/.kube/config
% kubectl --v=9 config view
WARN[2020-03-14T20:48:00.146588365-07:00] Unable to read /etc/rancher/k3s/k3s.yaml, please start server with --write-kubeconfig-mode to modify kube config permissions
F0314 20:48:00.159402   23853 helpers.go:114] error: error loading config file "/etc/rancher/k3s/k3s.yaml": open /etc/rancher/k3s/k3s.yaml: permission denied
```

**Comment by proligde** [comment] 2020-08-11 07:43
I agree, plus it behaves differently, when kubectl was installed via `snap install kubectl --classic` prior to installing k3s. Then kubectl keeps using ~/.kube/config so the behaviour depends on the installation order as well which I guess it shouldn't

**Comment by brandond** [comment] 2020-08-11 17:05
@proligde yes, the k3s embedded version of kubectl has some slightly modified behavior in order to accommodate loading config from a nonstandard location. If you install another kubectl binary to a location that's before k3s in your $PATH, that kubectl will be run by your shell instead, and it will not look for the k3s kubeconfig.

**Comment by andrewvaughan** [comment] 2020-09-21 22:10
This seems to be a problem with environment variables too.  Setting `KUBECONFIG` does nothing:

```
andrew@raspi001:~$ echo $KUBECONFIG
/home/andrew/.kube/config
```

Although it seems very... insistent on running with the default:

```
andrew@raspi001:~$ k3s kubectl config
WARN[2020-09-21T22:07:12.259477330Z] Unable to read /etc/rancher/k3s/k3s.yaml, please start server with --write-kubeconfig-mode to modify kube config permissions 
Modify kubeconfig files using subcommands like "kubectl config set
current-context my-context"

...
```

In fact, even using the `--kubeconfig` option is failing for me:

```
andrew@raspi001:~$ k3s kubectl config set-cluster default --server=https://10.0.0.201:6443 --kubeconfig ~andrew/.kube/config
WARN[2020-09-21T22:09:56.631637527Z] Unable to read /etc/rancher/k3s/k3s.yaml, please start server with --write-kubeconfig-mode to modify kube config permissions 
error: open /etc/rancher/k3s/k3s.yaml.lock: permission denied
```

This whole thing seems very broken...

**Comment by brandond** [comment] 2020-09-22 02:04
The behavior here probably varies a bit depending on which version of k3s you're using, as we've switched cli libraries a few times. You can always install your own if you don't like the one wrapped by k3s.

**Comment by anttilinno** [comment] 2020-10-30 08:02
Reasoning is sound for x86. Pre-built binaries exist, are easily downloadable and installable. Maybe even in package repositories. But for the raspberry, there are no prebuilt binaries that can easily be downloaded and installed :) I guess I can always download the source code and compile it for the pi, but it is general PITA.

**Comment by cjellick** [comment] 2020-12-16 20:55
I sorted by 👍  and saw that this was near the top of the list, so I spoke with @ibuildthecloud about it.

Easiest thing for me to convey his intent is to just paste the convo here:

Darren:
> Yeah, I don't like that behavior
> I don't like that we have a modified kubectl that looks for /etc/rancher/k3s/k3s.yaml.  I just wanted it to work out of the box so I added that hack.
> But I really wanted `curl ... | sh - && kubectl get all` to work

Me: why not jsut write to ~/.kube/config? im prob being simple there

Darren:
> So the kubeconfig is generated on k3s start. So that's what makes the flow odd.
> If we added a k3s init command it could help.
> That would generate CA, certs, kubeconfig.  We could then run that in the installer and copy the kubectl to ~/.kube/config

**Comment by innobead** [comment] 2020-12-21 03:31
cc @jenting

**Comment by jenting** [comment] 2020-12-23 08:23
From the discussion thread, I realized the purpose we want to achieve is to _use a completely unmodified version of kubectl_, and makes the `kubectl get all` works (also don't break changes on k3s upgrade and k3s HA).

By default, k3s server writes the kubeconfig to `/etc/rancher/k3s/k3s.yaml`. k3s server has a flag `--write-kubeconfig` to change the default kubeconfig location from `/etc/rancher/k3s/k3s.yaml` to user-specific location.

If we want to make unmodified kubectl works w/o pass `--kubeconfig` on each kubectl command, and w/o setup the $KUBECONFIG env to make all sessions works, then we have to write kubeconfig to `${HOME}/.kube/config` also. (with merge original `${HOME}/.kube/config` if present).

Therefore, we'll have two kubeconfig `/etc/rancher/k3s/k3s.yaml` and `${HOME}/.kube/config`. We also have to make sure two kubeconfigs certificates both got rotated when the certificate rotated.
- the modified kubectl uses `/etc/rancher/k3s/k3s.yaml`
- the upstream kubectl uses `${HOME}/.kube/config`

Is the above behavior works as expected or am I missing anything?

**Comment by brandond** [comment] 2020-12-23 22:05
Note that even if we use a completely unmodified version of kubectl, the kubectl command that we package is actually a wrapper, which gives us a chance to inject modifications to environment variables and the like. For example see: https://github.com/k3s-io/k3s/blob/master/cmd/k3s/main.go#L66

**Comment by optix2000** [comment] 2021-01-05 02:05
> If we want to make unmodified kubectl works w/o pass `--kubeconfig` on each kubectl command, and w/o setup the $KUBECONFIG env to make all sessions works, then we have to write kubeconfig to `${HOME}/.kube/config` also. (with merge original `${HOME}/.kube/config` if present).
>
> Therefore, we'll have two kubeconfig `/etc/rancher/k3s/k3s.yaml` and `${HOME}/.kube/config`. We also have to make sure two kubeconfigs certificates both got rotated when the certificate rotated.
> 
> * the modified kubectl uses `/etc/rancher/k3s/k3s.yaml`
> * the upstream kubectl uses `${HOME}/.kube/config`
> 
> Is the above behavior works as expected or am I missing anything?

I think something like that would work, something akin to syncing and merging `~/.kube/config` whenever k3s' `kubectl` is run (assuming it has permissions to `/etc/rancher/k3s/k3s.yaml`).

The other half of this issue is an ask to make k3s' `kubectl` behave like upstream `kubectl` and not forcefully override `--kubeconfig` to `/etc/rancher/k3s/k3s.yaml`. This would allow people to use k3s' `kubectl` like a normal `kubectl` and manage multiple clusters without needing a separate binary.

Ultimately the original issue boils down to related 2 problems.
1) `~/.kube/config` is needed for interop with existing k8s tools (ie Helm). This can be trivially generated with `sudo kubectl config view --raw > ~/.kube/config` when using k3s' `kubectl`, however...
2) K3s' `kubectl` doesn't read `~/.kube/config`, which means if you go down the route of using the standard k8s config file (`~/.kube/config`), you need an unmodified `kubectl` binary to do things like manage other clusters.

However you brought up a 3rd problem.
> We also have to make sure two kubeconfigs certificates both got rotated when the certificate rotated.
Syncing and merging should be straightforward, but how is upstream solving this problem? Normal k8s users have the same problem of dealing with credential rotations (albeit with only 1 config file), and they have the harder problem of dealing with roaming clients (ie laptops) where you can't just get the credentials locally.

**Comment by jenting** [comment] 2021-01-06 01:57
> Ultimately the original issue boils down to related 2 problems.
> 
> 1. `~/.kube/config` is needed for interop with existing k8s tools (ie Helm). This can be trivially generated with `sudo kubectl config view --raw > ~/.kube/config` when using k3s' `kubectl`, however...
> 2. K3s' `kubectl` doesn't read `~/.kube/config`, which means if you go down the route of using the standard k8s config file (`~/.kube/config`), you need an unmodified `kubectl` binary to do things like manage other clusters.

I'd like to remove the modification on the k3s pre-built _kubectl_ binary, and make sure that the kubectl operation works well without passing --kubeconfig _or_ configures the KUBECONFIG env. So the way I could think is to save the kubeconfig to ~/.kube/config.

I did not change the kubeconfig path from /etc/rancher/k3s/k3s.yaml to ~/.kube/config directly is because:
1. I want to make sure k3s is backward-compatible
2. probably more than one user would like to access the /etc/rancher/k3s/k3s.yaml

> However you brought up a 3rd problem.
> 
> > We also have to make sure two kubeconfigs certificates both got rotated when the certificate rotated.
> 
> Syncing and merging should be straightforward, but how is upstream solving this problem? Normal k8s users have the same problem of dealing with credential rotations (albeit with only 1 config file), and they have the harder problem of dealing with roaming clients (ie laptops) where you can't just get the credentials locally.

I had check the k3s code, the kubeconfig rotation happens at server start up. So when k3s server overwrites the rotated kubeconfig /etc/rancher/k3s/k3s.yaml will also writes the rotate kubeconfig to ~/.kube/config.

**Comment by sraillard** [comment] 2021-01-06 21:15
@cjellick running a `kubctl get` right after a k3s installation (with automatic start of the server) isn't working (at least on the v1.19.5+k3s2 version). You need to wait a while before having ressources listed by kubectl.

**Comment by johnlane** [comment] 2021-02-16 11:47
Just a passing comment, but `k3s server --help` reports a different default path to what is actually used (`/etc/rancher/k3s/k3s.yaml` ):

    $ k3s server --help | grep -- --config
    --config FILE, -c FILE                     (config) Load configuration from FILE (default: "/etc/rancher/k3s/config.yaml") [$K3S_CONFIG_FILE]
    $ k3s --version
    k3s version v1.20.2+k3s1 (1d4adb03)

**Comment by brandond** [comment] 2021-02-16 18:12
@johnlane the k3s config file is not the same as kubectl's config file.

**Comment by dereknola** [comment] 2022-02-01 19:25
As of v1.20.15 (and newer v1.21, v1.22, v1.23) the following situation exists:
1) `k3s kubectl` still prefers `/etc/rancher/k3s/k3s.yaml`
2) exporting `KUBECONFIG` or `KUBECONFIG=~/.kube/config k3s kubectl` does work.
3) using `k3s kubectl --kubeconfig=/home/$USER/.kube/config gives a warning, but still prints out information
```
derek@dinux-T14s:~/rancher/k3s$ k3s kubectl get pods -A --kubeconfig=/home/$USER/.kube/config
WARN[2022-02-01T11:24:36.296569065-08:00] Unable to read /etc/rancher/k3s/k3s.yaml, please start server with --write-kubeconfig-mode to modify kube config permissions 
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   metrics-server-86cbb8457f-pqp6h           1/1     Running     0          2m43s
kube-system   coredns-6488c6fcc6-hk5sf                  1/1     Running     0          2m43s
kube-system   local-path-provisioner-5ff76fc89d-2hjs6   1/1     Running     0          2m43s
kube-system   helm-install-traefik-tgnt6                0/1     Completed   0          2m43s
kube-system   svclb-traefik-cq5n8                       2/2     Running     0          2m11s
kube-system   traefik-799bbc5bd6-xrbxj                  1/1     Running     0          2m11s
```

At a minimum right now, the warning for 3) should be addressed.

**Comment by dereknola** [comment] 2022-02-03 22:15
Closing this issue, after discussion with the dev team, the current behavior of K3s is by design and will not be changed. Users looking to change the kubeconfig can use the KUEBCONFIG env or the `--kubeconfig` flag.

**Closed by dereknola** 2022-02-03 22:15 UTC
