### ISSUE TITLE
Upgrading k3s using Rancher (SUC) intermittently taking 30+ minutes

### ISSUE THREAD

**Issue by dnoland1** [k3s-io/k3s#3007] opened 2021-03-03 00:14 UTC
**Environmental Info:**
K3s Version: 
Reproduced upgrading from 1.18.13 to 1.18.15, 1.18.15 to 1.19.7, and 1.19.8 to 1.20.4 

Node(s) CPU architecture, OS, and Version: 
Ubuntu 20.04

Cluster Configuration:
2 nodes both with server role

**Describe the bug:**
When upgrading a k3s cluster using Rancher, around 50% of the time, the upgrade is stuck and takes over 30 minutes to complete. Other times upgrades complete in less than 5 minutes. Appears that SUC creates the k8s job, but the pod to perform the upgrade doesn't get created or immediately terminates. The job eventually times out after 30 minutes, a new pod is created, and the upgrade is successful.

**Steps To Reproduce:**
1. Install a 2 node k3s cluster (both server role) with MySQL backend. Use version 1.18.13.
2. Import cluster into Rancher (create Rancher import cluster, run kubectl apply -f https://<rancher-server>/<blah>.yaml)
3. Using Rancher UI, edit cluster and select version 1.18.15 (newer versions are ok too)
4. Wait and see how long the upgrade takes.
I like to run this command to monitor the progress:

watch "kubectl get nodes; echo; kubectl get jobs -n cattle-system; echo; kubectl get pods -n cattle-system -l upgrade.cattle.io/plan=k3s-master-plan"

**Expected behavior:**
A k3s upgrade on a 2 node cluster should take 10 minutes or less.

**Actual behavior:**
Around 50% of the time, k3s upgrades take 30 minutes or longer.

**Additional context / logs:**
```
Feb 02 00:02:07 ip-10-10-100-248 k3s[941]: I0202 00:02:07.468434     941 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "host-root" (UniqueName: "kubernetes.io/host-path/6743dfe2-ef7d-4856-ac84-4bc679efd86e-host-root") pod "apply-k3s-master-plan-on-ip-10-10-100-248-with-945e51567b-rqdrs" (UID: "6743dfe2-ef7d-4856-ac84-4bc679efd86e")
Feb 02 00:02:08 ip-10-10-100-248 k3s[941]: I0202 00:02:08.081687     941 reconciler.go:196] operationExecutor.UnmountVolume started for volume "host-root" (UniqueName: "kubernetes.io/host-path/6743dfe2-ef7d-4856-ac84-4bc679efd86e-host-root") pod "6743dfe2-ef7d-4856-ac84-4bc679efd86e" (UID: "6743dfe2-ef7d-4856-ac84-4bc679efd86e")
Feb 02 00:02:08 ip-10-10-100-248 k3s[941]: I0202 00:02:08.100940     941 operation_generator.go:782] UnmountVolume.TearDown succeeded for volume "kubernetes.io/host-path/6743dfe2-ef7d-4856-ac84-4bc679efd86e-host-root" (OuterVolumeSpecName: "host-root") pod "6743dfe2-ef7d-4856-ac84-4bc679efd86e" (UID: "6743dfe2-ef7d-4856-ac84-4bc679efd86e"). InnerVolumeSpecName "host-root". PluginName "kubernetes.io/host-path", VolumeGidValue ""
Feb 02 00:02:08 ip-10-10-100-248 k3s[941]: I0202 00:02:08.183004     941 reconciler.go:319] Volume detached for volume "host-root" (UniqueName: "kubernetes.io/host-path/6743dfe2-ef7d-4856-ac84-4bc679efd86e-host-root") on node "ip-10-10-100-248" DevicePath ""
Feb 02 00:02:08 ip-10-10-100-248 k3s[941]: E0202 00:02:08.316135     941 kubelet_pods.go:147] Mount cannot be satisfied for container "cordon", because the volume is missing or the volume mounter is nil: {Name:host-root ReadOnly:false MountPath:/host SubPath: MountPropagation:<nil> SubPathExpr:}
Feb 02 00:02:08 ip-10-10-100-248 k3s[941]: E0202 00:02:08.316214     941 kuberuntime_manager.go:818] init container start failed: CreateContainerConfigError: cannot find volume "host-root" to mount into container "cordon"
Feb 02 00:02:08 ip-10-10-100-248 k3s[941]: E0202 00:02:08.316245     941 pod_workers.go:191] Error syncing pod 6743dfe2-ef7d-4856-ac84-4bc679efd86e ("apply-k3s-master-plan-on-ip-10-10-100-248-with-945e51567b-rqdrs_cattle-system(6743dfe2-ef7d-4856-ac84-4bc679efd86e)"), skipping: failed to "StartContainer" for "cordon" with CreateContainerConfigError: "cannot find volume \"host-root\" to mount into container \"cordon\""
```
Full k3s logs available upon request.

Might be related to this upstream Kubernetes issue: https://github.com/kubernetes/kubernetes/issues/85330

gz#14783

**Comment by brandond** [comment] 2021-03-03 01:04
**NOTE:** If you see this, please check the K3s logs for "Mount cannot be satisfied for container" messages, as upstream has recently added more verbose logging to try to collect info on the root cause.

**Comment by dnoland1** [comment] 2021-03-03 03:14
@brandond Yes, was able to reproduce it on later versions (1.19.8) and capture more detailed logging:
```
Feb 23 04:48:19 ip-10-1-1-57 k3s[1461]: E0223 04:48:19.373686    1461 kubelet_pods.go:153] Mount cannot be satisfied for container "cordon", because the volume is missing (ok=false) or the volume mounter (vol.Mounter) is nil (vol={Mounter:<nil> BlockVolumeMapper:<nil> SELinuxLabeled:false ReadOnly:false InnerVolumeSpecName:}): {Name:host-root ReadOnly:false MountPath:/host SubPath: MountPropagation:<nil> SubPathExpr:}
Feb 24 05:57:02 ip-10-1-1-57 k3s[737835]: E0224 05:57:02.470793  737835 kubelet_pods.go:153] Mount cannot be satisfied for container "cordon", because the volume is missing (ok=false) or the volume mounter (vol.Mounter) is nil (vol={Mounter:<nil> BlockVolumeMapper:<nil> SELinuxLabeled:false ReadOnly:false InnerVolumeSpecName:}): {Name:host-root ReadOnly:false MountPath:/host SubPath: MountPropagation:<nil> SubPathExpr:}
```
You can DM me for the full log if needed.

**Comment by davidnuzik** [comment] 2021-03-03 17:20
Tentatively setting a 1.21 milestone but this is an upstream problem.

**Comment by brandond** [comment] 2021-03-31 20:33
Knocking this to backlog until I have a chance to see if upstream is interested in pursuing this.

**Comment by nikhilbhandari123** [comment] 2021-06-17 09:36
I am also facing this same issue intermittently:

"Mount cannot be satisfied for the container, because the volume is missing or the volume mounter (vol.Mounter) is nil" containerName="prepare" ok=false volumeMounter={Name:host-root ReadOnly:false MountPath:/host SubPath: MountPropagation:<nil> SubPathExpr:}

k3s version v1.21.1+k3s1 (75dba57f)

**Comment by cjellick** [comment] 2021-08-17 21:59
@nikhilbhandari123 do you reproduce this reliably or is it just flaky?

**Comment by dweomer** [comment] 2022-01-07 17:14
Fixed via:
- rancher/system-upgrade-controller#145
- rancher/system-upgrade-controller#153

**Closed by dweomer** 2022-01-07 17:14 UTC
Labels: kind/bug, kind/upstream-issue
