### ISSUE TITLE
coredns errors on 1.19.5 (coredns 1.7.1 + cache + DNSSEC)

### ISSUE THREAD

**Issue by plockaby** [k3s-io/k3s#2700] opened 2020-12-13 22:00 UTC
**Environmental Info:**
K3s Version: k3s version v1.19.5+k3s1 (b11612e2)

Node(s) CPU architecture, OS, and Version: Linux saturn 4.19.0-13-amd64 k3s-io/k3s#1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux

Cluster Configuration: 1 master, eight workers

**Describe the bug:**
Since upgrading to 1.19.5, DNS has become pretty reliably flaky. I run a github runner inside of my cluster and it very consistently fails to look up deb.debian.org. It's not regularly failing with every single query but it's failing often enough that I can't get a build to finish. When I reverted coredns back to 1.6.9 things worked again. I upgraded to 1.19.5 from 1.19.4-k3s2.

**Steps To Reproduce:**

- Installed K3s: k3s was installed like this:

curl -sfL https://get.k3s.io | sh -s - \
    --write-kubeconfig-mode=640 \
    --advertise-address=10.x.x.x \
    --cluster-cidr=10.y.0.0/16 \
    --service-cidr=10.z.0.0/16 \
    --cluster-dns=10.z.0.2 \
    --flannel-backend=host-gw \
    --disable=servicelb \
    --disable=traefik

And then upgraded by pulling the binaries, copying them into place, and restarting k3s master first and then all of the workers second.

**Expected behavior:**
I expected DNS to return reliably and consistently.

**Actual behavior:**
DNS queries fail some non-trivial percent of the time.

**Additional context / logs:**
There are no logs from coredns or from k3s about this issue. I'm just experiencing issues where software that tries to use built-in dns to lookup external addresses fail with coredns 1.7.1 but do not fail with coredns 1.6.9.

**Comment by plockaby** [comment] 2020-12-14 17:26
This is now doubly annoying because k3s keeps reverting my reversion so I have to go back in and make coredns run 1.6.9 on a regular basis.

**Comment by Kidswiss** [comment] 2020-12-17 12:37
Can confirm. Downgraded back to k3s 1.19.4-k3s1 for the time being.

**Comment by ankitrgadiya** [comment] 2020-12-17 17:27
I can confirm, it started happening after I upgraded to 1.19.5

**Comment by brandond** [comment] 2020-12-17 17:30
Can you provide any more info on what sort of DNS lookups are failing? In-cluster, out-of-cluster, etc? I'm not aware of any similar issues reported with the coredns project.

**Comment by ankitrgadiya** [comment] 2020-12-17 17:40
For me, the out-of-cluster DNS lookups are failing randomly. But, if I keep trying it eventually works. The exact configuration is such that I'm running two independent services in the same cluster but letting them communicate through external DNS (that is configured through Ingress).

**Comment by ankitrgadiya** [comment] 2020-12-17 17:56
I tried running `dig` to figure out what is exactly happening and I found out that everytime TTL expires I get a weird response.
```
/ # dig git.argc.in

; <<>> DiG 9.16.6 <<>> git.argc.in
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54532
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 2048
;; QUESTION SECTION:
;git.argc.in.                   IN      A

;; ANSWER SECTION:
git.argc.in.            30      IN      CNAME   lb-0.argd.in.
git.argc.in.            30      IN      RRSIG   CNAME 13 3 300 20201218185311 20201216165311 34505 argc.in. ARV1ABkpLZiInqcMcF5y6oK4HE+uMryTwnajPJrxMJIeo2giZ2sOWT6q jjELOyJS/h97XaNstHI2C9RgcJUsNQ==

;; Query time: 0 msec
;; SERVER: 10.43.0.10#53(10.43.0.10)
;; WHEN: Thu Dec 17 17:55:29 UTC 2020
;; MSG SIZE  rcvd: 191
```

This matches with the `curl` failing with Could not resolve host.
```
/ # curl -I git.argc.in
curl: (6) Could not resolve host: git.argc.in
```

**Comment by brandond** [comment] 2020-12-17 18:00
What's weird about that? Can you compare it to a cached response?

**Comment by ankitrgadiya** [comment] 2020-12-17 18:02
Updated original comment with the cached response. I'm not sure what exactly is RRSIG record but it seems to be related to DNSSEC. I will try disabling DNSSEC and see if that is really the case.

**Comment by Kidswiss** [comment] 2020-12-17 18:05
There's an upstream PR addressing this issue in CoreDNS:

https://github.com/coredns/coredns/issues/4189

Looks like it's fixed in 1.8.0.

**Comment by brandond** [comment] 2020-12-17 18:38
Thanks for digging that up! It appears to be specifically related to cache and dnssec. We'll evaluate going to v1.8.0 with our next release.

**Comment by brandond** [comment] 2020-12-17 22:36
For testing purposes, issues have reported failures resolving the following entries:
* git.argc.in
* deb.debian.org
* test.my.salesforce.com

You should be able to test these by running:
```
kubectl run --rm --tty --stdin --restart=Never --image=tutum/dnsutils dnsutils -- dig HOSTNAME
```

A successful response will have one or more A records in the ANSWER SECTION output:
```
; ANSWER SECTION:
git.argc.in.		25	IN	CNAME	lb-0.argd.in.
lb-0.argd.in.		25	IN	A	167.233.11.253
```

A failed response will have RRSIG records instead:
```
;; ANSWER SECTION:
git.argc.in.		30	IN	CNAME	lb-0.argd.in.
git.argc.in.		30	IN	RRSIG	CNAME 13 3 300 20201218233519 20201216213519 34505 argc.in. 86UMKuSTmm3y4ex/4orjGDpCdqsSi4rTfK9LJ7hhqhL368lpK1EIBXbt GQuS5yDyVNKp8rpq+6/2rW/wOerDGw==
```

**Comment by brandond** [comment] 2020-12-17 23:33
FYI - In case you couldn't tell from the PRs linked above, we are going to put out new releases this afternoon. The release-1.19 branch is going to go back to v1.6.9, and 1.20 (master) is going to go to v1.8.0 (unless we run into some other major issue with that version).

**Comment by plockaby** [comment] 2020-12-18 00:28
Thanks! Looking forward to the new release.

**Comment by jasonslay** [comment] 2020-12-18 07:27
I can confirm upgrading to v1.19.5+k3s2 has resolved these issues for me. Thanks for the release!

**Comment by ankitrgadiya** [comment] 2020-12-19 22:42
Confirming from my end as well. The upgrade does fix the issue.

**Comment by davidnuzik** [comment] 2021-01-06 16:17
Closing. This was tested and validated as a part of v1.19.5+k3s2 release (coreDNS 1.6.9). This is also good to go in v1.20.0+k3s2 as well and future releases (1.20.0 has coreDNS 1.8.0 which does not have the issue).

**Closed by davidnuzik** 2021-01-06 16:17 UTC
Labels: [zube]: To Test, area/dns, kind/bug, kind/upstream-issue, priority/critical-urgent
