### ISSUE TITLE
Embed cri-dockerd in k3s

### ISSUE THREAD

**Issue by ibuildthecloud** [k3s-io/k3s#5741] opened 2022-06-18 01:11 UTC
**Is your feature request related to a problem? Please describe.**

Bring back --docker

**Describe the solution you'd like**

I'd prefer k3s to vendor in cri-dockerd similar to all go stuff and run it when --docker is requested

**Describe alternatives you've considered**

**Additional context**

Docker is the number one container tool for development and I don't see that changing anytime soon.  Running k3s with --docker gives you the very nice advantage of being able to run images from docker build with no push/pull cycle.

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment] 2022-06-18 02:15
I proposed doing this for 1.24 and got voted down. cri-dockerd also turns out to have a bunch of performance issues related to pulling stats that we had to call in some favors at Mirantis to get addressed. They apparently have only one person on cri-dockerd maintenance who only checks the issues/PRs when he gets around to it: https://github.com/Mirantis/cri-dockerd/pull/38#issuecomment-1136665951

**Comment by ibuildthecloud** [comment] 2022-06-18 04:26
Is there more context as why it got voted down. Is Rancher Desktop not going to use cri-dockerd?

**Comment by brandond** [comment] 2022-06-18 05:34
I think folks were mostly just ready to make a clean break from it at the same time as upstream did. With docker support on windows evaporating and cri-dockerd maintenance from Mirantis being so half-hearted it didn't seem worth carrying.

**Comment by ibuildthecloud** [comment] 2022-06-21 06:11
Basically, if Rancher Desktop feels the need to package/fork/maintain cri-dockerd that basically proves there's value in doing that work upstream because docker is the primary solution on the desktop.  So can we just shift the effort of maintaining it in Rancher Desktop and do it in k3s.

**Comment by ibuildthecloud** [comment] 2022-07-28 16:10
Who are the gods of k3s that I need to convince that this is in fact a good idea to include cri-dockerd.  Now that 1.24 is the stable release this is becoming more of a problem for me.

**Comment by ekristen** [comment] 2022-07-28 16:14
I agree this needs to come back. Docker is still the preeminent way to do container/image development not having this feature in k3s makes using k3s for development difficult and hurts its place in the ecosystem.

**Comment by phillipsj** [comment] 2022-07-28 17:02
I believe @Oats87 is working on an issue related to cri-dockerd and CNI issues for 1.24 RKE. I would assume the issue could also exist here.

**Comment by brandond** [comment] 2022-07-28 17:08
https://github.com/k3s-io/k3s/commit/6feaec2cede9a7faba795173a385e40b68334452 should still apply mostly cleanly, it's just a matter of PM (or the team) deciding that it's something we want to take on as a support burden.

**Comment by jandubois** [comment] 2022-07-28 17:21
> Rancher Desktop is using it. They are actually packaging their own docker and containerd versions, along with a fork of cri-dockerd.

The fork was only temporary while upstream was not applying PRs. We are bundling the latest upstream version of cri-dockerd now.

For Rancher Desktop it will not matter if k3s starts bundling cri-dockerd or not. Since we support running all older versions of k3s, we will have to continue to ship it to support e.g. 1.24.1 to 1.24.3, which don't include it.

**Comment by xiaods** [comment] 2022-07-29 04:34
everyone like docker, but everyone care when the time switch to contained. in my side project, I use nerdctl + contained in my k3s branch. many user complain why use nerdctl. they also like docker. this is true story.
so I agree with embed cri-dockerd in k3s

**Comment by brandond** [comment] 2022-07-29 07:15
Anyone interested in this, please 👍🏻 the issue, and try out the linked PR to see if it meets your needs.

**Comment by cwayne18** [comment] 2022-07-29 11:51
@brandond once Derek's ADR reorg branch is merged, I think this is a perfect opportunity for an ADR to get public comment on

**Comment by brandond** [comment] 2022-07-30 02:33
ADR has been added to the PR.

**Comment by brandond** [comment] 2022-08-05 18:41
> better defaults so --network-plugin=cni isn't needed anymore (since CNI is the default in 1.24, basically)

At least on the [version](https://github.com/k3s-io/cri-dockerd/commits/bcbb75d5abff2ef6139ea7e41e0b090771492fd3) of cri-dockerd we're about to ship, not using `--network-plugin=cni` resulted in pods using the default docker address space, instead of the cluster pod CIDRs. When did that change?

**Comment by brandond** [comment] 2022-08-17 10:00
Thanks for the commentary! I'll take a look at updating the embedded version for our next release cycle, and trying to push up anything that hasn't already been addressed. I think the only big things were bumping the Kubernetes version and adding cgroupv2 support, which was pretty trivial. The change to panic instead of fatal is mostly just so that we can rescue out of some (if not all) errors.

**Comment by mateuszdrab** [comment] 2022-08-19 13:37
As we're on this topic, thought I'd sneak in a question related to supporting alternative runtimes. 

I saw this article https://opni.io/v0.4/setup/gpu/#rke and it confirmed my fears that alternative runtimes are not supported with dockershim.

Do you guys know if the cri-dockerd implementation supports them?

I'm currently running k3s with `--docker` flag and had some issues when moving away from it so would probably need to stick with it currently.

**Comment by ShylajaDevadiga** [comment] 2022-08-19 14:16
### Validated on master branch using commit id **b14cabc107e848ea4122e6917994925b1ca2418c**
## Environment Details
*Infrastructure*
Cloud EC2 instance

*Node(s) CPU architecture, OS, and Version:*
Ubuntu 20.04

*Cluster Configuration:*
One server One agent setup

**To validate:**
Server
```
sudo apt update
sudo apt install -y docker.io
curl -fL https://get.k3s.io | INSTALL_K3S_COMMIT=b14cabc107e848ea4122e6917994925b1ca2418c sh -s - server --token <TOKEN> --docker
```
Agent
```
sudo apt update
sudo apt install -y docker.io
curl -fL https://get.k3s.io | INSTALL_K3S_COMMIT=b14cabc107e848ea4122e6917994925b1ca2418c sh -s - agent --token <TOKEN> --docker --server <SERVER>:6443
```
**Output:**
```
ubuntu@ip-172-31-19-63:~$ kubectl get nodes
NAME              STATUS   ROLES                       AGE    VERSION
ip-172-31-19-63   Ready    control-plane,etcd,master   18m    v1.24.3+k3s-b14cabc1
ip-172-31-29-60   Ready    <none>                      3m7s   v1.24.3+k3s-b14cabc1
ubuntu@ip-172-31-19-63:~$ kubectl get pods -A 
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   coredns-b96499967-t4djb                   1/1     Running     0          25m
kube-system   helm-install-traefik-crd-2xv6k            0/1     Completed   0          25m
kube-system   helm-install-traefik-txh59                0/1     Completed   2          25m
kube-system   local-path-provisioner-7b7dc8d6f5-fskz9   1/1     Running     0          25m
kube-system   metrics-server-668d979685-srnm6           1/1     Running     0          25m
kube-system   svclb-traefik-b175a1a6-brlxk              2/2     Running     0          25m
kube-system   svclb-traefik-b175a1a6-t29d6              2/2     Running     0          10m
kube-system   traefik-7cd4fcff68-2th6c                  1/1     Running     0          25m
ubuntu@ip-172-31-19-63:~$ sudo docker images
REPOSITORY                         TAG                    IMAGE ID       CREATED         SIZE
rancher/klipper-helm               v0.7.3-build20220613   38b3b9ad736a   2 months ago    239MB
rancher/mirrored-library-traefik   2.6.2                  72463d8000a3   4 months ago    102MB
rancher/mirrored-coredns-coredns   1.9.1                  99376d8f35e0   5 months ago    49.5MB
rancher/klipper-lb                 v0.3.5                 dbd43b6716a0   6 months ago    8.09MB
rancher/local-path-provisioner     v0.0.21                fb9b574e03c3   8 months ago    35MB
rancher/mirrored-metrics-server    v0.5.2                 f73640fb5061   9 months ago    64.3MB
rancher/mirrored-pause             3.6                    6270bb605e12   11 months ago   683kB
ubuntu@ip-172-31-19-63:~$ 
```

**Comment by ShylajaDevadiga** [comment] 2022-08-19 20:23
Validated using rc **v1.24.4-rc1+k3s1**
Validated passing --docker flag as well as config.yaml
```
ubuntu@ip-172-31-19-63:~$ cat /etc/rancher/k3s/config.yaml 
token: "<TOKEN>"
docker: true
cluster-init: true
```

```
Cubuntu@ip-172-31-19-63:~$ k3s -v
k3s version v1.24.4-rc1+k3s1 (c3f830e9)
go version go1.18.1
ubuntu@ip-172-31-19-63:~$ kubectl get nodes
NAME               STATUS   ROLES                       AGE   VERSION
ip-172-31-18-87    Ready    control-plane,etcd,master   32m   v1.24.4-rc1+k3s1
ip-172-31-19-63    Ready    control-plane,etcd,master   33m   v1.24.4-rc1+k3s1
ip-172-31-21-236   Ready    control-plane,etcd,master   32m   v1.24.4-rc1+k3s1
ip-172-31-29-60    Ready    <none>                      33m   v1.24.4-rc1+k3s1
ubuntu@ip-172-31-19-63:~$ kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   coredns-b96499967-9cd55                   1/1     Running     0          33m
kube-system   helm-install-traefik-crd-khsmp            0/1     Completed   0          33m
kube-system   helm-install-traefik-zsnjf                0/1     Completed   2          33m
kube-system   local-path-provisioner-7b7dc8d6f5-lrtjw   1/1     Running     0          33m
kube-system   metrics-server-668d979685-8dnf5           1/1     Running     0          33m
kube-system   svclb-traefik-c12dcbe5-84cwf              2/2     Running     0          32m
kube-system   svclb-traefik-c12dcbe5-lp77k              2/2     Running     0          32m
kube-system   svclb-traefik-c12dcbe5-qdkb2              2/2     Running     0          32m
kube-system   svclb-traefik-c12dcbe5-tfpsg              2/2     Running     0          32m
kube-system   traefik-7cd4fcff68-pgnd4                  1/1     Running     0          32m
ubuntu@ip-172-31-19-63:~$ sudo docker images
REPOSITORY                         TAG                    IMAGE ID       CREATED         SIZE
rancher/klipper-helm               v0.7.3-build20220613   38b3b9ad736a   2 months ago    239MB
rancher/mirrored-library-traefik   2.6.2                  72463d8000a3   4 months ago    102MB
rancher/mirrored-coredns-coredns   1.9.1                  99376d8f35e0   5 months ago    49.5MB
rancher/klipper-lb                 v0.3.5                 dbd43b6716a0   6 months ago    8.09MB
rancher/local-path-provisioner     v0.0.21                fb9b574e03c3   8 months ago    35MB
rancher/mirrored-metrics-server    v0.5.2                 f73640fb5061   9 months ago    64.3MB
rancher/mirrored-pause             3.6                    6270bb605e12   11 months ago   683kB
```

**Closed by ShylajaDevadiga** 2022-08-19 20:23 UTC
Labels: kind/enhancement

**Comment by mateuszdrab** [comment] 2022-08-19 21:52
> > As we're on this topic, thought I'd sneak in a question related to supporting alternative runtimes.
> > 
> > I saw this article https://opni.io/v0.4/setup/gpu/#rke and it confirmed my fears that alternative runtimes are not supported with dockershim.
> > 
> > Do you guys know if the cri-dockerd implementation supports them?
> > 
> > I'm currently running k3s with `--docker` flag and had some issues when moving away from it so would probably need to stick with it currently.
> 
> @mateuszdrab  `cri-dockerd` is, essentially, a refactor of the `dockershim` driver (which the k8s team extracted and handed over). There is [very recent support](https://github.com/moby/moby/pull/43800) for alternative runtimes in `docker`, but it hasn't really been tested thoroughly yet. What's the use case? Can you open an issue on the cri-dockerd repo?

I totally didn't realize how new support for alternative runtimes is in Docker. I could swear I tried to find a runtime flag a few weeks ago and couldn't, this explains it. 

To be honest I don't really have a use case to stick with dockershim... I need to try reconfiguring my setup to run without the flag, but I tested it on one of the hosts and had issues. 

In a way I don't want to run two instances of containerd, so I might need to configure K3s to use an external containerd socket. 

I'll test it out more when I have some more time...
