### ISSUE TITLE
offline install k3s error

### ISSUE THREAD

**Issue by SpringHgui** [k3s-io/k3s#7940] opened 2023-07-11 09:04 UTC
```
[root@localhost ~]# curl -sfL https://rancher-mirror.oss-cn-beijing.aliyuncs.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn INSTALL_K3S_SKIP_DOWNLOAD=true sh -s -
[INFO]  Skipping k3s download and verify
[INFO]  Skipping installation of SELinux RPM
[ERROR]  Failed to find the k3s-selinux policy, please install:
    dnf install -y container-selinux
    dnf install -y https://rpm.rancher.io/k3s/stable/common/centos/9/noarch/
```

**Comment by dereknola** [comment] 2023-07-11 22:34
In order for airgapped installs to would you will need to download the appropriate selinux policy on a separate machine and then transfer it to the offline machine. Same with the k3s images as defined in https://docs.k3s.io/installation/airgap#manually-deploy-images-method

**Comment by dereknola** [comment] 2023-07-11 22:39
This is a duplicate of https://github.com/k3s-io/k3s/issues/7464

**Comment by brandond** [comment] 2023-07-13 17:14
Closing as duplicate

**Closed by brandond** 2023-07-13 17:14 UTC
