### ISSUE TITLE
[Release-1.27] - kubectl exec error-Internal error occurred: error executing command in container: http: invalid Host header

### ISSUE THREAD

**Issue by jintao-vip** [k3s-io/k3s#8160] opened 2023-08-09 06:22 UTC
**Environmental Info:**
K3s Version: 
v1.27.4+k3s1

Node(s) CPU architecture, OS, and Version: 
Linux stand-alone 3.10.0-1160.95.1.el7.x86_64 #1 SMP Mon Jul 24 13:59:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server（Single-node deployment）

Docker version:
[root@stand-alone srv]# docker version
Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:39:02 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:38:05 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Command:
The startup command for k3s is:
INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC='server --docker --disable=traefik --kube-apiserver-arg service-node-port-range=1-65535' ${base_dir}/package/k3s/install.sh

[root@stand-alone srv]# kubectl get node -owide
NAME          STATUS   ROLES                  AGE     VERSION        INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
stand-alone   Ready    control-plane,master   8m33s   v1.27.4+k3s1   172.31.40.32   <none>        CentOS Linux 7 (Core)   3.10.0-1160.95.1.el7.x86_64   docker://24.0.5

**Describe the bug:**
kubectl
**Steps To Reproduce:**
[root@stand-alone srv]# kubectl get pod -A
NAMESPACE     NAME                                     READY   STATUS    RESTARTS   AGE
kube-system   local-path-provisioner-957fdf8bc-cnff8   1/1     Running   0          8m39s
kuboard       kuboard-etcd-7gjnn                       1/1     Running   0          8m40s
kube-system   coredns-77ccd57875-zb4n7                 1/1     Running   0          8m39s
kube-system   metrics-server-648b5df564-c5c4b          1/1     Running   0          8m39s
kuboard       kuboard-v3-666bbb4d8c-frntd              1/1     Running   0          8m39s
kuboard       kuboard-agent-2-58d5cf4dbd-fmbvr         1/1     Running   0          7m50s
kuboard       kuboard-agent-bc9cbf9d8-snqnz            1/1     Running   0          7m50s
[root@stand-alone srv]# kubectl exec kuboard-v3-666bbb4d8c-frntd -n kuboard -- bash
**error: Internal error occurred: error executing command in container: http: invalid Host header**

**Comment by jstewart612** [comment] 2023-08-09 09:58
Fixed in https://github.com/k3s-io/k3s/issues/8089

Translation: 1.27.4 won't work for you.  Downgrade to 1.27.3 and wait for 1.27.5 to release.

**Comment by jintao-vip** [comment] 2023-08-09 10:05
> Fixed in #8089
> 
> Translation: 1.27.4 won't work for you. Downgrade to 1.27.3 and wait for 1.27.5 to release.

1.27.3 ok

**Comment by brandond** [comment] 2023-08-09 16:39
Duplicate of https://github.com/k3s-io/k3s/issues/8089

**Closed by brandond** 2023-08-09 16:39 UTC
