### ISSUE TITLE
already have the pause 3.1 ,still pull

### ISSUE THREAD

**Issue by liangyuanpeng** [k3s-io/k3s#576] opened 2019-06-25 15:11 UTC
Thanks for helping us to improve k3s! We welcome all bug reports. At this stage, we are also looking for help in testing/QAing fixes. Once we've fixed you're issue, we'll ping you in the comments to see if you can verify the fix. We'll give you details on what version can be used to test the fix. Additionally, if you are interested in testing fixes that you ***didn't*** report, look for the issues with the `status/to-test` label. You can pick any of these up for verification.  ***You can delete this message portion of the bug report.***

**Describe the bug**
i already have the pause 3.1  but why did k3s still pull

**To Reproduce**

**Expected behavior**
 use local pause 3.1

**Screenshots**
 ```  

E0625 23:13:38.198136   40282 pod_workers.go:190] Error syncing pod 24b81e22-975a-11e9-9515-000c2981dd06 ("coredns-695688789-mpkfc_kube-system(24b81e22-975a-11e9-9515-000c2981dd06)"), skipping: failed to "CreatePodSandbox" for "coredns-695688789-mpkfc_kube-system(24b81e22-975a-11e9-9515-000c2981dd06)" with CreatePodSandboxError: "CreatePodSandbox for pod \"coredns-695688789-mpkfc_kube-system(24b81e22-975a-11e9-9515-000c2981dd06)\" failed: rpc error: code = Unknown desc = failed to get sandbox image \"k8s.gcr.io/pause:3.1\": failed to pull image \"k8s.gcr.io/pause:3.1\": failed to resolve image \"k8s.gcr.io/pause:3.1\": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: dial tcp [2404:6800:4008:c01::52]:443: i/o timeout"
E0625 23:13:51.198485   40282 remote_runtime.go:109] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to resolve image "k8s.gcr.io/pause:3.1": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: dial tcp [2404:6800:4008:c01::52]:443: i/o timeout

```

```
sudo docker images
[sudo] password for lanren: 
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
k8s.gcr.io/kube-proxy                v1.14.3             004666307c5b        2 weeks ago         82.1MB
k8s.gcr.io/kube-controller-manager   v1.14.3             ac2ce44462bc        2 weeks ago         158MB
k8s.gcr.io/kube-apiserver            v1.14.3             9946f563237c        2 weeks ago         210MB
k8s.gcr.io/kube-scheduler            v1.14.3             953364a3ae7a        2 weeks ago         81.6MB
quay.io/coreos/flannel               v0.11.0-amd64       ff281650a721        4 months ago        52.6MB
k8s.gcr.io/coredns                   1.3.1               eb516548c180        5 months ago        40.3MB
k8s.gcr.io/etcd                      3.3.10              2c4adeb21b4f        6 months ago        258MB
k8s.gcr.io/pause                     3.1                 da86e6ba6ca1        18 months ago       742kB
```

**Additional context**

OS: ubuntu16
k3s version v0.6.1 (7ffe802a)

**Comment by erikwilson** [comment] 2019-06-25 16:44
Without steps to reproduce I am not sure what options you are using for k3s. 
Are you using the `--docker` flag also? 
k3s would normally have no knowledge of docker images since it uses containerd by default. Normally the `crictl` command would be used to view images that are loaded. The README has a section on using airgap images which can be used to pre-load the pause image.

**Comment by baohui0** [comment] 2019-09-06 07:37
when i using the --docker flag ,k3s server would failed and always trying to restart
### This is my screenshot:

```
 [root@kube-master bin]# systemctl status k3s
 k3s.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2019-09-06 15:14:36 CST; 1s ago
     Docs: https://k3s.io
  Process: 33498 ExecStart=/usr/local/bin/k3s server --docker (code=exited, status=255)
  Process: 33495 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 33492 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
 Main PID: 33498 (code=exited, status=255)

Sep 06 15:14:36 kube-master systemd[1]: Unit k3s.service entered failed state.
Sep 06 15:14:36 kube-master systemd[1]: k3s.service failed.
```

and i met the same problem with him.
what i should do now?

**Comment by brandond** [comment] 2020-12-05 00:21
Closing due to age.

**Closed by brandond** 2020-12-05 00:21 UTC
Labels: status/more-info
