### ISSUE TITLE
coreDNS failed when using more than one node

### ISSUE THREAD

**Issue by tengzhuofei** [k3s-io/k3s#1175] opened 2019-12-10 07:33 UTC
env

k3s 1.0.0 v1.16.3-k3s.2
CentOS Linux release 7.7.1908 (Core)  CentOS Linux release 7.6.1810 (Core)
3.10.0-1062.4.3.el7.x86_64
docker 19.03.4

describe

- only the node run coredns can resolve via 10.43.0.10, other (both master and agents) can't.
- pods with hostNetwork: true can't resolve servicename via it on the same node,  and can't resolve clusterip via it on the different node.(set ClusterFirstWithHostNet)

**Comment by sebastien-prudhomme** [comment] 2019-12-10 23:08
Maybe the same problem i have: #1142

**Comment by tengzhuofei** [comment] 2019-12-11 06:12
Ubuntu 16.04（amd64）is good

**Comment by davidnuzik** [comment] 2019-12-11 16:52
While we expect K3s to run on just about any Linux distro (amd64, arm64, armhf architectures) please note that currently only some distros are tested and fully supported. See https://rancher.com/docs/k3s/latest/en/installation/node-requirements/#operating-systems

We are planning to start testing with CentOS 7 and RHEL 7 however this does not necessarily mean we are going to add official support in the next release.

While running on CentOS 7.x / RHEL 7.x should work it's possible to come across issues with them.

**Comment by tengzhuofei** [comment] 2019-12-12 10:15
Ubuntu 16.04（amd64）coredns is also have 5s latency on other node
curl 10.43.0.10:53

**Comment by gilbahat** [comment] 2020-03-23 09:31
this reproduces for us as well. a comment on this bug: https://github.com/kubernetes/kubernetes/issues/56934 suggests it relates to flannel and should perhaps be filed with them.

**Comment by lefeverd** [comment] 2020-03-29 14:09
I do have the same issue when deploying metricbeat, which uses:
```
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
```
When removing it, it works fine.  
They added that to have the real hostnames in the metrics, instead of the names of the pods.

**Comment by collinwright** [comment] 2020-04-22 13:02
I'm seeing this issue as well with Metricbeat/Filebeat. Seems to occur on every release since 1.0.0, but not before that

**Comment by ShylajaDevadiga** [comment] 2021-07-09 09:36
@tengzhuofei I am trying to reproduce the issue on Ubuntu as well as CentOS using k3s version v1.21.2+k3s1 and k3s version v1.0.0
Here are the steps I followed which seems to be working as expected. 

- Installed k3s with traefik disabled. 
- Joined an agent node
- Deployed the manifest with **hostNetwork: true** and **dnsPolicy: ClusterFirstWithHostNet**,  ensuring pods are on separate nodes

```
$ cat nginx
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: my-nginx
spec:
  type: LoadBalancer
  ports:
  - port: 8800
    targetPort: 80
  selector:
    app: my-nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      app: my-nginx

  replicas: 2
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: my-nginx
        image: nginx:1.8.1

$ kubectl exec -it my-nginx-67db58bbd-9q9nx -- /usr/bin/nslookup my-nginx
Server:		10.43.0.10
Address:	10.43.0.10#53

Name:	my-nginx.default.svc.cluster.local
Address: 10.43.38.42

[centos@ip-172-31-43-223 ~]$ curl http://10.43.130.60:8800
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>

[centos@ip-172-31-43-223 ~]$ curl http://10.43.130.60:8800
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
```

**Comment by caroline-suse-rancher** [comment] 2022-12-01 15:49
Closing as this no longer seems to be an issue.

**Closed by caroline-suse-rancher** 2022-12-01 15:49 UTC
Labels: os/centos
