### ISSUE TITLE
External IP is empty for traefik setup in ipv6

### ISSUE THREAD

**Issue by btrepp** [k3s-io/k3s#5600] opened 2022-05-23 10:31 UTC
**Environmental Info:**
K3s Version: 
k3s version v1.23.6+k3s1 (418c3fa8)
go version go1.17.5

Node(s) CPU architecture, OS, and Version: 
Linux k8s1s1 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux

Cluster Configuration:
1 server, 2 agents

**Describe the bug:**

Traefik external ip states pending

```
NAMESPACE     NAME                                      TYPE           CLUSTER-IP             EXTERNAL-IP   PORT(S)                      AGE
default       kubernetes                                ClusterIP      2001:cafe:42:1::1      <none>        443/TCP                      25h
kube-system   kube-dns                                  ClusterIP      2001:cafe:42:1::a      <none>        53/UDP,53/TCP,9153/TCP       25h
kube-system   metrics-server                            ClusterIP      2001:cafe:42:1::f186   <none>        443/TCP                      25h
kube-system   traefik                                   LoadBalancer   2001:cafe:42:1::4816   <pending>     80:30657/TCP,443:31654/TCP   24h
```

It's useable, and traefik seems to serve traffic, just a bit confusing.
Unsure if this is IPv6 related or not.

**Steps To Reproduce:**

Installed a stock k3s system (this was using ansible) configuration is 
https://git.sr.ht/~btrepp/infrastructure/tree/main/item/bootstrap/group_vars/k8s1.yml

Ran `kubectl get svc -A` to get the external ips, and noticed this.

A website is running and accessible though.

**Expected behavior:**
Klipper updates the external IP in the service.

**Actual behavior:**
External IP is pending (though the external IPs of the node do seem useable)

**Additional context / logs:**
Could be related to #5575, but I am not running dual stack (the nodes do have dual stack, but k3s is configured only to use ipv6)

**Backporting**
- [ ] Needs backporting to older releases

**Comment by brandond** [comment] 2022-05-23 17:09
cc @rbrtbnfgl @manuelbuil any ideas?

**Comment by manuelbuil** [comment] 2022-05-23 17:16
> cc @rbrtbnfgl @manuelbuil any ideas?

Possibly related to https://github.com/k3s-io/k3s/issues/1162 which is fixed but still not released. The output is very familiar with what we fixed in 1.24 related to the upstream change (forcing kubelet's node-ip on the node manifest).

Let's verify this. @btrepp could you give me two outputs please?
1 - The node yaml file where traefik pod is running (kubectl get node $node_name -o yaml)
2 - The manifest of the traefik service (kubectl get service traefik -n kube-system -o yaml)

**Comment by VestigeJ** [comment] 2022-05-23 17:38
I've got a single node k3s setup showing the following

**$ k3s -v**
```
k3s version v1.23.6+k3s1 (418c3fa8)
go version go1.17.5
```

$ kubectl get all -A -o wide -o wide                                                                                                                                           
```
NAMESPACE     NAME                                          READY   STATUS      RESTARTS   AGE   IP               NODE              NOMINATED NODE   READINESS GATES
kube-system   pod/coredns-d76bd69b-77qgv                    1/1     Running     0          52s   2022:aced:7::2   ip-192-168-0-71   <none>           <none>
kube-system   pod/local-path-provisioner-6c79684f77-qn72n   1/1     Running     0          52s   2022:aced:7::6   ip-192-168-0-71   <none>           <none>
kube-system   pod/helm-install-traefik-crd-tphss            0/1     Completed   0          52s   2022:aced:7::4   ip-192-168-0-71   <none>           <none>
kube-system   pod/helm-install-traefik-22jsn                0/1     Completed   1          52s   2022:aced:7::5   ip-192-168-0-71   <none>           <none>
kube-system   pod/svclb-traefik-gvz7v                       2/2     Running     0          26s   2022:aced:7::7   ip-192-168-0-71   <none>           <none>
kube-system   pod/metrics-server-7cd5fcb6b7-md8p9           1/1     Running     0          52s   2022:aced:7::3   ip-192-168-0-71   <none>           <none>
kube-system   pod/traefik-df4ff85d6-p4dsx                   1/1     Running     0          26s   2022:aced:7::8   ip-192-168-0-71   <none>           <none>

NAMESPACE     NAME                     TYPE           CLUSTER-IP          EXTERNAL-IP                             PORT(S)                      AGE   SELECTOR
default       service/kubernetes       ClusterIP      2022:aced:8::1      <none>                                  443/TCP                      66s   <none>
kube-system   service/kube-dns         ClusterIP      2022:aced:8::a      <none>                                  53/UDP,53/TCP,9153/TCP       63s   k8s-app=kube-dns
kube-system   service/metrics-server   ClusterIP      2022:aced:8::404    <none>                                  443/TCP                      62s   k8s-app=metrics-server
kube-system   service/traefik          LoadBalancer   2022:aced:8::7356   2600:1f1c:ab4:ee48:b0e8:6e19:17b:1cc7   80:31718/TCP,443:30242/TCP   26s   app.kubernetes.io/instance=traefik,app.kubernetes.io/name=traefik

NAMESPACE     NAME                           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE   CONTAINERS             IMAGES                                                SELECTOR
kube-system   daemonset.apps/svclb-traefik   1         1         1       1            1           <none>          26s   lb-tcp-80,lb-tcp-443   rancher/klipper-lb:v0.3.5,rancher/klipper-lb:v0.3.5   app=svclb-traefik

NAMESPACE     NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS               IMAGES                                   SELECTOR
kube-system   deployment.apps/coredns                  1/1     1            1           63s   coredns                  rancher/mirrored-coredns-coredns:1.9.1   k8s-app=kube-dns
kube-system   deployment.apps/local-path-provisioner   1/1     1            1           63s   local-path-provisioner   rancher/local-path-provisioner:v0.0.21   app=local-path-provisioner
kube-system   deployment.apps/metrics-server           1/1     1            1           62s   metrics-server           rancher/mirrored-metrics-server:v0.5.2   k8s-app=metrics-server
kube-system   deployment.apps/traefik                  1/1     1            1           26s   traefik                  rancher/mirrored-library-traefik:2.6.2   app.kubernetes.io/instance=traefik,app.kubernetes.io/name=traefik

NAMESPACE     NAME                                                DESIRED   CURRENT   READY   AGE   CONTAINERS               IMAGES                                   SELECTOR
kube-system   replicaset.apps/coredns-d76bd69b                    1         1         1       52s   coredns                  rancher/mirrored-coredns-coredns:1.9.1   k8s-app=kube-dns,pod-template-hash=d76bd69b
kube-system   replicaset.apps/local-path-provisioner-6c79684f77   1         1         1       52s   local-path-provisioner   rancher/local-path-provisioner:v0.0.21   app=local-path-provisioner,pod-template-hash=6c79684f77
kube-system   replicaset.apps/metrics-server-7cd5fcb6b7           1         1         1       52s   metrics-server           rancher/mirrored-metrics-server:v0.5.2   k8s-app=metrics-server,pod-template-hash=7cd5fcb6b7
kube-system   replicaset.apps/traefik-df4ff85d6                   1         1         1       26s   traefik                  rancher/mirrored-library-traefik:2.6.2   app.kubernetes.io/instance=traefik,app.kubernetes.io/name=trae
fik,pod-template-hash=df4ff85d6

NAMESPACE     NAME                                 COMPLETIONS   DURATION   AGE   CONTAINERS   IMAGES                                      SELECTOR
kube-system   job.batch/helm-install-traefik-crd   1/1           26s        60s   helm         rancher/klipper-helm:v0.7.1-build20220407   controller-uid=19b5d3af-a7de-408f-8195-4de53d1f3347
kube-system   job.batch/helm-install-traefik       1/1           29s        60s   helm         rancher/klipper-helm:v0.7.1-build20220407   controller-uid=99ff91a4-6994-4a8a-b1fb-58d3b979c1eb
```


$ k get node -o yaml
```
apiVersion: v1
items:
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      alpha.kubernetes.io/provided-node-ip: 2600:1f1c:ab4:ee48:b0e8:6e19:17b:1cc7
      flannel.alpha.coreos.com/backend-type: vxlan
      flannel.alpha.coreos.com/backend-v6-data: '{"VNI":1,"VtepMAC":"42:65:94:14:0a:65"}'
      flannel.alpha.coreos.com/kube-subnet-manager: "true"
      flannel.alpha.coreos.com/public-ipv6: 2600:1f1c:ab4:ee48:b0e8:6e19:17b:1cc7
      k3s.io/external-ip: 2600:1f1c:ab4:ee48:b0e8:6e19:17b:1cc7
      k3s.io/hostname: ip-192-168-0-71
      k3s.io/internal-ip: 2600:1f1c:ab4:ee48:b0e8:6e19:17b:1cc7
      k3s.io/node-args: '["server","--write-kubeconfig-mode","644","--debug","true","--token","********","--cluster-cidr","2022:aced:7::/56","--service-cidr","2022:aced:8::/112","--disable-network-policy","true","--node-ip","2600:1f1c:ab4:ee48:b0e8:6e19:17b:1cc7","--disable-networkpolicy","true","--node-external-ip","2600:1f1c:ab4:ee48:b0e8:6e19:17b:1cc7"]'
      k3s.io/node-config-hash: DL2CZ5PXCEJYN63FA7RVSQOFHB6UNBSBYR7TMI2RLGI5WHTPJHOQ====
      k3s.io/node-env: '{"K3S_DATA_DIR":"/var/lib/rancher/k3s/data/8c2b0191f6e36ec6f3cb68e2302fcc4be850c6db31ec5f8a74e4b3be403101d8"}'
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: "2022-05-23T17:33:44Z"
    finalizers:
    - wrangler.cattle.io/node
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/instance-type: k3s
      beta.kubernetes.io/os: linux
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: ip-192-168-0-71
      kubernetes.io/os: linux
      node-role.kubernetes.io/control-plane: "true"
      node-role.kubernetes.io/master: "true"
      node.kubernetes.io/instance-type: k3s
    name: ip-192-168-0-71
    resourceVersion: "718"
    uid: bc9b9015-27cb-4c0c-95cd-8d1eb7a18224
  spec:
    podCIDR: 2022:aced:7::/64
    podCIDRs:
    - 2022:aced:7::/64
    providerID: k3s://ip-192-168-0-71
  status:
    addresses:
    - address: 2600:1f1c:ab4:ee48:b0e8:6e19:17b:1cc7
      type: InternalIP
    - address: 2600:1f1c:ab4:ee48:b0e8:6e19:17b:1cc7
      type: ExternalIP
    - address: ip-192-168-0-71
      type: Hostname
    allocatable:
      cpu: "2"
      ephemeral-storage: "29600903145"
      hugepages-2Mi: "0"
      memory: 4018284Ki
      pods: "110"
    capacity:
      cpu: "2"
      ephemeral-storage: 30428560Ki
      hugepages-2Mi: "0"
      memory: 4018284Ki
      pods: "110"
    conditions:
    - lastHeartbeatTime: "2022-05-23T17:34:45Z"
      lastTransitionTime: "2022-05-23T17:33:44Z"
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: "2022-05-23T17:34:45Z"
      lastTransitionTime: "2022-05-23T17:33:44Z"
      message: kubelet has no disk pressure
      reason: KubeletHasNoDiskPressure
      status: "False"
      type: DiskPressure
    - lastHeartbeatTime: "2022-05-23T17:34:45Z"
      lastTransitionTime: "2022-05-23T17:33:44Z"
      message: kubelet has sufficient PID available
      reason: KubeletHasSufficientPID
      status: "False"
      type: PIDPressure
    - lastHeartbeatTime: "2022-05-23T17:34:45Z"
      lastTransitionTime: "2022-05-23T17:33:54Z"
      message: kubelet is posting ready status. AppArmor enabled
      reason: KubeletReady
      status: "True"
      type: Ready
    daemonEndpoints:
      kubeletEndpoint:
        Port: 10250
    images:
    - names:
      - docker.io/rancher/klipper-helm@sha256:6eb12b5362bd19bb8c523dda3e5d5ed0137b134e334c8257a30f6a849a42e990
      - docker.io/rancher/klipper-helm:v0.7.1-build20220407
      sizeBytes: 82976045
    - names:
      - docker.io/rancher/mirrored-library-traefik@sha256:ad2226527eea71b7591d5e9dcc0bffd0e71b2235420c34f358de6db6d529561f
      - docker.io/rancher/mirrored-library-traefik:2.6.2
      sizeBytes: 30348500
    - names:
      - docker.io/rancher/mirrored-metrics-server@sha256:48ecad4fe641a09fa4459f93c7ad29d4916f6b9cf7e934d548f1d8eff96e2f35
      - docker.io/rancher/mirrored-metrics-server:v0.5.2
      sizeBytes: 26022698
    - names:
      - docker.io/rancher/mirrored-coredns-coredns@sha256:35e38f3165a19cb18c65d83334c13d61db6b24905f45640aa8c2d2a6f55ebcb0
      - docker.io/rancher/mirrored-coredns-coredns:1.9.1
      sizeBytes: 14111376
    - names:
      - docker.io/rancher/local-path-provisioner@sha256:1da612c913ce0b4ab82e20844baa9dce1f7065e39412d6a0bb4de99c413f21bf
      - docker.io/rancher/local-path-provisioner:v0.0.21
      sizeBytes: 11434864
    - names:
      - docker.io/rancher/klipper-lb@sha256:02f8cb41d53fe08b5726a563ce36c3675ad7f2694b65a8477f6a66afac89fef7
      - docker.io/rancher/klipper-lb:v0.3.5
      sizeBytes: 3334605
    - names:
      - docker.io/rancher/mirrored-pause@sha256:74c4244427b7312c5b901fe0f67cbc53683d06f4f24c6faee65d4182bf0fa893
      - docker.io/rancher/mirrored-pause:3.6
      sizeBytes: 301463
    nodeInfo:
      architecture: amd64
      bootID: 73413c0b-4f12-4fac-ad65-72f6048e0a44
      containerRuntimeVersion: containerd://1.5.11-k3s2
      kernelVersion: 5.11.0-1022-aws
      kubeProxyVersion: v1.23.6+k3s1
      kubeletVersion: v1.23.6+k3s1
      machineID: 056207efbfdc4a40ae56c59c725ece7b
      operatingSystem: linux
      osImage: Ubuntu 20.04.4 LTS
      systemUUID: ec2cce3d-054b-0622-cc39-78978e88a48b
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```



$ kgs traefik -n kube-system -o yaml
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2022-05-23T17:34:21Z"
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-10.19.300
  name: traefik
  namespace: kube-system
  resourceVersion: "692"
  uid: 20cacff8-f186-4812-a21b-b9aef3fdef8b
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 2022:aced:8::7356
  clusterIPs:
  - 2022:aced:8::7356
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    nodePort: 31718
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    nodePort: 30242
    port: 443
    protocol: TCP
    targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 2600:1f1c:ab4:ee48:b0e8:6e19:17b:1cc7
```

**Comment by btrepp** [comment] 2022-05-23 23:04
@manuelbuil  as requested :)

$ kubectl get node k8s1w -o yaml
```
apiVersion: v1
kind: Node
metadata:
  annotations:
    flannel.alpha.coreos.com/backend-type: vxlan
    flannel.alpha.coreos.com/backend-v6-data: '{"VNI":1,"VtepMAC":"da:48:92:60:a5:ca"}'
    flannel.alpha.coreos.com/kube-subnet-manager: "true"
    flannel.alpha.coreos.com/public-ipv6: 2403:580f:43f:1::675
    k3s.io/hostname: k8s1w2
    k3s.io/internal-ip: 192.168.4.13
    k3s.io/node-args: '["agent","--server","https://[2403:580f:43f:1::5d9]:6443","--token-file","/etc/rancher/k3s/cluster-token","--config","/etc/rancher/k3s/config.yaml"]'
    k3s.io/node-config-hash: NPF7KRJ3LVEDBQW2TVB22PMW4W5CNXOEO5EITZCIIQYWYPCHCHHQ====
    k3s.io/node-env: '{"K3S_DATA_DIR":"/var/lib/rancher/k3s/data/33f2f883e918543e89bba65177eafb6148f9fa38c07c61cf7ce6ae61c0f50a96"}'
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2022-05-22T09:43:24Z"
  finalizers:
  - wrangler.cattle.io/node
  labels:
    beta.kubernetes.io/arch: arm64
    beta.kubernetes.io/instance-type: k3s
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: arm64
    kubernetes.io/hostname: k8s1w2
    kubernetes.io/os: linux
    node.kubernetes.io/instance-type: k3s
  name: k8s1w2
  resourceVersion: "59472"
  uid: 2c708704-1be4-4c8f-9f56-e8942dd79370
spec:
  podCIDR: 2001:cafe:42:1::/64
  podCIDRs:
  - 2001:cafe:42:1::/64
  providerID: k3s://k8s1w2
status:
  addresses:
  - address: 192.168.4.13
    type: InternalIP
  - address: k8s1w2
    type: Hostname
  allocatable:
    cpu: "4"
    ephemeral-storage: "59652465618"
    memory: 7999972Ki
    pods: "110"
  capacity:
    cpu: "4"
    ephemeral-storage: 61320380Ki
    memory: 7999972Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2022-05-23T22:58:03Z"
    lastTransitionTime: "2022-05-22T09:43:24Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2022-05-23T22:58:03Z"
    lastTransitionTime: "2022-05-22T09:43:24Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2022-05-23T22:58:03Z"
    lastTransitionTime: "2022-05-22T09:43:24Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2022-05-23T22:58:03Z"
    lastTransitionTime: "2022-05-22T09:43:34Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - ghcr.io/goauthentik/server@sha256:cd7b20d1e44ad82c2ab8229cedcdb9de5be56d9c63f930082e4d90255b12c48d
    - ghcr.io/goauthentik/server:2022.3.3
    sizeBytes: 241556453
  - names:
    - quay.io/argoproj/argocd@sha256:dd738f234fcdb0aac8631a0fd1aafbbcd86f936480b06e8377b033ef7a764f71
    - quay.io/argoproj/argocd:v2.3.3
    sizeBytes: 184820580
  - names:
    - docker.io/rancher/klipper-helm@sha256:6eb12b5362bd19bb8c523dda3e5d5ed0137b134e334c8257a30f6a849a42e990
    - docker.io/rancher/klipper-helm:v0.7.1-build20220407
    sizeBytes: 76750270
  - names:
    - docker.io/rancher/mirrored-library-traefik@sha256:ad2226527eea71b7591d5e9dcc0bffd0e71b2235420c34f358de6db6d529561f
    - docker.io/rancher/mirrored-library-traefik:2.6.2
    sizeBytes: 27892300
  - names:
    - docker.io/rancher/mirrored-metrics-server@sha256:48ecad4fe641a09fa4459f93c7ad29d4916f6b9cf7e934d548f1d8eff96e2f35
    - docker.io/rancher/mirrored-metrics-server:v0.5.2
    sizeBytes: 24424221
  - names:
    - docker.io/rancher/mirrored-coredns-coredns@sha256:35e38f3165a19cb18c65d83334c13d61db6b24905f45640aa8c2d2a6f55ebcb0
    - docker.io/rancher/mirrored-coredns-coredns:1.9.1
    sizeBytes: 12820801
  - names:
    - docker.io/library/redis@sha256:132337b9d7744ffee4fae83f51de53c3530935ad3ba528b7110f2d805f55cbf5
    - docker.io/library/redis:6.2.6-alpine
    sizeBytes: 10844849
  - names:
    - docker.io/rancher/klipper-lb@sha256:02f8cb41d53fe08b5726a563ce36c3675ad7f2694b65a8477f6a66afac89fef7
    - docker.io/rancher/klipper-lb:v0.3.5
    sizeBytes: 3240172
  - names:
    - docker.io/rancher/mirrored-pause@sha256:74c4244427b7312c5b901fe0f67cbc53683d06f4f24c6faee65d4182bf0fa893
    - docker.io/rancher/mirrored-pause:3.6
    sizeBytes: 253243
  nodeInfo:
    architecture: arm64
    bootID: fe3d0194-f796-4a17-9b62-e90945607a3e
    containerRuntimeVersion: containerd://1.5.11-k3s2
    kernelVersion: 5.15.32-v8+
    kubeProxyVersion: v1.23.6+k3s1
    kubeletVersion: v1.23.6+k3s1
    machineID: b0cc67f248c141cba07f3264af348ec5
    operatingSystem: linux
    osImage: Debian GNU/Linux 11 (bullseye)
    systemUUID: b0cc67f248c141cba07f3264af348ec5
```
kubectl get service traefik -n kube-system -o yaml

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2022-05-22T09:44:49Z"
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-10.19.300
  name: traefik
  namespace: kube-system
  resourceVersion: "1687"
  uid: 28d98416-7d0d-43f4-97bd-74c46489b1dc
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 2001:cafe:42:1::4816
  clusterIPs:
  - 2001:cafe:42:1::4816
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    nodePort: 30657
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    nodePort: 31654
    port: 443
    protocol: TCP
    targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```

**Comment by manuelbuil** [comment] 2022-05-24 06:56
I think I know what the problem is. Your nodes have both ipv4 and ipv6 addresses in the main interface. If you don't specify the IP you want to use for the node, kubelet will always pick the ipv4 address. In your case:
```
status:
  addresses:
  - address: 192.168.4.13
    type: InternalIP
```

You should deploy all nodes specifying the ipv6 address with the `--node-ip` parameter. Look at how we do it in dual-stack: https://rancher.com/docs/k3s/latest/en/installation/network-options/#dual-stack-installation

**Comment by btrepp** [comment] 2022-05-24 09:06
@manuelbuil 

Yep that's 100% it.

```
sudo kubectl get service traefik -n kube-system
NAME      TYPE           CLUSTER-IP             EXTERNAL-IP                                 PORT(S)                      AGE
traefik   LoadBalancer   2001:cafe:42:1::4816   2403:580f:43f:1::3ac,2403:580f:43f:1::675   80:30657/TCP,443:31654/TCP   47h
```

I never actually specified that IPv4 address. So seems like the auto-detection referenced in your link maybe takes the first ipv4 address, even in a ipv6 cluster :).

Unsure if that is a different issue, but the resolution for anyone who runs into similar in a IPV6 cluster, is to just specify the node ip on install

**Comment by brandond** [comment] 2022-05-24 20:01
On 1.23 at least, the kubelet will only autodetect ipv4 addresses. It sounds like this behavior may have changed for 1.24; I'm not sure.

**Comment by ShylajaDevadiga** [comment] 2022-06-02 19:37
Validated in v1.23.7-rc1+k3s1, v1.24.1-rc2+k3s1 in ipv6 setup as well as dual stack
```
$ k3s -v
k3s version v1.23.7-rc1+k3s1 (4b2aa16c)
go version go1.17.5
$ cat config.yaml 
write-kubeconfig-mode: 644
token: "secret"
cluster-cidr: 2001:cafe:42:0::/56
service-cidr: 2001:cafe:42:1::/112
disable-network-policy: true
flannel-ipv6-masq: true

$ kubectl get svc -A |grep traefik
kube-system   traefik          LoadBalancer   fd00:43::f6a4   2600:<REDACTED>
   80:32637/TCP,443:32657/TCP   15m


$ k3s -v
k3s version v1.24.1-rc2+k3s1 (29397b4e)
go version go1.18.1
$ kubectl get svc -A |grep traefik
kube-system   traefik          LoadBalancer   2001:cafe:42:1::2ce2   2600:<REDACTED>
   80:30978/TCP,443:32142/TCP   58s

$ kubectl describe svc -n kube-system traefik |grep -i "LoadBalancer Ingress:"
LoadBalancer Ingress:     2600:<REDACTED>
```
Validated in v1.23.7-rc1+k3s1, v1.24.1-rc2+k3s1 in dual mode
```
$ k3s -v
k3s version v1.23.7-rc1+k3s1 (4b2aa16c)
go version go1.17.5

~$ cat /etc/rancher/k3s/config.yaml 
write-kubeconfig-mode: 644
node-ip: <Ipv4>,2600:<REDACTED>
token: "secret"
cluster-cidr: 10.42.0.0/16,2001:cafe:42:0::/56
service-cidr: 10.43.0.0/16,2001:cafe:43:1::/112
disable-network-policy: true
flannel-ipv6-masq: true

$ kubectl get svc traefik -n kube-system
NAME      TYPE           CLUSTER-IP     EXTERNAL-IP                                             PORT(S)                      AGE
traefik   LoadBalancer   10.43.236.71   192.168.76.176,2600:<REDACTED>  80:30133/TCP,443:30705/TCP   14m

$ k3s -v
k3s version v1.24.1-rc1+k3s1 (a5a0e8fd)
go version go1.18.1

$ kubectl get svc traefik -n kube-system
NAME      TYPE           CLUSTER-IP      EXTERNAL-IP                                             PORT(S)                      AGE
traefik   LoadBalancer   10.43.209.127   192.168.76.176,2600:<REDACTED>
  80:32364/TCP,443:32623/TCP   14s

```

**Closed as completed by ShylajaDevadiga** 2022-06-02 19:37 UTC
