### ISSUE TITLE
k3s cluster should use GPU without mentioning runtimeClassName: "nvidia" in pod specs

### ISSUE THREAD

**Issue by khalidkhushal** [k3s-io/k3s#10034] opened 2024-04-27 16:09 UTC
Hi,
I have installed a k3s cluster and gpu operator using nvidia official docs.
Everything seems to work fine and pods are able to use GPUs but I have to define `runtimeClassName: "nvidia"` in pod specs.

Do we have any other way of doing it?
Can I somehow make the k3s pods to use GPUs without defining `runtimeClassName: "nvidia"` in pod specs?

**Comment by cwayne18** [comment] 2024-04-27 16:15
This is expected behavior at this time, although we are looking at ways to make using GPUs easier

**Comment by khalidkhushal** [comment] 2024-04-27 17:52
> This is expected behavior at this time, although we are looking at ways to make using GPUs easier

I am using kubeflow manifest to deploy kubeflow on K3s, how can I add runtimeClassName in pods creation for it?
I have been looking for admisssion webhooks for it, but still I am on R&D.

I would appreciate your kind guidance on this.

**Comment by brandond** [comment] 2024-04-28 03:00
Duplicate of https://github.com/k3s-io/k3s/issues/8700 - see the `--default-runtime` flag from https://github.com/k3s-io/k3s/pull/8936

**Closed by brandond** 2024-04-28 03:00 UTC

**Comment by khalidkhushal** [comment] 2024-07-19 07:54
> Duplicate of #8700 - see the `--default-runtime` flag from #8936

Can I somehow change default runtime on single node k3s cluster?
