### ISSUE TITLE
k3s agent: SIGSEGV from flannel subsystem (ipv6 related?)

### ISSUE THREAD

**Issue by PeterGrace** [k3s-io/k3s#10557] opened 2024-07-24 15:24 UTC
**Environmental Info:**
K3s Version: k3s version v1.28.11+k3s1 (617b0e84)

Node(s) CPU architecture, OS, and Version: x86-64, kvm, ubuntu 24.04 lts

Cluster Configuration:
This cluster is dynamically autoscaled with kvm virtual machines.  The cluster is a dual-stack ipv4 and ipv6 deployment.

**Describe the bug:**
k3s agent SIGSEGV's approximately 15 seconds into starting up with the following stack trace:
```
Jul 24 15:18:19 k8s-libvirt-4650b9cf-32ea-42a1-82cf-f5f00d151f52 k3s[1256342]: I0724 15:18:19.879438 1256342 iptables.go:125] Setting up masking rules
Jul 24 15:18:19 k8s-libvirt-4650b9cf-32ea-42a1-82cf-f5f00d151f52 k3s[1256342]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 24 15:18:19 k8s-libvirt-4650b9cf-32ea-42a1-82cf-f5f00d151f52 k3s[1256342]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5876fb]
Jul 24 15:18:19 k8s-libvirt-4650b9cf-32ea-42a1-82cf-f5f00d151f52 k3s[1256342]: goroutine 588 [running]:
Jul 24 15:18:19 k8s-libvirt-4650b9cf-32ea-42a1-82cf-f5f00d151f52 k3s[1256342]: math/big.(*Int).Cmp(0x0?, 0x5f8f2b9?)
Jul 24 15:18:19 k8s-libvirt-4650b9cf-32ea-42a1-82cf-f5f00d151f52 k3s[1256342]:         /usr/local/go/src/math/big/int.go:381 +0x1b
Jul 24 15:18:19 k8s-libvirt-4650b9cf-32ea-42a1-82cf-f5f00d151f52 k3s[1256342]: github.com/flannel-io/flannel/pkg/ip.IP6Net.Equal(...)
Jul 24 15:18:19 k8s-libvirt-4650b9cf-32ea-42a1-82cf-f5f00d151f52 k3s[1256342]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.25.2/pkg/ip/ip6net.go:192
Jul 24 15:18:19 k8s-libvirt-4650b9cf-32ea-42a1-82cf-f5f00d151f52 k3s[1256342]: github.com/flannel-io/flannel/pkg/trafficmngr/iptables.(*IPTablesManager).SetupAndEnsureMasqRules(0xc002ab9200, {0x6e98ec0?, 0xc001fcc230}, {0xa2a0000, 0x10}, {0x0, 0x0}, {0x0, 0x0}, {0xc0028006c0, ...}, ...)
Jul 24 15:18:19 k8s-libvirt-4650b9cf-32ea-42a1-82cf-f5f00d151f52 k3s[1256342]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.25.2/pkg/trafficmngr/iptables/iptables.go:131 +0x459
Jul 24 15:18:19 k8s-libvirt-4650b9cf-32ea-42a1-82cf-f5f00d151f52 k3s[1256342]: github.com/k3s-io/k3s/pkg/agent/flannel.flannel({0x6e98ec0?, 0xc001fcc230}, 0x77516d?, {0xc00193c300, 0x34}, {0xc0018eab70, 0x2d}, 0x1, 0xb)
Jul 24 15:18:19 k8s-libvirt-4650b9cf-32ea-42a1-82cf-f5f00d151f52 k3s[1256342]:         /go/src/github.com/k3s-io/k3s/pkg/agent/flannel/flannel.go:103 +0x4b3
Jul 24 15:18:19 k8s-libvirt-4650b9cf-32ea-42a1-82cf-f5f00d151f52 k3s[1256342]: github.com/k3s-io/k3s/pkg/agent/flannel.Run.func1()
Jul 24 15:18:19 k8s-libvirt-4650b9cf-32ea-42a1-82cf-f5f00d151f52 k3s[1256342]:         /go/src/github.com/k3s-io/k3s/pkg/agent/flannel/setup.go:78 +0x4c
Jul 24 15:18:19 k8s-libvirt-4650b9cf-32ea-42a1-82cf-f5f00d151f52 k3s[1256342]: created by github.com/k3s-io/k3s/pkg/agent/flannel.Run in goroutine 1
Jul 24 15:18:19 k8s-libvirt-4650b9cf-32ea-42a1-82cf-f5f00d151f52 k3s[1256342]:         /go/src/github.com/k3s-io/k3s/pkg/agent/flannel/setup.go:77 +0x15a
Jul 24 15:18:19 k8s-libvirt-4650b9cf-32ea-42a1-82cf-f5f00d151f52 systemd[1]: k3s-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 24 15:18:19 k8s-libvirt-4650b9cf-32ea-42a1-82cf-f5f00d151f52 systemd[1]: k3s-agent.service: Failed with result 'exit-code'.
```

**Steps To Reproduce:**

- Installed K3s: k3s is installed via cloud-init with the following command line:
```
curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_START="true" INSTALL_K3S_VERSION="v1.28.11+k3s1" INSTALL_K3S_EXEC="agent --server https://redact:6443 --token K1redac78ddc7ae9bf681redact0e3420bc3f0redactabf928e::redacbredactb0psdf" sh -s -
```
**Expected behavior:**
kubelet should start and operate normally

**Actual behavior:**
kubelet crashes with SIGSEGV

**Additional context / logs:**
This doesn't always happen so I am assuming it has something to do with specific iptables rules, due to the stack trace.  I'm willing to help provide more context as necessary if the problem isn't immediately obvious from the log (one can hope!)

**Comment by brandond** [comment] 2024-07-24 17:35
Duplicate of https://github.com/k3s-io/k3s/issues/10419

This is why we released [v1.28.11+k3s2](https://github.com/k3s-io/k3s/releases/tag/v1.28.11%2Bk3s2), I'm not sure why you're using +k3s1 instead?

**Closed by brandond** 2024-07-24 17:35 UTC

**Comment by PeterGrace** [comment] 2024-07-24 18:54
> Duplicate of #10419
> 
> This is why we released [v1.28.11+k3s2](https://github.com/k3s-io/k3s/releases/tag/v1.28.11%2Bk3s2), I'm not sure why you're using +k3s1 instead?

@brandond 
I upgraded my fleet yesterday based on this website which does not list k3s2: https://docs.k3s.io/release-notes/v1.28.X

I'll get everything flipped over to k3s2 now, thanks for letting me know!

**Comment by brandond** [comment] 2024-07-24 19:08
The release notes on the docs site are never as up to date as the GH release page, or the channel server. I would not recommend using the docs site as an authoritative list of available releases.

**Comment by PeterGrace** [comment] 2024-07-25 00:54
> The release notes on the docs site are never as up to date as the GH release page, or the channel server. I would not recommend using the docs site as an authoritative list of available releases.

@brandond 
If the docs aren't part of the release process I'd consider that a process deficiency, otherwise why have release note docs?  Not everyone wants to sift through fifty rcX releases in a github to find the stable tree they're on amongst the noise, especially if there's a website that identifies itself as the properly-collated release notes.  To be clear, I get what you're saying but am politely replying that it might be an improvement to ensure the release notes docs get updated when a release is cut.

Regardless, I have upgraded to k3s2 and the issue has not recurred -- thank you for setting me on the right track.
