### ISSUE TITLE
k3s-agent failing to install iptables rules

### ISSUE THREAD

**Issue by devilmonastery** [k3s-io/k3s#3022] opened 2021-03-04 21:30 UTC
**Environmental Info:**
K3s Version: 
$ k3s --version
k3s version v1.20.4+k3s1 (838a906a)
go version go1.15.8

Node(s) CPU architecture, OS, and Version: 
Linux droplet-nyc 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 master, 3 workers

**Describe the bug:**
k3s agent fails
log entry: 
F0304 21:25:08.492483 1603136 network_policy_controller.go:261] Failed to verify rule exists in KUBE-ROUTER-INPUT chain due to running [/usr/sbin/iptables -t filter -C KUBE-ROUTER-INPUT -p tcp -m comment --comment allow LOCAL TCP traffic to node ports - NTGHJFAJAOEPWU6M -m addrtype --dst-type LOCAL -m multiport --dports  -j RETURN --wait]: exit status 2: iptables v1.8.4 (legacy): invalid port/service `' specified

**Steps To Reproduce:**
I have a single k3s master, running on Ubuntu 20.04.
I have a worker running on a digital ocean droplet.
Standard install.

The worker crashloops with the above log message.

**Comment by brandond** [comment] 2021-03-04 21:34
Duplicate of #2996

See the comment at https://github.com/k3s-io/k3s/issues/2996#issuecomment-788352375

**Closed** 2021-03-04 21:34 UTC
