### ISSUE TITLE
RISC-V Support

### ISSUE THREAD

**Issue by IngwiePhoenix** [k3s-io/k3s#9489] opened 2024-02-14 09:47 UTC
**Is your feature request related to a problem? Please describe.**
I wanted to build k3s from source, but even just the `make download` step fatally fails - dapper has no idea what riscv64 is :)

**Describe the solution you'd like**
I would like to see an elongated version of the build system that allows an "egg to chicken" pipeline; since there are a lot of things not built for riscv64 yet, I need to build those first, before the normal build. Having this build in would be neat.

**Describe alternatives you've considered**
A list of what I need to get/build before even attempting a build.

**Additional context**
I have a VisionFive2 with a JH7110 RISC-V CPU and I have finally gotten Podman to work successfuly (conmon, crun). Now, I have a lot of other devices in my network (NanoPi R6s, Radxa RockPi 5B, RockPro64) and a remote VPS with 4 vCores of an ARM cpu (I bet it's an Ampere, but Hetzner didn't list it precisely, lol) and I would like to utilize all this compute to the max. That said, I still have to figure out how to properly define all the nodes and whatnot, but before I can worry about that, I need a running instance of k3s.

And, this is why I am here - looking to build k3s for RISC-V. ^^

Kind regards,
Ingwie

**Comment by IngwiePhoenix** [comment] 2024-02-14 10:30
I forgot, this is what I got when attempting a build:

```
root@riscboi ~/w/k3s ((v1.29.1+k3s2)) [1]# mkdir -p build/data && make download && make generate
Downloading dapper
./.dapper.tmp: 1: Syntax error: redirection unexpected
make: *** [Makefile:9: .dapper] Error 2
root@riscboi ~/w/k3s ((v1.29.1+k3s2)) [2]# head -n 1 .dapper.tmp
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message></Error>⏎
```

**Comment by brandond** [comment] 2024-02-14 17:38
Duplicate of https://github.com/k3s-io/k3s/issues/7151

**Closed by brandond** 2024-02-14 17:38 UTC
