### ISSUE TITLE
[Release-1.25] - Observed crash in filtercn address controller

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#8271] opened 2023-08-30 05:56 UTC
Backport fix for Observed crash in filtercn address controller

* #8267

**Comment by rancher-max** [comment] 2023-09-14 14:56
This is something that was noticed in v1.28 and was not very reproducible. Backported per our policy of "backport everything" and should not cause any issues. Since we could not reproduce this in v1.28 itself though, I'm just going to close this out.

**Closed by rancher-max** 2023-09-14 14:56 UTC
