### ISSUE TITLE
Metrics server parameters

### ISSUE THREAD

**Issue by adi90x** [k3s-io/k3s#4135] opened 2021-10-03 12:58 UTC
Hello, 

On basic installation of k3s, metric-server is using hostname to retrieve kubelet information.
However, hostname is potentially not always setup while internal ip is.
Why don"t we pass    :     
```
args:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP
 ```
to metric-server deployment to avoid that issue ?
Should be update here : https://github.com/k3s-io/k3s/blob/12e675e2cc3431d25630f63535f66ad4bb22ae85/manifests/metrics-server/metrics-server-deployment.yaml#L43
Can push a PR if other people seems it make sense.

**Comment by brandond** [comment] 2021-10-03 17:45
K3s ensures that hostnames are resolvable by injecting them into the coredns hosts file configmap whenever a node is added to the cluster.

**Comment by adi90x** [comment] 2021-10-03 18:08
Interesting, thank à lot ! I guess I have an issue with coredns then, as I
got multiple timeout issue in metric-server logs.

Le dim. 3 oct. 2021 à 19:45, Brad Davidson ***@***.***> a
écrit :

**Comment by brandond** [comment] 2021-10-05 21:45
What specific issue are you seeing?

**Comment by tcurdt** [comment] 2022-02-20 22:46
So - did anyone manage to provide a manifest so the metrics do bind to the desired interface yet?

**Comment by brandond** [comment] 2022-02-22 22:31
You can set it via `--kubelet-arg=address=0.0.0.0`, or if you prefer to create a KubeletConfiguration file, you can specify that via --kubelet-arg=config=/path/to/config`

https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/#customized-flags

**Comment by tcurdt** [comment] 2022-02-23 22:20
So I understand this correctly: The `--kubelet-arg=address=0.0.0.0` should override the address that is provided by the packaged manifest?

**Comment by brandond** [comment] 2022-02-23 23:45
The kubelet isn't configured via a packaged manifest. The control-plane components are deployed via static pod manifests, and the remaining components (CNI, ingress, etc) are deployed via helm chart manifests. Containerd and the kubelet are directly executed as subprocesses, using args set by the main rke2 process, in combination with any component-specific args set by the user.

**Comment by rbrtbnfgl** [comment] 2023-06-13 17:25
8472 should be the port used by Vxlan in Flannel.

**Comment by brandond** [comment] 2023-06-13 17:32
> Instead of just disabling the metrics server - is there also a way to pass in an address?

No. There is not any way to customize the configuration of the bundled manifests, other than traefik which can be customized via a HelmChartConfig. The other bundled components must be disabled and replaced by a customized manifest if you want to adjust their default configuration.

**Comment by caroline-suse-rancher** [comment] 2023-06-14 21:13
Closing due to age - please reopen using our bug issue template if a bug can be reproduced on a more current version of k3s.

**Closed by caroline-suse-rancher** 2023-06-14 21:13 UTC
