### ISSUE TITLE
Flooding Trace message after restart k3s-server

### ISSUE THREAD

**Issue by tibetsam** [k3s-io/k3s#8396] opened 2023-09-20 12:45 UTC
**Environmental Info:**
K3s Version: 
k3s -v
k3s version v1.25.5+k3s2 (de654222)
go version go1.19.4

Node(s) CPU architecture, OS, and Version: 
uname -a
Linux 8BMQ363 5.3.18-150300.59.118-default #1 SMP Tue Apr 4 15:18:05 UTC 2023 (d9b953c) x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
single node

**Describe the bug:**
After restart k3s-server service, I found plenty of Trace message in the logs, e.g.
All these trace message will be printed if list/watch operation took longer than 10s(https://github.com/kubernetes/kubernetes/blob/ef1aed8cd80a6955dd6ef9e59e8e2f378336cf4f/staging/src/k8s.io/client-go/tools/cache/reflector.go#L475)

from the logs, we think all those trace messages is triggered by api or client current throttling.

Sep 20 12:19:03 8BMQ363 k3s[11943]: I0920 12:19:03.571557   11943 request.go:682] Waited for **11.39126873s due to client-side throttling**, not priority and fairness, request: GET:https://10.10.202.1:6443/api/v1/namespaces/pc/secrets?fieldSelector=metadata.name%3Dpm-server-cert&limit=500&resourceVersion=0
Sep 20 12:19:03 8BMQ363 k3s[11943]: I0920 12:19:03.575973   11943 trace.go:205] Trace[975563300]: "Reflector ListAndWatch" name:object-"pc"/"pm-server-cert" (20-Sep-2023 12:18:52.180) (**total time: 11395ms**):
Sep 20 12:19:03 8BMQ363 k3s[11943]: Trace[975563300]: ---"Objects listed" error:<nil> 11395ms (12:19:03.575)
Sep 20 12:19:03 8BMQ363 k3s[11943]: Trace[975563300]: [11.395738375s] [11.395738375s] END
Sep 20 12:19:03 8BMQ363 k3s[11943]: I0920 12:19:03.777198   11943 trace.go:205] Trace[305223644]: "Reflector ListAndWatch" name:object-"pc"/"ah-client-secret" (20-Sep-2023 12:18:52.180) (total time: 11596ms):
Sep 20 12:19:03 8BMQ363 k3s[11943]: Trace[305223644]: ---"Objects listed" error:<nil> 11596ms (12:19:03.777)
Sep 20 12:19:03 8BMQ363 k3s[11943]: Trace[305223644]: [11.596913107s] [11.596913107s] END
Sep 20 12:19:03 8BMQ363 k3s[11943]: I0920 12:19:03.976149   11943 trace.go:205] Trace[246029786]: "Reflector ListAndWatch" name:object-"pc"/"lt-client-cert" (20-Sep-2023 12:18:52.180) (total time: 11795ms):
Sep 20 12:19:03 8BMQ363 k3s[11943]: Trace[246029786]: ---"Objects listed" error:<nil> 11795ms (12:19:03.976)
Sep 20 12:19:03 8BMQ363 k3s[11943]: Trace[246029786]: [11.795820059s] [11.795820059s] END
Sep 20 12:19:04 8BMQ363 k3s[11943]: I0920 12:19:04.175872   11943 trace.go:205] Trace[715048251]: "Reflector ListAndWatch" name:object-"pc"/"certm" (20-Sep-2023 12:18:52.180) (total time: 11995ms):
Sep 20 12:19:04 8BMQ363 k3s[11943]: Trace[715048251]: ---"Objects listed" error:<nil> 11995ms (12:19:04.175)
Sep 20 12:19:04 8BMQ363 k3s[11943]: Trace[715048251]: [11.995556766s] [11.995556766s] END
Sep 20 12:19:04 8BMQ363 k3s[11943]: I0920 12:19:04.377479   11943 trace.go:205] Trace[641719437]: "Reflector ListAndWatch" name:object-"envoy-cm-agent" (20-Sep-2023 12:18:52.180) (total time: 12197ms):
Sep 20 12:19:04 8BMQ363 k3s[11943]: Trace[641719437]: ---"Objects listed" error:<nil> 12197ms (12:19:04.377)
Sep 20 12:19:04 8BMQ363 k3s[11943]: Trace[641719437]: [12.197177615s] [12.197177615s] END
Sep 20 12:19:04 8BMQ363 k3s[11943]: I0920 12:19:04.575880   11943 trace.go:205] Trace[1561941294]: "Reflector ListAndWatch" name:object-"pc"/"log-level" (20-Sep-2023 12:18:52.180) (total time: 12395ms):
Sep 20 12:19:04 8BMQ363 k3s[11943]: Trace[1561941294]: ---"Objects listed" error:<nil> 12395ms (12:19:04.575)
Sep 20 12:19:04 8BMQ363 k3s[11943]: Trace[1561941294]: [12.395539435s] [12.395539435s] END
Sep 20 12:19:04 8BMQ363 k3s[11943]: I0920 12:19:04.776646   11943 trace.go:205] Trace[204984126]: "Reflector ListAndWatch" name:object-"pc"/"db-pg-metrics-cert" (20-Sep-2023 12:18:52.180) (total time: 12596ms):

**Steps To Reproduce:**
restart k3s
- Installed K3s: 

**Expected behavior:**
no trace message

**Actual behavior:**
flooding trace message

**Additional context / logs:**

**Comment by tibetsam** [comment] 2023-09-20 12:53
here is the api limit
curl -s ${purl}/api/v1/query?query=apiserver_flowcontrol_request_concurrency_limit | jq '.data.result[] | .metric.priority_level, .value[1]'
"catch-all"
"13"
"global-default"
"49"
"leader-election"
"25"
"node-high"
"98"
"system"
"74"
"workload-high"
"98"
"workload-low"
"245"

**Comment by brandond** [comment] 2023-09-20 15:39
As you noted, those messages come directly from the Kubernetes apiserver, not anything in K3s. Usually, these messages indicate a problem with datastore performance, most frequently caused by insufficient storage - although in this case it looks like whatever you've deployed to the "pc" namespace is throttling itself on the client side.

I am closing this, as I don't see that there is anything to be resolved here in K3s.

**Closed by brandond** 2023-09-20 15:39 UTC

**Comment by tibetsam** [comment] 2023-09-21 08:55
Hi @brandond , thanks for the reply. 

I don't think it's datastore performance issue, i collected some database stats which doesn't show me there is issue with DB.

k3s=# SELECT query, calls, stddev_exec_time, total_exec_time, rows, 100.0 * shared_blks_hit /
               nullif(shared_blks_hit + shared_blks_read, 0) AS hit_percent
          FROM pg_stat_statements ORDER BY total_exec_time DESC LIMIT 5;
-[ RECORD 1 ]----+---------------------------------------------------------------------------------------------------------------------------------------------------------------
query            | SELECT *                                                                                                                                                      +
                 |                 FROM (                                                                                                                                        +
                 |                         SELECT (                                                                                                                              +
                 |                 SELECT MAX(rkv.id) AS id                                                                                                                      +
                 |                 FROM kine AS rkv), (                                                                                                                          +
                 |                 SELECT MAX(crkv.prev_revision) AS prev_revision                                                                                               +
                 |                 FROM kine AS crkv                                                                                                                             +
                 |                 WHERE crkv.name = $3), kv.id AS theid, kv.name, kv.created, kv.deleted, kv.create_revision, kv.prev_revision, kv.lease, kv.value, kv.old_value+
                 |                         FROM kine AS kv                                                                                                                       +
                 |                         JOIN (                                                                                                                                +
                 |                                 SELECT MAX(mkv.id) AS id                                                                                                      +
                 |                                 FROM kine AS mkv                                                                                                              +
                 |                                 WHERE                                                                                                                         +
                 |                                         mkv.name LIKE $1                                                                                                      +
                 |                                                                                                                                                               +
                 |                                 GROUP BY mkv.name) AS maxkv                                                                                                   +
                 |                                 ON maxkv.id = kv.id                                                                                                           +
                 |                         WHERE                                                                                                                                 +
                 |                                 kv.deleted = $4 OR                                                                                                            +
                 |                                 $2                                                                                                                            +
                 |                 ) AS lkv                                                                                                                                      +
                 |                 ORDER BY lkv.theid ASC
calls            | 3779328
stddev_exec_time | 4.539818007749012
total_exec_time  | 6980104.635328119
rows             | 42168241
hit_percent      | 99.9998237342711583
-[ RECORD 2 ]----+---------------------------------------------------------------------------------------------------------------------------------------------------------------
query            | SELECT *                                                                                                                                                      +
                 |                 FROM (                                                                                                                                        +
                 |                         SELECT (                                                                                                                              +
                 |                 SELECT MAX(rkv.id) AS id                                                                                                                      +
                 |                 FROM kine AS rkv), (                                                                                                                          +
                 |                 SELECT MAX(crkv.prev_revision) AS prev_revision                                                                                               +
                 |                 FROM kine AS crkv                                                                                                                             +
                 |                 WHERE crkv.name = $3), kv.id AS theid, kv.name, kv.created, kv.deleted, kv.create_revision, kv.prev_revision, kv.lease, kv.value, kv.old_value+
                 |                         FROM kine AS kv                                                                                                                       +
                 |                         JOIN (                                                                                                                                +
                 |                                 SELECT MAX(mkv.id) AS id                                                                                                      +
                 |                                 FROM kine AS mkv                                                                                                              +
                 |                                 WHERE                                                                                                                         +
                 |                                         mkv.name LIKE $1                                                                                                      +
                 |                                                                                                                                                               +
                 |                                 GROUP BY mkv.name) AS maxkv                                                                                                   +
                 |                                 ON maxkv.id = kv.id                                                                                                           +
                 |                         WHERE                                                                                                                                 +
                 |                                 kv.deleted = $4 OR                                                                                                            +
                 |                                 $2                                                                                                                            +
                 |                 ) AS lkv                                                                                                                                      +
                 |                 ORDER BY lkv.theid ASC                                                                                                                        +
                 |                  LIMIT $5
calls            | 867509
stddev_exec_time | 3.4225948909810473
total_exec_time  | 6012942.836147967
rows             | 1019401
hit_percent      | 99.9998826243609976
-[ RECORD 3 ]----+---------------------------------------------------------------------------------------------------------------------------------------------------------------
query            | SELECT (                                                                                                                                                      +
                 |                 SELECT MAX(rkv.id) AS id                                                                                                                      +
                 |                 FROM kine AS rkv), (                                                                                                                          +
                 |                 SELECT MAX(crkv.prev_revision) AS prev_revision                                                                                               +
                 |                 FROM kine AS crkv                                                                                                                             +
                 |                 WHERE crkv.name = $3), kv.id AS theid, kv.name, kv.created, kv.deleted, kv.create_revision, kv.prev_revision, kv.lease, kv.value, kv.old_value+
                 |                         FROM kine AS kv                                                                                                                       +
                 |                         WHERE                                                                                                                                 +
                 |                                 kv.name LIKE $1 AND                                                                                                           +
                 |                                 kv.id > $2                                                                                                                    +
                 |                         ORDER BY kv.id ASC
calls            | 520933
stddev_exec_time | 2.225200467457117
total_exec_time  | 1013428.2282620143
rows             | 11362
hit_percent      | 99.9993915512801570
-[ RECORD 4 ]----+---------------------------------------------------------------------------------------------------------------------------------------------------------------
query            | SELECT (                                                                                                                                                      +
                 |                 SELECT MAX(rkv.id) AS id                                                                                                                      +
                 |                 FROM kine AS rkv), COUNT(c.theid)                                                                                                             +
                 |                         FROM (                                                                                                                                +
                 |                                                                                                                                                               +
                 |                 SELECT *                                                                                                                                      +
                 |                 FROM (                                                                                                                                        +
                 |                         SELECT (                                                                                                                              +
                 |                 SELECT MAX(rkv.id) AS id                                                                                                                      +
                 |                 FROM kine AS rkv), (                                                                                                                          +
                 |                 SELECT MAX(crkv.prev_revision) AS prev_revision                                                                                               +
                 |                 FROM kine AS crkv                                                                                                                             +
                 |                 WHERE crkv.name = $3), kv.id AS theid, kv.name, kv.created, kv.deleted, kv.create_revision, kv.prev_revision, kv.lease, kv.value, kv.old_value+
                 |                         FROM kine AS kv                                                                                                                       +
                 |                         JOIN (                                                                                                                                +
                 |                                 SELECT MAX(mkv.id) AS id                                                                                                      +
                 |                                 FROM kine AS mkv                                                                                                              +
                 |                                 WHERE                                                                                                                         +
                 |                                         mkv.name LIKE $1                                                                                                      +
                 |                                                                                                                                                               +
                 |                                 GROUP BY mkv.name) AS maxkv                                                                                                   +
                 |                                 ON maxkv.id = kv.id                                                                                                           +
                 |                         WHERE                                                                                                                                 +
                 |                                 kv.deleted = $4 OR                                                                                                            +
                 |                                 $2                                                                                                                            +
                 |                 ) AS lkv                                                                                                                                      +
                 |                 ORDER BY lkv.theid ASC                                                                                                                        +
                 |                                                                                                                                                               +
                 |                         ) c
calls            | 165810
stddev_exec_time | 2.369614161833797
total_exec_time  | 750092.9169430122
rows             | 165810
hit_percent      | 99.9997586923787518
-[ RECORD 5 ]----+---------------------------------------------------------------------------------------------------------------------------------------------------------------
query            | SELECT *                                                                                                                                                      +
                 |                 FROM (                                                                                                                                        +
                 |                         SELECT (                                                                                                                              +
                 |                 SELECT MAX(rkv.id) AS id                                                                                                                      +
                 |                 FROM kine AS rkv), (                                                                                                                          +
                 |                 SELECT MAX(crkv.prev_revision) AS prev_revision                                                                                               +
                 |                 FROM kine AS crkv                                                                                                                             +
                 |                 WHERE crkv.name = $4), kv.id AS theid, kv.name, kv.created, kv.deleted, kv.create_revision, kv.prev_revision, kv.lease, kv.value, kv.old_value+
                 |                         FROM kine AS kv                                                                                                                       +
                 |                         JOIN (                                                                                                                                +
                 |                                 SELECT MAX(mkv.id) AS id                                                                                                      +
                 |                                 FROM kine AS mkv                                                                                                              +
                 |                                 WHERE                                                                                                                         +
                 |                                         mkv.name LIKE $1                                                                                                      +
                 |                                         AND mkv.id <= $2                                                                                                      +
                 |                                 GROUP BY mkv.name) AS maxkv                                                                                                   +
                 |                                 ON maxkv.id = kv.id                                                                                                           +
                 |                         WHERE                                                                                                                                 +
                 |                                 kv.deleted = $5 OR                                                                                                            +
                 |                                 $3                                                                                                                            +
                 |                 ) AS lkv                                                                                                                                      +
                 |                 ORDER BY lkv.theid ASC                                                                                                                        +
                 |                  LIMIT $6
calls            | 67724
stddev_exec_time | 1.4577535929033527
total_exec_time  | 259784.1310999979
rows             | 0
hit_percent      | 100.0000000000000000

Actually i did a tcp trace during k3s restart, i didn't see anything was connection to api-server rather than k3s itself, that's i think it's k3s issue. Beside tcptrace, i also noticed that while secret.go complains about the error, we saw trace message from request.go
here is the tcptrace:
8BMQ363:/usr/share/bcc/tools # ./tcpconnect -P 6443 -t & systemctl restart k3s-server
[1] 8674
Tracing connect ... Hit Ctrl-C to end
TIME(s)  PID    COMM         IP SADDR            DADDR            DPORT
0.000    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
0.001    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
0.003    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
0.004    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
0.004    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
0.004    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
0.006    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
0.006    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
0.008    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
0.567    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
0.607    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
0.607    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
0.607    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
0.608    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
1.009    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
1.009    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
1.012    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
1.799    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
1.799    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
2.007    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
2.009    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
2.009    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
2.010    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
2.010    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
2.011    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
2.018    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
8BMQ363:/usr/share/bcc/tools # 5.004    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
5.006    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
5.008    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
5.011    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
5.041    9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
16.320   9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
53.420   9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
53.421   9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
89.306   9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
89.638   9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
89.883   9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
90.103   9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
90.366   9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
116.383  9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
116.525  9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
116.666  9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
116.791  9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
116.921  9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
117.071  9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
139.950  9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
140.090  9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
140.226  9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
140.356  9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
140.490  9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
140.625  9224   k3s-server   4  10.10.202.1      10.10.202.1      6443
here are the snippet logs:
Sep 21 08:42:36 8BMQ363 k3s[3564]: E0921 08:42:36.347355    3564 secret.go:192] Couldn't get secret pc/license-getter-client-cert: failed to sync secret cache: timed out waiting for the condition
Sep 21 08:42:37 8BMQ363 k3s[3564]: I0921 08:42:37.529668    3564 request.go:682] Waited for 3.737726915s due to client-side throttling, not priority and fairness, request: GET:https://10.10.202.1:6443/api/v1/namespaces/pc/secrets?fieldSelector=metadata.name%3Dlicense-getter-client-cert&resourceVersion=2420880

**Comment by brandond** [comment] 2023-09-21 16:59
This does not look to me like a request that K3s would make:
`request: GET:https://10.10.202.1:6443/api/v1/namespaces/pc/secrets?fieldSelector=metadata.name%3Dlicense-getter-client-cert&resourceVersion=2420880`

Similarly, the other errors all seem to relate to envoy and/or the `pc` namespace. What have you deployed to that namespace? Do you still see these errors on a similar configuration of k3s that does not have that application deployed?

**Comment by tibetsam** [comment] 2023-09-22 14:52
thanks, i can give it try without pc namespace, but i don't think the result is comparable, bcz we have around 100 pods in that pc namespace, and without them i don't think the k3s will under pressure.

And do you know what is possible reason i don't see other process except k3s with this tracing command?
./tcpconnect -P 6443 -t & systemctl restart k3s-server

last question, where do you see this problem might related to envoy? dose envoy use go-client rest?

**Comment by brandond** [comment] 2023-09-22 15:42
I'm just working off of the section of logs you provided.

**Comment by tibetsam** [comment] 2023-09-26 08:36
@brandond thanks a lot for your support, fight for the user!!!

I don't see those message anymore after upgraded to 1.27.5+
k3s -v
k3s version v1.27.5+k3s1 (8d074ecb)
go version go1.20.7

**Comment by brandond** [comment] 2023-09-26 16:52
That's interesting. I wouldn't have expected it to make a significant difference. Do you see any changes in the responsiveness of the applications you're running in the cluster?

**Comment by tibetsam** [comment] 2023-09-27 07:47
Indeed, i've no idea what happened in the back. whole restart process is much faster than before. btw, maybe do you know how to debug all requests received by API server?

 ~# systemctl status k3s-server | grep since
     Active: active (running) since Wed 2023-09-27 07:40:47 UTC; 3min 11s ago
 ~# journalctl --since "2023-09-27 07:40:47" | grep Trace
 ~# journalctl --since "2023-09-27 07:40:47" | grep secret.go

**Comment by tibetsam** [comment] 2023-09-27 07:47
or any command i can run and compare these two versions?

**Comment by tibetsam** [comment] 2023-09-27 08:17
i saw some new message from the logs:
Sep 27 08:15:43 8BMQ363 k3s[7286]: time="2023-09-27T08:15:43Z" level=info msg="COMPACT compactRev=310256 targetCompactRev=311256 currentRev=313245"
Sep 27 08:15:44 8BMQ363 k3s[7286]: time="2023-09-27T08:15:44Z" level=info msg="COMPACT deleted 1000 rows from 1000 revisions in 26.447937ms - compacted to 311256/313245"
Sep 27 08:15:44 8BMQ363 k3s[7286]: time="2023-09-27T08:15:44Z" level=info msg="COMPACT compactRev=311256 targetCompactRev=311729 currentRev=313245"
Sep 27 08:15:44 8BMQ363 k3s[7286]: time="2023-09-27T08:15:44Z" level=info msg="COMPACT deleted 473 rows from 473 revisions in 18.26506ms - compacted to 311729/313245"

**Comment by brandond** [comment] 2023-09-27 08:20
We increased the verbosity of compaction details to info a while back.

If you want to log all requests to the apiserver, the best way to do that is to enable audit logging. That is covered in the upstream docs.

**Comment by tibetsam** [comment] 2023-09-27 09:47
Thanks a lot, i will give it a try to audit all api calls

the difference between v1.27 and v1.25 restart logs is basically 
secret.go:192] Couldn't get secret pc/vpn-gateway-forwarder-mbkf-client-secret: failed to sync secret cache: timed out waiting for the condition
