### ISSUE TITLE
Single K3s server with embedded ETCD - Goes to NotReady State

### ISSUE THREAD

**Issue by MohamedShaj** [k3s-io/k3s#7343] opened 2023-04-23 14:14 UTC
**Environmental Info:**
K3s Version: 'v1.25.4+k3s1'

Node(s) CPU architecture, OS, and Version: 
Linux Demo-Box 4.15.0-1113-azure #126~16.04.1-Ubuntu SMP Tue Apr 13 16:55:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server ( controlplane, etcd, master) 32vCPU and 128Mem

**Describe the bug:**

 I was creating single node k3s, Node is fine but, it was going to the NotReady state, I can see some embedded ETCD logs and k3s are stopping and starting automatically and even though NOT READY state is there throughout ...

**Steps To Reproduce:**

- Installed K3s: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='server --cluster-init --tls-san 1.1.1.1 --data-dir /application-volume/k3s --write-kubeconfig-mode 644 --etcd-arg=--data-dir=/var/lib/etcd --etcd-arg=--debug --disable traefik' INSTALL_K3S_VERSION='v1.25.4+k3s1' sh -

**Expected behavior:**
The node should be up and running without NotReady state

**Actual behavior:**

The node goes to NotReady state and I have attached the respective logs in attachment

 Once the server is rebooted the issue is fixed.

[k3s_bug.log](https://github.com/k3s-io/k3s/files/11303931/k3s_bug.log)

Why I have created in cluster mode means, in coming days may be in a month or 3 month , we will add additional 2 nodes and it will be form a 3 node cluster (which may be suitable for single node) 

I have a doubt due to embedded ETCD with single k3s server it making any issue ? ( but it is also a odd number (1)  without HA)

**Comment by brandond** [comment] 2023-04-24 17:41
Your iscsis storage system appears to be disconnecting and reconnecting the underlying disks that K3s is running on. The storage timeouts are causing the etcd datastore to time out requests and the node in turn fails readiness checks.

```
Apr 22 09:00:40 ip-172-31-22-19 k3s[1384]: Trace[2030830871]: [1.252529094s] [1.252529094s] END
Apr 22 09:00:42 ip-172-31-22-19 k3s[1384]: {"level":"warn","ts":"2023-04-22T09:00:40.928Z","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"298.467477ms","expected-duration":"100ms","prefix":"","request":"header:<ID:12264295156355890680 username:\"etcd-client\" auth_revision:1 > txn:<compare:<target:MOD key:\"/registry/leases/kube-system/kube-scheduler\" mod_revision:4207222 > success:<request_put:<key:\"/registry/leases/kube-system/kube-scheduler\" value_size:421 >> failure:<request_range:<key:\"/registry/leases/kube-system/kube-scheduler\" > >>","response":"size:20"}`

Apr 22 09:01:48 ip-172-31-22-19 iscsid[55114]: iscsid: Kernel reported iSCSI connection 55:0 error (1022 - ISCSI_ERR_NOP_TIMEDOUT: A NOP has timed out) state (3)
Apr 22 09:01:48 ip-172-31-22-19 iscsid[55114]: iscsid: Kernel reported iSCSI connection 44:0 error (1022 - ISCSI_ERR_NOP_TIMEDOUT: A NOP has timed out) state (3)
Apr 22 09:01:48 ip-172-31-22-19 iscsid[55114]: iscsid: connection55:0 is operational after recovery (1 attempts)
Apr 22 09:01:48 ip-172-31-22-19 iscsid[55114]: iscsid: connection44:0 is operational after recovery (1 attempts)
Apr 22 09:01:49 ip-172-31-22-19 k3s[1384]: E0422 09:00:50.218387    1384 leaderelection.go:367] Failed to update lock: Put "https://127.0.0.1:6444/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-scheduler?timeout=5s": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Apr 22 09:01:50 ip-172-31-22-19 k3s[1384]: I0422 09:01:17.453246    1384 trace.go:205] Trace[1276542916]: "Calculate volume metrics of kube-api-access-brc6r for pod default/dask-scheduler-68b7f5f76b-8p2xs" (22-Apr-2023 09:01:05.128) (total time: 2014ms):
Apr 22 09:01:50 ip-172-31-22-19 k3s[1384]: Trace[1276542916]: [2.014776236s] [2.014776236s] END
Apr 22 09:01:58 ip-172-31-22-19 k3s[1384]: I0422 09:01:24.955692    1384 trace.go:205] Trace[456216009]: "Calculate volume metrics of host-proc for pod longhorn-system/share-manager-pvc-1742a598-8689-4665-a036-22c5d4705d39" (22-Apr-2023 09:01:05.967) (total time: 2597ms):
Apr 22 09:01:58 ip-172-31-22-19 k3s[1384]: Trace[456216009]: [2.597932594s] [2.597932594s] END
Apr 22 09:02:20 ip-172-31-22-19 systemd[1]: Started Process Core Dump (PID 1816735/UID 0).
Apr 22 09:02:25 ip-172-31-22-19 kernel: sd 11:0:0:1: Power-on or device reset occurred
Apr 22 09:02:25 ip-172-31-22-19 systemd[1]: Started Process Core Dump (PID 1816736/UID 0).
Apr 22 09:02:28 ip-172-31-22-19 kernel: sd 0:0:0:1: Power-on or device reset occurred
Apr 22 09:02:29 ip-172-31-22-19 k3s[1384]: I0422 09:01:24.582921    1384 trace.go:205] Trace[389073660]: "Calculate volume metrics of kube-api-access-qhfdd for pod longhorn-system/share-manager-pvc-d95dce67-a883-4d5a-a9ba-12d0894c6ce7" (22-Apr-2023 09:01:06.000) (total time: 2422ms):
Apr 22 09:02:29 ip-172-31-22-19 k3s[1384]: Trace[389073660]: [2.422140855s] [2.422140855s] END
```

**Comment by brandond** [comment] 2023-04-24 18:33
Looking at this a little further, you didn't mention this but it appears that you are also running longhorn on this node, is that correct? Are you putting both Longhorn and k3s on the same physical disks? If so I suspect that the disks may not have sufficient IO throughput to support both products. Note that etcd calls `fsync` to flush all pending IO on the disk every time there is a write to the datastore. This includes any IO queued up for longhorn backing disk IO. Assuming that the iscsi errors are from LH and not some other storage system, the logs would further reinforce my guess that longhorn and etcd are contending for disk IO.

**Comment by MohamedShaj** [comment] 2023-05-25 17:07
> Looking at this a little further, you didn't mention this but it appears that you are also running longhorn on this node, is that correct? Are you putting both Longhorn and k3s on the same physical disks? If so I suspect that the disks may not have sufficient IO throughput to support both products. Note that etcd calls `fsync` to flush all pending IO on the disk (not the partition, but the physical disk) every time there is a write to the datastore. This includes any IO queued up for longhorn backing disk IO. Assuming that the iscsi errors are from LH and not some other storage system, the logs would further reinforce my guess that longhorn and etcd are contending for disk IO.

Before it was in the same physical disk, But now we made separate disk, but now the issue is different I believe,

please find the below logs from kernel and k3s,

`May 24 15:18:18 Demo-Box kernel: [1670655.742173] cni0: port 52(vethfa98589d) entered disabled state
May 24 15:18:18 Demo-Box kernel: [1670655.753874] device vethfa98589d left promiscuous mode
May 24 15:18:18 Demo-Box kernel: [1670655.753884] cni0: port 52(vethfa98589d) entered disabled state
May 24 15:18:21 Demo-Box kernel: [1670658.647720] IPv6: ADDRCONF(NETDEV_UP): veth6e07cfbf: link is not ready
May 24 15:18:21 Demo-Box kernel: [1670658.648223] cni0: port 52(veth6e07cfbf) entered blocking state
May 24 15:18:21 Demo-Box kernel: [1670658.648226] cni0: port 52(veth6e07cfbf) entered disabled state
May 24 15:18:21 Demo-Box kernel: [1670658.648402] device veth6e07cfbf entered promiscuous mode
May 24 15:18:21 Demo-Box kernel: [1670658.653907] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
May 24 15:18:21 Demo-Box kernel: [1670658.653935] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
May 24 15:18:21 Demo-Box kernel: [1670658.653997] IPv6: ADDRCONF(NETDEV_CHANGE): veth6e07cfbf: link becomes ready
May 24 15:18:21 Demo-Box kernel: [1670658.654068] cni0: port 52(veth6e07cfbf) entered blocking state
May 24 15:18:21 Demo-Box kernel: [1670658.654070] cni0: port 52(veth6e07cfbf) entered forwarding state
May 24 15:21:19 Demo-Box kernel: [1670836.700175] nfs: server 10.43.252.141 not responding, still trying
May 24 15:21:35 Demo-Box kernel: [1670852.252148] nfs: server 10.43.65.88 not responding, still trying
May 24 15:21:39 Demo-Box kernel: [1670856.860416] nfs: server 10.43.252.141 not responding, still trying
May 24 15:21:55 Demo-Box kernel: [1670872.284298] nfs: server 10.43.174.157 not responding, timed out
May 24 15:21:55 Demo-Box kernel: [1670872.408142] nfs: server 10.43.65.88 not responding, timed out
May 24 15:21:56 Demo-Box kernel: [1670872.988271] nfs: server 10.43.252.141 not responding, timed out
May 24 15:22:03 Demo-Box kernel: [1670880.476079] nfs: server 10.43.65.88 not responding, still trying
May 24 15:22:56 Demo-Box kernel: [1670933.724423] nfs: server 10.43.174.157 not responding, still trying
May 24 15:23:49 Demo-Box kernel: [1670986.717866] INFO: task influxd:27866 blocked for more than 120 seconds.
`
k3s logs -> [error.log](https://github.com/k3s-io/k3s/files/11567488/error.log)

We have reached the Longhorn community for the NFS server-related error and they clearly said "The stuck NFS client/server cases are sometimes caused by the operating system itself, and the restart of the worker node might be needed" they are working on to see why that happens ( I created a separate issue in Longhorn for that)

But they clearly mentioned due to Longhorn the ks "NodeNotReady" has not occurred, there may be some other reasons,

I would suspect there may be any issue with CNI (flannel), not sure just guessing so, 

can you help me on this !!!

**Comment by brandond** [comment] 2023-05-26 02:26
I'm guessing these NFS errors are coming from longhorn RWX volumes? I still don't see anything other than high latency warnings.

**Comment by MohamedShaj** [comment] 2023-05-26 02:28
> I'm guessing these NFS errors are coming from longhorn RWX volumes? I still don't see anything other than high latency warnings.

Yes correct and that can be fixed by upgrading the longhorn to 1.4.2 version

But not sure why k3s server went to NodeNotReady state!

**Comment by MohamedShaj** [comment] 2023-05-26 16:29
`E0524 15:18:23.351993    2560 proxier.go:863] "Failed to ensure chain exists" err="error creating chain \"KUBE-EXTERNAL-SERVICES\": executable file not found in $PATH: " table=filter chain=KUBE-EXTERNAL-SERVICES
May 24 15:18:23 Demo-Box k3s[2560]: I0524 15:18:23.352047    2560 proxier.go:855] "Sync failed" retryingTime="30s"
May 24 15:18:23 Demo-Box k3s[2560]: W0524 15:18:23.352271    2560 iptables.go:575] Could not set up iptables canary mangle/KUBE-PROXY-CANARY: error creating chain "KUBE-PROXY-CANARY": executable file not found in $PATH:
May 24 15:18:23 Demo-Box k3s[2560]: E0524 15:18:23.378432    2560 remote_runtime.go:734] "ExecSync cmd from runtime service failed" err="rpc error: code = Unknown desc = failed to exec in container: failed to start exec \"f83fe78fa642e96c16473feff3fa46a8bb4faab470c9d472accd1a94aa4b38bd\": OCI runtime exec failed: fork/exec /application-volume/k3s/data/7c994f47fd344e1637da337b92c51433c255b387d207b30b3e0262779457afe4/bin/runc: resource temporarily unavailable: unknown" containerID="19ec2628d7d8b7425919ac20f535586af0f9e6ca6a12c85f8b8e5d82da837e59" cmd=[cat /var/run/ganesha.pid]
May 24 15:18:23 Demo-Box k3s[2560]: E0524 15:18:23.384448    2560 remote_runtime.go:734] "ExecSync cmd from runtime service failed" err="rpc error: code = Unknown desc = failed to exec in container: failed to start exec \"fba415d4621faa2abcaec091d48aa0b9f5094207830393a1922c5a4898f203d4\": OCI runtime exec failed: fork/exec /application-volume/k3s/data/7c994f47fd344e1637da337b92c51433c255b387d207b30b3e0262779457afe4/bin/runc: resource temporarily unavailable: unknown" containerID="19ec2628d7d8b7425919ac20f535586af0f9e6ca6a12c85f8b8e5d82da837e59" cmd=[cat /var/run/ganesha.pid]
May 24 15:18:23 Demo-Box k3s[2560]: E0524 15:18:23.391495    2560 remote_runtime.go:734] "ExecSync cmd from runtime service failed" err="rpc error: code = Unknown desc = failed to exec in container: failed to start exec \"b4c1b63beaccd5007414e0568b3c37452c44c568dd7dc919850c873b1b671273\": OCI runtime exec failed: fork/exec /application-volume/k3s/data/7c994f47fd344e1637da337b92c51433c255b387d207b30b3e0262779457afe4/bin/runc: resource temporarily unavailable: unknown" containerID="19ec2628d7d8b7425919ac20f535586af0f9e6ca6a12c85f8b8e5d82da837e59" cmd=[cat /var/run/ganesha.pid]
May 24 15:18:23 Demo-Box k3s[2560]: E0524 15:18:23.410510    2560 remote_runtime.go:734] "ExecSync cmd from runtime service failed" err="rpc error: code = Unknown desc = failed to exec in container: failed to start exec \"793e744d261d5147dc7ebe0b19be11d76a7964b592e168a056e723e7dfe31b2f\": OCI runtime exec failed: runc did not terminate successfully: exit status 2: unknown" containerID="4a6cd6c5f6fd9ea09e1d0c6856279e245a84aee277932caae9b6a0e084b5a728" cmd=[/opt/stunnel/stunnel_healthcheck.sh 2181]
May 24 15:18:23 Demo-Box k3s[2560]: E0524 15:18:23.414776    2560 remote_runtime.go:734] "ExecSync cmd from runtime service failed" err="rpc error: code = Unknown desc = failed to exec in container: failed to start exec \"89945db90c8a61d8e48238e592c04f908d870e0a08bf3cfb7c98e70c6a39aa43\": OCI runtime exec failed: exec failed: unable to start container process: error executing setns process: exit status 1: unknown" containerID="f1fc362fbd11445b27fe6e1673b6983f24cedf5b8b374b92923aeeaeb59d8cd1" cmd=[/opt/kafka/kafka_liveness.sh]
May 24 15:18:23 Demo-Box k3s[2560]: E0524 15:18:23.429275    2560 remote_runtime.go:734] "ExecSync cmd from runtime service failed" err="rpc error: code = Unknown desc = failed to exec in container: failed to start exec \"d120a6b1b210c98c2962e6aa6b178bb105c66103cbf4366b8912333e58705090\": OCI runtime exec failed: exec failed: unable to start container process: error starting setns process: fork/exec /proc/self/exe: resource temporarily unavailable: unknown" containerID="4a6cd6c5f6fd9ea09e1d0c6856279e245a84aee277932caae9b6a0e084b5a728" cmd=[/opt/stunnel/stunnel_healthcheck.sh 2181]
May 24 15:18:23 Demo-Box k3s[2560]: E0524 15:18:23.442410    2560 remote_runtime.go:734] "ExecSync cmd from runtime service failed" err="rpc error: code = Unknown desc = failed to exec in container: failed to start exec \"8c9fcc61621450e76e828d9da1b06ee474f749cd3667c7ff016985b689cb1413\": OCI runtime exec failed: exec failed: unable to start container process: error starting setns process: fork/exec /proc/self/exe: resource temporarily unavailable: unknown" containerID="4a6cd6c5f6fd9ea09e1d0c6856279e245a84aee277932caae9b6a0e084b5a728" cmd=[/opt/stunnel/stunnel_healthcheck.sh 2181]
May 24 15:18:23 Demo-Box k3s[2560]: F0524 15:18:23.482320    2560 network_policy_controller.go:381] failed to run iptables command to create KUBE-ROUTER-INPUT chain due to fork/exec /sbin/iptables: resource temporarily unavailable
May 24 15:18:23 Demo-Box k3s[2560]: panic: F0524 15:18:23.482320    2560 network_policy_controller.go:381] failed to run iptables command to create KUBE-ROUTER-INPUT chain due to fork/exec /sbin/iptables: resource temporarily unavailable
May 24 15:18:23 Demo-Box k3s[2560]: goroutine 14259 [running]:
May 24 15:18:23 Demo-Box k3s[2560]: k8s.io/klog/v2.(*loggingT).output(0x810cec0, 0x3, 0x0, 0xc0251422a0, 0x1, {0x66391df?, 0x2?}, 0xc000911c00?, 0x0)
May 24 15:18:23 Demo-Box k3s[2560]: #011/go/pkg/mod/github.com/k3s-io/klog/v2@v2.60.1-k3s1/klog.go:820 +0x694
May 24 15:18:23 Demo-Box k3s[2560]: k8s.io/klog/v2.(*loggingT).printfDepth(0x810cec0, 0x11?, 0x0, {0x0, 0x0}, 0xc01911f480?, {0x4e2507b, 0x3b}, {0xc018bb05c0, 0x2, ...})
May 24 15:18:23 Demo-Box k3s[2560]: #011/go/pkg/mod/github.com/k3s-io/klog/v2@v2.60.1-k3s1/klog.go:630 +0x1f2
May 24 15:18:23 Demo-Box k3s[2560]: k8s.io/klog/v2.(*loggingT).printf(...)
May 24 15:18:23 Demo-Box k3s[2560]: #011/go/pkg/mod/github.com/k3s-io/klog/v2@v2.60.1-k3s1/klog.go:612
May 24 15:18:23 Demo-Box k3s[2560]: k8s.io/klog/v2.Fatalf(...)
May 24 15:18:23 Demo-Box k3s[2560]: #011/go/pkg/mod/github.com/k3s-io/klog/v2@v2.60.1-k3s1/klog.go:1496
May 24 15:18:23 Demo-Box k3s[2560]: github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).ensureTopLevelChains(0xc004b69900)
May 24 15:18:23 Demo-Box k3s[2560]: #011/go/pkg/mod/github.com/k3s-io/kube-router@v1.5.2-0.20221026101626-e01045262706/pkg/controllers/netpol/network_policy_controller.go:381 +0x15a5
May 24 15:18:23 Demo-Box k3s[2560]: github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).fullPolicySync(0xc004b69900)
May 24 15:18:23 Demo-Box k3s[2560]: #011/go/pkg/mod/github.com/k3s-io/kube-router@v1.5.2-0.20221026101626-e01045262706/pkg/controllers/netpol/network_policy_controller.go:243 +0x386
May 24 15:18:23 Demo-Box k3s[2560]: github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).Run.func1(0xc010066de0, 0xc0011d6000, 0x0?)
May 24 15:18:23 Demo-Box k3s[2560]: #011/go/pkg/mod/github.com/k3s-io/kube-router@v1.5.2-0.20221026101626-e01045262706/pkg/controllers/netpol/network_policy_controller.go:193 +0x88
May 24 15:18:23 Demo-Box k3s[2560]: created by github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).Run
May 24 15:18:23 Demo-Box k3s[2560]: #011/go/pkg/mod/github.com/k3s-io/kube-router@v1.5.2-0.20221026101626-e01045262706/pkg/controllers/netpol/network_policy_controller.go:177 +0x2d0
May 24 15:18:23 Demo-Box systemd[1]: k3s.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 24 15:18:23 Demo-Box systemd[1]: k3s.service: Unit entered failed state.
May 24 15:18:23 Demo-Box systemd[1]: k3s.service: Failed with result 'exit-code'.
May 24 15:18:28 Demo-Box systemd[1]: k3s.service: Service hold-off time over, scheduling restart.
May 24 15:18:28 Demo-Box systemd[1]: Stopped Lightweight Kubernetes.
`

these logs already attacheds above as error logs,

this shows some n/w policy controller error logs, we are using flannel as the CNI plugin, any changes of issue with that ?

**Comment by MohamedShaj** [comment] 2023-05-27 12:05
Hi brandond,

Thanks for the analysis, but I can see the `data/bin/runc` folders in the server

![image](https://github.com/k3s-io/k3s/assets/102578451/3dae3169-bd51-408d-a399-a07be09694c5)

And we have not upgraded the k3s server since it started too.

The error is `resource temporarily unavailable: unknown` may be the container is unable to reach the bin location and once we have rebooted the server, that is fine...

so again,  we need to know why the k3s server went NodeNotReady state ?

**Comment by brandond** [comment] 2023-05-30 18:44
I don't know what is going on with your nodes that causes it to give a `resource temporarily unavailable` error when trying to exec runc. Perhaps you have some sysctls or limits that are set too low on your node? You might check the max `nproc` in `/etc/security/limits*`.

**Comment by MohamedShaj** [comment] 2023-05-31 04:04
`# /etc/security/limits.conf
#
#Each line describes a limit for a user in the form:
#
#<domain>        <type>  <item>  <value>
#
#Where:
#<domain> can be:
#        - a user name
#        - a group name, with @group syntax
#        - the wildcard *, for default entry
#        - the wildcard %, can be also used with %group syntax,
#                 for maxlogin limit
#        - NOTE: group and wildcard limits are not applied to root.
#          To apply a limit to the root user, <domain> must be
#          the literal username root.
#
#<type> can have the two values:
#        - "soft" for enforcing the soft limits
#        - "hard" for enforcing hard limits
#
#<item> can be one of the following:
#        - core - limits the core file size (KB)
#        - data - max data size (KB)
#        - fsize - maximum filesize (KB)
#        - memlock - max locked-in-memory address space (KB)
#        - nofile - max number of open files
#        - rss - max resident set size (KB)
#        - stack - max stack size (KB)
#        - cpu - max CPU time (MIN)
#        - nproc - max number of processes
#        - as - address space limit (KB)
#        - maxlogins - max number of logins for this user
#        - maxsyslogins - max number of logins on the system
#        - priority - the priority to run user process with
#        - locks - max number of file locks the user can hold
#        - sigpending - max number of pending signals
#        - msgqueue - max memory used by POSIX message queues (bytes)
#        - nice - max nice priority allowed to raise to values: [-20, 19]
#        - rtprio - max realtime priority
#        - chroot - change root to directory (Debian-specific)
#
#<domain>      <type>  <item>         <value>
#

#*               soft    core            0
#root            hard    core            100000
#*               hard    rss             10000
#@student        hard    nproc           20
#@faculty        soft    nproc           20
#@faculty        hard    nproc           50
#ftp             hard    nproc           0
#ftp             -       chroot          /ftp
#@student        -       maxlogins       4

# End of file`

This is limits.conf file in the machine and every value in `#`, So I don't think we are passing any customized values and going only default values.

The server OS is : "Ubuntu 16.04.6 LTS"

**Comment by brandond** [comment] 2023-05-31 05:11
I don't believe we support 16.04 for either longhorn or k3s. I know we don't test k3s on it, as 16.04 has been end of support since 2021. Are you able to reproduce this on a newer distro? 20.04 or better yet 22.04?

**Comment by MohamedShaj** [comment] 2023-05-31 07:43
Okay sure, Thank you for the info.

**Comment by brandond** [comment] 2023-08-03 00:04
Closing; please reopen if this still occurs on more recent OS releases.

**Closed by brandond** 2023-08-03 00:04 UTC
