### ISSUE TITLE
Installation script is failing 

### ISSUE THREAD

**Issue by pmantica11** [k3s-io/k3s#10728] opened 2024-08-19 22:45 UTC
```
curl -sfL https://get.k3s.io | sh -
[INFO]  Finding release for channel stable
[INFO]  Using stable as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/stable/sha256sum-amd64.txt
[ERROR]  Download failed
```

**Comment by brandond** [comment] 2024-08-19 23:13
Duplicate of pinned issue: https://github.com/k3s-io/k3s/issues/10578

**Closed by brandond** 2024-08-19 23:13 UTC
