### ISSUE TITLE
After add --log parameter to k3s server,  systemctl start k3s hangs forever

### ISSUE THREAD

**Issue by zengyongjie** [k3s-io/k3s#2277] opened 2020-09-18 02:40 UTC
**Environmental Info:**
K3s Version: 
1.17.3

Node(s) CPU architecture, OS, and Version: 
X86-64, Centos 7.7.1908 64bit

Cluster Configuration:
1 master, 2 workers

**Describe the bug:**
I want to write the k3s server log to a file .not to /var/log/messages,   So I add `--log=/var/log/k3s-server.log` to k3s.service file, then I use `systemctl daemon-reload` and `systemctl restart k3s` to start it,   this command `systemctl restart k3s` hangs and occupies the terminal forever.   But the cluster has started successfully.

**Steps To Reproduce:**
add `--log=/var/log/k3s-server.log` to k3s.service file

- Installed K3s: 

**Expected behavior:**
It writes log to the file and restart successfully.

**Actual behavior:**
 command `systemctl restart k3s` hangs and occupies the terminal forever.   But the cluster has started successfully.

**Additional context / logs:**
This is my k3s.service file:
```bash
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=/etc/systemd/system/k3s.service.env
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server \
	'--bind-address=192.168.1.150' \
	'--cluster-cidr=10.42.0.0/16' \
	'--service-cidr=10.43.0.0/16' \
	'--kube-apiserver-arg' \
	'service-node-port-range=10000-60000' \
	'--kube-apiserver-arg' \
	'event-ttl=168h0m0s' \
	'--node-label' \
	'asrole=master' \
	'--write-kubeconfig=/root/.kube/config' \
	'--write-kubeconfig-mode=644' \
	'--token=37eb14d86a061f4e6cdc2533e8b7df15' \
	'--kubelet-arg' \
	'enforce-node-allocatable=pods,system-reserved,kube-reserved' \
	'--kubelet-arg' \
	'kube-reserved=cpu=500m,memory=512Mi,ephemeral-storage=10Gi' \
	'--kubelet-arg' \
	'kube-reserved-cgroup=/kubereserved.slice' \
	'--kubelet-arg' \
	'system-reserved=cpu=500m,memory=512Mi,ephemeral-storage=10Gi' \
	'--kubelet-arg' \
	'system-reserved-cgroup=/systemreserved.slice' \
        '--log=/var/log/k3s-server.log' \

```

**Comment by doublegrey** [comment] 2020-09-23 09:45
Please consider removing redundant '=' from k3s args
```
--log /var/log/k3s-server.log
```
---
> I want to write the k3s server log to a file .not to /var/log/messages

**Note**: [Documentation](https://rancher.com/docs/k3s/latest/en/advanced/) says that **default log path for systemd installation** is /var/log/syslog
> The installation script will auto-detect if your OS is using systemd or openrc and start the service. When running with openrc, logs will be created at /var/log/k3s.log.
> When running with systemd, logs will be created in /var/log/syslog and viewed using journalctl -u k3s

Have a nice day! 😄

**Comment by zengyongjie** [comment] 2020-09-28 07:50
> Please consider removing redundant '=' from k3s args
> 
> ```
> --log /var/log/k3s-server.log
> ```
> 
> > I want to write the k3s server log to a file .not to /var/log/messages
> 
> **Note**: [Documentation](https://rancher.com/docs/k3s/latest/en/advanced/) says that **default log path for systemd installation** is /var/log/syslog
> 
> > The installation script will auto-detect if your OS is using systemd or openrc and start the service. When running with openrc, logs will be created at /var/log/k3s.log.
> > When running with systemd, logs will be created in /var/log/syslog and viewed using journalctl -u k3s
> 
> Have a nice day! 😄

Hello,    I found the issue,   I use Cent OS 7 and Ubuntu 18/20  ,   all of them use systemd,   I checked the k3s server systemd unit file `/etc/systemd/system/k3s.service`:
```
 [Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=/etc/systemd/system/k3s.service.env
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server \
	'--bind-address=192.168.1.169' \
	'--cluster-cidr=10.42.0.0/16' \
	'--service-cidr=10.43.0.0/16' \
	'--kube-apiserver-arg' \
	'service-node-port-range=10000-60000' \
	'--kube-apiserver-arg' \
	'event-ttl=168h0m0s' \
	'--node-label' \
	'asrole=master' \
	'--write-kubeconfig=/root/.kube/config' \
	'--write-kubeconfig-mode=644' \
	'--token=37eb14d86a061f4e6cdc2533e8b7df15' \
	'--kubelet-arg' \
	'enforce-node-allocatable=pods,system-reserved,kube-reserved' \
	'--kubelet-arg' \
	'kube-reserved=cpu=500m,memory=512Mi,ephemeral-storage=10Gi' \
	'--kubelet-arg' \
	'kube-reserved-cgroup=/kubereserved.slice' \
	'--kubelet-arg' \
	'system-reserved=cpu=500m,memory=512Mi,ephemeral-storage=10Gi' \
	'--kubelet-arg' \
	'system-reserved-cgroup=/systemreserved.slice' \
```


As you seen, the `Type` is notify, when I changed the log output to customed file,  It desrtroyed the notify mechanism(I don't know the specific resons),  Because systemd cannot receive a starting finished signal, so it hangs.


When I add the line "NotifyAccess=all",  In my opinion, systemd can receive the notify message anywhere, It resolved my problem.

the complete systemd unit file is :
```
 [Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
NotifyAccess=all
EnvironmentFile=/etc/systemd/system/k3s.service.env
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
Noti
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server \
	'--bind-address=192.168.1.169' \
	'--cluster-cidr=10.42.0.0/16' \
	'--service-cidr=10.43.0.0/16' \
	'--kube-apiserver-arg' \
	'service-node-port-range=10000-60000' \
	'--kube-apiserver-arg' \
	'event-ttl=168h0m0s' \
	'--node-label' \
	'asrole=master' \
	'--write-kubeconfig=/root/.kube/config' \
	'--write-kubeconfig-mode=644' \
	'--token=37eb14d86a061f4e6cdc2533e8b7df15' \
	'--kubelet-arg' \
	'enforce-node-allocatable=pods,system-reserved,kube-reserved' \
	'--kubelet-arg' \
	'kube-reserved=cpu=500m,memory=512Mi,ephemeral-storage=10Gi' \
	'--kubelet-arg' \
	'kube-reserved-cgroup=/kubereserved.slice' \
	'--kubelet-arg' \
	'system-reserved=cpu=500m,memory=512Mi,ephemeral-storage=10Gi' \
	'--kubelet-arg' \
	'system-reserved-cgroup=/systemreserved.slice' \
```

**Comment by doublegrey** [comment] 2020-09-28 08:26
Oh, nice!
Please close the issue if the problem is solved
Have a nice day! 😄

**Comment by brandond** [comment] 2020-09-29 06:01
NotifyAccess=all works because k3s silently re-execs itself to redirect log output to a file. Unfortunately in the default configuration, only the specific child process started by systemd is allowed to send a message to the systemd notification socket.

**Comment by zengyongjie** [comment] 2020-09-30 01:59
> NotifyAccess=all works because k3s silently re-execs itself to redirect log output to a file. Unfortunately in the default configuration, only the specific child process started by systemd is allowed to send a message to the systemd notification socket, which means that the re-exec'd child process does not have access.

Tks, got it

**Comment by vhuezo** [comment] 2021-07-20 02:02
:like:

**Comment by brandond** [comment] 2021-10-21 17:59
Yes, see the PRs linked above.

**Comment by ShylajaDevadiga** [comment] 2021-11-23 00:16
Validated using k3s version v1.22.4-rc1+k3s1, passing --log parameter successfully logs into the file specified.
```
$ curl -fL https://get.k3s.io | INSTALL_K3S_VERSION=v1.22.4-rc1+k3s1 sh -s - server --log /var/log/k3s-server.log

$ tail -4 /etc/systemd/system/k3s.service 
    server \
	'--log' \
	'/var/log/k3s-server.log' \

$ cat  /var/log/k3s-server.log |head
time="2021-11-23T00:11:16Z" level=info msg="Starting k3s v1.22.4-rc1+k3s1 (1a513bba)"
time="2021-11-23T00:11:16Z" level=info msg="Configuring sqlite3 database connection pooling: maxIdleConns=2, maxOpenConns=0, connMaxLifetime=0s"
time="2021-11-23T00:11:16Z" level=info msg="Configuring database table schema and indexes, this may take a moment..."
time="2021-11-23T00:11:16Z" level=info msg="Database tables and indexes are up to date"
time="2021-11-23T00:11:16Z" level=info msg="Kine available at unix://kine.sock"
time="2021-11-23T00:11:16Z" level=info msg="certificate CN=system:admin,O=system:masters signed by CN=k3s-client-ca@1637626276: notBefore=2021-11-23 00:11:16 +0000 UTC notAfter=2022-11-23 00:11:16 +0000 UTC"
```

**Closed by ShylajaDevadiga** 2021-11-23 00:16 UTC
Labels: kind/bug, [zube]: Unscheduled
