### ISSUE TITLE
New CoreDNS pod warnings in log

### ISSUE THREAD

**Issue by bguzman-3pillar** [k3s-io/k3s#4919] opened 2022-01-12 16:30 UTC
**Is your feature request related to a problem? Please describe.**

Related with https://github.com/k3s-io/k3s/issues/462
Verifying the logs output is displaying some WARNINGS Messages 

**Describe the solution you'd like**

Validate that current behavior does not affect functionality

**Steps to reproduce**

Validations steps:
Using version: v1.23.1-rc1+k3s1
Create 1 server node and 1 agent node.
Deploy a coredns-custom, run commands and look the output.

Once server is ready, deployt this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  example.server: |
    example.org {
      log
      whoami
      }
```

For logs, this warning was displayed:
`kubectl logs -n kube-system coredns-84c56f7bfb-qcl4q
`

```
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
```

**Comment by brandond** [comment] 2022-01-12 20:34
Yes, that's expected. If you import a globbed set of files, but no files match, coredns will log a warning about it. We added support for this import in https://github.com/k3s-io/k3s/pull/4397 but since it is optional as to whether or not the user creates any customizations, the warning will be logged if they do not.

This is tracked upstream at https://github.com/coredns/coredns/issues/3600#issuecomment-575228515 - there does not seem to be any interest in fixing it.

**Comment by brokenjacobs** [comment] 2022-01-25 23:53
I believe the issue is that there IS a configmap with a configured filename as a key that matches the glob pattern, but coredns is not seeing it because the pod has not been restarted. There is no way to provide this configmap as part of the server install, so you must provision it after the server has been started. 

Does the pod see the optional configmap without restarting?

**Comment by gfrankliu** [comment] 2022-04-17 00:19
@brandond Do you have any update on this? In this case, there is a file match, so coredns should NOT log a warning. As you can see in the configmap, there is `example.server` so the file /etc/coredns/custom/example.server should be created.

**Comment by brandond** [comment] 2022-04-17 01:56
The file only exists if you create and populate the customization configmap. If you're don't do this, then you will see warnings in the logs.

**Comment by gfrankliu** [comment] 2022-04-17 02:40
is below considered `create and populate the customization configmap` ?

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  example.server: |
    example.org {
      log
      whoami
      }
```

The warnings still show in the log, as mentioned in post#1

**Comment by brandond** [comment] 2022-04-17 06:04
Did you delete the coredns pod after creating that configmap? It has to exist at the time the pod is created to be projected into the pod as a volume.

**Comment by gfrankliu** [comment] 2022-04-17 06:31
First, my customization in configmap did get picked up by coredns, so I thought there's no need to delete.

After your suggestion, I tried to delete the pod, and let k3s to recreate, but the new pod still gives the same warning.

**Comment by brandond** [comment] 2022-04-17 08:38
Hmm. If it's getting picked up by coredns then I'm not sure why it would be complaining about it in the logs. I'd suggest taking it up with the coredns team but as you saw in the issue linked above they don't seem too concerned about it.

If it's working then what are you still trying to resolve?

**Comment by gfrankliu** [comment] 2022-04-18 01:37
It turned out someone on the team changed the configmap name from coredns-custom to coredns-custom-config since I last tested. This caused those warnings and they are legit. Once I fix the configmap name, the warning goes away and it starts working again. Thanks and sorry for the false alarm.

**Comment by dfoxg** [comment] 2022-09-24 20:16
Would it be possible to hide the `import /etc/coredns/custom/*.server` behind a feature flag during installation? At the moment all k3s-users are getting spammed with the logs.

**Comment by kamikaze** [comment] 2022-11-30 11:54
very annoying message spam in loki/grafana

**Comment by stavros-k** [comment] 2022-12-21 22:31
Can atleast only show up once when it starts and not spam? I have 20k lines of the same warning over 5days uptime..

**Comment by brandond** [comment] 2022-12-22 07:39
Closing this out in favor of tracking the upstream issue at https://github.com/coredns/coredns/issues/3600#issuecomment-575228515

We will leave the import statement in the config file as a user extension point; it is unfortunate that coredns logs so aggressively if the files don't exist.

**Closed by brandond** 2022-12-22 07:39 UTC
Labels: kind/enhancement
