### ISSUE TITLE
Error on containerd startup

### ISSUE THREAD

**Issue by techgnosis** [k3s-io/k3s#78] opened 2019-02-27 22:18 UTC
I'm not sure if the error is a serious problem or not. I was able to launch an nginx pod. The error certainly reads fairly serious.

All I did was run ` sudo /home/james/bin/k3s server` on Ubuntu 18.10

```
james@growth:~$ k3s -v
k3s version dev (HEAD)
```

```
INFO[2019-02-27T14:13:26.181414671-08:00] Running containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd 
INFO[2019-02-27T14:13:26.181503121-08:00] Waiting for containerd startup: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /run/k3s/containerd/containerd.sock: connect: no such file or directory"
```

**Comment by kissgyorgy** [comment] 2019-02-27 22:52
I have the same problem with the installer:
`curl -sfL https://get.k3s.io | sh -`

**Comment by kissgyorgy** [comment] 2019-02-27 23:07
This is the duplicate of #60.

**Comment by gaussianblurs** [comment] 2019-03-10 21:44
Same problem here except `containerd.sock` is missing

**Comment by warmchang** [comment] 2019-04-01 08:22
> This is the duplicate of #60.

And https://github.com/rancher/k3s/issues/138, https://github.com/rancher/k3s/issues/210, https://github.com/rancher/k3s/issues/271

**Closed** 2020-12-04 23:57 UTC
Labels: help wanted

**Comment by nguyenvulong** [comment] 2021-06-03 10:57
tested with other versions (v4.4.0 and v3.4.0), same problem happened. It always stopped at second server node.

![image](https://user-images.githubusercontent.com/1311412/120634051-cba26e80-c4a5-11eb-8f7c-648a3585d951.png)
