### ISSUE TITLE
Kernel modules does not seem to be loaded when rootless flag is passed on sles

### ISSUE THREAD

**Issue by ShylajaDevadiga** [k3s-io/k3s#2942] opened 2021-02-17 20:22 UTC
**Environmental Info:**
K3s Version: 
```
k3s -v
k3s version v1.20.2+k3s-5749f66a (5749f66a)
```
Node(s) CPU architecture, OS, and Version: 
Sles 15 SP2, amd64

**Cluster Configuration:**
Single Node cluster

**Describe the bug:**
Creating.a cluster with rootless arg with --snapshotter=native or --snapshotter=fuse-overlayfs fails.

**Steps To Reproduce:**
On Sles 15 SP2

Using --snapshotter=native, seems like some kernel modules are missing. Logs attached.
```
$ k3s server --rootless --snapshotter=native
kubelet_network_linux.go:79] Failed to ensure that nat chain KUBE-MARK-DROP exists: error creating chain "KUBE-MARK-DROP": exit status 3: modprobe: ERROR: could not insert 'ip_tables': Operation not permitted
iptables v1.8.5 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
```
Using --snapshotter=fuse-overlayfs 
```
$ k3s server --rootless --snapshotter=fuse-overlayfs

Failed to retrieve agent config: "fuse-overlayfs" snapshotter cannot be enabled for "/home/ec2-user/.rancher/k3s/agent/containerd", try using "native": fuse-overlayfs not functional, make sure running with kernel >= 4.18: failed to mount fuse-overlayfs ({Type:fuse3.fuse-overlayfs Source:overlay Options:[lowerdir=/home/ec2-user/.rancher/k3s/agent/containerd/fuseoverlayfs-check077766963/lower2:/home/ec2-user/.rancher/k3s/agent/containerd/fuseoverlayfs-check077766963/lower1]}) on /home/ec2-user/.rancher/k3s/agent/containerd/fuseoverlayfs-check077766963/merged: mount helper [mount.fuse3 [overlay /home/ec2-user/.rancher/k3s/agent/containerd/fuseoverlayfs-check077766963/merged -o lowerdir=/home/ec2-user/.rancher/k3s/agent/containerd/fuseoverlayfs-check077766963/lower2:/home/ec2-user/.rancher/k3s/agent/containerd/fuseoverlayfs-check077766963/lower1 -t fuse-overlayfs]] failed: "": exec: "mount.fuse3": executable file not found in $PATH 
```

**Expected behavior:**
Able to bring up a cluster as a non-root user

**Actual behavior:**
```
 kubectl get pods -A 
NAMESPACE     NAME                                      READY   STATUS              RESTARTS   AGE
kube-system   helm-install-traefik-q64hf                0/1     ContainerCreating   0          55m
kube-system   coredns-854c77959c-6m8fv                  0/1     ContainerCreating   0          55m
kube-system   local-path-provisioner-5ff76fc89d-brxsx   0/1     Pending             0          55m
kube-system   metrics-server-86cbb8457f-hq2cz           0/1     Pending             0          55m
```

**Additional context / logs:**
Logs attached.
[suserootless.log](https://github.com/k3s-io/k3s/files/5998353/suserootless.log)

**Comment by AkihiroSuda** [comment] 2021-02-18 02:47
This is not a bug. We can't load kernel modules without the root.

**Comment by brandond** [comment] 2021-02-26 20:49
Closing; working as designed for rootless. Root user needs to ensure that the modules are loaded first.

**Closed by brandond** 2021-02-26 20:49 UTC
Labels: kind/bug
