### ISSUE TITLE
Unable to access services using "kubectl proxy"

### ISSUE THREAD

**Issue by vitobotta** [k3s-io/k3s#418] opened 2019-04-30 11:34 UTC
**Describe the bug**
If I try to access a service with the command `kubectl proxy`, all I get is a timeout which doesn't occur with standard Kubernetes.

**To Reproduce**
1. Create a service (the Rook Ceph dashboard in this example)
2. Run `kubectl proxy`
3. Attempt to access the service with something like:

```
http://localhost:8001/api/v1/namespaces/rook-ceph/services/https:rook-ceph-mgr-dashboard:https-dashboard/proxy/
```

**Expected behavior**
I should be able to access the service from my browser but the page times out with the an error message similar to this:

```
Error: 'dial tcp 10.42.2.5:8443: i/o timeout'
Trying to reach: 'https://10.42.2.5:8443/'
```

**Additional context**
K3S version 0.4.0.

**Comment by galal-hussein** [comment] 2019-05-01 17:54
@vitobotta I am not able to reproduce the problem from my end, it may be a problem with the created service/deployment, here are my steps:

- run a deployment/service:
```
kubectl run nginx --image=nginx --replicas=1
kubectl expose deployment nginx --port=80 --target-port=80
```
- kubectl proxy
- access the service using the following format:
```
http://kubernetes_master_address/api/v1/namespaces/namespace_name/services/[https:]service_name[:port_name]
```
```
curl -IL http://127.0.0.1:8001/api/v1/namespaces/default/services/nginx:80/proxy/ 
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Type: text/html
Date: Wed, 01 May 2019 17:38:31 GMT
Etag: "5cb5d3c3-264"
Last-Modified: Tue, 16 Apr 2019 13:08:19 GMT
Server: nginx/1.15.12
```

**Comment by vitobotta** [comment] 2019-05-01 18:42
Hi @galal-hussein , I have tried with the exact steps in your example, and I get `503 Service Unavailable` with curl, while if I visit that URL in the browser I get 

```
Error: 'dial tcp 10.42.2.14:80: i/o timeout'
Trying to reach: 'http://10.42.2.14:80/'
```

Could it be something related to the ingress and the way I have installed it, or is it totally unrelated to ingress? 

Or could it be the firewall? At the moment I have the firewall configured to allow all traffic between the nodes, the ports 80 and 443 are open to anyone and 6443 open only for Rancher and my home IP. Do I have to open anything in the firewall for the proxy to work properly? The weird thing is that I use the same firewall configuration (set up by the same Ansible playbook) with standard Kubernetes and I don't have this issue. Only with K3S. Is there something I can check to investigate further? Thanks!

**Comment by vitobotta** [comment] 2019-05-01 18:50
I just tried again after disabling the firewall on all the nodes but I have the same timeout issue.

**Comment by vitobotta** [comment] 2019-05-01 19:08
Uhm... I have tried `curl http://10.42.2.14:80/` on the workers directly and I can get the nginx index page. I have tried on the master though, and I get the timeout. So it's something with the master somehow. But it's not just this cluster, I have tried with 3-4 clusters although set up the same way.

**Comment by vitobotta** [comment] 2019-05-01 19:59
Aha! I may have found the reason it doesn't work... If I start the server with `--disable-agent` (since I have 3 servers dedicated to the worker role), no network interfaces are created on the master and therefore the master cannot communicate with services on the workers through flannel or whatever (still learning).

However if I start the server without `--disable-agent` then the network interfaces cni and flannel plus others are created and the server/master can communicate with the services on the workers, so `kubectl proxy` works and I can access the service via proxy without problems.

So it looks like it's a problem with server starting as server only and not agent. Is there a workaround? Thanks

**Comment by vitobotta** [comment] 2019-05-01 20:05
For the time being I am leaving the server with agent enabled and I have cordoned it.

**Comment by vitobotta** [comment] 2019-05-01 20:42
Interesting.... with `kubectl port-forward` it works even if I start the master with `--disable-agent`.

**Comment by brandond** [comment] 2020-12-05 00:12
Closing due to age.

**Closed by brandond** 2020-12-05 00:12 UTC
