### ISSUE TITLE
When using the --log parameter to specify the log directory, K3s master cannot be started

### ISSUE THREAD

**Issue by kingsd041** [k3s-io/k3s#3202] opened 2021-04-15 03:06 UTC
**Environmental Info:**
K3s Version:  

$ k3s -v
k3s version v1.20.5+k3s1 (355fff30)
go version go1.15.10

Node(s) CPU architecture, OS, and Version: 

OS: Ubuntu 1804

$ uname -a
Linux ip-172-31-21-37 4.15.0-1044-aws #46-Ubuntu SMP Thu Jul 4 13:38:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 master

**Describe the bug:**

When using the `--log` parameter to specify the log directory, K3s master cannot be started

**Steps To Reproduce:**

- Installed K3s: 
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='--log /opt/k3s.log' sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.20.5+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.20.5+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.20.5+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s

**Expected behavior:**

K3s master can be started successfully and K3s logs can be obtained in `--log`
**Actual behavior:**

K3s is always in the `activating` state

**Additional context / logs:**

systemctl status k3s
● k3s.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
   Active: activating (start) since Thu 2021-04-15 02:50:46 UTC; 9min ago
     Docs: https://k3s.io
  Process: 2203 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 2192 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
 Main PID: 2204 (k3s-server)
    Tasks: 94
   CGroup: /system.slice/k3s.service
           ├─2204 /usr/local/bin/k3s
           ├─2222 k3s server
           ├─2256 containerd
           ├─2673 /var/lib/rancher/k3s/data/926943070e893920b703e893777d0cdc577dea7609f819abb14a97ea8ea1d30b/bin/containerd-shim-runc-v2 -namespace k8s.io -id a213ac97170b926c8e352d939ee2cca6
           ├─2733 /pause
           ├─2754 /var/lib/rancher/k3s/data/926943070e893920b703e893777d0cdc577dea7609f819abb14a97ea8ea1d30b/bin/containerd-shim-runc-v2 -namespace k8s.io -id 241c72d33c0d0f4b6f3447aab6689ac1
           ├─2778 /var/lib/rancher/k3s/data/926943070e893920b703e893777d0cdc577dea7609f819abb14a97ea8ea1d30b/bin/containerd-shim-runc-v2 -namespace k8s.io -id 00d44e35639273c197b0b1f30897568d
           ├─2809 /pause
           ├─2842 /pause
           ├─2944 /coredns -conf /etc/coredns/Corefile
           ├─2955 local-path-provisioner start --config /etc/config/config.json
           ├─3002 /metrics-server
           ├─3502 /var/lib/rancher/k3s/data/926943070e893920b703e893777d0cdc577dea7609f819abb14a97ea8ea1d30b/bin/containerd-shim-runc-v2 -namespace k8s.io -id 4324939722d843cd4559d4768642dc85
           ├─3523 /pause
           ├─3749 /var/lib/rancher/k3s/data/926943070e893920b703e893777d0cdc577dea7609f819abb14a97ea8ea1d30b/bin/containerd-shim-runc-v2 -namespace k8s.io -id a84472e2e85b5ef03b3a81141588b853
           ├─3770 /pause
           ├─3820 /traefik --configfile=/config/traefik.toml
           ├─3920 /bin/sh /usr/bin/entry
           └─3975 /bin/sh /usr/bin/entry

Apr 15 02:50:46 ip-172-31-21-37 systemd[1]: Starting Lightweight Kubernetes...
Apr 15 02:50:46 ip-172-31-21-37 k3s[2204]: time="2021-04-15T02:50:46Z" level=info msg="Acquiring lock file /var/lib/rancher/k3s/data/.lock"
Apr 15 02:50:46 ip-172-31-21-37 k3s[2204]: time="2021-04-15T02:50:46Z" level=info msg="Preparing data dir /var/lib/rancher/k3s/data/926943070e893920b703e893777d0cdc577dea7609f819abb14a97ea8ea
Apr 15 02:50:55 ip-172-31-21-37 systemd[1]: k3s.service: Got notification message from PID 2222, but reception only permitted for main PID 2204

journalctl -u k3s
-- Logs begin at Thu 2021-04-15 02:50:10 UTC, end at Thu 2021-04-15 02:55:36 UTC. --
Apr 15 02:50:46 ip-172-31-21-37 systemd[1]: Starting Lightweight Kubernetes...
Apr 15 02:50:46 ip-172-31-21-37 k3s[2204]: time="2021-04-15T02:50:46Z" level=info msg="Acquiring lock file /var/lib/rancher/k3s/data/.lock"
Apr 15 02:50:46 ip-172-31-21-37 k3s[2204]: time="2021-04-15T02:50:46Z" level=info msg="Preparing data dir /var/lib/rancher/k3s/data/926943070e893920b703e893777d0cdc577dea7609f819abb14a97ea8ea
Apr 15 02:50:55 ip-172-31-21-37 systemd[1]: k3s.service: Got notification message from PID 2222, but reception only permitted for main PID 2204

cat /opt/k3s.log

[k3s.log](https://github.com/k3s-io/k3s/files/6314944/k3s.log)

**Comment by brandond** [comment] 2021-04-15 04:01
It starts, it just doesn't successfully notify systemd. This is a duplicate of #2277

**Closed** 2021-04-15 04:02 UTC
