### ISSUE TITLE
DNS resolution on Alpine images

### ISSUE THREAD

**Issue by deromemont** [k3s-io/k3s#6561] opened 2022-11-24 22:36 UTC
**Environmental Info:**
K3s Version: v1.25.4+k3s1

Node(s) CPU architecture, OS, and Version: Linux marge 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux

Cluster Configuration: 1server

**Describe the bug:**
When I use alpine image, the DNS is not resolved
kubectl run -ti --rm alpine-musl --image=giantswarm/tiny-tools:3.12 --restart=Never --timeout=5s -- nslookup [google.com](http://google.com/)

```
Server:		10.43.0.10
Address:	10.43.0.10#53

Non-authoritative answer:
*** Can't find google.com.mydomain.com: No answer

pod "alpine-musl" deleted 
```

On ubuntu image it seems OK

**Steps To Reproduce:**

kubectl run -ti --rm alpine-musl --image=giantswarm/tiny-tools:3.12 --restart=Never --timeout=5s -- nslookup [google.com](http://google.com/)

**Expected behavior:**
Resolution of the domain google.com

**Actual behavior:**
Error on DNS resolution

**Additional context / logs:**
/etc/resolv.conf on alpine image

```
search default.svc.cluster.local svc.cluster.local cluster.local mydomain.com
nameserver 10.43.0.10
options ndots:5
```

tcpdump on node when I ask google.com from alpine image

```
00:07:11.601271 IP 10.7.0.1.52025 > one.one.one.one.domain: 35132+ [1au] A? google.com.mydomain.com. (54)
00:07:11.625601 IP 10.7.0.1.52025 > one.one.one.one.domain: 2576+ [1au] AAAA? google.com.mydomain.com. (54)
```

**Comment by brandond** [comment] 2022-11-24 23:31
I believe this is a duplicate of 
* https://github.com/k3s-io/k3s/issues/6132

**Comment by deromemont** [comment] 2022-11-25 08:18
It can be fixed in alpine linux ?

**Comment by brandond** [comment] 2022-11-25 09:23
Are you sure it is **just** alpine-based images that experience this problem? Is it not related to which node the pod is running on?

**Comment by deromemont** [comment] 2022-11-25 10:04
I've just a one node k3s (homelab) and debian / ubunutu images are OK but alpine is not OK

**Comment by brandond** [comment] 2022-11-26 00:33
yeah, so it is most likely the alpine issue then. As discussed in that issue, you can sometimes fix this by changing the search list on the node.

**Comment by deromemont** [comment] 2022-11-26 09:03
Yes, that what I did but it's not possible when you use some helm chart based on alpine for example

**Comment by ruschecker** [comment] 2023-02-24 12:03
Long story short is that ndots:5 in /etc/resov.conf breaks alpine because it is using musl instead of glibc.
https://www.openwall.com/lists/musl/2017/03/15/3
But can anybody explain why ndots:5 is set? =)

**Comment by caroline-suse-rancher** [comment] 2023-05-02 20:31
This would likely be a question better suited for the Alpine issue

**Closed by caroline-suse-rancher** 2023-05-02 20:31 UTC
