### ISSUE TITLE
kubectl logs error: dial tcp 127.0.0.1:6443: connect: connection refused

### ISSUE THREAD

**Issue by jrcichra** [k3s-io/k3s#5772] opened 2022-06-28 12:35 UTC
**Environmental Info:**
K3s Version: v1.24.2+k3s1

k3s version v1.24.2+k3s1 (b0ed1348)
go version go1.18.1

Node(s) CPU architecture, OS, and Version: 

`Linux oracle-arm01 5.13.0-1036-oracle #43~20.04.1-Ubuntu SMP Tue Jun 14 01:06:54 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`
Cluster Configuration:

```
NAME            STATUS   ROLES                  AGE    VERSION
timcloudamd01   Ready    <none>                 100d   v1.24.2+k3s1
oracle-arm01    Ready    control-plane,master   386d   v1.24.2+k3s1
jrc-ca-01       Ready    <none>                 100d   v1.24.2+k3s1
oracle-arm04    Ready    <none>                 386d   v1.24.2+k3s1
oracle-arm02    Ready    <none>                 386d   v1.24.2+k3s1
timcloudarm01   Ready    <none>                 105d   v1.24.2+k3s1
justin-k8s-01   Ready    <none>                 119d   v1.24.2+k3s1
timcloudarm02   Ready    <none>                 105d   v1.24.2+k3s1
oracle02        Ready    <none>                 169d   v1.24.2+k3s1
oracle-arm03    Ready    <none>                 386d   v1.24.2+k3s1
timcloudarm04   Ready    <none>                 105d   v1.24.2+k3s1
timcloudamd02   Ready    <none>                 100d   v1.24.2+k3s1
timcloudarm03   Ready    <none>                 105d   v1.24.2+k3s1
oracle01        Ready    <none>                 169d   v1.24.2+k3s1
```
**Describe the bug:**

```
[default|kube-system] ➜  cloud-k8s git:(master) ✗ k logs deployment/coredns -n kube-system
Error from server: Get "https://oracle-arm01:10250/containerLogs/kube-system/coredns-d76bd69b-g6d5l/coredns": dial tcp 127.0.0.1:6443: connect: connection refused
[default|kube-system] ➜  cloud-k8s git:(master) ✗ 
```
**Steps To Reproduce:**

- Installed K3s: 

I run k3s with flannel over a wireguard mesh interface and have never had trouble before. The cluster is operating fine, just not logging.

```
justin@oracle-arm01:/etc/systemd/system$ cat k3s.service
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
Wants=network-online.target
After=network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=notify
EnvironmentFile=-/etc/default/%N
EnvironmentFile=-/etc/sysconfig/%N
EnvironmentFile=-/etc/systemd/system/k3s.service.env
KillMode=process
Delegate=yes
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Restart=always
RestartSec=5s
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server \
        '--no-deploy' \
        'traefik' \
        '--advertise-address' \
        '10.5.0.1' \
        '--bind-address' \
        '10.5.0.1' \
        '--flannel-iface' \
        'wg0' \
        '--kube-proxy-arg' \
        'bind-address=10.5.0.1' \
        '--disable-cloud-controller' \
```
**Expected behavior:**

Logs are shown.
**Actual behavior:**

An error is produced and no logs are shown.

**Additional context / logs:**

I had the same issue on k3s `1.23.8+k3s1`. I tried upgrading to `v1.24.2+k3s1` and it didn't make a difference.
Some additional context on what 127.0.0.1:6443 means in this context would be helpful. Is it talking to the master or a local node api proxy?

**Backporting**

- [ ] Needs backporting to older releases

**Comment by brandond** [comment] 2022-06-28 17:34
This appears to be a duplicate of https://github.com/k3s-io/k3s/issues/5772. As noted in that issue, setting `--egress-selector-mode=disabled` is probably the best work-around until the next release.

**Closed** 2022-06-28 17:36 UTC
