### ISSUE TITLE
The installation script for k3s is incompatible with an IPv6-only environment.

### ISSUE THREAD

**Issue by OrvilleQ** [k3s-io/k3s#8979] opened 2023-12-02 12:54 UTC
Reason behind this issue is github have no support on ipv6 until yet.

So when ever the installation script download checksum file or binary using github.com url, the script will crash.

Ps. Tried to install k3s with `HTTPS_PROXY`, it works but also been logged into k3s's systemd env file.

**Comment by brandond** [comment] 2023-12-02 17:42
Duplicate of https://github.com/k3s-io/k3s/issues/5921

We're not tracking this here as there is nothing we can do about it.

**Closed by brandond** 2023-12-02 17:42 UTC
