### ISSUE TITLE
agent must be run as root

### ISSUE THREAD

**Issue by ghost** [k3s-io/k3s#1147] opened 2019-11-28 04:54 UTC
**Version:** 1.0

Agent requires to use sudo even when the server is running in --rootless mode.

**To Reproduce**
- Start server in rootless mode.
- Try to join server as agent in rootless mode.

**Expected behavior**
Agent too should be able to run as rootless.

**Actual behavior**
Throws above error.

**Comment by galal-hussein** [comment] 2019-12-06 22:17
I can reproduce the issue with agent:
```
./k3s agent --rootless --server https://172.31.14.80:6443 --token K10d253888996a26243390b018099c9d477fd7b1b147e19d6db8cd973db26c25a25::server:9aae9845b45b7c09ddd76f3f9ebcec5a 
INFO[0000] Preparing data dir /var/lib/rancher/k3s/data/2492a28b74abfbdbd3f943c8109a93e979669647bbbe95eadae43b60c667df69 
INFO[0000] error extracting tarball into /var/lib/rancher/k3s/data/2492a28b74abfbdbd3f943c8109a93e979669647bbbe95eadae43b60c667df69-tmp after 0 files, 0 dirs, 423.374µs: mkdir /var/lib/rancher: permission denied 
FATA[0000] extracting data: mkdir /var/lib/rancher: permission denied 
```

**Comment by andypost** [comment] 2019-12-06 23:03
It means datadir should be checked about write, or for rootless provide default in `.local`

**Comment by Leschge** [comment] 2021-05-20 07:04
Only as further information: This still occours but the reason may not be a _permission denied_ on data dir as @galal-hussein stated (at least thats what I can read from the logs). But the debug log may also be incorrect, as running in rootless uses the dir  ${HOME}/.rancher/k3s is used and not /var/lib/... .

```
 ./k3s-arm64 agent --rootless --debug --server 192.168.178.129:6443 --token K1079a75589a2348686b5702cd758b6c2ace52a7b086fce2cd1208c0c3a97ddc1ae::server:98ff63548a055b9ecca5b08fdaf6c659
DEBU[0000] Asset dir /var/lib/rancher/k3s/data/5ff642266687619a153eb68c449fa322d64f70f90c29cce741f5a4f9b2dcf784
DEBU[0000] Running /var/lib/rancher/k3s/data/5ff642266687619a153eb68c449fa322d64f70f90c29cce741f5a4f9b2dcf784/bin/k3s-agent [./k3s-arm64 agent --rootless --debug --server 192.168.178.129:6443 --token K1079a75589a2348686b5702cd758b6c2ace52a7b086fce2cd1208c0c3a97ddc1ae::server:98ff63548a055b9ecca5b08fdaf6c659]
FATA[2021-05-20T06:43:08.643802242Z] agent must be ran as root

```

**Comment by caroline-suse-rancher** [comment] 2023-02-06 15:52
closing due to age and no longer an issue - please reopen or create anew if issue reappears.

**Closed by caroline-suse-rancher** 2023-02-06 15:52 UTC
Labels: kind/bug
