### ISSUE TITLE
[release-1.25] `k3s server` exits instead of retrying when receiving "too many learners" error from etcd join

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#7511] opened 2023-05-09 23:03 UTC
* Backport #7000

**Comment by VestigeJ** [comment] 2023-05-15 22:15
I will post more updates here soon because the initial issue does seem to be resolved with the explicit error stated above disappearing on the latest COMMIT for the branch. 

However I see this new error occur on one out of four server nodes joining simultaneously. The other three server nodes all started humming along nicely - the fix to get this fourth node to join correctly is literally to just re-run the startup command and then it joins the cluster just fine. 

$ sudo k3s server
```
INFO[0000] Acquiring lock file /var/lib/rancher/k3s/data/.lock 
INFO[0000] Preparing data dir /var/lib/rancher/k3s/data/139baf56dd73135b3c4c2aea21e749ad26a4db4e71a0177dbb00c3e0793b3d3d 
INFO[0000] Starting k3s v1.25.9+k3s-3ce8dd17 (3ce8dd17) 
FATA[0000] starting kubernetes: preparing server: CA cert validation failed: Get "https://1.2.3.205:6443/cacerts": x509: certificate is valid for 10.43.0.1, 127.0.0.1, 1.1.1.170, ::1, not 1.2.3.205
```

**Comment by brandond** [comment] 2023-05-15 22:20
That appears to be something with the dynamiclistener cert; I suspect the servers are all racing to add their SANs to the cert as they start up. Lets track that separately.

**Comment by VestigeJ** [comment] 2023-05-15 23:21
##Environment Details
Verified existing behavior using VERSION=v1.25.9+k3s1
Verified new behavior using COMMIT=3ce8dd17c9202508109bf9bc84cddcbf79d3674f

*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and version:*
```
Linux 5.14.21-150400.24.11-default x86_64 GNU/Linux 
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP4"
```
 
*Cluster Configuration:*
```
NAME               STATUS   ROLES                       AGE     VERSION
ip-1-1-2-49        Ready    control-plane,etcd,master   19s     v1.25.9+k3s-3ce8dd17
ip-1-1-2-218       Ready    control-plane,etcd,master   2m4s    v1.25.9+k3s-3ce8dd17
ip-1-1-2-170       Ready    control-plane,etcd,master   8m11s   v1.25.9+k3s-3ce8dd17
ip-1-1-2-254       Ready    control-plane,etcd,master   2m22s   v1.25.9+k3s-3ce8dd17
ip-1-1-3-231       Ready    control-plane,etcd,master   2m34s   v1.25.9+k3s-3ce8dd17 
```

*Config.yaml:*
```
write-kubeconfig-mode: 644
debug: true
token: darkerpolyphenolsplease
selinux: true
protect-kernel-defaults: true
cluster-init: true
```

<details><summmary><h4>Reproduced existing join failures</h4></summary>



```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/90-kubelet.conf
$ sudo cp 90-kubelet.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ sudo INSTALL_K3S_VERSION=v1.25.9+k3s1 INSTALL_K3S_EXEC=server ./install-k3s.sh 
$ set_kubefig
$ kgn
$ w2 kgn
```

note on secondary nodes perform the installation with INSTALL_K3S_SKIP_ENABLE=true so that you can more easily run them quickly in tandem to trigger the race condition.

**Results:**

Existing too many learners error observed on existing releases.

```
{"level":"warn","ts":"2023-05-15T20:51:54.646Z","logger":"etcd-client","caller":"v3@v3.5.3-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000bbaa80/1.1.2.170:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: too many learner members in cluster"}
FATA[0003] ETCD join failed: etcdserver: too many learner members in cluster 
```

</details>

<details><summmary><h4> YOUR_VALIDATION_RESULTS_HERE </h4></summary>
 
## Validation Steps
 
```
$ sudo INSTALL_K3S_COMMIT=3ce8dd17c9202508109bf9bc84cddcbf79d3674f INSTALL_K3S_SKIP_ENABLE=true INSTALL_K3S_EXEC=server ./install-k3s.sh 
$ set_kubefig //export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
$ kgn //kubectl get nodes
$ w2 kgn 
$ get_report //generate this template
```

**Results:** 
expect to see normal stdout from running the k3s server process in the terminal - note you say also see the newer dynamiclistener cert issue uncovered.


</details>

**Closed by VestigeJ** 2023-05-15 23:21 UTC
