### ISSUE TITLE
Channel server returns inconsistent versions for channel v1.30

### ISSUE THREAD

**Issue by janfrederik** [k3s-io/k3s#11422] opened 2024-12-06 19:26 UTC
For channel v1.30, the channel server's json says the latest version is "v1.30.7+k3s1". However, the link for channel v1.30 leads to version "v1.30.6+k3s1".

**Steps To Reproduce:**
https://update.k3s.io/v1-release/channels returns:
```json
...
    {
      "id": "v1.30",
      "type": "channel",
      "links": {
        "self": "https://update.k3s.io/v1-release/channels/v1.30"
      },
      "name": "v1.30",
      "latest": "v1.30.7+k3s1",
      "latestRegexp": "v1\\.30\\..*",
      "excludeRegexp": "^[^+]+-"
    }
...
```

Following the self link https://update.k3s.io/v1-release/channels/v1.30, I get a redirect to https://github.com/k3s-io/k3s/releases/tag/v1.30.6+k3s1.

**Expected behavior:**
Shouldn't the redirect be to "v1.30.7+k3s1"?

https://github.com/k3s-io/k3s/releases/tag/v1.30.7+k3s1

**Actual behavior:**
Redirected to v1.30.6+k3s1.

So the install script installs v1.30.6+k3s1 :-(

**Additional context**
Could this be because somehow v1.30.7+k3s1 is tagged as a pre-release in GitHub ? This doesn't make sense according to the versioning scheme.

![image](https://github.com/user-attachments/assets/656ccd55-c3c2-415c-a96d-ab64e40776a5)

**Comment by brandond** [comment] 2024-12-06 19:40
Duplicate of https://github.com/k3s-io/k3s/issues/11421#issuecomment-2523956669

**Closed by brandond** 2024-12-06 19:40 UTC
