### ISSUE TITLE
SSL Certificate errors when accessing https://get.k3s.io 

### ISSUE THREAD

**Issue by spurin** [k3s-io/k3s#8019] opened 2023-07-20 13:03 UTC
**Environmental Info:**
K3s Version:  N/A

Node(s) CPU architecture, OS, and Version: N/A

Cluster Configuration: N/A

**Describe the bug:**

SSL Certificate errors when accessing https://get.k3s.io from a Google Cloud Shell Terminal

**Steps To Reproduce:**

Run ```curl -sfLv https://get.k3s.io```

**Expected behavior:**

It to work transparently

**Actual behavior:**

```
curl -sfLv https://get.k3s.io
*   Trying 172.67.69.209:443...
* Connected to get.k3s.io (172.67.69.209) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Apr 10 00:00:00 2023 GMT
*  expire date: Apr  9 23:59:59 2024 GMT
*  subjectAltName does not match get.k3s.io
* SSL: no alternative certificate subject name matches target host name 'get.k3s.io'
* Closing connection 0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS alert, close notify (256):
```

**Additional context / logs:**

Worked fine from my local desktop

**Comment by brandond** [comment] 2023-07-20 15:54
I can't reproduce this on any of the hosts I have access to. Please confirm that there isn't something in the Google Cloud Shell environment that is intercepting SSL connections for the purposes of traffic inspection.

Even if you work around this error though, I suspect K3s will not run in the restricted Google Cloud Shell environment.

**Comment by cwayne18** [comment] 2023-07-26 13:58
We do appreciate you bringing this to our attention! Since it seems to be limited to this environment and we've yet been unable to reproduce this I'm going to close it out for now as suggested, if anyone runs into this again please feel free to reopen

**Closed by cwayne18** 2023-07-26 13:58 UTC
