### ISSUE TITLE
failed to update resources: runc did not terminate successfully: container "-" does not exist

### ISSUE THREAD

**Issue by lackhoa** [k3s-io/k3s#3104] opened 2021-03-22 06:37 UTC
**Environmental Info:**
K3s Version: `v1.20.4+k3s1`

Node(s) CPU architecture, OS, and Version: 
`Linux node-0 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:
3 server nodes, no worker.

**Describe the bug:**
The journald logs on all nodes are being spammed with messages like these:

```
Mar 21 05:39:50 node-0 k3s[1643]: E0321 05:39:50.322352    1643 cpu_manager.go:437] [cpumanager] reconcileState: failed to update container (pod: ingress-nginx-controller-nld9n, container: controller, container id: 3d66f4a8dd5abda7bd27ee08b892eb99c33245d066d23e6fc1c18fd4404be0ee, cpuset: "0-3,5-7", error: rpc error: code = Unknown desc = failed to update resources: failed to update resources: runc did not terminate successfully: container "-" does not exist
```

That message isn't limited to a single pods/containers.

Cluster activity otherwise is normal, at least I haven't encountered any problems related to updating containers.

**Steps To Reproduce:**

- Installed K3s:
```
      curl -sfL https://get.k3s.io |
      INSTALL_K3S_VERSION=${local.k3s_version} sh -s - server --cluster-init \
      -t ${random_string.server_token.result} \
      --advertise-address ${var.servers[0].private_ip} \
      --node-ip ${var.servers[0].private_ip} \
      --node-external-ip ${var.servers[0].public_ip} \
      --cluster-cidr ${local.cluster_cidr} \
      --service-cidr ${local.service_cidr} \
      --agent-token ${random_string.agent_token.result} \
      --flannel-backend wireguard \
      --resolv-conf /run/systemd/resolve/resolv.conf \
      --tls-san ${var.name} \
    --kubelet-arg='eviction-soft=memory.available<300Mi' \
    --kubelet-arg='eviction-soft-grace-period=memory.available=1m' \
    --kubelet-arg='eviction-hard=memory.available<150Mi,imagefs.available<15%,nodefs.available<10%,nodefs.inodesFree<5%' \
    --kubelet-arg='kube-reserved=cpu=250m,memory=250Mi,ephemeral-storage=1Gi' \
    --kubelet-arg='system-reserved=cpu=250m,memory=250Mi,ephemeral-storage=2Gi' \
    --kubelet-arg='cpu-manager-policy=static' \
    --kubelet-arg='feature-gates=CRIContainerLogRotation=true' \
    --kubelet-arg='container-log-max-size=10Mi' \
    --kubelet-arg='container-log-max-files=10' \
    --kubelet-arg 'containerd=/run/k3s/containerd/containerd.sock' \
      --disable-cloud-controller \
      --disable servicelb \
      --disable traefik \
```

**Comment by brandond** [comment] 2021-03-22 17:11
The error appears to be coming from containerd's runc wrapper:
https://github.com/k3s-io/k3s/blob/9bae285bfd6d06c62af179557e81c5f68f637ba3/vendor/github.com/containerd/go-runc/runc.go#L599

For some reason it's not parsing the argument list properly, and is using `-` as the container id even though this should in fact be telling it to read the resources from stdin:
https://github.com/opencontainers/runc/blob/master/man/runc-update.8.md


While I'm here, I will note that you're disabling the cloud controller but also trying to set a node external IP. Are you using an external cloud provider? If not, the K3s embedded cloud controller must be enabled to properly set the node external IP.

**Comment by davidnuzik** [comment] 2021-05-04 16:16
@brandond I see https://github.com/containerd/go-runc/pull/71 is merged - is that all we needed? If so can you update the issue state to "To Test" so it gets assigned out to QA?

**Comment by brandond** [comment] 2021-05-04 18:13
No, we'll need to pull the fix into our containerd fork and then bump containerd in k3s.

**Comment by zdyxry** [comment] 2021-05-09 01:21
I'm getting the same error.

When I start k3s-agent and configure `cpu-manager-policy=static` , CPU Manager fails to update existing Container resources.

logs:

```
May 09 10:18:06 214 k3s[8021]: E0509 10:18:06.507347    8021 remote_runtime.go:360] UpdateContainerResources "483ad91690f122de98d4299f1d29a25660fc210c1cedd11af13e020cf332abf8" from runtime service failed: rpc error: code = Unknown desc = failed to update resources: failed to update resources: runc did not terminate successfully: container "-" does not exist
May 09 10:18:06 214 k3s[8021]: E0509 10:18:06.507362    8021 cpu_manager.go:437] [cpumanager] reconcileState: failed to update container (pod: nginx9, container: nginx, container id: 483ad91690f122de98d4299f1d29a25660fc210c1cedd11af13e020cf332abf8, cpuset: "0,5-8", error: rpc error: code = Unknown desc = failed to update resources: failed to update resources: runc did not terminate successfully: container "-" does not exist
[root@214 cgroup]# cat cpuset/kubepods/burstable/pod7d7df054-6823-4d61-863c-e8bde56c69b4/483ad91690f122de98d4299f1d29a25660fc210c1cedd11af13e020cf332abf8/cpuset.cpus
0,3-8
```

**Comment by brandond** [comment] 2021-05-09 04:54
Yes, as noted above the fix hasn't been pulled in to K3s yet.

**Comment by cjellick** [comment] 2021-05-12 15:19
@brandond @dweomer will this be addressed by our bump of runc?

**Comment by brandond** [comment] 2021-05-12 16:21
@cjellick no, this is the go-runc library used by containerd to talk to runc. I don't believe we have plans to bump containerd at this time.

**Comment by brandond** [comment] 2021-05-12 16:33
Actually, this issue is apparently caused by our building runc against a different version of urfave/cli than it expects, so this might actually get fixed by @dweomer reconfiguring the build to no longer build runc out of vendor.

**Comment by rancher-max** [comment] 2021-05-17 22:33
Validated this error is reproducible on v1.18.18, v1.19.10, v1.20.6, and v1.21.0 when bringing up the cluster via:
```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.20.7-rc1+k3s1 sh -s - server --cluster-init --write-kubeconfig-mode=644 \
  --kubelet-arg='cpu-manager-policy=static' \
  --kubelet-arg='eviction-soft=memory.available<300Mi' \
  --kubelet-arg='eviction-soft-grace-period=memory.available=1m' \
  --kubelet-arg='eviction-hard=memory.available<150Mi,imagefs.available<15%,nodefs.available<10%,nodefs.inodesFree<5%' \
  --kubelet-arg='kube-reserved=cpu=250m,memory=250Mi,ephemeral-storage=1Gi' \
  --kubelet-arg='system-reserved=cpu=250m,memory=250Mi,ephemeral-storage=2Gi' \
  --kubelet-arg='container-log-max-size=10Mi' \
  --kubelet-arg='container-log-max-files=10'
```

Using this same command on v1.18.19-rc1, v1.19.11-rc1, v1.20.7-rc1, and v1.21.1-rc1 all are working correctly, without this error in the logs.

**Closed by rancher-max** 2021-05-17 22:33 UTC
Labels: kind/upstream-issue
