### ISSUE TITLE
Etcd snapshot controller spews logs while waiting for nodes to annotate

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#8892] opened 2023-11-17 01:22 UTC
Early in cluster startup, before any etcd nodes have reconciled their snapshots and set the annotations, the full sync loop will continually return errNotReconciled and be immediately reenqueued:

* https://github.com/k3s-io/k3s/blob/e53c189587f8fe0f2aebb243e213ea03b5e38e76/pkg/etcd/snapshot_controller.go#L201-L203
* https://github.com/k3s-io/k3s/blob/e53c189587f8fe0f2aebb243e213ea03b5e38e76/pkg/etcd/snapshot_controller.go#L62-L67

Unfortunately this creates a LOT of log spew, especially on RKE2 where startup takes a little longer to settle out.

We should move the log line further down the function, or reduce its verbosity.

**Comment by brandond** [comment] 2023-11-17 01:24
Example log spew from a recent test cluster startup:
```
Nov 08 13:09:50 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:50Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:50 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:50Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:51 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:51Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:51 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:51Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:52 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:52Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:52 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:52Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:53 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:53Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:53 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:53Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:53 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:53Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:54 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:54Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:54 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:54Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:55 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:55Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:55 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:55Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:55 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:55Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:56 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:56Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:56 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:56Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:57 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:57Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:57 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:57Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:57 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:57Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:58 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:58Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:58 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:58Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:59 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:59Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:09:59 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:09:59Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:10:00 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:10:00Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:10:00 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:10:00Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
Nov 08 13:10:00 test-node-xr6bx rke2[379]: time=\"2023-11-08T13:10:00Z\" level=info msg=\"Reconciling snapshot ConfigMap data\"
```

**Comment by mdrahman-suse** [comment] 2023-11-28 16:46
Hi @brandond, is this issue and the corresponding backports ready to be moved to Test? I see the PR linked has been merged

**Comment by brandond** [comment] 2023-11-28 17:24
Yes, sorry - I apparently missed assigning it to myself so I didn't see it in the project board.

**Comment by rancher-max** [comment] 2023-11-28 21:18
I'm wondering if whatever rancher manager is doing in their CI is causing this because I cannot reproduce it whether through rancher or standalone, even when having the etcd-snapshots tuned to take one every minute. I have tried all versions available. I will confirm no regressions to this logging and then close this issue. Using `journalctl -u rke2-server | grep "Reconciling snapshot ConfigMap data"` for rke2 and `journalctl -u k3s | grep "Reconciling snapshot ConfigMap data"` for k3s.

**Comment by brandond** [comment] 2023-11-28 22:27
@rancher-max you'll see this spew when using embedded etcd, but no snapshots exist - either locally, or in the configured S3 bucket.

**Comment by rancher-max** [comment] 2023-11-28 23:18
# Validated on v1.28.4-rc1+k3s1 
 
## Environment Details

 
*Infrastructure*
- [x] Cloud (AWS)
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
 
*Cluster Configuration:*

```
1 server
```
 
*Config.yaml:*

```
write-kubeconfig-mode: 644
cluster-init: true
etcd-s3: true
etcd-s3-bucket: mybucket
etcd-s3-folder: myfolder
etcd-s3-region: us-east-2
etcd-s3-access-key: <redacted>
etcd-s3-secret-key: <redacted>
token: sometoken
```
 
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s
```
$ curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.28.4-rc1+k3s1 sh -
```
3. Check logs for unnecessary spew:
```
$ journalctl -u k3s | grep "Reconciling snapshot ConfigMap data"
Nov 28 23:09:32 ip-172-31-46-231 k3s[1605]: time="2023-11-28T23:09:32Z" level=info msg="Reconciling snapshot ConfigMap data"
```
 
**Replication Results:**
- k3s version used for replication:

```
k3s version v1.28.3+k3s2 (bbafb86e)
go version go1.20.10
```
 

- I was not able to replicate the issue
```
$ journalctl -u k3s | grep "Reconciling snapshot ConfigMap data"
Nov 28 23:09:21 ip-172-31-37-124 k3s[1598]: time="2023-11-28T23:09:21Z" level=info msg="Reconciling snapshot ConfigMap data"
```
 
 
**Validation Results:**
- k3s version used for validation:

```
k3s version v1.28.4-rc1+k3s1 (3f237230)
go version go1.20.11
```
 

- The results were the same:
```
$ journalctl -u k3s | grep "Reconciling snapshot ConfigMap data"
Nov 28 23:09:32 ip-172-31-46-231 k3s[1605]: time="2023-11-28T23:09:32Z" level=info msg="Reconciling snapshot ConfigMap data"
```
- No regressions noticed. Attempted in SLES15 SP4 and RHEL 9.2 as well with multinode setups and without s3 snapshots configured
- In one case during validation, I saw two logs of this spit out but never more than that which should be acceptable.

Based on the above, I'm going to close this out. I think the log spew must appear under different circumstances, and I'm not noticing any base functionality changes here so should be okay either way.

**Closed by rancher-max** 2023-11-28 23:18 UTC
