### ISSUE TITLE
2 node server k3s embedded etcd DB cluster fails when 1 node goes offline

### ISSUE THREAD

**Issue by tHachWorks** [k3s-io/k3s#5969] opened 2022-08-06 10:15 UTC
**Environmental Info:**
K3s Version: 

k3s version v1.24.3+k3s1 (990ba0e8)
go version go1.18.1

Node(s) CPU architecture, OS, and Version: 

Linux k3s-em1 5.10.0-16-amd64 #1 SMP Debian 5.10.127-2 (2022-07-23) x86_64 GNU/Linux
Linux k3s-em2 5.10.0-16-amd64 #1 SMP Debian 5.10.127-2 (2022-07-23) x86_64 GNU/Linux

Cluster Configuration:

2 node server HA Embedded etcd DB cluster

**Describe the bug:**

To test/simulate node failure i do `systemctl stop k3s` on one node and the whole cluster fails.

**Steps To Reproduce:**

- Installed K3s on Node1 with `curl -sfL https://get.k3s.io | K3S_TOKEN=SECRET sh -s - server --cluster-init` 
- Node2 joined the cluster with `curl -sfL https://get.k3s.io | K3S_TOKEN=SECRET sh -s - server --server https://<ip of Node1>:6443`
- Simulate node failure on Node2 with `systemctl stop k3s`
- Run `kubectl get nodes` on Node1

**Expected behavior:**

I expect to be able to access the cluster with only one node active. 
```bash
NAME      STATUS      ROLES                       AGE     VERSION
k3s-em1   Ready       control-plane,etcd,master   13m     v1.24.3+k3s1
k3s-em2   NotReady    control-plane,etcd,master   9m46s   v1.24.3+k3s1
```
**Actual behavior:**

I get 
```bash
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
```
**Additional context / logs:**

`systemctl status k3s`
```bash
● k3s.service - Lightweight Kubernetes
     Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
     Active: activating (start) since Sat 2022-08-06 11:41:57 CEST; 3min 8s ago
       Docs: https://k3s.io
    Process: 4168 ExecStartPre=/bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service (code=exited, status=0/SUCCESS)
    Process: 4170 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
    Process: 4171 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
   Main PID: 4172 (k3s-server)
      Tasks: 81
     Memory: 1.0G
        CPU: 3min 2.787s
     CGroup: /system.slice/k3s.service
             ├─1646 /var/lib/rancher/k3s/data/1d787a9b6122e3e3b24afe621daa97f895d85f2cb9cc66860ea5ff973b5c78f2/bin/containerd-shim-runc-v2 -namespace k8s.io -id 1116c0bb73fb37ff7d66e473f7486b581d702f9087b28f1deb8daf60daf51d71 -address />
             ├─1649 /var/lib/rancher/k3s/data/1d787a9b6122e3e3b24afe621daa97f895d85f2cb9cc66860ea5ff973b5c78f2/bin/containerd-shim-runc-v2 -namespace k8s.io -id 6d762ca48c6734d68898bf22a73d6f7554e291469147041156363a69f2a47ae9 -address />
             ├─1689 /var/lib/rancher/k3s/data/1d787a9b6122e3e3b24afe621daa97f895d85f2cb9cc66860ea5ff973b5c78f2/bin/containerd-shim-runc-v2 -namespace k8s.io -id c07669a4203245adf59e3e58f1169b6c22a832c9f02b4b2618738f01b3ccd01b -address />
             ├─3194 /var/lib/rancher/k3s/data/1d787a9b6122e3e3b24afe621daa97f895d85f2cb9cc66860ea5ff973b5c78f2/bin/containerd-shim-runc-v2 -namespace k8s.io -id 9c32d5060b2cafad6ea7d1bbe189b5f7b7ebd39e03554259ab0c244b4ad311ba -address />
             ├─3300 /var/lib/rancher/k3s/data/1d787a9b6122e3e3b24afe621daa97f895d85f2cb9cc66860ea5ff973b5c78f2/bin/containerd-shim-runc-v2 -namespace k8s.io -id cba25697dffcde425c478bc2402c1e4cd9bb8fdeae778d65575ee6c0f9ab4775 -address />
             ├─4172 /usr/local/bin/k3s server
             └─4188 containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd

Aug 06 11:45:02 k3s-em1 k3s[4172]: {"level":"info","ts":"2022-08-06T11:45:02.126+0200","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"ea423c26c0884560 received MsgPreVoteResp from ea423c26c0884560 at term 4"}
Aug 06 11:45:02 k3s-em1 k3s[4172]: {"level":"info","ts":"2022-08-06T11:45:02.126+0200","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"ea423c26c0884560 [logterm: 4, index: 1720] sent MsgPreVote request to bbe9280cf68f081c at>
Aug 06 11:45:02 k3s-em1 k3s[4172]: {"level":"warn","ts":"2022-08-06T11:45:02.165+0200","logger":"etcd-client","caller":"v3@v3.5.3-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000aa>
Aug 06 11:45:02 k3s-em1 k3s[4172]: time="2022-08-06T11:45:02+02:00" level=info msg="Failed to test data store connection: context deadline exceeded"
Aug 06 11:45:02 k3s-em1 k3s[4172]: time="2022-08-06T11:45:02+02:00" level=info msg="Tunnel server egress proxy waiting for runtime core to become available"
Aug 06 11:45:02 k3s-em1 k3s[4172]: {"level":"warn","ts":"2022-08-06T11:45:02.170+0200","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_SNAPSHOT","remote-peer-id":"bbe>
Aug 06 11:45:02 k3s-em1 k3s[4172]: {"level":"warn","ts":"2022-08-06T11:45:02.173+0200","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":>
Aug 06 11:45:03 k3s-em1 k3s[4172]: {"level":"warn","ts":"2022-08-06T11:45:03.222+0200","logger":"etcd-client","caller":"v3@v3.5.3-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000aa>
Aug 06 11:45:03 k3s-em1 k3s[4172]: time="2022-08-06T11:45:03+02:00" level=error msg="Failed to check local etcd status for learner management: context deadline exceeded"
Aug 06 11:45:03 k3s-em1 k3s[4172]: time="2022-08-06T11:45:03+02:00" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:6443/v1-k3s/readyz: 500 Internal Server Error"
```
`journalctl -u k3s`
[journal_k3s.log](https://github.com/k3s-io/k3s/files/9274792/journal_k3s.log)

**Comment by brandond** [comment] 2022-08-06 16:28
Duplicate of https://github.com/k3s-io/k3s/issues/5210 - see https://github.com/k3s-io/k3s/issues/5210#issuecomment-1059073954

**Closed by brandond** 2022-08-06 16:28 UTC
