### ISSUE TITLE
Coredns getting preempted by other pods even though they are set to preempt never

### ISSUE THREAD

**Issue by 2fst4u** [k3s-io/k3s#2528] opened 2020-11-13 20:45 UTC
**Environmental Info:**
K3s Version: k3s version v1.18.10+k3s1 (6fa97306)

Node(s) CPU architecture, OS, and Version: Linux k3s-node1 5.4.51-v7+ rancher/k3s#1333   SMP Mon Aug 10 16:45:19 BST 2020 armv7l GNU/Linux

Cluster Configuration: single raspberry pi 3B

**Describe the bug:** when starting too many pods for the node to handle, k3s terminates the coredns pod(s) in favour of the pod I attempt to start even though the new pod's preemption policy in the policy class it belongs to is set to "never".

**Steps To Reproduce:**1. k3s is installed using the Ansible playbook.
2. Set the following extra_server_args in order to reserve resources on the node:
```
--disable traefik --kubelet-arg system-reserved=cpu=100m,memory=100Mi --kubelet-arg kube-reserved=cpu=200m,memory=400Mi
```
3. Priorityclass with following information is created:
```
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority-nonpreempting
value: 900000
preemptionPolicy: Never
globalDefault: false
description: "High priority but will not kill other pods"
```
4. Create enough pods with this priorityclass that the node can't start them all.
5. Check kubectl get events -A and it shows the following output:
```
kube-system   9s          Normal    Preempted           pod/coredns-7944c66d8d-vld7b                  Preempted by prod/sonarr-deployment-55f9df6b5-qdnwz on node k3s-node1
kube-system   10s         Normal    Killing             pod/coredns-7944c66d8d-vld7b                  Stopping container coredns
kube-system   9s          Normal    SuccessfulCreate    replicaset/coredns-7944c66d8d                 Created pod: coredns-7944c66d8d-t9lvb
prod          9s          Warning   FailedScheduling    pod/sonarr-deployment-55f9df6b5-qdnwz         0/1 nodes are available: 1 Insufficient memory.
kube-system   8s          Warning   FailedScheduling    pod/coredns-7944c66d8d-t9lvb                  0/1 nodes are available: 1 Insufficient memory.
prod          8s          Warning   FailedScheduling    pod/sonarr-deployment-55f9df6b5-qdnwz         0/1 nodes are available: 1 Insufficient memory.
prod          2s          Normal    Scheduled           pod/sonarr-deployment-55f9df6b5-qdnwz         Successfully assigned prod/sonarr-deployment-55f9df6b5-qdnwz to k3s-node1
kube-system   8s          Warning   FailedScheduling    pod/coredns-7944c66d8d-t9lvb                  0/1 nodes are available: 1 Insufficient memory.
kube-system   2s          Warning   Unhealthy           pod/coredns-7944c66d8d-vld7b                  Readiness probe failed: Get http://10.42.0.46:8181/ready: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Expected behavior:** I would expect coredns not to be preempted ever. It should surely have a higher priority than "0".

**Actual behavior:** coredns gets preempted and terminated.

**Additional context / logs:**
 Output of describe pod coredns[xxx]
```
Name:           coredns-7944c66d8d-t9lvb
Namespace:      kube-system
Priority:       0
Node:           <none>
Labels:         k8s-app=kube-dns
                pod-template-hash=7944c66d8d
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/coredns-7944c66d8d
Containers:
  coredns:
    Image:       rancher/coredns-coredns:1.6.9
    Ports:       53/UDP, 53/TCP, 9153/TCP
    Host Ports:  0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:    http-get http://:8181/ready delay=10s timeout=5s period=10s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from coredns-token-97v4g (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  coredns-token-97v4g:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coredns-token-97v4g
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  2m37s  default-scheduler  0/1 nodes are available: 1 Insufficient memory.
  Warning  FailedScheduling  2m36s  default-scheduler  0/1 nodes are available: 1 Insufficient memory.
```
Output of `kubectl get pods --all-namespaces -o custom-columns=NAME:.metadata.name,PRIORITY:.spec.priorityClassName`:
```
local-path-provisioner-6d59f47c7-mssbn    <none>
coredns-7944c66d8d-t9lvb                  <none>
sonarr-deployment-55f9df6b5-qdnwz         high-priority-nonpreempting
```
Shows that coredns and other default pods have no priorityclass name

**Comment by brandond** [comment] 2020-11-13 22:04
Yes, we should probably be setting `priorityClassName` for the packaged components.

**Comment by 2fst4u** [comment] 2020-11-13 23:45
Just a few questions because I'm actually an absolute noob at this.

1. Does it look like I've done everything as intended? I haven't screwed up anything?

2. Do those extra_server_args look ok? I'm hoping they haven't impacted it negatively.

3. Do these core components count as an element of the kube-reserved or are they considered regular pods? I tried increasing the kube-reserved in case that allowed it to save more memory but it seemed to make no charge.

I'm super curious to know if anyone can replicate this because I'm surprised it's never come up before this far into use.

**Comment by transhapHigsn** [comment] 2020-11-15 23:14
@brandond Should I pick this up? Does this include only modifying yaml files for core components?

**Comment by brandond** [comment] 2020-11-16 03:57
This would be a great contribution. You should only need to modify the things in https://github.com/rancher/k3s/tree/master/manifests although  traefik may be a bit more difficult to modify since it comes from a helm chart, and you'll need to dig through the chart values stuff to figure out how to set it assuming it is possible at all on the version of the chart we're bundling.

**Comment by transhapHigsn** [comment] 2020-11-17 12:44
@brandond great.

**Comment by transhapHigsn** [comment] 2020-11-19 15:50
@brandond I have added pull request for same https://github.com/rancher/k3s/pull/2555

**Comment by transhapHigsn** [comment] 2020-11-19 22:49
@brandond messed up commits in previous pull request, have closed that and created new one with your suggested changes. https://github.com/rancher/k3s/pull/2558

Let me know if i need to make further changes.

**Comment by Timvissers** [comment] 2020-12-04 09:47
Could this one be in 1.20? People using priority classes for their pods could have the core services like coredns being preempted.

**Comment by davidnuzik** [comment] 2020-12-09 00:05
@brandond can we get this in RKE2 as well?

**Comment by brandond** [comment] 2020-12-09 00:37
@davidnuzik yeah I can work on a PR for rancher/rke2-charts

**Comment by ShylajaDevadiga** [comment] 2020-12-09 15:58
Validated using commit k3s version v1.20.0+k3s-c5aad1b5

Reproduced the issue setting testpods with highPriority class 
```
kube-system   76s         Normal    Preempted                 pod/coredns-7944c66d8d-j5bhr                  Preempted by default/nginx-deployment-bf7dcdf5b-tk2mh on node ip-172-31-18-80
```

Validated the fix, system pods were not evicted and testpods FailedScheduling as expected.
```
kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS    RESTARTS   AGE
kube-system   metrics-server-86cbb8457f-75jxs           1/1     Running   0          12m
kube-system   local-path-provisioner-7c458769fb-pkc7x   1/1     Running   0          12m
kube-system   coredns-7dc8bdd58c-8znlv                  1/1     Running   0          12m


default       3m28s       Warning   FailedScheduling          pod/nginx-deployment-758b5c67b5-blsz4          0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/disk-pressure: }, that the pod didn't tolerate.
```

**Comment by ShylajaDevadiga** [comment] 2020-12-09 21:08
Closing this issue as validated and open a new one  for validating fix on rke2.

**Closed by ShylajaDevadiga** 2020-12-09 21:08 UTC
Labels: [zube]: To Test, area/packaged-components, good first issue, kind/enhancement, priority/important-longterm
