### ISSUE TITLE
build failed when download traefik chart

### ISSUE THREAD

**Issue by liyimeng** [k3s-io/k3s#6529] opened 2022-11-21 12:33 UTC
**Environmental Info:**
K3s Version: 

master branch

Node(s) CPU architecture, OS, and Version: 

ubuntu

Cluster Configuration:

**Describe the bug:**

**Steps To Reproduce:**

- in a buildkit enabled env
- check out master branch
- issue `make`

**Expected behavior:**

k3s should be built successfully
**Actual behavior:**

build failed with following logs

**Additional context / logs:**

```
[+] Building 28.2s (7/7) FINISHED                                                                                                            
 => [internal] load build definition from Dockerfile.dapper515355921                                                                    0.0s
 => => transferring dockerfile: 113B                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                       0.0s 
 => => transferring context: 34B                                                                                                        0.0s 
 => [internal] load metadata for docker.io/library/k3s:td-1-25                                                                          0.0s 
 => CACHED [1/2] FROM docker.io/library/k3s:td-1-25                                                                                     0.0s 
 => [internal] load build context                                                                                                       0.1s 
 => => transferring context: 73.32kB                                                                                                    0.1s
 => [2/2] COPY . /go/src/github.com/k3s-io/k3s/                                                                                         6.8s
 => exporting to image                                                                                                                 21.1s
 => => exporting layers                                                                                                                21.1s
 => => writing image sha256:11719f4f4fd6af96df95d17fdddf73e67312869d366e4ad1340581ecde58ea45                                            0.0s
 => => naming to docker.io/library/k3s:td-1-25                                                                                          0.0s 
/go/src/github.com/k3s-io/k3s/scripts /go/src/github.com/k3s-io/k3s                                                                          
Cloning into 'build/src/github.com/opencontainers/runc'...
remote: Enumerating objects: 1347, done.
remote: Counting objects: 100% (1347/1347), done.
remote: Compressing objects: 100% (1090/1090), done.
remote: Total 1347 (delta 234), reused 722 (delta 191), pack-reused 0
Receiving objects: 100% (1347/1347), 2.23 MiB | 7.89 MiB/s, done.
Resolving deltas: 100% (234/234), done.
Note: switching to '5fd4c4d144137e991c4acebb2146ab1483a97925'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Cloning into 'build/src/github.com/containerd/containerd'...
remote: Enumerating objects: 7214, done.
remote: Counting objects: 100% (7214/7214), done.
remote: Compressing objects: 100% (5181/5181), done.
remote: Total 7214 (delta 2104), reused 4391 (delta 1590), pack-reused 0
Receiving objects: 100% (7214/7214), 10.25 MiB | 2.05 MiB/s, done.
Resolving deltas: 100% (2104/2104), done.
Note: switching to 'd55db719497a2cb86cfcfc15ceb60f0df683ec6d'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Updating files: 100% (6127/6127), done.
Downloading Traefik Helm chart from https://helm.traefik.io/traefik/traefik-12.0.0.tgz
FATA[0046] exit status 22                               
make: *** [Makefile:11: ci] Error 1

```

**Comment by liyimeng** [comment] 2022-11-21 12:38
hmm, it is the same error when turn off buildkit 
`DOCKER_BUILDKIT=0 make`

```
Updating files: 100% (6127/6127), done.
Downloading Traefik Helm chart from https://helm.traefik.io/traefik/traefik-12.0.0.tgz
FATA[0237] exit status 22                               
make: *** [Makefile:11: ci] Error 1
```

So I update the headline.  I have run this in two machine, the same error, but if I do `curl  https://helm.traefik.io/traefik/traefik-12.0.0.tgz`   it both work properly. Not sure what is going wrong, how can I debug.

**Comment by brandond** [comment] 2022-11-21 19:28
This is a duplicate of https://github.com/k3s-io/k3s/issues/6467

Have you pulled from this repo recently? The Traefik team has changed their helm repos around several times, and we had to make several changes to our scripts to download the charts from the new locations. If you're building an old release of K3s, or haven't pulled from our repo recently, then you are likely missing those chances.

**Closed by brandond** 2022-11-21 19:28 UTC

**Comment by liyimeng** [comment] 2022-11-21 19:34
Thanks @brandond Good to know!

**Comment by 120L020314** [comment] 2024-11-02 08:44
i change ./scripts/download to this, it works:
#!/bin/bash

set -e

cd $(dirname $0)/..

. ./scripts/version.sh

TRAEFIK_CHART_VERSION=$(yq e '.spec.chart' manifests/traefik.yaml | awk 'match($0, /([0-9.]+)([0-9]{2})/, m) { print m[1]; exit; }')
TRAEFIK_PACKAGE_VERSION=$(yq e '.spec.chart' manifests/traefik.yaml | awk 'match($0, /([0-9.]+)([0-9]{2})/, m) { print m[2]; exit; }')

TRAEFIK_URL=https://traefik.github.io/charts
TRAEFIK_FILE=traefik-${TRAEFIK_CHART_VERSION}${TRAEFIK_PACKAGE_VERSION}.tgz
TRAEFIK_CRD_FILE=traefik-crd-${TRAEFIK_CHART_VERSION}${TRAEFIK_PACKAGE_VERSION}.tgz
CHARTS_DIR=build/static/charts
RUNC_DIR=build/src/github.com/opencontainers/runc
DATA_DIR=build/data
export TZ=UTC

umask 022
rm -rf ${CHARTS_DIR}
rm -rf ${RUNC_DIR}
mkdir -p ${CHARTS_DIR}
mkdir -p ${DATA_DIR}

curl --compressed -sfL https://github.com/k3s-io/k3s-root/releases/download/${VERSION_ROOT}/k3s-root-${ARCH}.tar | tar xf - --exclude=bin/socat

git clone --single-branch --branch=${VERSION_RUNC} --depth=1 https://github.com/opencontainers/runc ${RUNC_DIR}

setup_tmp() {
    TMP_DIR=$(mktemp -d --tmpdir=${CHARTS_DIR})
    cleanup() {
        code=$?
        set +e
        trap - EXIT
        rm -rf ${TMP_DIR}
        exit $code
    }
    trap cleanup INT EXIT
}

download_and_package_traefik () {
  echo "Downloading Traefik Helm chart from ${TRAEFIK_URL}"
  
  # 这里使用新的 URL 下载 Helm 图表
  # curl -sfL ${TRAEFIK_URL}/${TRAEFIK_FILE} -o ${TMP_DIR}/${TRAEFIK_FILE}
  curl -SLO https://get.helm.sh/helm-v3.2.3-linux-amd64.tar.gz
  tar xzvf helm-v3.2.3-linux-amd64.tar.gz
  mv linux-amd64/helm /usr/bin/
  helm repo add traefik https://traefik.github.io/charts
  helm repo update
  helm pull traefik/traefik --version=v10.19.3
  mv traefik-10.19.3.tgz ${TMP_DIR}/${TRAEFIK_FILE}
  code=$?

  if [ $code -ne 0 ]; then
    echo "Error: Failed to download Traefik Helm chart!"
    exit $code
  fi

  echo "Uncompress ${TMP_DIR}/${TRAEFIK_FILE}"
  tar xf ${TMP_DIR}/${TRAEFIK_FILE} -C ${TMP_DIR}

  echo "Prepare traefik CRD"
  TRAEFIK_TMP_CHART=${TMP_DIR}/traefik
  TRAEFIK_TMP_CRD=${TRAEFIK_TMP_CHART}-crd

  # Collect information on chart
  name=$(yq e '.name' ${TRAEFIK_TMP_CHART}/Chart.yaml)
  api_version=$(yq e '.apiVersion' ${TRAEFIK_TMP_CHART}/Chart.yaml)
  chart_version=${TRAEFIK_CHART_VERSION}
  package_version=${TRAEFIK_PACKAGE_VERSION}

  # Collect information on CRDs
  crd_apis=()
  for crd_yaml in $(find ${TRAEFIK_TMP_CHART}/crds -type f | sort); do
    echo "Processing CRD at ${crd_yaml}"
    crd_group=$(yq e '.spec.group' ${crd_yaml})
    crd_kind=$(yq e '.spec.names.kind' ${crd_yaml})
    crd_version=$(yq e '.spec.version' ${crd_yaml})
    if [[ -z "$crd_version" ]] || [[ "$crd_version" == "null" ]]; then
      crd_version=$(yq e '.spec.versions[0].name' ${crd_yaml})
    fi
    echo "Found CRD with GVK ${crd_group}/${crd_version}/${crd_kind}"
    crd_apis+=("${crd_group}/${crd_version}/${crd_kind}")
  done

  set_found_crd=$(
  for crd in ${crd_apis[@]}; do
    echo "# {{- set \$found \"${crd}\" false -}}"
  done
  )

  # Copy base template and apply variables to the template
  mkdir -p ${TRAEFIK_TMP_CRD}
  cp -R ./scripts/chart-templates/crd-base/* ${TRAEFIK_TMP_CRD}
  for template_file in $(find ${TRAEFIK_TMP_CRD} -type f | sort); do
    # Applies any environment variables currently set onto your template file
    echo "Templating ${template_file}"
    eval "echo \"$(sed 's/"/\\"/g' ${template_file})\"" > ${template_file}
  done

  # Move anything from ${f}/charts-crd/overlay-upstream to the main chart
  cp -R ${TRAEFIK_TMP_CRD}/overlay-upstream/* ${TRAEFIK_TMP_CHART}
  rm -rf ${TRAEFIK_TMP_CRD}/overlay-upstream

  # Modify charts to support system-default-registry
  echo -e 'global:\n  systemDefaultRegistry: ""' >> ${TRAEFIK_TMP_CHART}/values.yaml
  find ${TRAEFIK_TMP_CHART} -type f | xargs sed -i 's/{{ .Values.image.name }}/{{ template "system_default_registry" .}}&/g'

  # Modify chart version to append package version
  sed -i "s/version: .*/&${TRAEFIK_PACKAGE_VERSION}/" ${TRAEFIK_TMP_CHART}/Chart.yaml

  # Add dashboard annotations to main chart
  cat <<EOF >>${TRAEFIK_TMP_CHART}/Chart.yaml
annotations:
  fleet.cattle.io/bundle-id: k3s
EOF

  # Move CRDs from main chart to CRD chart
  mkdir -p ${TRAEFIK_TMP_CRD}/templates
  mv ${TRAEFIK_TMP_CHART}/crds/* ${TRAEFIK_TMP_CRD}/templates
  rm -rf ${TRAEFIK_TMP_CHART}/crds

  # Package charts
  OPTS="--format=gnu --sort=name --owner=0 --group=0 --mode=gou-s --numeric-owner --no-acls --no-selinux --no-xattrs"
  tar ${OPTS} --mtime='2021-01-01 00:00:00Z' -cf - -C ${TMP_DIR} $(basename ${TRAEFIK_TMP_CHART}) | gzip -n > ${CHARTS_DIR}/${TRAEFIK_FILE}
  tar ${OPTS} --mtime='2021-01-01 00:00:00Z' -cf - -C ${TMP_DIR} $(basename ${TRAEFIK_TMP_CRD}) | gzip -n > ${CHARTS_DIR}/${TRAEFIK_CRD_FILE}
  for TAR in ${CHARTS_DIR}/${TRAEFIK_FILE} ${CHARTS_DIR}/${TRAEFIK_CRD_FILE}; do
    sha256sum ${TAR}
    stat ${TAR}
    tar -vtf ${TAR}
  done
}

setup_tmp
download_and_package_traefik

cp scripts/wg-add.sh bin/aux/
