### ISSUE TITLE
Kustomize secrets are "regenerated" even though they are the same.

### ISSUE THREAD

**Issue by hholst80** [k3s-io/k3s#5941] opened 2022-08-02 22:01 UTC
Kustomize uses linebreaks in the base64 output of `kubectl kustomize` and that creates a spurious recreate signal.

kubectl kustomize | kubectl apply -f - reapplies secrets even though they have not changed.

This has been reported to the kustomize guys but they had zero fucks to give so hoping you can fix it on your end.

https://github.com/kubernetes-sigs/kustomize/issues/4653

```
k3s version v1.23.6+k3s1 (418c3fa8)
go version go1.17.5
```

Ubuntu 20.04 LTS @ Azure.

1 Server. 1 Agent.

**Expected behavior:**

apply should not "configure" the resource that has not changed.

**Actual behavior:**

```
/qqq om@fedora 6s
❯ kustomize build
apiVersion: v1
data:
  secret.txt: |
    VGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQuClRoaXMgaXMgYSB2ZXJ5IGxvbmcgc2Vjcm
    V0LgpUaGlzIGlzIGEgdmVyeSBsb25nIHNlY3JldC4KVGhpcyBpcyBhIHZlcnkgbG9uZyBz
    ZWNyZXQuClRoaXMgaXMgYSB2ZXJ5IGxvbmcgc2VjcmV0LgpUaGlzIGlzIGEgdmVyeSBsb2
    5nIHNlY3JldC4KVGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQuClRoaXMgaXMgYSB2ZXJ5
    IGxvbmcgc2VjcmV0LgpUaGlzIGlzIGEgdmVyeSBsb25nIHNlY3JldC4KVGhpcyBpcyBhIH
    ZlcnkgbG9uZyBzZWNyZXQuCg==
kind: Secret
metadata:
  name: secrets-kbhhh2kc45
type: Opaque

~/qqq om@fedora
❯ kustomize build | kubectl apply -f 
error: flag needs an argument: 'f' in -f
See 'kubectl apply --help' for usage.

~/qqq om@fedora
❯ kustomize build | kubectl apply -f -
secret/secrets-kbhhh2kc45 created

~/qqq om@fedora
❯ kustomize build | kubectl apply -f -
secret/secrets-kbhhh2kc45 configured

~/qqq om@fedora
❯ kustomize build | kubectl apply -f -
secret/secrets-kbhhh2kc45 configured

~/qqq om@fedora
❯ cat secret.txt 
This is a very long secret.
This is a very long secret.
This is a very long secret.
This is a very long secret.
This is a very long secret.
This is a very long secret.
This is a very long secret.
This is a very long secret.
This is a very long secret.
This is a very long secret.

~/qqq om@fedora
❯ cat kustomization.yaml 
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: secrets
    files:
      - secret.txt

~/qqq om@fedora
❯ 
```

**Comment by brandond** [comment] 2022-08-02 22:18
I'm not sure how we could fix this... we don't carry patches to upstream Kubernetes that aren't critical to enabling our goal of running the entire control-plane+datastore in a single process, and we don't package kustomize at all.

**Comment by cwayne18** [comment] 2022-08-02 22:46
Hi there,

We appreciate you taking the time to log this. As you mentioned, this is something that would need to be fixed by upstream Kustomize folks, as we pull directly from there and don't really change it. Closing this since the issue is reported upstream

**Closed by cwayne18** 2022-08-02 22:46 UTC
