### ISSUE TITLE
Middlewares not working (404) after traefik 2.10 upgrade

### ISSUE THREAD

**Issue by javiertury** [k3s-io/k3s#8784] opened 2023-11-05 10:23 UTC
**Environmental Info:**
K3s Version: 
k3s version v1.27.7+k3s1 (b6f23014)
go version go1.20.10

Node(s) CPU architecture, OS, and Version: 
Linux centos-2gb-fsn1-1 5.14.0-284.30.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Sep 12 09:28:32 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server, 1 agent

**Describe the bug:**
On October 30 my k3s cluster updated traefik proxy to 2.10.5 and ingress is not working properly ever since. Queries return 404 errors whenever middlewares are used to service them.

Probably related to #8755

**Additional context / logs:**
```
W1105 10:12:16.877250       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.IngressRoute: ingressroutes.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "ingressroutes" in API group "traefik.io" at the cluster scope
E1105 10:12:16.877748       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.IngressRoute: failed to list *v1alpha1.IngressRoute: ingressroutes.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "ingressroutes" in API group "traefik.io" at the cluster scope
W1105 10:12:17.259646       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.MiddlewareTCP: middlewaretcps.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "middlewaretcps" in API group "traefik.io" at the cluster scope
E1105 10:12:17.259732       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.MiddlewareTCP: failed to list *v1alpha1.MiddlewareTCP: middlewaretcps.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "middlewaretcps" in API group "traefik.io" at the cluster scope
W1105 10:12:31.005880       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.TLSStore: tlsstores.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "tlsstores" in API group "traefik.io" at the cluster scope
E1105 10:12:31.006907       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.TLSStore: failed to list *v1alpha1.TLSStore: tlsstores.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "tlsstores" in API group "traefik.io" at the cluster scope
W1105 10:12:31.007325       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.TLSOption: tlsoptions.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "tlsoptions" in API group "traefik.io" at the cluster scope
E1105 10:12:31.007489       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.TLSOption: failed to list *v1alpha1.TLSOption: tlsoptions.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "tlsoptions" in API group "traefik.io" at the cluster scope
W1105 10:12:38.889129       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.Middleware: middlewares.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "middlewares" in API group "traefik.io" at the cluster scope
E1105 10:12:38.889201       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.Middleware: failed to list *v1alpha1.Middleware: middlewares.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "middlewares" in API group "traefik.io" at the cluster scope
W1105 10:12:38.995091       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.TraefikService: traefikservices.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "traefikservices" in API group "traefik.io" at the cluster scope
E1105 10:12:39.005430       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.TraefikService: failed to list *v1alpha1.TraefikService: traefikservices.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "traefikservices" in API group "traefik.io" at the cluster scope
W1105 10:12:44.900812       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.IngressRouteUDP: ingressrouteudps.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "ingressrouteudps" in API group "traefik.io" at the cluster scope
E1105 10:12:44.901140       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.IngressRouteUDP: failed to list *v1alpha1.IngressRouteUDP: ingressrouteudps.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "ingressrouteudps" in API group "traefik.io" at the cluster scope
W1105 10:12:57.299568       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.ServersTransport: serverstransports.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "serverstransports" in API group "traefik.io" at the cluster scope
E1105 10:12:57.300529       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.ServersTransport: failed to list *v1alpha1.ServersTransport: serverstransports.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "serverstransports" in API group "traefik.io" at the cluster scope
W1105 10:13:06.081266       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.IngressRoute: ingressroutes.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "ingressroutes" in API group "traefik.io" at the cluster scope
E1105 10:13:06.082426       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.IngressRoute: failed to list *v1alpha1.IngressRoute: ingressroutes.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "ingressroutes" in API group "traefik.io" at the cluster scope
W1105 10:13:06.122597       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.IngressRouteTCP: ingressroutetcps.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "ingressroutetcps" in API group "traefik.io" at the cluster scope
E1105 10:13:06.122903       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.IngressRouteTCP: failed to list *v1alpha1.IngressRouteTCP: ingressroutetcps.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "ingressroutetcps" in API group "traefik.io" at the cluster scope
W1105 10:13:08.475645       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.MiddlewareTCP: middlewaretcps.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "middlewaretcps" in API group "traefik.io" at the cluster scope
E1105 10:13:08.476221       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.MiddlewareTCP: failed to list *v1alpha1.MiddlewareTCP: middlewaretcps.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "middlewaretcps" in API group "traefik.io" at the cluster scope
W1105 10:13:11.935373       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.TLSStore: tlsstores.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "tlsstores" in API group "traefik.io" at the cluster scope
E1105 10:13:11.935483       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.TLSStore: failed to list *v1alpha1.TLSStore: tlsstores.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "tlsstores" in API group "traefik.io" at the cluster scope
W1105 10:13:20.066528       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.TraefikService: traefikservices.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "traefikservices" in API group "traefik.io" at the cluster scope
E1105 10:13:20.068982       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.TraefikService: failed to list *v1alpha1.TraefikService: traefikservices.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "traefikservices" in API group "traefik.io" at the cluster scope
W1105 10:13:20.069917       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.TLSOption: tlsoptions.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "tlsoptions" in API group "traefik.io" at the cluster scope
E1105 10:13:20.070197       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.TLSOption: failed to list *v1alpha1.TLSOption: tlsoptions.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "tlsoptions" in API group "traefik.io" at the cluster scope
W1105 10:13:25.680089       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.Middleware: middlewares.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "middlewares" in API group "traefik.io" at the cluster scope
E1105 10:13:25.680581       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.Middleware: failed to list *v1alpha1.Middleware: middlewares.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "middlewares" in API group "traefik.io" at the cluster scope
W1105 10:13:37.884416       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.IngressRouteUDP: ingressrouteudps.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "ingressrouteudps" in API group "traefik.io" at the cluster scope
E1105 10:13:37.886249       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.IngressRouteUDP: failed to list *v1alpha1.IngressRouteUDP: ingressrouteudps.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "ingressrouteudps" in API group "traefik.io" at the cluster scope
W1105 10:13:39.430453       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.MiddlewareTCP: middlewaretcps.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "middlewaretcps" in API group "traefik.io" at the cluster scope
E1105 10:13:39.431487       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.MiddlewareTCP: failed to list *v1alpha1.MiddlewareTCP: middlewaretcps.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "middlewaretcps" in API group "traefik.io" at the cluster scope
W1105 10:13:44.905734       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.IngressRoute: ingressroutes.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "ingressroutes" in API group "traefik.io" at the cluster scope
E1105 10:13:44.906638       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.IngressRoute: failed to list *v1alpha1.IngressRoute: ingressroutes.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "ingressroutes" in API group "traefik.io" at the cluster scope
W1105 10:13:53.405548       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.ServersTransport: serverstransports.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "serverstransports" in API group "traefik.io" at the cluster scope
E1105 10:13:53.406992       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.ServersTransport: failed to list *v1alpha1.ServersTransport: serverstransports.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "serverstransports" in API group "traefik.io" at the cluster scope
W1105 10:13:53.544385       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.TLSStore: tlsstores.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "tlsstores" in API group "traefik.io" at the cluster scope
E1105 10:13:53.544954       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.TLSStore: failed to list *v1alpha1.TLSStore: tlsstores.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "tlsstores" in API group "traefik.io" at the cluster scope
W1105 10:13:59.603833       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.IngressRouteTCP: ingressroutetcps.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "ingressroutetcps" in API group "traefik.io" at the cluster scope
E1105 10:13:59.604114       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.IngressRouteTCP: failed to list *v1alpha1.IngressRouteTCP: ingressroutetcps.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "ingressroutetcps" in API group "traefik.io" at the cluster scope
W1105 10:14:04.663395       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.TraefikService: traefikservices.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "traefikservices" in API group "traefik.io" at the cluster scope
E1105 10:14:04.663973       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.TraefikService: failed to list *v1alpha1.TraefikService: traefikservices.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "traefikservices" in API group "traefik.io" at the cluster scope
W1105 10:14:07.784569       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.Middleware: middlewares.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "middlewares" in API group "traefik.io" at the cluster scope
E1105 10:14:07.785742       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.Middleware: failed to list *v1alpha1.Middleware: middlewares.traefik.io is forbidden: User "system:serviceaccount:kube-system:traefik" cannot list resource "middlewares" in API group "traefik.io" at the cluster scope
```

**Comment by view715** [comment] 2023-11-05 21:39
Same here for k3s v1.25 and up on a clean Debian 12.2 installation.

**Comment by ChristianCiach** [comment] 2023-11-06 12:19
Pretty sure this is a duplicate of https://github.com/k3s-io/k3s/issues/8755.

There is already a release candidate of `v1.27.7+k3s2` to fix the issue by bundling an updated Traefik helm chart.

**Comment by ShylajaDevadiga** [comment] 2023-11-06 17:24
@javiertury Are you using the CRDs in your setup? Could you use v1.27.7-rc1+k3s2 to see if you still have the same issue?

**Comment by javiertury** [comment] 2023-11-06 17:44
@ShylajaDevadiga I'm using only the CRDs installed by k3s. After manually upgrading to v1.27.7-rc1+k3s2, the issue is solved.

**Comment by dereknola** [comment] 2023-11-06 17:46
Closing as duplicate (root issue) of https://github.com/k3s-io/k3s/issues/8755

**Closed by dereknola** 2023-11-06 17:46 UTC
