### ISSUE TITLE
New Coredns NodeHosts entries disappear after cluster restart

### ISSUE THREAD

**Issue by ashok-mariyala** [k3s-io/k3s#8225] opened 2023-08-22 05:54 UTC
**Environmental Info:**
K3s Version: 
```
ubuntu@ashok:~$ k3s -v
k3s version v1.27.4+k3s1 (36645e73)
go version go1.20.6
```

Node(s) CPU architecture, OS, and Version: 
```
ubuntu@ashok:~$ uname -a
Linux ashok 5.4.0-156-generic #173-Ubuntu SMP Tue Jul 11 07:25:14 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

Cluster Configuration:
Single node cluster

**Describe the bug:**
I have added some custom host entries in coredns configmap. 
```
    hosts /etc/coredns/NodeHosts {
      192.168.64.6 ashok.dev.com
      192.168.64.6 ashok.dev.net
      ttl 60
      reload 15s
      fallthrough
    }
```
After cluster reboot these changes are disapper.
**Steps To Reproduce:**
- Installed K3s: 
- Added custom hosts in coredns configmap
- Restart k3s cluster or reboot the cluster node.

**Expected behavior:**
Custom hosts should persist even after cluster reboot.

**Comment by brandond** [comment] 2023-08-22 06:49
Duplicate of https://github.com/k3s-io/k3s/issues/5394#issuecomment-1092378039

**Closed by brandond** 2023-08-22 06:49 UTC
